### ISSUE TITLE
[docs] adding jar section example keyword should be "jar" but "filename"

### ISSUE THREAD

**Issue by alan791205** [oharastream/ohara#1016]
[See rest interface readme](https://github.com/oharastream/ohara/blob/master/docs/rest_interface.md#upload-a-jar-to-ohara)
under
```
Example Request

Content-Disposition: form-data
filename="aa.jar"
```
the keyword "filename" should be "jar" to use this api, or you guys want to change the keyword inside your api?

**Comment by chia7712** [comment]
I prefer to revise the docs rather than code base...

@alan791205 Do you have free cycle to take over this issue?

**Comment by alan791205** [comment]
sure

**Comment by chia7712** [comment]
@alan791205 Thanks for the PR
