### ISSUE TITLE
Fix flaky ZookeeperCollie.scala unsupported exception

### ISSUE THREAD

**Issue by jackyoh** [oharastream/ohara#1020]
需要將 ZookeeperCollie.scala 的 unsupported exception 放在實做裡面

first commit (#1021 ):
revert to (#1025) for commit comment typo
recreate PR (#1031)

**Comment by chia7712** [comment]
@jackyoh Is this done?

**Comment by jackyoh** [comment]
已經 done 了, 我來關閉
