### ISSUE TITLE
Remove the ssh.Cache

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#1023]
Crane still use ssh.Cache. We should replace ssh.Cache by common.Cache, and then get rid of ssh.Cache

**Comment by saivirtue** [comment]
you can relate this issue to #885

**Comment by chia7712** [comment]
> you can relate this issue to #885

got it. I add this to #885's description.

**Comment by chia7712** [comment]
> you can relate this issue to #885

Seems #904 included this stuff. Do I misunderstand anything?

**Comment by saivirtue** [comment]
> Seems #904 included this stuff. Do I misunderstand anything?
Yep. we can close this issue now.
