### ISSUE TITLE
OharaStream 0.4 release

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#1024]
What should be done during the 0.4 release:

- [x] Create 0.4 branch (base on last commit of the frozen day -> 5/5)
- [x] Update ohara's master branch version to 0.5-SNAPSHOT
- [ ] ~~Remove unused (or unnecessary) functions from 0.4 branch~~
- [x] deploy to demo environment
- [x] Add a change log in release wiki page
- [x] Update version of 0.4 branch to 0.4.0
- [x] Update Bintray repo
- [x] Add tags in release wiki page
- [x] Add 0.4 binaries to GitHub download

[release link](https://github.com/oharastream/ohara/releases)

**Comment by chia7712** [comment]
@konekoya Could we highlight the feature of 0.4 release? For example, metrics APIs, shabondi prototype, and  developer docs

**Comment by konekoya** [comment]
Such a good idea. I'll include a summary in the release note

**Comment by konekoya** [comment]
@chia7712 I've updated the release note. Would love to hear your feedback on this update :)

**Comment by chia7712** [comment]
@konekoya could you add more description to the new features? 

- Metrics APIs: ohara supports jmx servcie now! Both [connector APIs](https://github.com/oharastream/ohara/blob/0.4/docs/rest_interface.md#connector) and [topic APIs](https://github.com/oharastream/ohara/blob/0.4/docs/rest_interface.md#topic) are able to fetch the metrics for you. For custom connector developers, you can leverage the counter (see [docs](https://github.com/oharastream/ohara/blob/0.4/docs/custom_connector.md) for more details) to expose your custom metrics.

**Comment by konekoya** [comment]
This is great! Added

**Comment by chia7712** [comment]
@jackyoh @saivirtue Please offer some **words** for @konekoya. We ought to make our release announcement more readable and friendly.

**Comment by chia7712** [comment]
- Developer docs: the [official guide](https://github.com/oharastream/ohara/tree/0.4/docs) is online now. Ohara welcome and encourage all connector/streampp developers to read it.

**Comment by saivirtue** [comment]
@konekoya help to improve sentence fluency, thanks :)
- Support multiple instances for streamApp
- Use different environment between docker and kubernetes in Pipeline without any influence except using different parameters in configurator. See [use docker](https://github.com/oharastream/ohara/blob/master/docs/user_guide.md#execute-configurator) and [use kubernetes](https://github.com/oharastream/ohara/tree/master/kubernetes#how-to-use-kubernetes-in-oharastream)

**Comment by vitojeng** [comment]
* Shabondi prototype: Shabondi is a data proxy which can receive streaming dataset from http request into a Pipeline.

**Comment by konekoya** [comment]
Thanks everyone for the help! Ohara stream 0.4.0 has been released :)

**Comment by chia7712** [comment]
@konekoya https://github.com/oharastream/ohara/releases is still in draft???
