### ISSUE TITLE
Update ohara's master branch version to 0.5-SNAPSHOT

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#1034]
- [x] Build and push 0.5-SNAPSHOT Docker images to Docker Hub
- [x] Replace 0.4-SNAPSHOT with 0.5-SNAPSHOT in ohara codebase (#1037)
- [x] Replace 0.4-SNAPSHOT with 0.5-SNAPSHOT all Jenkins tasks

required by #1024

**Comment by konekoya** [comment]
@chia7712 @saivirtue @jackyoh Pinging all Jenkins maintainers!

Please update Jenkins tasks to use `0.5-SNAPSHOT` tag instead of `0.4-SNAPSHOT`.

Thanks!

**Comment by saivirtue** [comment]
got it :)

**Comment by jackyoh** [comment]
OK, 我來更新

**Comment by saivirtue** [comment]
CD change to `0.5-SNAPSHOT` done!

**Comment by chia7712** [comment]
感恩RM 讚嘆RM

**Comment by konekoya** [comment]
我們的目標就是發大財啊

**Comment by konekoya** [comment]
@jackyoh Could you also help update the docker images on it-nodes?
