### ISSUE TITLE
ohara agent 的 worker 需要能夠設定 /etc/hosts

### ISSUE THREAD

**Issue by jackyoh** [oharastream/ohara#1035]
如果使用 HDFS Sink Connector, 必須要讓每台的 Kafka Worker 知道 Hadoop 的 namenode 和 datanode 的連線資訊如 Hostname 對應的 IP, 因此需要將這些資訊設定在 /etc/hosts 的檔案裡.
Kafka Worker 才能順利連到 HDFS 的環境裡.

**Comment by chia7712** [comment]
類似的議題之前討論過。理想上客戶要能提供dns的設定，則否後續的路由很難維護

**Comment by jackyoh** [comment]
目前在 k8s 環境上的 worker 執行 hdfs sink connector. 感覺上 dns server 不太穩定一下 ping 的到 host name, 一下又會有 unknow host 的錯誤. 造成使用 hdfs sink connector 寫入資料會有問題. 我還會再去確認是 k8s 的問題還是 dns server 設定的問題.

**Comment by chia7712** [comment]
@jackyoh any updates??? could we close this issue?

**Comment by jackyoh** [comment]
目前沒有 update, 先朝解內部環境的 dns 為目標. 我先把此議題關閉.

**Comment by jackyoh** [comment]
需要在 demo 環境上使用 HDFS Storage, 所以我再把此議題打開

**Comment by jackyoh** [comment]
目前使用的解決方法是修改 K8S 的 coredns 環境設定, 把 ohara-demo-cdh01, ohara-demo-cdh02, ohara-demo-cdh03 三台 VM 的 host name 和 host ip 加入到 k8s 的設定檔裡. 這樣可以避免 DNS 不穩的問題.

使用指令如下：
```
# kubectl edit configmap -n kube-system coredns
```

修改的設定檔如下：
```
data:
  Corefile: |
    .:53 {
        errors
        health
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           upstream 10.3.1.253 10.3.1.197 8.8.4.4
           fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf
        #proxy . 10.3.1.253 10.3.1.197 8.8.4.4
        cache 30
        loop
        reload
        loadbalance
        hosts {
          10.200.x.x ohara-demo-cdh01
          10.200.x.x ohara-demo-cdh02
          10.200.x.x ohara-demo-cdh03
          fallthrough
        }
    }
```

**Comment by jackyoh** [comment]
這個議題沒有更新了，我把它關閉。
