### ISSUE TITLE
file operations should not use OS-dependent char

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#1038]
In `CommonUtils.path(String parent, String name)` :
```java
if (parent.endsWith("/")) return parent + name;
else return parent + "/" + name;
```
This won't work in non-unix like environment (small users though...). We can change the implementation to `Path.get(paths)`

**Comment by saivirtue** [comment]
ping @chia7712 any thoughts? I can take over this issue and the related file operations

**Comment by chia7712** [comment]
This is a good issue, though we support the CentOS only. +1 to fix it
