### ISSUE TITLE
Able to add duplicate HDFS info

### ISSUE THREAD

**Issue by alan791205** [oharastream/ohara#1042]
As title,
I can add 2 exactly same hdfs info (name, uri) to my configurator by using ohara restful API
```
{"id":"65f936c5-7cc4-4b9a-a9c5-1736418d4d09","name":"hdfs1","uri":"hdfs://******","lastModified":1557138187941} 
{"id":"6e6bffd0-328b-4805-84f8-762f04b3a567","name":"hdfs1","uri":"hdfs://******","lastModified":1557138191920}
```
I know the difference is that different ID has been assigned to 2 hdfs info but seems either name or uri should be unique?

**Comment by chia7712** [comment]
> either name or uri should be unique?

What is your point of disallowing user to use unique name or uri???

**Comment by alan791205** [comment]
I mean that is that possible to prevent redundant hdfs infos with exact same name and uri?

**Comment by chia7712** [comment]
> I mean that is that possible to prevent redundant hdfs infos with exact same name and uri?

Is it necessary? Except for id, ohara is free to change all properties of a data object. Querying the duplicate content across whole storage is not cheaper and it brings only a error message "hi your data is duplicate to someone"...

**Comment by alan791205** [comment]
> Is it necessary? Except for id, ohara is free to change all properties of a data object. Querying the duplicate content across whole storage is not cheaper and it brings only a error message "hi your data is duplicate to someone"...
No it is not that necessary, so I really just added it to my wish list of user friendlier only.

**Comment by chia7712** [comment]
go back for this issue. #1080 had removed the id from topic info. Should we remove the id from hdfs information also? I feel it makes sense since the **name** is more readable to user.

**Comment by chia7712** [comment]
@wu87988622 @eechih @jackyoh @konekoya @vitojeng @saivirtue Any suggestions?

**Comment by jackyoh** [comment]
>  Should we remove the id from hdfs information also? I feel it makes sense since the name is more readable to user.
 +1

**Comment by chia7712** [comment]
ok. I have filed issue#1286.
