### ISSUE TITLE
As a Frontend dev, there should be Restful API tests that ensure changes made in backend won’t break the UI

### ISSUE THREAD

**Issue by eechih** [oharastream/ohara#1051]
- [x] Figure out a way to do the test either with Cypress or Jest
- [x] Running frontend and backend restful API test on CI
- [x] Writing brokers, zookeepers, workers API tests
- [x] Writing nodes, pipelines, stream app API tests
- [x] Writing topics, validate, jars, logs API tests
- [x] Writing connectors API tests

**Comment by jackyoh** [comment]
ping @wu87988622 這個 issue 應該可以關掉了吧
