### ISSUE TITLE
Speedup the error handle for k8s env and test

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#1056]
The issue includes the following tasks.

- [x] add k8s vm image
- [x] narrow the rebuild of custom image
~build temporary images concurrently~

**Comment by jackyoh** [comment]
第二點 build temporary images concurrently 是用來測試 k8s VM image 是否能正常的建立執行嗎？

**Comment by chia7712** [comment]
> 第二點 build temporary images concurrently 是用來測試 k8s VM image 是否能正常的建立執行嗎？

No really. It means we can build temporary images (for IT) concurrently if jenkins is powerful enough.

**Comment by jackyoh** [comment]
Yes, I see.

**Comment by chia7712** [comment]
all done!
