### ISSUE TITLE
Fix material UI warning in the browser console

### ISSUE THREAD

**Issue by wu87988622** [oharastream/ohara#1070]
This looks like a bug coming from Mui. The fix has been merged into Mui's branch but hasn't released yet. We'll upgrade our Mui version once a new release is available to the public.

The warning in the browser console:  

>   ![Capture d’écran 2019-05-05 à 18 02 34](https://user-images.githubusercontent.com/3165635/57196741-fb49ba00-6f5f-11e9-8ea0-754849d1f171.png)

Mui PR:
[[styles] Fix warning false positive #15595](https://github.com/mui-org/material-ui/pull/15595)

**Comment by konekoya** [comment]
@wu87988622 I'm going to upgrade our Mui as a new release has been out for a while. And I'm really tired of that warning message...

https://github.com/mui-org/material-ui/releases

**Comment by wu87988622** [comment]
> @wu87988622 I'm going to upgrade our Mui as a new release has been out for a while. And I'm really tired of that warning message...
> 
> https://github.com/mui-org/material-ui/releases

ok 
maybe you only update @material-ui/styles@v4.0.0-beta.1 to @material-ui/styles@v4.0.0-beta.2
