### ISSUE TITLE
Remove ID from Topic APIs

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#1080]
required by #1043

ohara doesn't generate ID for topic any more, and it uses user-defined name instead. The benefit is that users can **see** the really topic name. The side-effect is that topic naming needs to face the limit from kafka.

**Comment by saivirtue** [comment]
So the following changes are correct?

Rest API response :

```diff
 {
    "name": "topic0",
    "brokerClusterName": "bk00",
    "lastModified": 1557139470020,
    "numberOfReplications": 1,
-   "id": "20256056-f43e-4c7f-b7ce-763df0af0433",
+   "id": "topic0",
    "metrics": {
      "meters": []
    },
    "numberOfPartitions": 1
  }
```

**Comment by chia7712** [comment]
> Are we going to do the following changes?

Topic APIs don't show the ID any more. Both "id": "20256056-f43e-4c7f-b7ce-763df0af0433" and  "id": "topic0" disappear from our topics
