### ISSUE TITLE
[Phase 1] Complete tests for ContainerCollie

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#1083]
@jackyoh has introduced a great middle layer, which is called ContainerCollie, for all collie implementations. ContainerCollie consists of most common code for collie and it is independent on any docker code. Hence, it is time to add tests for our ohara-agent module.

- [x]  #1142 ContainerCollie 需要做到 addNode 的 check (move to issue #1104)

the follow-up to this is #1320

**Comment by jackyoh** [comment]
OK, 收到. 目前主要的目標是要做到如下：
- [ ] check 在 ContainerCollie 的邏輯撰寫
- [ ] doXXX implement 在 K8S 和 SSH 
- [ ] ContainerCollie 的測試程式撰寫
