### ISSUE TITLE
Automate deployment of Ohara-demo at Jenkins

### ISSUE THREAD

**Issue by eechih** [oharastream/ohara#1086]
設定一組 Jenkins job，進行 Ohara-demo 的部署或更新 ，讓每個人都可以使用。

請 @jackyoh 幫忙設定編輯權限

**Comment by chia7712** [comment]
有請777

**Comment by jackyoh** [comment]
OK, 早上太忙了. 現在才看到訊息.

**Comment by jackyoh** [comment]
Ohara-demo 主要是使用 jenkins 的來部署 demo 環境. 例如是 pull oharastream 的 image, 啟動 configurator, reset k8s container 的工作.
