### ISSUE TITLE
Syntax error on query string using JDBC Connector with mysql 

### ISSUE THREAD

**Issue by alan791205** [oharastream/ohara#1103]
I've set up everything (worker broker zookeeper connnector) by using rest api.
when I tried to start my connector using "mysql-connector-java-8.0.12.jar" as jdbc to poll things from my mysql DB, validate rdb runs fine but I found out no data was transfered to the topic. So I went through the worker's log and found this:
```
ERROR You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"test123" WHERE "start" > '1970-01-01 00:00:00.0' and "start" < '2019-05-09 18:0' at line 1 (com.island.ohara.connector.jdbc.source.JDBCSourceTask:98)
java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"test123" WHERE "start" > '1970-01-01 00:00:00.0' and "start" < '2019-05-09 18:0' at line 1
```

Using CentOS
```
~ # cat /etc/redhat-release                                                                                                                                                      
CentOS Linux release 7.5.1804 (Core) 
------------------------------------------------------------
```

By the way, also checked with "mysql-connector-java-8.0.15.jar", maybe can rule out jdbc version issue.

**Comment by jackyoh** [comment]
可以提供 create table 的 schema 嗎？

**Comment by alan791205** [comment]
Sure.
```CREATE table test123 (start TIME_STAMP PRIMARY KEY, ID INT);```
```
insert into test123 (start, ID) values ('2019-05-08 00:00:00', 0);
insert into test123 (start, ID) values ('2019-05-08 00:00:01', 1);
insert into test123 (start, ID) values ('2019-05-08 00:00:02', 2);
```
I only added 3 items into mysql database.

**Comment by jackyoh** [comment]
OK, 了解. 我會找時間去測試以上的資料

**Comment by jackyoh** [comment]
目前的 JDBC Source Connector 查詢的 SQL 語法, 需要支援 double quote 的設定.
如果是 mysql 需要使用以下的設定：
```
SET GLOBAL SQL_MODE=ANSI_QUOTES
```
參考網址：
https://stackoverflow.com/questions/1992314/what-is-the-difference-between-single-and-double-quotes-in-sql

在之後的版本再決定是否修改這個部份.

**Comment by chia7712** [comment]
這陣子很多jdbc有關的議題和需要修正的地方，麻煩開個umbrella 整理下

**Comment by jackyoh** [comment]
OK, 我先來開 umbrella

**Comment by alan791205** [comment]
Sorry, misclicked ..
