### ISSUE TITLE
Do we need a "ohara version" Pair class?

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#1105]
As title, since there are many many cases that we need to do something like :
```java
pair = Pair.of(a, b);
// use pair.left do something...
// use pair.right do something...
```
Or
```java
List<Pair<String, String>> list = new ArrayList<>();
//do something to the list...
```

Currently, for ohara already includes dependencies, we have two kinds Pair available :
- `javafx.util.Pair`
- `org.apache.commons.lang3.tuple.Pair`

But the Pair implementation seems is simple, do we need to own this class in our ohara ?

**Comment by saivirtue** [comment]
ping @jackyoh @vitojeng @chia7712 
have any thoughts?

**Comment by chia7712** [comment]
+1

**Comment by chia7712** [comment]
Tuple and Pair is useful in java :)

**Comment by jackyoh** [comment]
> do we need to own this class in our ohara ?
+1

**Comment by vitojeng** [comment]
+1

Pair is useful.
IMO, I would prefer to provide `Immutable` pair for thread safe.

**Comment by chia7712** [comment]
Pair and tuple should have following attributes.

1. Immutable
1. Comparable 
1. Hash code
1. Copy and replace
1. noninheritable
1. generic
1. readable tostring

**Comment by saivirtue** [comment]
Got it, will create another issue #1114 do the job.
