### ISSUE TITLE
Use wk as the connect worker name will produce a different name

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#1106]
**Describe the bug**

_Note that this behavior can only be reproduced in k8s mode_

Normally, when creating a new connect worker, the user supplied worker names should be returned after a successful request call. For example:

Given a request like this:

POST `/v0/workers`
```json
clientPort: null
jars: []
name: "myawesomeworker"
nodeNames: ["ohara-dev-103"]
```

The response will include the supplied name from the above request we just made
```json
imageName: "oharastream/connect-worker:0.4-SNAPSHOT"
jarIds: []
jarNames: []
jarUrls: []
jmxPort: 8084
name: "myawesomeworker"
...
```

When using __wk__ as the connect worker name, the response from the API will be __wk__, but when fetching the worker list with GET `/v0/workers`. The worker name will be __"k8soccl"__

**To Reproduce**
This can be repro with our web UI
- Prepare necessary configurator, manager, zookeeper and broker services.
- And in our UI, go to services page and click on the _New cluster_ button
- Use __wk__ as the name, and fill out the form with normal data. Then hit the add button
- The newly created connect worker name will be  __"k8soccl"__

**Expected behavior**
The worker names return from GET `/v0/workers` should be the same from POST `/v0/workers/

**Screenshots**
Nope

**Operation System (please complete the following information):**
Services are running on CentOS
Manager is running on macOS

**Additional context**
Using other names as the connect worker's name won't produce the abovementioned result

**Comment by jackyoh** [comment]
OK, 收到. 我再來研究就這個 issue

**Comment by konekoya** [comment]
> OK, 收到. 我再來研究就這個 issue

:)

**Comment by saivirtue** [comment]
This issue is due to the "parsing" logic on backend:
```scala
container.name.split(s"$DIVIDER${serviceName}$DIVIDER").head -> container
```
we use the `wk` as `serviceName` ; the above regrex will split the wrong part (the clusterName)

**Comment by jackyoh** [comment]
這個是 parser 字串的問題， 我再去解.

@saivirtue Thank you

**Comment by jackyoh** [comment]
這個 issue 沒有合併到 master, 重新 reopen 把 code 合併到 master

**Comment by konekoya** [comment]
@jackyoh I'll need to add 0.6.0 label to this issue :)

**Comment by jackyoh** [comment]
> @jackyoh I'll need to add 0.6.0 label to this issue :)

我已經加入 0.6.0 的標籤了

**Comment by chia7712** [comment]
@jackyoh 你推到master的PR是不是破壞了build? see https://builds.is-land.com.tw/job/PreCommit-OHARA/2940/

**Comment by jackyoh** [comment]
> @jackyoh 你推到master的PR是不是破壞了build? see https://builds.is-land.com.tw/job/PreCommit-OHARA/2940/

我來研究看看

**Comment by jackyoh** [comment]
我剛才有測試過這個 commit id, 看起來 build 沒問題. 主要的問題是在 #1438, 在測試程式裡少傳一個參數
ping @saivirtue, 先 revert code 看是否可以 build code
