### ISSUE TITLE
Remove get table button from jdbc config form

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#1109]
Caused by #1102 

Due to the recent API changes. Manager's jdbc config form is no longer working as it should. As we're working on a more comprehensive solution that will eventually land in #1107. We will temporarily fix the UI problem by removing the get table button and provide a text field for users to manually supply the table name.

 This fix will go into both 0.4 and 0.5

**Comment by konekoya** [comment]
@eechih What do you think if we include this issue in 0.5.0? As this issue will cause our UI to break , therefore users won't be able to create a jdbc connector inside pipeline.

**Comment by konekoya** [comment]
Misunderstood the issue. The get table button still works in v0.4.0. since jdbc connector is using the deprecated API. But as we're migrating to new metadata API, we won't have a definition for get table component. I'm keeping this issue open as a reminder that we will get rid of the get table button from the UI

**Comment by konekoya** [comment]
@eechih Thanks for clearing things up :)

**Comment by eechih** [comment]
🙂

**Comment by chia7712** [comment]
Please remove the button from 0.5 also. We can reenable the button later (#1107)

**Comment by chia7712** [comment]
Hot fix is hot fix. Don’t block it for a “future” fix.

I

**Comment by konekoya** [comment]
> Please remove the button from both 0.4 and 0.5. We can reenable the button for 0.5 later (#1107)

But the button is still working :) If that's the case should we remove the button anyway?

>Hot fix is hot fix. Don’t block it for a “future” fix.

It won't be a hotfix though. I haven't release 0.4 yet

**Comment by chia7712** [comment]
> But the button is still working :) 

It is impossible to work for #1102. The driver is unavailable to configurator and user is impossible to operate our UI to start jdbc connector

**Comment by konekoya** [comment]
Sorry about the troubles... I will file a PR to remove the get table button :)
Thanks for your patience my friend
