### ISSUE TITLE
Prevent frontend e2e tests from running into an infinite loop

### ISSUE THREAD

**Issue by wu87988622** [oharastream/ohara#1111]
The e2e tests can sometimes run into an infinite loop. In some tests, we do start a worker cluster with an http request to the configurator, and use a recursive function to wait for worker cluster to be ready. This piece of code looks like the root cause for the infinite loop but we will need dig in a bit to see if we can repro this from our local

fix to #1193

**Comment by konekoya** [comment]
@wu87988622 I can recall this issue has been fixed in one of your issues which addressed a bunch of frontend end-to-end test bugs. Could you link to that issue here and so we can close this issue?

**Comment by wu87988622** [comment]
This bug is fix in #1193 i forget link , sorry .
