### ISSUE TITLE
Introduce exactly once into ohara ?

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#1116]
I know there was some discussion on this topic before, but since we have implemented a lot of features and functions on ohara, it is time to discuss the availability of data.
The following components will be affected by this issue:
1. for connector
2. for producer / consumer
3. for streamApp

Currently, streamApp should be supported exactly once for two reasions:
- enable should be no impact (it is config flag)
- user will wish the data should be no-loss in any condition in our ohara environment ;  This means topic -> streamApp -> topic should have high availability

**Comment by saivirtue** [comment]
ping @vitojeng @jackyoh @chia7712 @eechih @wu87988622 @konekoya

**Comment by chia7712** [comment]
I love this feature. However, what we can offer to developers except for kafka’s function?
 
For streamapp, kafka had offered the configurations to set to guarantee exactly once. For connectors, kafka offers many helper methods for developer to address exactly once with their data flow.

 shabondi is a good place to discuss exactly once.

Another important issue which should be discussed before this one is how to evaluate the cost of exactly once for ohara? Should we implements our benchmark first?

**Comment by vitojeng** [comment]
> Another important issue which should be discussed before this one is how to evaluate the cost of exactly once for ohara? Should we implements our benchmark first?

Following is a benchmark table about enable exactly-once:
https://www.pinterest.com/pin/582090320568861050/

**Comment by vitojeng** [comment]
> Currently, streamApp should be supported exactly once for two reasions:
> 
> * enable should be no impact (it is config flag)
> * user will wish the data should be no-loss in any condition in our ohara environment ;  This means topic -> streamApp -> topic should have high availability

Another reason:
* stateful operation in the streamApp need exactly-once to avoid the wrong result in the state store

**Comment by chia7712** [comment]
> Following is a benchmark table about enable exactly-once:

This is a good reference and it is just a reference. We (ohara) needs our performance profiles.

**Comment by vitojeng** [comment]
Certainly.

**Comment by saivirtue** [comment]
Seems we have some conclusion, right?
maybe it's time to move the actual tasks to #1133

**Comment by chia7712** [comment]
> maybe it's time to move the actual tasks to #1133

Please close issue after reaching the consensus. :)

**Comment by chia7712** [comment]
@saivirtue Please add the conclusion to this issue's description. It saves reader's time.
