### ISSUE TITLE
Make jars APIs more friendly to user

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#1121]
- [x] Display the URL on Jar APIs (#1203)
- [x] Worker APIs should show the details of Jar (#1205)

**Comment by chia7712** [comment]
@konekoya @wu87988622  After this issue, worker APIs is able to display the jar's name. I feel ohara manager can provide more readable information on worker page.

**Comment by vitojeng** [comment]
Does this is an umbrella issue?

**Comment by chia7712** [comment]
>Does this is an umbrella issue?

It is just a issue consisting of many PRs so I added the version label to it.

**Comment by vitojeng** [comment]
Got it!

**Comment by konekoya** [comment]
>  I feel ohara manager can provide more readable information on worker page.

/cc @eechih @wu87988622 

Sounds like a good idea. But I will need to take a look at the new response body and see how we can go about it. I'll file another issue to do so.

**Comment by chia7712** [comment]
done and done
