### ISSUE TITLE
[Question] Add a group concept into JarStore ?

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#1151]
We have JarStore APIs which can help manage uploaded jars. Currently there are two kind of jars need to be handle :
1. connector jars
2. streamApp jars

for connector, jar uploading is controlled by worker cluster, which imply **jars are in the worker cluster**
for streamApp, jar uploading is controlled by user assign a `cluster` parameter to point a specific worker cluster ; we cannot **group the jar in a specific worker cluster** by current JarStore API

Do we need a group concept into JarStore?

**Comment by saivirtue** [comment]
/cc @chia7712 
Is adding a group concept a good way to solve this problem ?

**Comment by chia7712** [comment]
This is a good suggestion. We have more and more use cases about custom jars. By the way, apart from the group **label**, we should have a way to manage all jars uploaded to Ohara Configurator. For example, the page show all jars and their usages (used by xxx clusters/services), attributes (name, upload time, group and so on)

ping @eechih @konekoya @vitojeng @wu87988622 

BTW, we can add group label first if it is not a huge work.

**Comment by eechih** [comment]
> we can add group label first if it is not a huge work.

+1

**Comment by vitojeng** [comment]
+1

**Comment by saivirtue** [comment]
Thanks for the feedback, I will fire a issue for label first

**Comment by saivirtue** [comment]
move implementation to #1214
