### ISSUE TITLE
Some of the connector definitions in workers API do not have the correct orderInGroup prop 

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#1157]
We're now using `orderInGroup` prop to sort connector definitions and so it will display in the correct order in the Ohara UI. But I've found out that some of the official connectors like hdfs sink connector doesn't have the right value for this prop.

**Comment by konekoya** [comment]
Another connector which has the same issue -> jdbc source connector

**Comment by konekoya** [comment]
@wu87988622 Does ftp source connector have the same issue?

**Comment by konekoya** [comment]
@chia7712 ✋ Any updates on this issue :)

**Comment by chia7712** [comment]
let me tick off this one
