### ISSUE TITLE
Fix flaky TestK8SStreamApp and TestSshStreamApp

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#1185]
The test pass request with incorrect id

[error report](https://builds.is-land.com.tw/job/PreCommit-OHARA/2097/testReport/junit/)

**Comment by saivirtue** [comment]
I thought this issue will be fix in #1093...should I closed #1093 ?

**Comment by chia7712** [comment]
> I thought this issue will be fix in #1093...should I closed #1093 ?

my bad :( I did not you have raised a issue. Let me close this one

**Comment by saivirtue** [comment]
No problem :)
let me add some comment in #1093
