### ISSUE TITLE
Assign third-party library version in build.yml instead of each dockerfile

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#1188]

**Comment by chia7712** [comment]
Pardon me, what **version** you want to specify via build.yml? third-party version? ohara version?

**Comment by saivirtue** [comment]
> Pardon me, what **version** you want to specify via build.yml? third-party version? ohara version?

The third-party version :)

**Comment by chia7712** [comment]
>The third-party version :)

build.yml had already defined the thirdy-party version. What do you want to add in this issue?

**Comment by saivirtue** [comment]
> build.yml had already defined the thirdy-party version.

That's right. But we still use same version definition in docker file.
for example,
in build.yml, we have
```text
KAFKA_VERSION: 1.0.2
LOG_VERSION: 1.7.25
GRADLE_VERSION: 5.1.1
COMMON_LANG_VERSION: 3.7
ROCKDB_VERSION: 5.7.3
```
But in **streamapp.dockerfile**
```text
ARG KAFKA_VERSION=1.0.2
ARG LOG_VERSION=1.7.25
ARG GRADLE_VERSION=5.1.1
ARG COMMON_LANG_VERSION=3.7
ARG ROCKDB_VERSION=5.7.3
ARG COMMONS_IO=2.4
```

**Comment by chia7712** [comment]
> And we should move out all the 3rd-party version in dockerfiles.

So we have to use docker-compose to build ohara in the future? Removing all pre-defined args from dockerfile obstructs us from building single image via pure docker command. Also, we don’t stict on docker-compose actually. In fact, it is just a tool used in jenkins...

I prefer to remove args from build.yml rather than dockerfile if we do worry about the maintainability.

**Comment by saivirtue** [comment]
Personally, I like use docker-compose (even for single image, we can use `docker-compose build XXX` 
[docker-compose build](https://docs.docker.com/compose/reference/build/)
Also, we can use the build.yml to define some simple service dependency rule (zookeeper -> broker -> worker) to avoid the dependent stale images not pulled.
The disadvantage is, we need to install the additional compose tool besides native docker command.

at any rate, both files have it's own usage, I thought this issue could closed since flexible is everything.
