### ISSUE TITLE
Skip K8S integration test for environment error

### ISSUE THREAD

**Issue by jackyoh** [oharastream/ohara#1208]
目前整合測試的 k8s 環境有異常, 先跳過 k8s 的測試. 環境修復完畢會將 skiptest 取消掉

**Comment by chia7712** [comment]
> 先跳過 k8s 的測試. 環境修復完畢會將 skiptest 取消掉

There are only few PRs created on the weekend and you will fix it on Monday. Hence, it is unnecessary to skip k8s tests now.

**Comment by jackyoh** [comment]
yep.
