### ISSUE TITLE
[Question] How we handle the state of a partial-running cluster?

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#1220]
As discuss [here](https://github.com/oharastream/ohara/pull/1212#discussion_r285419548), what is the correct response for the following situation?
1. create a streamApp cluster with 3 instances
2. Now, the streamApp api is response `state = RUNNING`
3. one of the instance (container) is fail (maybe network timeout)
4. update the cluster state by previous condition, should we change the state from `RUNNING` to `DEAD` ?

**Comment by saivirtue** [comment]
ping
@chia7712 @vitojeng @eechih @konekoya @jackyoh @wu87988622

**Comment by chia7712** [comment]
from my previous comment
```
A cluster means it is doable to tolerant a part of nodes which are dead. For example, we don't say a hadoop cluster is dead even if one of datanodes is gone. I feel we should have the same concept if we have chosen the cluster naming.
Speak clearly, we say a cluster is dead only if we ensure that the cluster does not work anymore.
```

> 我們依舊需要把cluster的狀態反映給使用者

```
This is another issue about how to tell user that a part of nodes (containers) are gone. For instance, we can add a field - deadNodes - to interface ClusterInfo.
```

**Comment by vitojeng** [comment]
與 @chia7712 的意見一致.

StreamApp state = "DEAD" 比較適合用來描述 **streamapp cluster** 完全不可用的情形.
若只是一部份, 以另外的方式描述這個情形比較好. 
UI 的設計也會有相同的情形需要考慮.

**Comment by chia7712** [comment]
>UI 的設計也會有相同的情形需要考慮.

 bad news to @eechih @konekoya @wu87988622  :_

**Comment by saivirtue** [comment]
I almost forgot this question...

From previous conclusion, we should have :
1. cluster (zk, bk, wk, streamApp) should still available (running) even if **partial** nodes are dead.
2. cluster should be considered **dead** if and only if all the belonging nodes are dead.
3. whatever status of nodes, cluster should always be able to fetch from **collie**.
4. support **deadNodes**. (move to issue #1438)

**Comment by saivirtue** [comment]
ping @vitojeng @chia7712 @jackyoh 
sorry for the late response, are we in the same page of this conclusion?

**Comment by chia7712** [comment]
> are we in the same page of this conclusion?

It seems to me the following changes are required.

1. ClusterInfo should carry the dead nodes
1. cluster(name: String) can fetch the cluster even if all containers are “exited”

Also, I have two questions.

1. Should we show the cluster info if all containers are gone (removed)
1. How to save the dead info?

**Comment by saivirtue** [comment]
>1. Should we show the cluster info if all containers are gone (removed)

In this case, I think the cluster should be **removed** also (since there are no actual containers)
> 2. How to save the dead info?

From **collie** interface, we still can get the cluster info from dead containers ; In the actual cluster info, maybe we could add some fields (deadNodes, status) to indicate the cluster is dead.
For example, the zookeeper response could be :
```diff
{
  "name": "cluster00",
  "electionPort": 12347,
  "imageName": "oharastream/zookeeper:0.6-SNAPSHOT",
  "clientPort": 12345,
  "peerPort": 12346,
  "nodeNames": [],
+ "deadNodes": ["node00"],
+ "status": "dead"
}
```

**Comment by chia7712** [comment]
@saivirtue LGTM :)

**Comment by saivirtue** [comment]
The follow-up issue is in #1438.
close this question now.
