### ISSUE TITLE
Upload metrics jar to maven repo

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#1221]
Since `ohara-kafka` module depends on `ohara-metrics` (streamApp uses ohara-kafka), we need to add the upload-script in it.
This issue will create two PRs :

- [x] for master branch (#1222)
- [x] for 0.4branch (#1223)

**Comment by chia7712** [comment]
@saivirtue Please use checkbox instead of list in the description.

before

- for master branch (PR #1222)

after

- [x] for master branch (#1222)

**Comment by saivirtue** [comment]
I will follow the format as #1224...

**Comment by chia7712** [comment]
> I will follow the format as #1224...

嗯? 我還沒更新#1224你要怎麼follow?

**Comment by saivirtue** [comment]
> > I will follow the format as #1224...
> 
> 嗯? 我還沒更新#1224你要怎麼follow?

即時同步XD
加上PR number感覺怪怪的 (link都是用issue number)

**Comment by chia7712** [comment]
> 加上PR number感覺怪怪的 (link都是用issue number)

我是偏好常見的就約定成俗 #xxx 就好

其他例如duplicate to #xxx, moved to issue #xxx 等等才另外說明
