### ISSUE TITLE
UI cannot add ohara node

### ISSUE THREAD

**Issue by HarryChiang143** [oharastream/ohara#1227]
**Describe the bug**
透過Ohara Manager UI 新增 Ohara nodes失敗，並產生 `Unsupported Content-Type, supported: application/json`  Error exception

**To Reproduce**
Steps  the behavior:
1. 安裝k8s master
2. 安裝k8s agent
3. 透過docker command 啟動configurator
4. 透過docker command 啟動manager
5. 透過UI新增節點 > Got Exception

**Screenshots**
![1](https://user-images.githubusercontent.com/46185836/58013126-8e6e1c80-7b28-11e9-852f-83797f70ba8e.png)

<img width="1089" alt="螢幕快照 2019-05-20 下午5 42 31" src="https://user-images.githubusercontent.com/46185836/58012785-d6407400-7b27-11e9-99e7-6a0dd201a35e.png">

**Operation System :**
 - Backend OS & Version: [CentOS 7.6]
 - Frontend OS & Version: [CentOS 7.6]
 - Browser & Version [Chrome 72.0.3626.119 64bit]

**Additional context**
none.

**Comment by konekoya** [comment]
After some investigation with @chia7712 and @jackyoh. This error is originated from k8s and not related to our UI. Cc @jackyoh for further investigation :)

**Comment by jackyoh** [comment]
以上的問題主要是在重新 reset k8s 環境時沒有先把 k8s api server 重新啟動, 造成連不到 k8s api server 的問題. 我會在 k8s 安裝的 README.md 再補充 reset k8s 環境時所要的連結.

**Comment by HarryChiang143** [comment]
The root cause was the older DNS server not closed when i install the new ohara stream version, so if u already installed the older version , please double check the 8080 port not be use before installing the new version.

>sudo lsof -i:8080

if port in use, please kill the current process

>sudo kill -9 $PID
