### ISSUE TITLE
OharaStream 0.4.1 Release

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#1229]
- [x] Create `0.4.1` docker images
- [x] Create a new draft release with a title of `0.4.1`
- [ ] ~Update docker image version in ohara codebase from `0.4.0` to `0.4.1-SNAPSHOT`~
- [x] Update docker image version in our codebase from `0.4.0` to `0.4.1`
- [x] Upload jars to Bintray repo
- [x] Add a new tag `0.4.1` and push to oharastream repo
- [x] Upload `0.4.1` build artifact to `0.4.1` release page
- [x] Deploy `0.4.1` to demo environment

**Comment by chia7712** [comment]
This issue is blocked by
- [ ] #1224 The scala module's source jar is not uploaded to our repo center
