### ISSUE TITLE
remove the file size limit for streamApp jar

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#1234]
We have limit the upload file size < 1MB, which seems too small for our user...
For a workaround, we remove this restriction.
- [x] for master branch (#1236)
- [x] for 0.4 branch (#1235)

**Comment by DavidMi-1** [comment]
great !! waiting for it .

**Comment by konekoya** [comment]
0.4.1 PR has been merged :)

**Comment by konekoya** [comment]
> great !! waiting for it .

If everything goes well. We'll be releasing v0.4.1 on this Thu

**Comment by DavidMi-1** [comment]
> > great !! waiting for it .
> 
> If everything goes well. We'll be releasing v0.4.1 on this Thu

got it, tks.
