### ISSUE TITLE
Create Topic Failed cause Futures timed out after [25 seconds]

### ISSUE THREAD

**Issue by HarryChiang143** [oharastream/ohara#1240]
**Describe the bug**
新建topic碰到timeout 問題

**To Reproduce**
1. K8S流程建立configurator及manager
2. 啟動ZK&BK
3. 新建topic碰到timeout 問題(尚未新增connect service)

**Expected behavior**
理論上應該要可以建立topic。

**Screenshots**
建立Topic時撞到timeout exception
<img width="1440" alt="螢幕快照 2019-05-21 下午6 01 18" src="https://user-images.githubusercontent.com/46185836/58087582-6697bb00-7bf3-11e9-88eb-2304ed4baf82.png">

Configuartor logs:
![螢幕快照 2019-05-21 下午6 00 08](https://user-images.githubusercontent.com/46185836/58087612-71eae680-7bf3-11e9-9282-20245c2c7433.png)

![螢幕快照 2019-05-21 下午6 00 43](https://user-images.githubusercontent.com/46185836/58087617-76170400-7bf3-11e9-9736-bfb141d21973.png)

*且當發生這個exception後，其他UI頁面讀取也發生問題，重整也沒有用*
<img width="1134" alt="螢幕快照 2019-05-21 下午6 07 30" src="https://user-images.githubusercontent.com/46185836/58087645-8b8c2e00-7bf3-11e9-8285-d15bced38397.png">
<img width="1131" alt="螢幕快照 2019-05-21 下午6 07 34" src="https://user-images.githubusercontent.com/46185836/58087650-8dee8800-7bf3-11e9-8cc3-65ecf1af7209.png">
<img width="1185" alt="螢幕快照 2019-05-21 下午6 07 38" src="https://user-images.githubusercontent.com/46185836/58087655-8fb84b80-7bf3-11e9-8749-2dff51f217b4.png">
<img width="651" alt="螢幕快照 2019-05-21 下午6 07 48" src="https://user-images.githubusercontent.com/46185836/58087659-90e97880-7bf3-11e9-9c55-cc307069d3c6.png">

**Operation System (please complete the following information):**
- Backend OS & Version: [CentOS 7.6]
- Frontend OS & Version: [CentOS 7.6]
- Browser & Version [Chrome 72.0.3626.119 64bit]

**Additional context**
none.

**Comment by chia7712** [comment]
@HarryChiang143 Please close this issue if it is resolved.

**Comment by HarryChiang143** [comment]
The root cause by the ohara stream will stored the docker network info in /var/lib/docker/network/file/local-ky.db
<img width="412" alt="螢幕快照 2019-05-24 上午10 08 00" src="https://user-images.githubusercontent.com/46185836/58297850-e009f600-7e0b-11e9-8981-830737bac167.png">

If re-install the ohara stream through by kubernetes script(k8s-master-install.sh/k8s-worker-install.sh), it will lunch the k8s-pre-install.sh to re-install docker-ce, but it not clean the older network setting if exist. so it will mount **TWO** network when docker lunch. and **the K8S pods(configurator connect to zk or bk) may not be workable.** 

@jackyoh could u plz add the command to clean docker network setting if exist on  `k8s-pre-install.sh`

**Comment by HarryChiang143** [comment]
@jackyoh 
I open the new issue #1282 and @ u to fixed this problem.

**Comment by jackyoh** [comment]
ok, 收到
