### ISSUE TITLE
Enable streamapp image to show the revision

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#1251]
Support the same version format for streamApp.

**Comment by chia7712** [comment]
@saivirtue It is ok to just file a PR for #1026, and add yourself to the assignee of #1026 at the same time. We don't need to file another issue for trivial stuff.

**Comment by chia7712** [comment]
Also, it is ok to revise the description of #1026 even if it is not opened by you. No one will accuse you of touching not-belong-to-you issue.

**Comment by chia7712** [comment]
And for another one, please update the description of #1026 if you **have to** file another issue. It is not suitable to fork another issue and then leave the origin one. It is painful to origin reporter/assignees that they have to trace your forked issue and then see what similar functions you take away.

**Comment by saivirtue** [comment]
> It is ok to just file a PR for #1026

OK, close this issue now
