### ISSUE TITLE
Remove ClusterInfo from ClusterCache and MeterCache

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#1254]
The cluster info is used in getter of cache but it is not used by comparison. Hence, the older key is not replaced by new one, and the cluster info is always the stale one. 

- [x] for master (#1255)
- [x] for 0.4 (#1263) (this requires #1172)

**Comment by chia7712** [comment]
@konekoya This is a critical bug since it causes the data miss. Could I backport this one to 0.4?

**Comment by konekoya** [comment]
> @konekoya This is a critical bug since it causes the data miss. Could I backport this one to 0.4?

Sure thing, keep them coming :)
