### ISSUE TITLE
[Question] I met a question abount install ohara through docker

### ISSUE THREAD

**Issue by louie5486** [oharastream/ohara#1257]
I have one host,and my enviroment: 
centos 7.6
docker 18.09.6
host ip: 192.168.122.1

run step:
1.docker run --rm --add-host ohara-test-node1:192.168.122.1 -p 12345:12345 oharastream/configutor:0.4.0 --port 12345

2.docker run --rm -p 5050:5050 oharastream/manager:0.4.0 --port 5050 --configurator http://192.168.122.1:12345/v0

when i run step 2,  it's broken......

and result:
[HPM] Proxy created: /  ->  http://192.168.122.1:12345/v0
[HPM] Proxy rewrite rule created: "/api" ~> ""
Ohara manager is running at port: 5050
Configurator API: http://192.168.122.1:12345/v0

  --configurator: we're not able to connect to http://192.168.122.1:12345/v0

  Please make sure your Configurator is running at http://192.168.122.1:12345/v0

**Comment by louie5486** [comment]
I'am sure configrator in docker in running~

and got result with web api:(http://192.168.122.1:12345/v0)
-->  Unsupported API: v0

**Comment by saivirtue** [comment]
> --> Unsupported API: v0

This is because we cannot handle the uri : http://192.168.122.1:12345/v0
you can test the api like `http://192.168.122.1:12345/v0/nodes`

**Comment by chia7712** [comment]
@louie5486 Please take a look at [docs](https://github.com/oharastream/ohara/tree/master/docs)

**Comment by louie5486** [comment]
> > --> Unsupported API: v0
> 
> This is because we cannot handle the uri : http://192.168.122.1:12345/v0
> you can test the api like `http://192.168.122.1:12345/v0/nodes`

I try it ,and get result --> []

**Comment by louie5486** [comment]
> @louie5486 Please take a look at [docs](https://github.com/oharastream/ohara/tree/master/docs)

thank you for reply infomaction, but my question is , why the manager reulst--->
[HPM] Proxy created: / -> http://192.168.122.1:12345/v0
[HPM] Proxy rewrite rule created: "/api" ~> ""
Ohara manager is running at port: 5050
Configurator API: http://192.168.122.1:12345/v0

--configurator: we're not able to connect to http://192.168.122.1:12345/v0

Please make sure your Configurator is running at http://192.168.122.1:12345/v0

**Comment by chia7712** [comment]
> and the manager docker is exited......

Please check your firewall (see [docs](https://github.com/oharastream/ohara/blob/master/docs/user_guide.md))

**Comment by louie5486** [comment]
I check firewall policy , all chain is ACCEPT.
and I use curl command in that machine to test configrator service url,It look like block with firewall.
`curl http://192.168.122.1:12345/v0`
result-
`Unsupported API: v0`

**Comment by chia7712** [comment]
http://192.168.122.1:12345/v0 is the root of APIs and it always returns “unsupported”. Please see docs to find the available restful APIs.

For example, /v0/nodes returns the nodes hosted by configurator.

**Comment by louie5486** [comment]
> http://192.168.122.1:12345/v0 is the root of APIs and it always returns “unsupported”. Please see docs to find the available restful APIs.
> 
> For example, /v0/nodes returns the nodes hosted by configurator.

thank's, I know.
but I don't know, There are those apis that are necessary between the two services??
So I can't rule out the problem.
and why 'Manager service' run with result  `we're not able to connect to http://192.168.122.1:12345/v0`。
I have verified firewall is normal (use curl command for test),what's the problem with 'Manager service'???

**Comment by chia7712** [comment]
> There are those apis that are necessary between the two services??

Ohara Manager (UI) depends on Ohara Configurator's restful APIs so Manager requires the root of APIs to compose the other APIs.

> we're not able to connect to http://192.168.122.1:12345/v0

In fact, Ohara Manager test Configurator by sending request to http://192.168.122.1:12345/v0/info. What you see is just a error message.

> I have verified firewall is normal

Have you test the connection between your docker containers? For example, please run another container and then try to connect to Ohara Configurator from the container. For example:
```sh
$ docker run --rm -p 12345:12345 -d oharastream/configurator:0.5-SNAPSHOT --port 12345
$ docker run --rm centos:7 /bin/bash -c "curl http://192.168.56.150:12345/v0/info
```

Noted that above IP (192.168.56.150:12345) should be replaced by your container host's address.

**Comment by louie5486** [comment]
I got it, it's routing table between docker container problems,
the solution ref: [NO ROUTE TO HOST network request from container to host-ip:port published from other container](https://forums.docker.com/t/no-route-to-host-network-request-from-container-to-host-ip-port-published-from-other-container/39063/5) 。

thank you @chia7712 , I suggest you have documentation on the environment, plus this necessary settings.

**Comment by chia7712** [comment]
>  I suggest you have documentation on the environment, plus this necessary settings.

@louie5486 In fact, I did not understand the network envs you have set up, and you didn't share it to us, by the way. As our [docs](https://github.com/oharastream/ohara/blob/master/docs/user_guide.md#network-configurations) say, users have to make sure the connection between containers must be **available**, and of course, we can document all cases one by one. However, it is hard to include all cases and all we can do (similar to hadoop) is to list all checklists to all user and then expect they are able to check them one by one.
