### ISSUE TITLE
Ohara Configurator should return the link to docs instead of unsupported apis

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#1258]
inspired by #1257. The error message should be the lighthouse of user.

**Comment by chia7712** [comment]
@eechih Any suggested format of error message which can point to the docs? How about the following response?
```json
{
  "code": "Unsupported APIs: xxxxx",
  "message": "please see https://github.com/oharastream/ohara/blob/master/docs/rest_interface.md to find the available APIs",
  "stack": "just the error stack"
}
```

**Comment by eechih** [comment]
@chia7712 建議 url 獨立出來，會比較清楚。

範例一： (推薦)
{
  "code": "Unsupported APIs: xxxxx",
  "message": "please see link to find the available APIs",
  "stack": "just the error stack"
  "links": {
    "api": "https://github.com/oharastream/ohara/blob/master/docs/rest_interface.md"
  }
}

範例二：
{
  "code": "Unsupported APIs: xxxxx",
  "message": "please see link to find the available APIs",
  "stack": "just the error stack"
  "api_url": "https://github.com/oharastream/ohara/blob/master/docs/rest_interface.md"
}

**Comment by chia7712** [comment]
>建議 url 獨立出來，會比較清楚。

Copy that. I will address the first format. :)
