### ISSUE TITLE
[docs] Unable to start ohara manager by following the documentation

### ISSUE THREAD

**Issue by louie5486** [oharastream/ohara#1266]
I  read document from [ohara install doc](https://github.com/oharastream/ohara/blob/master/docs/user_guide.md#installation)

The installation process is as follows-
step by step:

#### Step 1:
Install Centos7.6 with mini install .

#### Step 2:
install docker-ce ,[Get Docker CE for CentOS](https://docs.docker.com/install/linux/docker-ce/centos/)

#### Step 3:
download oharastream docker images.
docker pull oharastream/broker:0.4.0
docker pull oharastream/zookeeper:0.4.0
docker pull oharastream/connect-worker:0.4.0
docker pull oharastream/configurator:0.4.0
docker pull oharastream/manager:0.4.0
docker pull oharastream/streamapp:0.4.0

#### Step 4:
Start oharastream/configurator

```sh
docker run --rm -d --add-host ohara-test-node1:192.168.56.130 -p 12345:12345 oharastream/configurator:0.4.0 --port 12345
```

And oharastream/manager
```sh
docker run --rm -d -p 5050:5050 oharastream/manager:0.4.0 --port 5050 --configurator http://192.168.56.130:12345/v0
```

The problem is oharastream/manager execute process can't start??
when I call the configrator api through another normal container, I found that can't call configrator api in container.
It seems to be a problem with network blocking between with host and container.
when I setting firewall policy in host(192.168.56.130),and try again, It work, yes!!

```
firewall-cmd --zone=public --permanent --add-rich-rule='rule family="ipv4" source address="172.18.0.0/16" accept'
```

```
firewall-cmd --zone=public --permanent --add-rich-rule='rule family="ipv4" source address="172.17.0.0/16" accept'
```

When installing docker package, I found the default network communication is blocked between docker and host, share this experience to everyone

**Comment by chia7712** [comment]
>firewall-cmd --zone=public --permanent --add-rich-rule='rule family="ipv4" source address="172.17.0.0/16" accept' 

It would be better to use network interface than ip address since the ip may be changed in the future. Also, adding the docker network interface to trust zone is more simple for your case. For example:

```sh
sudo firewall-cmd --zone=trusted --permanent --add-interface=docker0
```

(In most cases, network interface of docker is called ```docker0```)

**Comment by chia7712** [comment]
@louie5486 Feel free to file the PR for this issue :)

**Comment by louie5486** [comment]
> > firewall-cmd --zone=public --permanent --add-rich-rule='rule family="ipv4" source address="172.17.0.0/16" accept'
> 
> It would be better to use network interface than ip address since the ip may be changed in the future. Also, adding the docker network interface to trust zone is more simple for your case. For example:
> 
> ```shell
> sudo firewall-cmd --zone=trusted --permanent --add-interface=docker0
> ```
> 
> (In most cases, network interface of docker is called `docker0`)

This idea is good, I will try,thank you.

**Comment by vitojeng** [comment]
@louie5486 Superb! 👍

**Comment by louie5486** [comment]
I am happy to help improve this, but how to 『file the PR for this issue』，Please give help ，thank you~

**Comment by konekoya** [comment]
> I am happy to help improve this, but how to 『file the PR for this issue』，Please give help ，thank you~

You can start from our contribution docs here:
https://github.com/oharastream/ohara/blob/master/CONTRIBUTING.md

**Comment by konekoya** [comment]
@louie5486 Is it okay to close this issue? Looks like #1285 has been merged :)
