### ISSUE TITLE
Add a command-line option to gradle build to turn on `ignoreFailures` 

### ISSUE THREAD

**Issue by vitojeng** [oharastream/ohara#1272]
Gradle have an [ignoreFailures](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.testing.Test.html#org.gradle.api.tasks.testing.Test:ignoreFailures) to specifies whether the build should break when the verifications performed by the testing fail.

The default is false, but sometimes we need to turn it on.
So we need a command-line option to specify `ignoreFailures` to true.

**Comment by chia7712** [comment]
Gradle already expose a similar option "--continue",

**Comment by vitojeng** [comment]
Got it, thanks!
