### ISSUE TITLE
Add a command to clean up docker network setting if it exists in k8s-pre-install.sh

### ISSUE THREAD

**Issue by HarryChiang143** [oharastream/ohara#1282]
link to #1240 

@jackyoh cheers~

**Comment by chia7712** [comment]
@HarryChiang143 I add you to assignee. Please help us confirm this issue is indeed resolved.

**Comment by jackyoh** [comment]
@HarryChiang143  我已經把檢查 docker 的 script 修改好了. 我先把這個 issue 關閉, 如果有發現問題在 reopen 此 issue
