### ISSUE TITLE
OharaStream 0.5 release

### ISSUE THREAD

**Issue by eechih** [oharastream/ohara#1299]
- [x] Create 0.5 branch (base on last commit of the frozen day -> 6/3)
- [x] Update ohara's master branch version to 0.6-SNAPSHOT (Issue #1363 )
- [ ] ~~Remove unused (or unnecessary) functions from 0.5 branch~~
- [x] deploy to demo environment
- [x] Add a change log in release wiki page [release note](https://github.com/oharastream/ohara/releases)
  - [x] Highlight
  - [x] Changlog
- [x] Update version of 0.5 branch to 0.5.0 (Issue #1420 )
- [x] Update Bintray repo
- [x] Add tags in release wiki page
- [x] Add 0.5 binaries to GitHub download
- [x] Delivery 0.5.0 to Docker hub
- [x] Send an announcement email

**Comment by eechih** [comment]
ping @vitojeng @chia7712 @jackyoh @saivirtue @konekoya @wu87988622 
Could you help to highlight the feature of 0.5 release? And offer me more description for the feature. Thanks. ^^

**Comment by chia7712** [comment]
persistent store of Ohara Configurator: Ohara, now, supports to store all your data in RocksDB. see [docs](https://github.com/oharastream/ohara/blob/master/docs/user_guide.md#store-of-ohara-configurator) for more details.

**Comment by eechih** [comment]
Thanks. @chia7712

**Comment by saivirtue** [comment]
- streamApp could delete from Ohara Stream Manager now
- more straightforward streamApp java api and more examples for development. See [doc](https://github.com/oharastream/ohara/blob/0.5/docs/custom_streamapp.md) for more details.

**Comment by eechih** [comment]
Thanks. @saivirtue

**Comment by chia7712** [comment]
@eechih Please share the new (text) connector via this release as well.

**Comment by eechih** [comment]
@chia7712 OK

**Comment by vitojeng** [comment]
* Update kafka version from 1.0.2 to 2.2.0

**Comment by konekoya** [comment]
@eechih new features of Ohara manager:

- we now support deleting streamApp from the UI
- Upgraded official connectors to use the custom connector APIs

**Comment by eechih** [comment]
Thanks. @vitojeng @konekoya

**Comment by eechih** [comment]
- **CSV Source Connector**: Ohara now support official source connector of CSV to easily customize your connector

**Comment by eechih** [comment]
ping @chia7712 @saivirtue @vitojeng @konekoya  Could you review the Highlights? thanks.

## Highlights
- **Upgrading Kafka**: Update kafka version from `1.0.2` to `2.2.0`
- **Persistent store of Ohara Configurator**: Ohara, now, supports to store all your data in RocksDB. see [docs](https://github.com/oharastream/ohara/blob/master/docs/user_guide.md#store-of-ohara-configurator)  for more details.
- **Developer docs**: More straightforward streamApp java api and more examples for development. See [docs](https://github.com/oharastream/ohara/blob/0.5/docs/custom_streamapp.md) for more details.
- **Manager**: 
  - We now support deleting streamApp from the UI.
  - Upgraded official connectors to use the custom connector APIs.
- **Custom Connector**: We now support official source task of CSV to easily customize your connector.

**Comment by konekoya** [comment]
A few suggestions, but not sure if this has changed you guys original thoughts?


> Persistent store of Ohara Configurator: Ohara, now, supports to store all your data in RocksDB. see docs for more details.

Ohara now supports storing all of your data in RocksDB. See docs for more deatils

> More straightforward streamApp java api and more examples for development. See docs for more details.

Improved streamApp Java API documentation which is more straightforward and easier to understand. In addition, we've also added a few more examples to better assist your development process.

**Comment by chia7712** [comment]
> Ohara now supports storing all of your data in RocksDB. See docs for more deatils

This description LGTM :)

**Comment by eechih** [comment]
Thanks. @konekoya

**Comment by vitojeng** [comment]
> * **Upgrading Kafka**: Update kafka version from `1.0.2` to `2.2.0`

Upgrade Kafka version to 2.2.0

would be better?

**Comment by eechih** [comment]
> Upgrade Kafka version to 2.2.0

It is great.
