### ISSUE TITLE
Increase file size limit in JarRoute and StreamRoute

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#1302]
From [document](https://doc.akka.io/docs/akka-http/current/configuration.html):
```diff
# Default maximum content length which should not be exceeded by incoming request entities.
# Can be changed at runtime (to a higher or lower value) via the `HttpEntity::withSizeLimit` method.
# Note that it is not necessarily a problem to set this to a high value as all stream operations
# are always properly backpressured.
# Nevertheless you might want to apply some limit in order to prevent a single client from consuming
# an excessive amount of server resources.
#
# Set to `infinite` to completely disable entity length checks. (Even then you can still apply one
# programmatically via `withSizeLimit`.)
max-content-length = 8m

# The maximum number of bytes to allow when reading the entire entity into memory with `toStrict`
# (which is used by the `toStrictEntity` and `extractStrictEntity` directives)
max-to-strict-bytes = 8m
```

Since streamApp use `toStrict` to solve the [issue](https://github.com/akka/akka-http/issues/1216#issuecomment-311973943), we need to increase the file limit configuration to a suitable value, says **50m** by programmatically use `withSizeLimit`.
This issue will add the limit into:
- JarRoute upload api
- StreamRoute upload api

The StreamRoute upload api will be refactor in #1252

**Comment by chia7712** [comment]
Are you talking about file size? If so, I recommend to change only the jar route instead of global configs.

For example, we can compose the file upload directive by withSizeLimit

**Comment by saivirtue** [comment]
> For example, we can compose the file upload directive by withSizeLimit

As far as I know, the default `max-to-strict-bytes` is check before `withSizeLimit` ; User will face an exception like **Request Content-Length XXXX exceeds the configured limit of 8388608**.
I think the cause is from global config since I don't set any limit in stream route

**Comment by saivirtue** [comment]
BTW, the error is thrown by streamApp upload api instead of jarRoute...which inspired me the error is from `toStrict` part...

**Comment by vitojeng** [comment]
+1

The user only can run streamapp with fat-jar at this time, so we really need to increase the file size limitation when upload streamapp jar.

**Comment by chia7712** [comment]
> As far as I know, the default max-to-strict-bytes is check before withSizeLimit

Not really. please read the [docs](https://doc.akka.io/docs/akka-http/current/routing-dsl/directives/misc-directives/withSizeLimit.html) 

```
. Limit given as parameter overrides limit configured with akka.http.parsing.max-content-length.
```

**Comment by saivirtue** [comment]
Hmm...interesting. I was seeing this  [toStrict doc](https://doc.akka.io/docs/akka-http/current/routing-dsl/directives/basic-directives/toStrictEntity.html#description) instead.
May can give a try to restrict file size in the streamRoute only.

**Comment by chia7712** [comment]
The docs you attached also remind that 
```
 The size limit can be configured globally with akka.http.parsing.max-content-length or overridden by wrapping with withSizeLimit or withoutSizeLimit directive.
```

> Maybe can give a try to restrict file size in the streamRoute only.

There already a test case of uploading file to jar route. You can wrap the jar route via WithSizeLimit and then increase the file size in TestJarRoute.

**Comment by saivirtue** [comment]
There are some overlap works with #1252. Maybe add `WithSizeLimit` to StreamRoute first, then refactor the implementation to JarRoute in #1252 will be better?

**Comment by chia7712** [comment]
> Maybe add WithSizeLimit to StreamRoute first, then refactor the implementation to JarRoute in #1252 will be better?

Please make both streamroute and jarroute benefit from WithSizeLimit. And the refactor can move to 0.6.

**Comment by saivirtue** [comment]
> Please make both streamroute and jarroute benefit

Sure. Updating the description to fit this conclusion.

**Comment by chia7712** [comment]
Nice one!
