### ISSUE TITLE
Fix unstable k8s IT tests

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#1313]
see [here](https://builds.is-land.com.tw/job/PreCommit-OHARA/2369/)

**Comment by chia7712** [comment]
FYI @jackyoh

**Comment by jackyoh** [comment]
* com.island.ohara.it.agent.k8s.TestK8SSimpleCollie.testLog 是因為把 kafka 版本升級 log 訊息有修改, 造成測試程式找不到字串, 而發生 timeout.
* 其它的錯誤有調整 timeout 的設定, 再看是否可以解決 timeout 的問題

please refer PR #1314
