### ISSUE TITLE
Connector config forms are not updating correctly when making changes

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#1333]
Need to look into this and see if it's causing by final form?

__UPDATED:__ This turned out to be an issue causing by final form and Mui. We're passing an event handler which handles the logic of updating text field and select components when users have triggered some update event like `onChange`. This bug is caused by passing that handle to Mui. So a very simple fix is just not passing that handle to the Mui at all and leave the whole updating logic to final form.

- [ ] A quick fix
- [ ] Better solution that completely get rid of this behavior

**Comment by wu87988622** [comment]
> /cc @wu87988622 Not sure if there are other components which also have the same issue?

Maybe only in here, because we in pipeline overwrite onChange fun to save input value, other mui + final from page only use default onChange fun, but i will to checking other page is fine.

**Comment by konekoya** [comment]
I have no idea. I've tried not to pass an `onChange` handler, but the bug is still there. I might need to read thru the final form docs see if there's something that may help

**Comment by konekoya** [comment]
@wu87988622 #1338 should have fixed this issue. But it's a workaround, not a complete solution. We should come up with something that's less hacky and be easier to maintain in the long run :)
