### ISSUE TITLE
[Question] Could we use fixed hostname for configurator in IT test?

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#1356]
I found that when we run an IT test, it will create a temporary container for configurator. The container <hostname, ip> configuration is random and could not remote connect from other remote hosts if we use the following way to create a configurator :
```
Configurator.builder().build()
```
Since the hostname is used to create jar-downloaded url, we could not download a jar in any other hosts if the jar url is like `http://0f53a0bed78c:34857/v0/downloadJars/56bd89eeda.jar`, it could be download in the host which creates the container only.

Is there a way to avoid this problem?

**Comment by chia7712** [comment]
There is already a IT case facing this issue. The IT case requires a env variable to set the suitable hostname to Configurator. You can see [this test](https://github.com/oharastream/ohara/blob/master/ohara-it/src/test/scala/com/island/ohara/it/agent/ssh/TestLoadCustomJarToWorkerCluster.scala) for more details.

**Comment by saivirtue** [comment]
> There is already a IT case facing this issue. The IT case requires a env variable to set the suitable hostname to Configurator. You can see [this test](https://github.com/oharastream/ohara/blob/master/ohara-it/src/test/scala/com/island/ohara/it/agent/ssh/TestLoadCustomJarToWorkerCluster.scala) for more details.

Thanks for the help :)
