### ISSUE TITLE
Integration test timeout exception for test topic on TestK8SClusterCollie#testMultiBkClustersOnSingleNode

### ISSUE THREAD

**Issue by jackyoh** [oharastream/ohara#1358]
目前在整合測試 TestK8SClusterCollie#testMultiBkClustersOnSingleNode 當執行到 testTopic , 呼叫檢查 topic 的內容時常會發生 OharaTimeOutException.

主要發生 OharaTimeOutException 的程式碼如下：
```
result(bk_clusters()).foreach { broker =>
  testTopic(broker)
}
```
通常在第一次執行 testTopic 可以順利的把 topic 建立起來, producer 寫入資料, consumer 取資料出來. 但是測試到了第二個 cluster 的 broker 之後就會在 create topic 的 awiat 方法等待建立 topic 之後就發生了 OharaTimeOutException 的測試.

有另外去寫建立 topic 和 producer consumer 的程式, 然後直接連到測試程式所建立的二個 cluster, 都可以順利的把 topic 建立起來然後使用 producer 寫入資料到 topic 和 consumer 取出資料. 

目前還沒找到實際的解決方法, 先開個 issue 紀錄有此問題.

**Comment by chia7712** [comment]
I'm fixing the IT and then notice this one. Is there a conclusion for this issue?
