### ISSUE TITLE
Fix flaky test of TestPageViewRegionExample

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#1367]
Currently, we use a special `appId` to make the test more stable, this needs a further survey and record result here.

**Comment by saivirtue** [comment]
目前追蹤狀況：
1. 在kafka source code -> `KStreamKTableJoinProcessor` -> `valueGetter` 會取不到
2. leftjoin()的join table會把資料存到internal topic，從rocksdb取出

**Comment by saivirtue** [comment]
the supplier of Materialized seems cause the leftjoin will get `null`...
use `Stores.inMemoryKeyValueStore()` has no problem.

**Comment by chia7712** [comment]
> use Stores.inMemoryKeyValueStore() has no problem.

Seems error is caused by time offset. Could you make following changes:

1. produce data after starting streamapp
1. produce join data first
1. sleep 3 seconds (wait for internal topic)
1. Produce be-joined data

**Comment by saivirtue** [comment]
I'll git it a try, thanks!

**Comment by saivirtue** [comment]
>1. produce data after starting streamapp
> 2. produce join data first
> 3. sleep 3 seconds (wait for internal topic)
> 4. Produce be-joined data

With no luck...the test still unstable.

**Comment by chia7712** [comment]
> With no luck...the test still unstable.

maybe you don't give enough time to wait. see my patch
[fix_1367.txt](https://github.com/oharastream/ohara/files/3260242/fix_1367.txt)

**Comment by saivirtue** [comment]
strange behavior... All I **did** are exactly as your code except I don't initial a **private final** object...
and suddenly, all things seems stable until now (test for 10+)
