### ISSUE TITLE
Adjust the Demo-Ohara job of Jenkins to use RocksDB as default store for Configurator

### ISSUE THREAD

**Issue by eechih** [oharastream/ohara#1373]
Adjust the Demo-Ohara job of Jenkins to use RocksDB as default store for Configurator

**Comment by chia7712** [comment]
The default store is already based on rocksdb. All you have to do is mount a local folder to the Configurator container.

**Comment by eechih** [comment]
Yes, I only add the following two lines to the command for running configurator:
```
-v /tmp/configurator:/home/ohara/configurator
--folder /home/ohara/configurator  
```
