### ISSUE TITLE
Do not run frontend e2e tests if create services failed

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#1379]
Prior to a frontend's e2e test run, a handful of services are required to spin off. There are possible errors or problems that could occur during this phase, but we're not handling them in the script right now. This makes our e2e test runs sometimes look like passed but in fact, they failed. 

We can address this issue by __NOT__ generating a test report and not running the e2e tests at all if there are errors occurred while creating these services.

**Comment by konekoya** [comment]
@chia7712 I've added some logic to ensure that when a test run fails in its creating service phase won't generate a test report. Please see test https://builds.is-land.com.tw/job/PreCommit-OHARA/2554/

But Jenkins still treated this as a successful test run. Was it because we were mixing unit tests with e2e tests and so even though there wasn't a e2e test report but the unit test report made Jenkins think it's passed?

**Comment by chia7712** [comment]
> Was it because we were mixing unit tests with e2e tests and so even though there wasn't a e2e test report but the unit test report made Jenkins think it's a passing test run anyway?

You are right. Let me fix it for our jenkins :)

**Comment by konekoya** [comment]
> You are right. Let me fix it for our jenkins :)

Thanks and fist bump! Get some rest though @@

**Comment by konekoya** [comment]
Thanks for the help @chia7712 :)
