### ISSUE TITLE
Cannot run FtpSinkConnector normally in pipeline

### ISSUE THREAD

**Issue by eechih** [oharastream/ohara#1388]
**Describe the bug**
無法啟動 Ftp Source Connector，錯誤訊息如下：
```
write header
1: Missing required configuration "ftp.needHeader" which has no default value.
2: ftp.needHeader is required!
```

**Operation System (please complete the following information):**
 - Backend OS & Version: CentOS 7.2
 - Frontend OS & Version: macOS 10.14.1
 - Browser & Version: Chrome 74.0.3729.169

**Ohara Version**
 - 0.5-SNAPSHOT
 - Build on 2019-06-03 06:48:00 

__Fix should go in__
- [x] 0.5.0 (#1402)
- [x] 0.6.0 (#1390)

**Comment by eechih** [comment]
ping @konekoya @wu87988622 麻煩幫忙看一下這個問題，謝謝。

**Comment by konekoya** [comment]
@eechih Thanks for reporting. This is a definition that we miss to render. I'll create a PR to fix this!

**Comment by eechih** [comment]
@konekoya This problem have tested successful on 0.5 branch. You can close this issue. Thank you very much. :)

**Comment by konekoya** [comment]
Thank you for the help @eechih 💯
