### ISSUE TITLE
ConnectorRoute ought to check the existence of connector before fetching status

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#1396]
The error message is noisy...

- [x] for master (#1398)
- [x] for 0.5 (#1401)

**Comment by chia7712** [comment]
@eechih This issue, which is related to #1387, tries to eliminate the weird error message from configurator. Do you want to this in 0.5?

**Comment by eechih** [comment]
Please resolve this bug at 0.5 too. Thanks. @chia7712
