### ISSUE TITLE
測試 OharaStream 是否有支援 K8S v1.14.2

### ISSUE THREAD

**Issue by jackyoh** [oharastream/ohara#1422]
在 #1371 的 issue 裡發現 QA2 的 k8s 環境有問題, 目前已經將 k8s 的版本降成 v1.14.1 解決了 #1371 的問題. 

目前懷疑是 k8s v.1.14.2 API 的 json 格式有做修改, 因此要找個時間來做測試並且要在文件裡註明目前 ohara 支援 k8s 的版本

**Comment by chia7712** [comment]
>  k8s v.1.14.2 API

1.14.1 -> 1.14.2 ? it does be terrible if this **patch update** break the compatibility.

**Comment by jackyoh** [comment]
這個問題我還需要去做確認, 是我的程式沒寫好還是真的有相容性的問題. 順便還會去補測試程式

**Comment by jackyoh** [comment]
目前看起來 OharaStream 不支援 v1.14.2 的版本
