### ISSUE TITLE
[Question] Remove rename operation of streamApp in manager?

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#1426]
For the new UI (workspace) consistency, rename streamApp should be not supported in upload page ; User can still use API to upload a jar with `newName` as worker plugin did.

**Comment by saivirtue** [comment]
Does anyone have concerns?

**Comment by chia7712** [comment]
Renaming a object should be disabled from all ops of UI since we are getting rid of id. :)

**Comment by konekoya** [comment]
Sound good to me +1

**Comment by jackyoh** [comment]
+1

**Comment by saivirtue** [comment]
Seems we all on the same conclusion : **Remove the renaming api from streamApp**
close this question.
