### ISSUE TITLE
[Question] 討論解決 JDBC Source Connector 查詢資料 OutOfMemory 的問題

### ISSUE THREAD

**Issue by jackyoh** [oharastream/ohara#1431]
目前想到二種方法來解決 JDBC Source Connector 查詢資料量較大時發生 OutOfMemory 的問題：

**1.JDBC 的 PreparedStatement.setFetchSize 設定 ResultSet 每次從 table 撈出來的資料筆數**
使用此方法做修改, 修改程式碼的量不會太大. 只要加上 PreparedStatement.setFetchSize 的設定並且增加 config 的設定讓使用者可以決定 ResultSet 取出的筆數.

缺點就是當在 JDBC Source Connector 在撈資料寫到 kafka topic 的過程中, 如果 JDBC Source Connector 程式被意外中止, 這時還沒有把 timestamp 的資訊存到 topic 裡. 重新啟動 connector 後原本的資料也會再被重新撈一次. 所以 kafka topic 的資料有可能會發生重複的問題.

**2.在 SQL 的查詢語法裡面加入 LIMIT 的查詢條件**
使用此方法需要調整 JDBC Source Connector SQL 語法的寫法, 增加 LIMIT 的條件做到分頁的功能, 限制查詢資料的筆數, 使用此方法修改的程式碼會較多, 像是 SQL 語法,程式邏輯決定分頁, offset 存放分頁的狀態, 因此難度會較高一點.

**Comment by chia7712** [comment]
@jackyoh 麻煩先敘述OOM的發生原因，因為你講的兩個解法是不一樣的事情。

setFetchSize是限制client端從server端每次拉資料的數量。SQL limit則是此次query最大的資料量。這兩者是完全不一樣的概念。

例如limit = 100, fetch size =10是暗示你走完整個resultset至少要付出十次連線溝通的成本(for rows only)

**Comment by jackyoh** [comment]
OK, 了解意思. 
因為這個 issue 是 Geordie 回報的, 目前給的資訊不太足夠. 我覺得我應該要自己先建立一個環境來重現 OOM 的問題, 這樣我敘述的 OOM 原因會比較準確. 再來討論解決方法會比較有意義.

**Comment by jackyoh** [comment]
OharaStream 的 JDBC Source Connector 發生 OutOfMemory 原因，主要有以下二個部份：

1. 在 JDBC PrepareStatement 的 executeQuery 方法，會按照不同資料庫實作的 JDBC Driver 來決定，每次 ResultSet 會撈出多少筆資料，在 postgresql 預設 fetchSize 是設定成 0，所以會將所有資料的 ResultSet 全部放在 client 端的記憶體裡面，因此如果查詢資料量太大的話就會發生 OutOfMemory 的問題。這個部份已經加入 source.jdbc.fetch.size 來解這個問題了 #1506

2. 目前 JDBC Source Connector 的 poll 方法實作是把所有的 ResultSet 拿回放到記憶體之後，再寫入到 Topic 裡，因此此部份也會有 OutOfMemory 的問題，程式如下：

```
    try resultSet
    //Create Ohara Schema
      .map(
        columns =>
          (if (schema.isEmpty)
             columns.map(c => Column.builder().name(c.columnName).dataType(DataType.OBJECT).order(0).build())
           else schema,
           columns))
      .flatMap {
        case (newSchema, columns) =>
          val offsetTimestampValue = dbTimestampColumnValue(columns, timestampColumnName)
          offsets.updateInMemOffset(offsetTimestampValue)
          topics.map(
            RowSourceRecord
              .builder()
              .sourcePartition(JDBCSourceTask.partition(tableName).asJava)
              //Writer Offset
              .sourceOffset(JDBCSourceTask.offset(offsetTimestampValue).asJava)
              //Create Ohara Row
              .row(row(newSchema, columns))
              .topicName(_)
              .build())
      }

```
這裡需要把程式修改成拿到一些資料之後就要先寫入到 Topic 裡，不要等到所有的資料都拿回再寫入到 Topic。因此需要再加入 source.jdbc.flush.size 的參數來控制寫入到 Kafka Topic 的數量。


TODO 要有一個 Offset 來紀錄目前的 ResultSet 走到第幾筆資料。用來做 task restart 時使用，避免撈到重覆的資料(這個會放在 0.7.0 實作)

**Comment by vitojeng** [comment]
> 因此需要再加入 source.jdbc.flush.size 的參數來控制寫入到 Kafka Topic 的數量

為什麼 2. 也是要加入 source.jdbc.flush.size ?

**Comment by jackyoh** [comment]
> 為什麼 2. 也是要加入 source.jdbc.flush.size ?

因為如果每拿到一筆資料就往 topic 寫, 效能會非常差. 所以要先放在一個 cache 裡, 等到資料筆數到一定數量之後在寫入到 topic 裡.

**Comment by chia7712** [comment]
> source.jdbc.flush.size 

單位是啥？

**Comment by jackyoh** [comment]
單位是資料筆數

**Comment by jackyoh** [comment]
我先把這個討論關掉, 如果有想到問題再打開來
