### ISSUE TITLE
Remove the limit of node name

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#1436]
#705 disabled user to add upper case to node name, but there are many use cases of upper case for host name...

- [x] #1446 Remove the limit of node name in K8S impelement

**Comment by chia7712** [comment]
@jackyoh Could you take a look? Why we forbid user to choose upper case?

**Comment by jackyoh** [comment]
目前 ohara 使用 k8s 建立的 pod name 規則是 prefix-clustername-servicename-xxx-hostname, 因為 k8s 的 pod name 規定不能大寫, 所以 hostname 如果設定成大寫的話, 建立 k8s 的 pod name 就會失敗.

之前為了簡單的解這個問題就統一把 hostname 全部改成規定只能小寫. 如果 hostname 有大寫的需求, 就需要改成在建立 pod name 時再把 hostname 轉成小寫.

**Comment by jackyoh** [comment]
我嘗試來修改看看.

**Comment by chia7712** [comment]
The postfix can be a random String than the hostname.

BTW, do both implementations have same name format now?

**Comment by jackyoh** [comment]
> BTW, do both implementations have same name format now?

是指 ssh 和 k8s 的實作嗎？
目前 ssh 和 k8s 的名稱格式是相似的, 不一樣的地方是 k8s 在 postfix 有建立 hostname 而 ssh 沒有.

**Comment by chia7712** [comment]
@jackyoh please take a look at https://github.com/oharastream/ohara/blob/master/ohara-agent/src/main/scala/com/island/ohara/agent/ContainerCollie.scala#L137

Seems both impls use the same format.

**Comment by jackyoh** [comment]
對，它們的格式是相同的。但是我在 K8S 的 implement 時，在建立 pod name 時又會在從 ContainerCollie#format 的格式後面加上 hostname。如果要有一致性我覺得，這個 hostname 可以被移除掉。

**Comment by chia7712** [comment]
So the postfix (hostname) is useless to k8s collie?

**Comment by jackyoh** [comment]
應該是，我來修改看看。在跑測試程式來確認

**Comment by chia7712** [comment]
@jackyoh Could we close this issue ?

**Comment by jackyoh** [comment]
目前 k8s 的 pod name 已經沒有使用到 node name 了. 此 issue 我把它關閉
