### ISSUE TITLE
Cannot create a new pipeline due to configurator API changes

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#1439]
The pipeline ID was removed in #1286. This breaks the current UI. If this API change is not backward compatible(cc @chia7712), a quick fix would be to allow users to enter a pipeline title before creating the pipeline.

This can be done in the new pipeline modal (select a cluster). In addition to choosing a cluster for the pipeline, users should also enter a valid pipeline name(`[a-zA-Z0-9]`) which cannot be changed once the pipeline is created(we should also warn users about this restriction in UI).

**Comment by konekoya** [comment]
Any thoughts @vitojeng @chia7712 @saivirtue @jackyoh @eechih and @wu87988622

**Comment by konekoya** [comment]
If we go with the quick fix that I mentioned in the above, I'd create a quick design mockup so you guys can have a better understanding of what the changes might look like :)

**Comment by chia7712** [comment]
+1 to a hot fix :)

**Comment by saivirtue** [comment]
> If we go with the quick fix that I mentioned in the above

sounds good, +1

**Comment by konekoya** [comment]
I've put together a quick mockup:

![New pipeline modal](https://www.dropbox.com/s/v8sxyl9xfbmp8vg/new-pipeline-modal.jpg?raw=1)

**Comment by eechih** [comment]
@konekoya  LGTM~
想請教個小問題，為何按鈕是用 “Next” 而不是 “Create” 或 "Add"？ :)

**Comment by konekoya** [comment]
> 想請教個小問題，為何按鈕是用 “Next” 而不是 “Create” 或 "Add"？ :)

Good call. Let's change this to __Add__ :)

**Comment by konekoya** [comment]
@wu87988622 will help address this issue 👍

**Comment by konekoya** [comment]
@wu87988622 Please also add a link in the modal which links to the connect-worker page if the dropdown doesn't contain any clusters in it. Thanks :)

**Comment by konekoya** [comment]
@wu87988622 The warning message that should be displayed in the modal when there's no worker cluster service found in the dropdown.

It seems like you haven't had any worker clusters yet. You can create one from [here](http://www.host.com.tw)
