### ISSUE TITLE
建立一個 DataBase 的環境, 讓 JDBC Source Connector 做更大資料量的測試

### ISSUE THREAD

**Issue by jackyoh** [oharastream/ohara#1440]
目前測試環境規劃建立 3 台 VM, 第 1 台 VM 台用來建立 Postgresql(9.2.7) DataBase, 另一台 VM 使用 OharaStream 建立 manager, configurator. 最後一台 VM 用 OharaStream agent 的 ssh 版本建立zookeeper, broker 和 worker service 並且在此環境上啟動 JDBC Source Connector.

測試資料主要是撰寫一個簡單的程式將資料寫入到 Postgresql Database 裡.

**Comment by chia7712** [comment]
we already have oracle database so could we close this issue?

**Comment by jackyoh** [comment]
目前已經有 oracle database 的 docker image 了， 我先把此 issue 關閉。
