### ISSUE TITLE
Cannot create a new connector due to connector API changes 

### ISSUE THREAD

**Issue by wu87988622** [oharastream/ohara#1462]
The connector ID was removed in #1286. This breaks the current UI. If this API change is not backward compatible(cc @chia7712 ), a quick fix would be to allow users to enter a connector title before creating the connector.

I've put together a quick mockup:

Changes:

Select connector toolbar
Added a new input for users to enter a connector name

![New connector modal](https://www.dropbox.com/s/8e8tkcefjkpgjw1/螢幕快照%202019-06-17%20上午10.15.22.png?raw=1)

**Comment by wu87988622** [comment]
Any thoughts @vitojeng @chia7712 @saivirtue @jackyoh @eechih and @konekoya

**Comment by chia7712** [comment]
+1 to this one. In fact, the name is required for all objects (excluding streamapp and jar. Pending for PR). And hence, it would be better to pop a window to demand user to enter the name for any object. 

BTW, could we remove the duplicate word “connector name” from the input window?

**Comment by wu87988622** [comment]
> +1 to this one. In fact, the name is required for all objects (excluding streamapp and jar. Pending for PR). And hence, it would be better to pop a window to demand user to enter the name for any object.
> 
> BTW, could we remove the duplicate word “connector name” from the input window?

Do you main label or placeholder ?

**Comment by chia7712** [comment]
I prefer to remove label since there is already a BIG title for the input window.

**Comment by wu87988622** [comment]
> I prefer to remove label since there is already a BIG title for the input window.

ok~ no problem

**Comment by vitojeng** [comment]
> I prefer to remove label since there is already a BIG title for the input window.

+1 on remove label

**Comment by konekoya** [comment]
Looks good to me! Thanks @wu87988622
