### ISSUE TITLE
HDFSSinkConnector some fields are not displayed

### ISSUE THREAD

**Issue by eechih** [oharastream/ohara#1472]
**Describe the bug**
HDFSSinkConnector some fields are not displayed.
For example: 
  - Data Buffer size
  - Rotate Interval (MS)

**Comment by eechih** [comment]
\cc @konekoya @wu87988622

**Comment by chia7712** [comment]
Don't we use dynamical page for HDFSSinkConnector?

**Comment by eechih** [comment]
@chia7712 HDFSSinkConnector 已經換成 dynamical page，不過有些型態的 UI 還沒支援。例如：Long, Double。

Data Buffer size, Rotate Interval (MS) 的型態是 Long，所以沒有顯示在 UI 上。

**Comment by konekoya** [comment]
Thanks for reporting @eechih
