### ISSUE TITLE
[Question] Ohara 要保證 Exactly-one 會有一些條件及限制，User 建立 workspace 時，需要讓使用者清楚知道

### ISSUE THREAD

**Issue by eechih** [oharastream/ohara#1479]
建立 workspace 時，需引導使用者知道下列資訊：
- 說明好處、壞處
- 資源需求：至少 3 台 node

**Comment by eechih** [comment]
/cc @vitojeng @chia7712 @saivirtue @jackyoh @konekoya @wu87988622 

還有任何建議嗎？歡迎提出喔～

**Comment by vitojeng** [comment]
@eechih 我想這個議題目前的階段可能還不適合以 "討論" 的形式進行.

**Comment by chia7712** [comment]
這個議題會需要一些後端APIs和前端UI的配合才能開始，包含
1. 後端collie APIs需要開放讓呼叫者自訂參數
1. 後端collie APIs需要能暴露參數的說明和建議值
1. 後端collie APIs要具備事先檢查參數值的功能
1. UI需要有畫面可以讓使用者調整某些參數
1. UI需要有畫面能讓使用者閱讀相關說明和建議值
1. UI需要有畫面能讓使用者測試custom arguments

上述的議題可以稱之為 "身為一個進階使用者，我希望能tuning叢集相關設定"

待上述功能都完成後，我們才可以在UI上設計"特規設定"的流程，例如基於上述可彈性參數後，我們可以在UI上長出一個流程是專門討論exactly once的設定流程(因為這需要適當的畫面輔助使用者才能完成符合心理預期的準確無誤的設定)

**Comment by chia7712** [comment]
簡單來說，現在開的議題需要一些基礎設施先完成。而待基礎設施完成後，這個議題就只是個延伸而已，甚至我們可以延伸出更多種的"情境設定"

**Comment by eechih** [comment]
@vitojeng 開這個 Issue 只是為了持續關注這個問題，並且收集更多資訊。按照 @chia7712 的想法，我們應該開一個 umbrella，來涵蓋前後端的工作。

**Comment by vitojeng** [comment]
@eechih 嗯，了解。我的想法跟 @chia7712 差不多.
我想這是從 Pipeline Workspace 的部份延伸的議題.
我們應該展開新的議題，繼續進行 Pipeline Workspace 增加的功能(新的流程)。


---
Vito

**Comment by DavidMi-1** [comment]
@eechih test dashboard

**Comment by eechih** [comment]
I will close this issue, because it is covered in future v1.0
