### ISSUE TITLE
Update the docs URL in the API response body

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#1488]
As our docs have moved. The docs URL from the RESTful API response body should be updated as well. The current API URL will point to a 404 page from GitHub

Res body:

```json
{
    "code": "Unsupported API: v0/containers",
    "message": "please see link to find the available APIs",
    "stack": "N/A",
    "apiUrl": "https://github.com/oharastream/ohara/blob/master/docs/rest_interface.md"
}
```

**Comment by konekoya** [comment]
I will file a PR to fix this if I get a chance today

**Comment by konekoya** [comment]
@vitojeng A quick question. Is this (👇 ) the correct URL of our new RESTful API home?
https://oharastream.readthedocs.io/en/latest/rest_interface.html

**Comment by konekoya** [comment]
PR is up https://github.com/oharastream/ohara/pull/1489

**Comment by chia7712** [comment]
@konekoya This issue break the [test](https://builds.is-land.com.tw/job/PostCommit-OHARA/428/testReport/). Could you file a issue for the flaky?

**Comment by konekoya** [comment]
> @konekoya This issue break the test. Could you file a issue for the flaky?

Oops, thought It was only an easy fix... Will give it a look as soon as I can
