### ISSUE TITLE
Add new QA commands to our contributing document

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#1505]
Now, our jenkins is doable to execute many fine-grained QA for ohara manager. And we ought to document it for all manager developer.

These new commands include:  "retry manager-it", "retry manager-api", "retry manager-ut"

**Comment by chia7712** [comment]
@konekoya @wu87988622 Do you have free cycle to take over this one?

**Comment by konekoya** [comment]
Sure thing. Just need to know where should these commands live. Contributing guide?

**Comment by chia7712** [comment]
> Just need to know where should these commands live. Contributing guide?

yep. the file is moved to docs/src/contributing.md

**Comment by konekoya** [comment]
No problem :)
