### ISSUE TITLE
Bump version from 0.6-SNAPSHOT to 0.6.0-SNAPSHOT

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#1514]
just notice that we use incorrect Snapshot format ...

**Comment by chia7712** [comment]
FYI @jackyoh @saivirtue @vitojeng @wu87988622 @konekoya @eechih

**Comment by jackyoh** [comment]
OK, 收到了.

**Comment by jackyoh** [comment]
我不太確定 retry manager-it 在 it 環境上所使用的 docker image 是動態 build 的 docker image 還是從 docker hub 上拉 0.6.0-SNAPSHOT?
因為在跑 retry manager-it 有收到 message: ’****-it-02 doesn\‘t have docker image:****stream/zookeeper:0.6.0-SNAPSHOT’ 的訊息

**Comment by vitojeng** [comment]
Ok, got it!

**Comment by chia7712** [comment]
> 因為在跑 retry manager-it 有收到 message: ’****-it-02 doesn\‘t have docker image:****stream/zookeeper:0.6.0-SNAPSHOT’ 的訊息,

那這樣應該算是個jenkins bug。因為目前只有後段的測試會主動去更新image。我晚點會修復

**Comment by jackyoh** [comment]
> 那這樣應該算是個jenkins bug。因為目前只有後段的測試會主動去更新image。我晚點會修復

Thank you.

**Comment by konekoya** [comment]
Thank you for the help @jackyoh and @chia7712  :)
