### ISSUE TITLE
Get topic API should use name instead of ID in docs

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#1525]
Current docs:
https://github.com/oharastream/ohara/blob/master/docs/src/rest_interface.md#get-a-topic

`GET /v0/topics/${id}`

I believe it should be a topic name instead of topic ID:

`GET /v0/topics/${name}`

/cc @chia7712

**Comment by konekoya** [comment]
I can file a PR to fix this once it's confirmed :)

**Comment by chia7712** [comment]
+1 to this issue :)
