### ISSUE TITLE
整理目前 Ohara QA 環境列表

### ISSUE THREAD

**Issue by jackyoh** [oharastream/ohara#1551]
我們需要一目了然知道自動化環境的資源狀況, 因此需要做一個表格來紀錄目前 QA 環境的資源有多少， 例如：CPU core 數, 記憶體大小, 硬碟大小和是否使用 SSD...等等的資源狀況. 之後就可以導出 csv 格式, 把結果貼到 google driver 或是 paper

**Comment by chia7712** [comment]
@jackyoh 這個題目有後續嘛？

**Comment by jackyoh** [comment]
目前已經有把環境列表放在 paper 上了，如果異動就會更新表格。因此我把此議題關閉掉
