### ISSUE TITLE
Manager tests in QA seems not stable

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#1609]
see the following QA test reports:

[#3091](https://builds.is-land.com.tw/job/PreCommit-OHARA/3091/#showFailuresLink)
[#3092](https://builds.is-land.com.tw/job/PreCommit-OHARA/3092/#showFailuresLink)
[#3093](https://builds.is-land.com.tw/job/PreCommit-OHARA/3093/#showFailuresLink)

the failed manager tests seems not related each issue, need a further investigation.

**Comment by chia7712** [comment]
看起來像是臨時啟動的configurator無法連線 我會檢查一下jenkins

**Comment by konekoya** [comment]
> 看起來像是臨時啟動的configurator無法連線 我會檢查一下jenkins

Yep. Manager failed with the maximum retry :(

**Comment by saivirtue** [comment]
This issue is related to jenkins environment and it's more stable now, closing this issue.
