### ISSUE TITLE
身為開發者, 我希望有一組 RESTful API 可以管理 Shabondi Service

### ISSUE THREAD

**Issue by vitojeng** [oharastream/ohara#161]
child of #160, required by #160

Add a set of RESTful API into Configurator service to start/stop Shabondi service of a pipeline

### Criteria
- [ ] RESTful API Docs(move to #951)
- [x] REST API
  - [x] add shabondi
  - [x] delete shabondi
  - [x] update property
  - [x] get property
  - [x] start shabondi
  - [x] stop shabondi

**Comment by vitojeng** [comment]
@eechih 
I would write the document after Shabondi feature finished.
So move doc related task to #951, not include this issue.

**Comment by eechih** [comment]
> move doc related task to #951

OK
