### ISSUE TITLE
Slowly reflection of loading connectors in fake configurator

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#1610]
This issue is similar to https://issues.apache.org/jira/browse/KAFKA-4247. In order to expose fake configurator to ohara-manager developers,  #1370 enable configurator image to run the fake mode. However, the fake configurator does not load connectors on the local so it is unable to return connector information. Hence, #1581 add the reflection of loading connector dynamically. The reflection tool traces all url from class paths and our startup script made a bit error on class path that it included a colon at the end of class path (by contrast, kafka included a colon at the start of class path). The reflection tool views the "empty path" as "working path", and hence it tries to seek all files in system if the working path is on "/" ...

**Comment by jackyoh** [comment]
classpath 設定成 / 根目錄, 造成載入過慢的問題.
