### ISSUE TITLE
Bump akka dependencies

### ISSUE THREAD

**Issue by vitojeng** [oharastream/ohara#1614]
the updated dependencies are shown below.

1. akka 2.5.12 -> 2.5.29
1. minor: update lib naming in build.gradle

**Comment by chia7712** [comment]
@vitojeng I promote this issue to update all deps than only akka. Please dig in our deps to list the upgradable deps.

**Comment by vitojeng** [comment]
No problem.
Due to Akka latest release 2.5.25 still in Scala 2.12.8. It would be better pending this issue until the next Akka release.

**Comment by chia7712** [comment]
bump to 0.9 :)

**Comment by vitojeng** [comment]
bump to 0.10 :)
