### ISSUE TITLE
add string restriction to JsonRefiner

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#1619]
The name is controllable to user and it is a part of url. Hence, we should have a limit for naming.

The most hard restrictions in our APIs is k8s APIs that it accepts only [a-z0-9-.]. It seems to me that we can make all APIs obey the same rule - [a-z0-9-.] - in order to avoid chaos.

**Comment by chia7712** [comment]
@wu87988622 @eechih @vitojeng @saivirtue @jackyoh @konekoya any suggestions?

**Comment by jackyoh** [comment]
+1. 可以有個簡單的 sample 嗎？

**Comment by saivirtue** [comment]
This may restrict some flexible, like `/jars`
the name of jar object is controlled by **uploaded file**, user need to change All the uppercase char in order to use our api.

**Comment by chia7712** [comment]
> Maybe we can just set the naming rule for those names that used for container name (docker or k8s), how's like?

it is ok to me. I will add a infra to JsonRefiner and make each APIs have custom rule in name.
