### ISSUE TITLE
Remove username and password fields in new node modal when running in k8s mode

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#1631]
Since these two fields are only useful for SSH mode. There's no need to supply them when running in k8s mode. Thanks for raising this @wu87988622

**Comment by chia7712** [comment]
> I think will need to tweak the validate API a bit so it won't check the username and password when a request is coming from a k8s mode cluster?

see #1809

**Comment by konekoya** [comment]
Can't wait to see it happen :)

**Comment by konekoya** [comment]
@wu87988622 will be tackling this issue

**Comment by konekoya** [comment]
Moving to new UI
