### ISSUE TITLE
Manager should honor the zookeeper deploy rules when creating workspace

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#1632]
When creating a workspace we should honor the rule as listed below (copied from #1082):

在 Node 上部署 Service 的規則：
- Zookeeper
  - 當指定的 Node 數量少於（或等於）3 台，隨機挑選 1 台 Node
  - 當指定的 Node 數量大於（或等於）4 台，隨機挑選 3 台 Node
- Broker 部署在全部指定的 Node 上
- Worker 部署在全部指定的 Node 上 

But due a bug in #696. We can't implement this logic: __當指定的 Node 數量大於（或等於）4 台，隨機挑選 3 台__ yet

Ref #1082 for more info

**Comment by konekoya** [comment]
@eechih Is this fule still valid and should be implemented in the new UI?

**Comment by eechih** [comment]
> Is this rule still valid and should be implemented in the new UI?

@konekoya Yep, in the new UI, this rule will be used in quick mode (create workspace).

/cc @wu87988622

**Comment by konekoya** [comment]
I will keep this issue open then :)

**Comment by konekoya** [comment]
Closed in #3157
