### ISSUE TITLE
Replace JsArray() by JsArray.empty

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#1656]
JsArray.empty is more readable I'd say :)

**Comment by dc-tw** [comment]
I would like to try it.

**Comment by chia7712** [comment]
@dc-tw please assign this issue to yourself and attach the version label (v0.7.0)

**Comment by dc-tw** [comment]
I cannot assign this issue to myself because I don't have right permission. 😅 Would you like to help me? Or you can assign the issue to me. @chia7712

**Comment by chia7712** [comment]
@dc-tw your permission is granted :)
