### ISSUE TITLE
[Question] what is "port" in workspace???

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#1671]
There is a argument called "port" in creating a work space. Currently, it is used in assigning the client port for worker cluster. However, it is awkward in work space since all connection to the port can retrieve only a part "information" from our work space ... It means the port is not suitable to be a entrypoint port.

It seems to me that we should hide it from our UI before we reach consensus on how to expose configs details of services (zk, bk and wk) (see #1479)

**Comment by chia7712** [comment]
FYI @wu87988622 @konekoya

**Comment by konekoya** [comment]
This "port" is currently used for workers only while zookeeper and broker are using randomly generated port from our code. Agreed to hide it from the UI for now and use a generated port instead.

**Comment by vitojeng** [comment]
> Agreed to hide it from the UI for now and use a generated port instead.

+1

**Comment by eechih** [comment]
> Agreed to hide it from the UI for now and use a generated port instead.

+1

**Comment by wu87988622** [comment]
+1

**Comment by konekoya** [comment]
Thanks for the input everyone! This issue will be addressed in #1628 as part of its sub-task.
