### ISSUE TITLE
Add a link back to workspace's topics tab in pipeline's new topic modal

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#1672]
Could we add a friendly hyper link to create topic when there is no topic in the work space

a link to http://${node}:${port}/workspaces/${cluster}/topics

**Comment by chia7712** [comment]
ping @wu87988622 @konekoya

**Comment by konekoya** [comment]
Hmm, not sure if this is doable. Can't we do this with API? In UI, a topic should belong to a specific workspace. That's why we have this URL: `/workspaces/topics` :)

**Comment by konekoya** [comment]
I misread the question... `http://${node}:${port}/workspaces/${cluster}/topics` this is supposed to be working. I'll give it a look today :)

**Comment by konekoya** [comment]
@chia7712 we'll be adding a new link in topic modal which will take the users to workspace's topics tab :). Thanks for raising this issue!
