### ISSUE TITLE
Support draggable modal in manager

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#1692]
Since Mui already has an [example](https://material-ui.com/components/dialogs/#draggable-dialog) for draggable dialog and this feature has been mentioned serval times in our meetings. We should consider adding this feature to our modals

/cc @vitojeng and @wu87988622

**Comment by vitojeng** [comment]
Very nice feature.  I'm +1 on this.

**Comment by konekoya** [comment]
Since we're in the middle of migrating all of our react components to material UI. What I've implemented here are components which use Mui's Dialog component. And the rest of the modal components should be implemented in #1730
