### ISSUE TITLE
ping Ohara Manager committers if PR breaks the APIs compatibility

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#1694]
the manager-api test alerts us to notice the broken Restful APIs compatibility caused by PR. In order to have correct fix to UI code, jenkins should ping the suitable committers to check the APIs code for Ohara Manager.

**Comment by chia7712** [comment]
@vitojeng @jackyoh @saivirtue @eechih @konekoya @wu87988622 Any suggestions?

我預期會讓jenkins自動在commect上貼上相關人員的名字，藉此提醒相關人員

**Comment by saivirtue** [comment]
> 貼上相關人員的名字

+1

**Comment by vitojeng** [comment]
如何決定相關的人?

**Comment by konekoya** [comment]
> 我預期會讓jenkins自動在commect上貼上相關人員的名字，藉此提醒相關人員

+1 Sounds good to me :)

**Comment by chia7712** [comment]
> 如何決定相關的人?

現在來徵選 想被貼的請舉手

**Comment by konekoya** [comment]
> 現在來徵選 想被貼的請舉手

XXD  🙋‍♂🙋‍♂🙋‍♂🙋‍♂🙋‍♂🙋‍♂🙋‍♂

**Comment by wu87988622** [comment]
> > 如何決定相關的人?
> 
> 現在來徵選 想被貼的請舉手
@konekoya 舉手,我做👨‍💻....

**Comment by chia7712** [comment]
https://github.com/oharastream/ohara/pull/1699#issuecomment-507960814

效果大概如上，麻煩大家看一下

**Comment by konekoya** [comment]
Works perfectly for me. I think you can close this issue now @chia7712
