### ISSUE TITLE
[Question] Tweak new workspace modal 

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#1695]
I've been talking with @wu87988622 about how to tweak the new workspace modal as we're removing the client port form it (#1671)

The proposed changes will be looking like this:

![New workspace modal](https://www.dropbox.com/s/9kbibr7i8z1qrun/new-workspace.png?raw=1)

#### Some notable changes are listed below:
- Remove the add node modal and display the available nodes right in the __Node List__ 
- Same like the add node modal but keep the button for users to upload new jars and display the added jars in the __Plug List__
- Following from 1 & 2, users can select nodes or jars by checking the checkbox in the __Node__ and __Plug__ list.

I think we might need to call for a quick meeting to better describe the intent and redesign of this modal 😅 

/cc @vitojeng @chia7712 @eechih @saivirtue @jackyoh @wu87988622

**Comment by jackyoh** [comment]
+1

**Comment by vitojeng** [comment]
That's cool. Please feel free to call a quick meeting.

**Comment by konekoya** [comment]
Thanks for everyone's idea and suggestion. I'm going to close this issue as the relevant work/tasks will be tracked in #1628
