### ISSUE TITLE
Enable dockerfile to run custom command before building ohara code

### ISSUE THREAD

**Issue by jackyoh** [oharastream/ohara#1696]
在 build configurator 的 image 時會出現已下網址的錯誤：
https://builds.is-land.com.tw/job/PreCommit-OHARA/3262/artifact/checks/build_configurator_image.log

我們的QA有越來越多的邏輯需要dockerfile配合，為了讓相關邏輯可以更順暢的直接運用在目前的dockerfile，我傾向增加讓dockerfile直接執行custom command，如此之後jenkins QA的調整就可以和dockerfile脫鉤 by chia

- [x] for 0.7 (#1697)
- [x] for 0.6 (#1698)

**Comment by chia7712** [comment]
@jackyoh 這個在我離開辦公室的時候應該已經有修復了 你先retry看看

**Comment by jackyoh** [comment]
ok, 我來跑看看

**Comment by chia7712** [comment]
我好像看錯log了XD

交給你處理了

**Comment by jackyoh** [comment]
ok, 我嘗試修改看看

**Comment by jackyoh** [comment]
我有用 local 去測試可以正常的 build code

**Comment by chia7712** [comment]
因為有觸發rebase的關係才會出現的錯誤...或許先把QA裡面REBASE這個參數移除好了

**Comment by jackyoh** [comment]
把 jenkins 設定的 --build-arg REBASE=$PR_BASE_BRANCH 參數刪掉, 就能跑了

**Comment by chia7712** [comment]
@jackyoh Let me take over this issue.

**Comment by jackyoh** [comment]
Thank you.
