### ISSUE TITLE
Abandon all the services if an error occurs while creating a workspace

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#1700]
We're now able to create a new workspace with the UI which contains a zookeeper, a broker and a worker. But It's likely that a failure would occur during the process and cause the whole workspace creation to fail. For example, if we create a new workspace with the current UI and it fails due to some problems with the worker API(say, a duplicated worker name). The previous created zookeeper and broker will still live among our nodes as they were in fact successfully created. For this very reason, we should abandon (kill these services) if one of the services are failed in the whole workspace creation process. 

Would love to hear from other committers too:

@vitojeng @chia7712 @eechih @saivirtue @jackyoh @wu87988622

**Comment by vitojeng** [comment]
Thanks @konekoya for raising this issue.
It would improve the user experience and become more elegant.
