### ISSUE TITLE
Add React error boundaries to provide a nicer error message for users

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#1717]
The current error is meant to display for devs while in the development process. We should display a nicer and meaningful (at least not the stack trace...) message for users when an unexpected is happed

**Comment by chia7712** [comment]
@konekoya could you share the preview of the error message to me ?

**Comment by konekoya** [comment]
Definitely :)

![](https://www.dropbox.com/s/l12wh9x711njeto/Screen%20Shot%202019-09-05%20at%201.59.55%20PM.png?raw=true)

**Comment by konekoya** [comment]
Please note that this error can only be seemed in production mode :)

**Comment by chia7712** [comment]
@konekoya thanks for the preview. Is this unrelated to the error response from Configurator?

**Comment by konekoya** [comment]
> @konekoya thanks for the preview. Is this unrelated to the error response from Configurator?

It's mostly related to Frontend. When an unexpected error happened in the manager we will throw this error. But it could also cause by the API. e.g. Pipeline API's flows field is updated but the objects remain empty.

**Comment by chia7712** [comment]
@konekoya thanks for explanation :)
