### ISSUE TITLE
why we need to fake k8s client in IT?

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#1718]
com.island.ohara.it.agent.k8s.FakeK8SClient is a fake stuff but it is placed at IT scope ... I don't think it makes sense to our ohara. We should remove it or move the related code to UT scope ...

**Comment by chia7712** [comment]
FYI @jackyoh

**Comment by jackyoh** [comment]
收到. fake 應該要移到 ohara-agent 的 module. 我再 0.7 的版本來 refactor

**Comment by chia7712** [comment]
@jackyoh please close this one if you plan to fix it in another issue.

**Comment by jackyoh** [comment]
OK, 我在 #1723 有另外開個 issue 了.
