### ISSUE TITLE
Enable user to config cluster with more custom arguments

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#1736]
from #1479 

detail link: https://github.com/oharastream/ohara/issues/1479#issuecomment-503456815

1. - [x] enable user to config *Stream* cluster with more cluster arguments (duplicated to #810)
1. - [ ] enable user to config *Zookeeper* cluster with more cluster arguments
1. - [ ] enable user to config *Broker* cluster with more cluster arguments
1. - [ ] enable user to config *Worker* cluster with more cluster arguments

duplicated to #2191

**Comment by saivirtue** [comment]
Is this something you talk about  before "Refactor Collie - part 3" ?
If so, I'd like to take over this XD

**Comment by chia7712** [comment]
> Is this something you talk about before "Refactor Collie - part 3" ?
If so, I'd like to be involved this. XD

feel free to take over this issue :)

**Comment by chia7712** [comment]
@saivirtue Is this issue kicked into touch? We can go back for 0.8.

**Comment by saivirtue** [comment]
Let's discuss this in 0.8 :)
