### ISSUE TITLE
Update kafka version from 1.0.2 to 2.2.0

### ISSUE THREAD

**Issue by vitojeng** [oharastream/ohara#175]

**Comment by vitojeng** [comment]
There some blocker or critical issue in kafka 1.0.2, we need to upgrade to 1.0.3

**Comment by vitojeng** [comment]
@chia7712 
It seems that kafka 1.0.3 release should not happen. 😢 
Kafka release 2.2.1 is in progress currently, should we consider an upgrade to 2.2.1?

**Comment by chia7712** [comment]
> should we consider an upgrade to 2.2.1?

+ 1000 :)

**Comment by vitojeng** [comment]
Kafka 2.2.1 release plan:
https://cwiki.apache.org/confluence/display/KAFKA/Release+Plan+2.2.1

ping @saivirtue , @eechih , @jackyoh

**Comment by jackyoh** [comment]
+1

**Comment by chia7712** [comment]
@vitojeng Do you want to this one be in 0.5? If so, we can migrate to 2.2.0 first. And then file another one to update it from 2.2.0 to 2.2.1. I believe there are some works introduced by updating kafka from 1.0.2 to 2.2.0.

**Comment by vitojeng** [comment]
That's a good idea. I will start the upgrade ASAP.

**Comment by vitojeng** [comment]
After some investigation, we can upgrade to kafka 2.1.0 with some minor change.
But upgrade 2.1.0 to 2.2.0 have no luck, there are many testing failed, so need more investigation.

**Comment by chia7712** [comment]
>But upgrade 2.1.0 to 2.2.0 have no luck, there are many testing failed, so need more investigation.

Could you upload the PR first? It is good to migrate to kafka 2.2 as soon as possible since it get harder to update kafka in the future.

**Comment by vitojeng** [comment]
> Could you upload the PR first? 

Maybe tomorrow? I guess I could find the root cause tomorrow. ^^
