### ISSUE TITLE
修改所有文件連結的副檔名為 .html

### ISSUE THREAD

**Issue by jackyoh** [oharastream/ohara#1753]
目前文件的連結如下：
https://ohara.readthedocs.io/en/0.6/custom_connector.md#metrics

以上的網址無法正確連結到文件的路徑, 因此需要修改成以下的網址：
https://ohara.readthedocs.io/en/0.6/custom_connector.html#metrics

**Comment by vitojeng** [comment]
感謝 @jackyoh !

**Comment by jackyoh** [comment]
這個 issue 已經修改完畢, 我將此 issue close
