### ISSUE TITLE
修改 JDBC Source Connector 資料為 NULL 時 Cell 的 value

### ISSUE THREAD

**Issue by jackyoh** [oharastream/ohara#1763]
目前如果 DataBase 的資料為 NULL 時, JDBC Source Connector 在寫入 topic 時會將回傳 Row 的 Cell value 設定成 scala 的 None, 這樣在使用 streamapp 時, 如果沒有包 scala 的 jar 檔時會出現 ClassNotFound 的錯誤找不到 scala 的 None class, 因此 JDBC Source Connector 需要把 Cell value 修改成 java 的 Optional.empty

**Comment by chia7712** [comment]
In fact, this is a critical bug as it produces a error over which we can’t paper. Also, the error departs from our java compatibility.

Hence, it would be better to fix it in 0.6

**Comment by jackyoh** [comment]
OK，我今天應該會開 PR。如果沒問題在這幾天內應該可以 Merge 到 0.6 branch

**Comment by alan791205** [comment]
@alan791205 @mathsigit @DawnJheng
