### ISSUE TITLE
Fix workspace end-to-end tests

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#1780]
The failing jobs

https://builds.is-land.com.tw/job/PreCommit-OHARA/3416/console
https://builds.is-land.com.tw/job/PreCommit-OHARA/3425/console
https://builds.is-land.com.tw/job/PreCommit-OHARA/3429/console
https://builds.is-land.com.tw/job/PreCommit-OHARA/3456/console
https://builds.is-land.com.tw/job/PreCommit-OHARA/3460/console

There is a couple of possible causes that need to be tackled:

- [x] Fix cypress is not correctly waiting for creating worker API issue (#1796)
- [x] Fix flaky tests in workspaces (#1870)

**Comment by chia7712** [comment]
@konekoya could you file a PR to test it again?

**Comment by konekoya** [comment]
>  could you file a PR to test it again?

Do you mean a new PR?

**Comment by chia7712** [comment]
> Do you mean a new PR?

Is there a PR which can produce this error continually?

**Comment by konekoya** [comment]
> Is there a PR which can produce this error continually?

Yep. This one has been failed two times with the exact same report. I will retry a couple more and see if the error persists
