### ISSUE TITLE
Docs: Quick start

### ISSUE THREAD

**Issue by vitojeng** [oharastream/ohara#1787]
required by #1486 

Demonstrate how to rapidly build data pipelines using Ohara.(Use the Quickstart VM)
Overall content include:
* How to setup Quickstart VM
* Introduce built-in services and pre-prepared files
* How to create workspace, pipeline
* Troubleshotting

Todo Items
- [ ] English version
- [ ] Chinese traditional version

**Comment by vitojeng** [comment]
@wu87988622 Quickstart related files already moved to [oharastream/ohara-quickstart](https://github.com/oharastream/ohara-quickstart), please move this job to **ohara-quickstart**.

**Comment by wu87988622** [comment]
This issue is move to https://github.com/oharastream/ohara-quickstart/issues
