### ISSUE TITLE
Ohara Product Testing Report (Template)

### ISSUE THREAD

**Issue by eechih** [oharastream/ohara#1794]
### 基本測試：
  - [ ] 確認畫面（UI）與設計稿（Design）是否一致
    - 顏色、字型、符號、圖片、...
  - [ ] 檢查所有畫面的 Title 名稱是否正確
  - [ ] 所有連結是否有前往正確頁面
  - [ ] 切換視窗大小時，有無跑版情形
  - [ ] 切換視窗大小後，文字與圖形是否竄行
  - 表單
    - [ ] 任何一個必填欄位未填寫，不能送出
    - [ ] 表單送出中，應該明確表達正在處理中的訊號
    - [ ] 表單送出中，應該要凍結表單（除非有提供取消功能）
    - [ ] 任何表單至少要有 CTA 及 Cancel 兩類按紐 (CTA: Call-To-Action)
  - 訊息
    - [ ] 成功訊息，應該要明確指出完成對象
    - [ ] 錯誤訊息，應該要明確指出錯誤對象
    - [ ] 確認訊息
      - [ ] 刪除確認，應該要明確指出欲刪除對象
  - 按鈕
    - [ ] 任何一個刪除按鈕，都要有刪除確認提示
  - 鼠標
    - [ ] 移動到所有可以點擊的元素，要出現 pointer cursor
        - Button, Link icon, Link text, ...
### 功能測試：
  - Normal case (可參考[測試腳本](https://paper.dropbox.com/doc/--AgrWW27QTwB5lQq4zVR1qG0jAg-7i1JSsE3jJeVODqCKgcgo#:uid=800501275390061108085686&h2=%E6%B8%AC%E8%A9%A6%E8%85%B3%E6%9C%AC))
    - [ ] Create a new workspace with three nodes
    - [ ] Create two topic and upload a stream app jar into the workspace
    - [ ] Create a new pipeline and add some components into pipeline
    - [ ] 連接 FTP Source -> Topic 1 -> Stream App -> Topic 2 -> HDFS Sink
    - [ ] Prepare required folders and test data on the FTP server
    - [ ] Start all connectors and stream app
    - [ ] Verify which test data was successfully dumped to HDFS

### 設計稿：
- (設計稿 Issue Number 紀錄在此)

### 測試環境：
- Ohara
  - Mode: xxx
  - Version: xxx
  - Build date: xxx
- 測試工具
  - 瀏覽器：xxx
  - 最小螢幕寬度：xxx

### 基本測試：
- (基本測試所發現的問題，紀錄在此)

### 功能測試：
- (功能測試所發現的問題，紀錄在此)

**Comment by eechih** [comment]
/cc @chia7712 @jackyoh @konekoya @saivirtue  @vitojeng @wu87988622

關於測試的項目，問題紀錄的格式，已經初步擬定一個版本。歡迎大家提出建議及想法，我們可以再進一步討論，謝謝。

**Comment by vitojeng** [comment]
Thanks @eechih for the template, very nice.

Some comments:
* title: OharaStream Test (Template) => Ohara Product Testing Report(Template)
* header: 加上版號應該會更好
  * 測試項目 => Ohara ${version} 產品測試項目

**Comment by eechih** [comment]
> title: OharaStream Test (Template) => Ohara Product Testing Report(Template)

OK，已調整好了  :)

**Comment by eechih** [comment]
> header: 加上版號應該會更好

@vitojeng  版號放在 title 是否比較好呢？

**Comment by vitojeng** [comment]
> @vitojeng 版號放在 title 是否比較好呢？

OK!

**Comment by konekoya** [comment]
@vitojeng @eechih Should we close this issue now?

**Comment by eechih** [comment]
> Should we close this issue now?

@konekoya Yes, I will close it, thanks.
