### ISSUE TITLE
文字風格不一致

### ISSUE THREAD

**Issue by eechih** [oharastream/ohara#1800]
- 文字風格不一致：
  - Table header 文字風格沒有統一，例如 NAME v.s Name
  - Button label 文字風格沒有統一，例如 NEW WORKSPACE v.s New pipeline
  - Menu/Tab item label 文字風格沒有統一，例如 OVERVIEW v.s Workspaces

- 頁面 Title 不一致：
  - Nodes > New node：Create button 與 Modal title 文字內容與風格不一致，NEW NODE v.s New ohara node
  - Workspaces > New workspace：Create button 與 Modal title 文字風格不一致，NEW WORKSPACE v.s New workspace

**Comment by jackyoh** [comment]
這個問題不會影響到程式執行, 在之後的版本修就可以了. 我先把 v0.6.0 label 拔掉
ping @konekoya  @wu87988622  FYI

**Comment by konekoya** [comment]
This will be fixed in #1730

**Comment by wu87988622** [comment]
>頁面 Title 不一致：
>
>Nodes > New node：Create button 與 Modal title 文字內容與風格不一致，NEW NODE v.s New ohara node
>Workspaces > New workspace：Create button 與 Modal title 文字風格不一致，NEW WORKSPACE v.s New workspace

我們是以material-ui的設計為主，Button會以全大寫為顯示，Modal會以首字大寫，後續為小寫的設計。

/cc @konekoya @eechih

**Comment by eechih** [comment]
@konekoya @wu87988622 @vitojeng 我們可能需要進一步討論整體（網站）的文字風格，可否先請 @wu87988622 整理 Material-UI Components 的文字風格（限制），例如 Button, Table header, Tabs title, Modal title,  Menu title, ...

**Comment by vitojeng** [comment]
> 我們可能需要進一步討論整體（網站）的文字風格

+1

**Comment by konekoya** [comment]
> @konekoya @wu87988622 @vitojeng 我們可能需要進一步討論整體（網站）的文字風格

+ 1 to this :)

**Comment by wu87988622** [comment]
This fixed in #1730
