### ISSUE TITLE
刪除確認提示，應該要明確指出欲刪除對象

### ISSUE THREAD

**Issue by eechih** [oharastream/ohara#1802]
- Pipelines > Delete pipeline：應該要明確指出欲刪除對象
- Workspaces > Edit workspace > Topics > Delete topic：應該要明確指出欲刪除對象
- Workspaces > Edit workspace > Stream Apps > Delete jar：應該要明確指出欲刪除對象

**Comment by jackyoh** [comment]
這個 issue 在之後的版本再來修 @konekoya @wu87988622

**Comment by konekoya** [comment]
No problem. I'll be working on this in 0.7
