### ISSUE TITLE
表單送出中，應該要凍結表單

### ISSUE THREAD

**Issue by eechih** [oharastream/ohara#1803]
- Workspaces > New workspace：送出 Add 請求中，Cancel 按鈕及右上角打叉的 Icon 應該要 disable

**Comment by jackyoh** [comment]
這個問題之後版本再來修改. ping @konekoya @wu87988622 FYI

**Comment by konekoya** [comment]
No problem! @wu87988622 will be tackling this in 0.7

**Comment by wu87988622** [comment]
This will be fixed in #1730
