### ISSUE TITLE
新增 Node 時，輸入不正確的資訊，不應該通過連線測試

### ISSUE THREAD

**Issue by eechih** [oharastream/ohara#1804]
Nodes > New node：Port、User 與 Password 欄位，輸入不正確的資料，不應該通過連線測試

**Comment by jackyoh** [comment]
這個在之後的版本會做修改. ping @konekoya @wu87988622

**Comment by chia7712** [comment]
The password and user name will be ignorable in k8s mode. see #1809

**Comment by chia7712** [comment]
BTW, #1631 is duplicate to this one.

**Comment by jackyoh** [comment]
那我先把此 issue 關閉
