### ISSUE TITLE
無法有效識別 Nodes 頁面的 SERVICES 欄位資訊

### ISSUE THREAD

**Issue by eechih** [oharastream/ohara#1805]
- Nodes > List：使用者無法有效識別 SERVICES 欄位內的資訊，例如 dklewmp92c, rqt2duurp2...，不應該顯示這類無用的資訊

**Comment by jackyoh** [comment]
這個問題須要之後大家來討論要顯示哪些資訊. ping @chia7712 @konekoya @vitojeng @eechih @wu87988622 @saivirtue  FYI

**Comment by konekoya** [comment]
I'm thinking about adding a prefix to the randomly generated names like:

borkerakjsfjkklajf
zookeeperlkjlksadjfda

**Comment by konekoya** [comment]
We will be discussing a better way to display the info in #1855
