### ISSUE TITLE
表單：沒有修改任何欄位內容，按鈕應該 disable

### ISSUE THREAD

**Issue by eechih** [oharastream/ohara#1807]
Nodes > Edit node：沒有修改任何欄位內容，TEST CONNECTION 與 SAVE 按鈕應該 disable

**Comment by jackyoh** [comment]
這屬於操作上的 bug, 我先把此 issue label 拔掉. ping @konekoya @wu87988622 FYI

**Comment by konekoya** [comment]
Thanks for the report @eechih and @jackyoh
