### ISSUE TITLE
新增 Workspace 時，發現沒有任何一個 Node 可用，應該要引導使用者先去新增 Node

### ISSUE THREAD

**Issue by eechih** [oharastream/ohara#1808]
Workspaces > New workspace：尚未建立任何 Node 前，應該要提示 User，先前往 Nodes 頁面新增 Node

**Comment by jackyoh** [comment]
ping @konekoya @wu87988622  FYI

**Comment by konekoya** [comment]
No problem. This will be addressed in 0.7
