### ISSUE TITLE
Add template for testing report issue

### ISSUE THREAD

**Issue by vitojeng** [oharastream/ohara#1810]
follow-up of #1794

**Comment by vitojeng** [comment]
A quick preview for Test Report template:
https://github.com/oharastream/ohara/issues/8

@oharastream/developer Have any suggestion?

**Comment by vitojeng** [comment]
More detail we can discuss after PR submit.

**Comment by chia7712** [comment]
wiki終於派上用場了

**Comment by jackyoh** [comment]
+1

**Comment by konekoya** [comment]
+1 :)

**Comment by vitojeng** [comment]
Product testing report issue template 已加入:
![screenshot 23](https://user-images.githubusercontent.com/475186/61016666-00ddd900-a3c3-11e9-9e7f-1bcf616ea9ba.jpg)
