### ISSUE TITLE
Support to use RocksDB as default store for Configurator

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#185]
Configurator, currently, uses in-memory store to save objects. It is not persistent so we have to clone whole Configurator container to keep data. The clone is a kind of "snapshot" so there is likelihood that data loss.

- [x] Introduce RocksDB Store (#1166)
- [x] document usage of RocksDB (#1207)

**Comment by vitojeng** [comment]
an important part for ohara backend.
I'm +1 on this issue.
