### ISSUE TITLE
把 0.6 branch 所有程式和文件的版本號修改成 0.6.1-SNAPSHOT

### ISSUE THREAD

**Issue by jackyoh** [oharastream/ohara#1853]
當 0.6.0 版本 release 之後需要把 0.6 branch 相關的程式和文件版號改成 0.6.1-SNAPSHOT, 避免之後 0.6.0 的 tag 在 QA 裡到處出現.

**Comment by konekoya** [comment]
Should this issue belong to 0.6.1?

**Comment by jackyoh** [comment]
> Should this issue belong to 0.6.1?

OK, 我來修改
