### ISSUE TITLE
Remove and ignore git merge reject files

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#1865]
There are some files in source code that are created due to `git` command and should be removed.
this issue need to:
1. remove `*.rej` files in ohara
2. add a rule to .gitignore

**Comment by vitojeng** [comment]
> 1. remove *.rst files in ohara

What's the file?

**Comment by saivirtue** [comment]
> What's the file?

My bad...it should be **.rej**, not **.rst** :(

**Comment by chia7712** [comment]
This is a good issue and it is worthy of being in 0.7 :)
