### ISSUE TITLE
Provide branch name in gradle.properties

### ISSUE THREAD

**Issue by vitojeng** [oharastream/ohara#1867]
More and more situations need to know the branch name, we should append a *branch* property to reduce the chance of hard-code branch name.

- [x] Provide branch name in gradle.properties(#1883)
- [x] Add branch name into InfoApi(#1913)

**Comment by chia7712** [comment]
+1

**Comment by vitojeng** [comment]
@konekoya , @wu87988622 

I found there are some files have hard-code **version** value:
* ohara-manager/client/cypress/api/api.test.js
* ohara-manager/client/cypress/support/commands.js 

I think these should be read the **version** value from gradle.properties in the future.
Is this possible?

**Comment by chia7712** [comment]
@vitojeng Could you add the new field "branch" to our ConfiguratorVersion? Also, update the docs for info APIs.

**Comment by vitojeng** [comment]
> @vitojeng Could you add the new field "branch" to our ConfiguratorVersion? Also, update the docs for info APIs.

Sure, will do.

**Comment by konekoya** [comment]
> I think these should be read the version value from gradle.properties in the future.
Is this possible?

Yes, I think it's possible. I'll file a new issue to work on this :)

**Comment by vitojeng** [comment]
Great! Thanks @konekoya!

**Comment by vitojeng** [comment]
Tasks are done.
