### ISSUE TITLE
Store the info of whether a jar is used in a service in the tags

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#1880]
In order to prevent creating a giant backend API which does a lot of stuff in an XHR request. We will be storing this info in the specific field that was just added in #1711.

**Comment by chia7712** [comment]
@konekoya Great but difficult issue :(

feel free to draw up specification to backend :)

**Comment by konekoya** [comment]
> feel free to draw up specification to backend 

Hmm, I thought backend won't need to do anything in this issue as the info will be stored directly in the __tags__ field :)

**Comment by konekoya** [comment]
@wu87988622 could we close this issue? This seems already resolved on your end?

**Comment by wu87988622** [comment]
This issue is finish with #2682
