### ISSUE TITLE
Generate ohara version info as a json file for manager to consume

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#1888]
@chia7712 Please help generate a JSON file which contains necessary version info for manager and place it at manager's root dir. Thank you :)

**Comment by chia7712** [comment]
@konekoya there will be a file in ```/home/ohara/default/bin/ohara_version```
```json
{
  "version": "xxx",
  "revision": "xxx",
  "branch": "xxx",
  "user": "xxx",
  "date": "xxx",
}
```
