### ISSUE TITLE
Remove "workerClusterName" from Pipeline

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#1897]
We are be cognizant of the fact that too strict checks for Pipeline APIs is unnecessary and depart from decoupling APIs and UI flow. #1655 got rid of too strict checks for Pipeline APIs. On account of APIs compatibility, "workerClusterName" is useless but it still lie in Pipeline.

- [x] Remove "workerClusterName" from Pipeline with manager #2186

**Comment by chia7712** [comment]
@wu87988622 @konekoya Could we resolve this one in 0.7?

**Comment by wu87988622** [comment]
> @wu87988622 @konekoya Could we resolve this one in 0.7?

This issues will finish in 0.7.

**Comment by chia7712** [comment]
@wu87988622 please add the link to PR for sub task.
