### ISSUE TITLE
User Guide: Workspace section

### ISSUE THREAD

**Issue by vitojeng** [oharastream/ohara#1924]
**Workspace** was introduced in version 0.6, the user guide should be updated.

- [x] Fix inconsistent rst styles in user guide
- [x] 0.7 (#2416)
- [x] 0.8 (#2415)

**Comment by jackyoh** [comment]
這個議題會更新到 0.6 的 branch 嗎？

**Comment by vitojeng** [comment]
應該不會...

**Comment by jackyoh** [comment]
OK

**Comment by vitojeng** [comment]
@konekoya Could you have time to help this task?
It would be great add into v0.7

**Comment by konekoya** [comment]
> Could you have time to help this task?
It would be great to add into v0.7

No problem :)

**Comment by vitojeng** [comment]
> No problem! Is this the only task in this issue? If so, I'm going to file a new PR and link directly to here :)

Thanks a lot.
Could you check the whole Ohara Manager part in the user guide?
Maybe some contents outdate, too.

**Comment by konekoya** [comment]
> Could you check the whole Ohara Manager part in the user guide?
Maybe some contents outdate, too.

Will do :)

**Comment by vitojeng** [comment]
Thanks a lot!!
