### ISSUE TITLE
把 ohara-agent 實作 K8S 版本, 整合到ohara-configurator 的 module 裡

### ISSUE THREAD

**Issue by jackyoh** [oharastream/ohara#195]
required by #425
整合 K8S 的實作,到 ohara-configurator module 裡

**Comment by chia7712** [comment]
this issue must be resolved in 0.3!

**Comment by jackyoh** [comment]
OK

**Comment by jackyoh** [comment]
需要實作的部份如下：
1. 在 configurator 需要能傳遞 K8S Restful API 的 HTTP URL
2. 找到在 configurator 可以建立 K8SClusterCollieImpl 物件的地方
3. 確保測試程式能正常的執行 K8S 的測試
