### ISSUE TITLE
中文版的quickly start（將發布於社團頁面）

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#1954]
社團頁面：https://www.facebook.com/groups/oharastream/

緣由：
中文社團面將面向一般大眾，容易閱讀和容易上手的文件非常必要。我們應該撰寫下列文件：
- [x] quickly start映像檔的使用介紹（映像檔將由#1787完成）[連結](https://www.facebook.com/notes/ohara-stream-user-group/%E5%98%97%E9%AE%AEohara%E5%B9%B3%E5%8F%B0/440778056650675/)
- [x] 透過quickly start映像檔介紹ohara UI [草稿](https://paper.dropbox.com/doc/2R4YebocN619exueUXbD0?cl=en_US)
- [x] ohara貢獻介紹 [草稿](https://paper.dropbox.com/doc/Ohara-6b4Wbr3Z5Fj0e6opDBoxn)
- [x]  如何面對失敗的 QA [草稿](https://paper.dropbox.com/doc/QA--AkK_~imhCPEJ8ovATEhJC~X~Ag-sWEMbkxwSiTFtjUC6YSnf)

**Comment by chia7712** [comment]
@wu87988622 @konekoya 能否麻煩你們幫忙撰寫中文版的UI操作介紹？基於0.6.0的quickly start映像檔？

原則上透過fb社群的「文章」來撰寫，不過UI會是第二篇文章，因此如果你們提早寫完可以先壓著不要發布：）

**Comment by chia7712** [comment]
@jackyoh 如何貢獻的文章可否麻煩你幫忙撰寫，這會是系列的第三篇

**Comment by jackyoh** [comment]
OK, 收到. 第三篇就交給我寫

**Comment by konekoya** [comment]
> @wu87988622 @konekoya 能否麻煩你們幫忙撰寫中文版的UI操作介紹？基於0.6.0的quickly start映像檔？

Sure thing :) Just wanted to know if there's a due date for this post...

**Comment by chia7712** [comment]
> Just wanted to know if there's a due date for this post...

原則上別太晚就好，第一篇由我開始，後續就大家接著發文就好

**Comment by jackyoh** [comment]
我問一下, 是照著英文版本直接翻譯, 還是直接另外寫中文的版本

**Comment by chia7712** [comment]
> 還是直接另外寫中文的版本

用中文的方式去寫一份

**Comment by jackyoh** [comment]
OK, 了解

**Comment by konekoya** [comment]
> 原則上別太晚就好，第一篇由我開始，後續就大家接著發文就好

No problem. I'll do that this week :)

**Comment by vitojeng** [comment]
@chia7712 ~粉絲頁~ => 社團

**Comment by jackyoh** [comment]
如果寫完之後要先放在哪裡給大家 review 會比較好

**Comment by chia7712** [comment]
> 如果寫完之後要先放在哪裡給大家 review 會比較好

開個paper或是任何線上文件都行

**Comment by jackyoh** [comment]
> 開個paper或是任何線上文件都行

ok, 那我就寫在 paper 裡

**Comment by chia7712** [comment]
@oharastream/developer [草稿](https://www.facebook.com/notes/ohara-stream-user-group/ohara%E8%88%87%E4%BB%96%E7%9A%84%E5%BF%AB%E6%A8%82%E4%BD%BF%E7%94%A8%E8%80%85/440751453320002/) 麻煩幫忙看看 謝謝

**Comment by saivirtue** [comment]
> @oharastream/developer [草稿](https://www.facebook.com/notes/ohara-stream-user-group/ohara%E8%88%87%E4%BB%96%E7%9A%84%E5%BF%AB%E6%A8%82%E4%BD%BF%E7%94%A8%E8%80%85/440751453320002/) 麻煩幫忙看看 謝謝

好像沒有權限觀看?
![image](https://user-images.githubusercontent.com/8088616/61692279-e95a0500-ad5f-11e9-9fa1-861a7eb1d1c3.png)

**Comment by chia7712** [comment]
@saivirtue 我改放到dropbox paper 了 （https://paper.dropbox.com/doc/Ohara--AhcfEp4x5H9~P1rIxRMoiIKlAg-aM7mlSQ4Kcn5RX4S3Tomw)

**Comment by jackyoh** [comment]
我的部份是寫介紹 ohara 貢獻, 如下連結：
https://paper.dropbox.com/doc/Ohara-6b4Wbr3Z5Fj0e6opDBoxn  

再請大家幫忙 review

**Comment by chia7712** [comment]
@vitojeng 0.6.0的快速啟動映像檔是否先用我自己做的？

**Comment by vitojeng** [comment]
> @vitojeng 0.6.0的快速啟動映像檔是否先用我自己做的？

Sure~ thanks!

**Comment by chia7712** [comment]
@jackyoh 麻煩下載[映像檔](https://drive.google.com/open?id=18Dp1BUtyWv6V0uihx_8ZFjCZ0dEejUf4)並分割成兩份（zip）後放到0.6.0的頁面～感恩

**Comment by jackyoh** [comment]
> @jackyoh 麻煩下載[映像檔](https://drive.google.com/open?id=18Dp1BUtyWv6V0uihx_8ZFjCZ0dEejUf4)並分割成兩份（zip）後放到0.6.0的頁面～感恩

OK，晚一點來放。是放在下面這個連結的地方嗎：
https://github.com/oharastream/ohara/releases/tag/0.6.0

**Comment by chia7712** [comment]
> OK，晚一點來放。是放在下面這個連結的地方嗎：

yep

**Comment by jackyoh** [comment]
我已經把程式碼傳上去了，我在測試看看能不能使用

**Comment by jackyoh** [comment]
我把如何貢獻 ohara 的文件修改完了, 有空再幫我 review 看看：
https://paper.dropbox.com/doc/Ohara-6b4Wbr3Z5Fj0e6opDBoxn

**Comment by chia7712** [comment]
@konekoya 換你了:)

**Comment by chia7712** [comment]
@jackyoh 可否麻煩你把我們這篇提到的教學連結貼到0.6.0 release頁面？

**Comment by jackyoh** [comment]
> @jackyoh 可否麻煩你把我們這篇提到的教學連結貼到0.6.0 release頁面？

ok, 是下面這個連結貼到 0.6.0 release 頁面嗎？
https://www.facebook.com/notes/ohara-stream-user-group/%E5%98%97%E9%AE%AEohara%E5%B9%B3%E5%8F%B0/440778056650675/

**Comment by chia7712** [comment]
> ok, 是下面這個連結貼到 0.6.0 release 頁面嗎？

沒錯～感恩

**Comment by jackyoh** [comment]
ok, 等等我貼上去

**Comment by jackyoh** [comment]
我更新了， 寫在 document 的項目裡。如果英文語法有問題再跟我說，我再來調整

**Comment by chia7712** [comment]
@konekoya would you please attach the link?

**Comment by konekoya** [comment]
@chia7712  Here is the link to my post :)
https://paper.dropbox.com/doc/2R4YebocN619exueUXbD0?cl=en_US

Please help review the post everyone!

**Comment by chia7712** [comment]
@jackyoh @konekoya 我覺得可以準備發布了

@jackyoh 例外請注意一下 文件裡面有關"指令"的部分可以的話都要格式化顯示喔

**Comment by jackyoh** [comment]
> @jackyoh 例外請注意一下 文件裡面有關"指令"的部分可以的話都要格式化顯示喔

OK，我要等 @konekoya  嗎？還是下午就先上去了

**Comment by chia7712** [comment]
> 我要等 @konekoya 嗎？還是下午就先上去了

你的主題比較獨立 先上沒關係

**Comment by jackyoh** [comment]
好，那我下午我就先貼上去

**Comment by konekoya** [comment]
Sorry, Mine still have some edit suggestions from @wu87988622 I will need some time to give them a look and edit the post a bit 😅

**Comment by chia7712** [comment]
@jackyoh Please update the description of this issue if you have published the article.

**Comment by jackyoh** [comment]
OK, 我把 ohara貢獻介紹 的項目在 description 打勾了。

**Comment by chia7712** [comment]
@konekoya @jackyoh please update the description if you have published the articles :)

**Comment by jackyoh** [comment]
@chia7712 OK, 如果我有發佈文章會更新 description

**Comment by chia7712** [comment]
@jackyoh any update?

**Comment by jackyoh** [comment]
目前沒有更新

**Comment by chia7712** [comment]
@jackyoh could we give a deadline to it, boss?

**Comment by jackyoh** [comment]
那這星期五會先給一個草稿, 下星期會完成。

**Comment by konekoya** [comment]
@jackyoh could you close this issue since the post was already published on Facebook :)

**Comment by jackyoh** [comment]
OK, I am going to close this issue.
