### ISSUE TITLE
Some UI minor fixes

### ISSUE THREAD

**Issue by vitojeng** [oharastream/ohara#200]
Todos:
- [ ] Pipeline -> Topic editor -> *Delete topic* button
* rename from `Delete` to `Remove`
- [ ] Pipeline -> Delete topic -> Delete topic dialog
* update title: `Remove topic`
* update message: `Are you sure you want to remove this topic from pipeline graph? This action cannot be undo!`
* rename button: `Yes, Remove this topic`
- [ ] Upper left corner: `Ohara` --> `OharaStream`
- [ ] Readme title: `Ohara` --> `OharaStream`

**Comment by konekoya** [comment]
Hmm, I'm gonna fix this in v0.2 and the jira issue is already here:
https://is-land.atlassian.net/browse/OHARA-1552

Should we close this? Otherwise, we would end up having an issue in both Jira and GitHub :)

**Comment by vitojeng** [comment]
@konekoya Can we address this issue in **M26**?

**Comment by konekoya** [comment]
I think we can. But I will need to finish #419 first :)

**Comment by konekoya** [comment]
Since this is urgent. I'm going to open a PR to close this issue :)

**Comment by vitojeng** [comment]
@konekoya Thanks a lot!
