### ISSUE TITLE
Update cluster requests of auto-filled behavior

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#2005]
From [here](https://github.com/oharastream/ohara/issues/1544#issuecomment-515054684)
> User is able to see the changes of properties if we auto-complete properties in CREATE phase, because the response is the properties we have updated.

User should see the auto-filled parameters from response of creating data, instead of in starting phase.

For example,
create a broker without specify zookeeper
```
{
  "name": "bk01"
}
```
If there is only 1 zookeeper exists, the response will be
```
{
  "name": "bk01",
  "zookeeperClusterName": "defaultzk"
}
```

apply this behavior to all the following route:
1. - [x] ~move auto filled behavior to creation phase in zookeeper~
zookeeper doesn't have any auto-filled behavior
1. - [x] move auto filled behavior to creation phase in broker (#2126)
1. - [x] ~move auto filled behavior to creation phase in worker~
move to part of #2144
1. - [x] move auto filled behavior to creation phase in connector (@chia7712) (#2103)
1. - [x] ~move auto filled behavior to creation phase in stream~
stream auto-filled logic move to creation already

**Comment by saivirtue** [comment]
/cc @oharastream/developer 
Please refer to the [discussion thread](https://github.com/oharastream/ohara/issues/1544#issuecomment-515054684) if you are not aware about what's going on :)
Feel free to leave your feedback.

**Comment by chia7712** [comment]
@saivirtue Let me take over a part of tasks :)
