### ISSUE TITLE
Support exactly-once in CsvSinkTask

### ISSUE THREAD

**Issue by eechih** [oharastream/ohara#2010]
Support exactly-once in CsvSinkTask

**Comment by chia7712** [comment]
Is "exactly-once" applied to "input" or "output"? The input is based on kafka's consumer so addressing exactly-once is not a problem. By contrast, the output, which is able to direct to various storage in spades, is hard to carry out the exactly-once I'd say.

**Comment by eechih** [comment]
> Is "exactly-once" applied to "input" or "output"?

Output

> By contrast, the output, which is able to direct to various storage in spades, is hard to carry out the exactly-once I'd say.

We will discuss this issue on Monday.

**Comment by eechih** [comment]
This issue has been too long, so close it
