### ISSUE TITLE
Change cypress' integration folder name to e2e

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#2013]
Since this is really the tests that we're referring to in the source code

**Comment by konekoya** [comment]
@chia7712 Any chance that we can change the name of __retry manager-it__ to __retry manager-e2e__ :)

**Comment by chia7712** [comment]
> retry manager-it to retry manager-e2e :)

just renaming??? Or there is another kind of test called "manager-e2e"

**Comment by konekoya** [comment]
Yes, just renaming :)

**Comment by chia7712** [comment]
> Yes, just renaming :)

I'm fine with this change. Please file PR and Jenkins will update command as well.

**Comment by konekoya** [comment]
> Please file PR and Jenkins will update command as well.

Ooops, didn't notice your message until now. The PR was merged... @@

**Comment by chia7712** [comment]
> Ooops, didn't notice your message until now. The PR was merged... @@

file another issue for it?

**Comment by konekoya** [comment]
> file another issue for it?

Sounds good, let's do this in #2025

**Comment by konekoya** [comment]
Closing this
