### ISSUE TITLE
Test running multiple JDBC source connector to confirm data row count

### ISSUE THREAD

**Issue by jackyoh** [oharastream/ohara#2024]
JDBC source connector 需要支援多個 jdbc source connector 使用同一個資料表。應該要做到一個 connector 執行完之後，其他新建立的 jdbc source connector 還是可以把資料寫入到 kafka topic 裡。

**Comment by chia7712** [comment]
為什麼會有這個議題? 不同connectors之間的會有依賴性?不然為何會影響彼此拉資料的事情

**Comment by jackyoh** [comment]
會有這個議題主要的原因,  是因為我這邊實作的 JDBC source connector 存放的 offset 只有 tableName 對應到 timestamp。這樣我不太確定啟動多個 connector 時, 使用相同的 table name 以及 topic name是否會有發生衝突的問題。

**Comment by chia7712** [comment]
> 這樣我不太確定啟動多個 connector 時, 使用相同的 table name 以及 topic name是否會有發生衝突的問題。

there is a internal index of "connector name" so the different connectors don't share the same offset.

**Comment by vitojeng** [comment]
It would be better to add some test for this case ?

**Comment by jackyoh** [comment]
OK, 我只使用 table 當 index 應該會有共享 offset 的問題，我會修改加上 connector name 當作 index 來避免發生共享 offset 的問題。

**Comment by jackyoh** [comment]
> It would be better to add some test for this case ?

這種情況不只要加上 test case 還需要修改程式碼。 issue 的標題我再來修改
