### ISSUE TITLE
Change retry manager-it to retry manager-e2e

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#2025]
The test we're referring to in frontend is end-to-end test not integration test. 

Ref #2013 

- [x] Change "retry manager-it" to "retry manager-e2e" for jenkins (@chia7712)
- [x] Change gradle command and update docs to use the new retry command (#2026)

**Comment by chia7712** [comment]
@konekoya Could u file a PR to change manager "it" to "e2e"? The task is not related to command of jenkins. However, consistent naming is better to us in maintaining :)

**Comment by chia7712** [comment]
@konekoya Also, the document about jenkins command need to be updated as well.

**Comment by konekoya** [comment]
Will do :)

**Comment by chia7712** [comment]
all done :)

**Comment by konekoya** [comment]
@wu87988622 @DavidMi-1 the end to end test command has been renamed to `retry manager-e2e`
