### ISSUE TITLE
Exclude gradle/wrapper/gradle-wrapper.properties from license check

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#2030]
We are not going to use gradlew and the latest intellij (2019.02) build the gradlew automatically. The license check is conscientious  but I'm fed up with the error :(

Let me exclude the wrapper files from license check.

**Comment by vitojeng** [comment]
Do we need to add this exclude?
I think Ohara doesn't include Gradle wrapper.

**Comment by chia7712** [comment]
@vitojeng The IntelliJ does generate the wrapper automatically when it detects that the configs of Gradle have been updated. Deleting the wrapper is too noisy...

**Comment by chia7712** [comment]
@vitojeng any feedback? Or I'm about to commit it.

**Comment by vitojeng** [comment]
Sorry, my notebook not available now. You may merge first.
-- 


---
Vito

**Comment by vitojeng** [comment]
/cc @oharastream/developer 

In Intellij, when you init/import a new project, the `Use Gradle from` setting:
![screenshot 27](https://user-images.githubusercontent.com/475186/62189801-85a88b00-b3a2-11e9-8ad5-0c893680fb2b.jpg)
would be `gradle-wrapper.properties`.

The `gradle-wrapper.properties` setting would cause IntelliJ to create some wapper files for your project:
* gradlew
* gradlew.bat
* gradle/wrapper/gradle-wrapper.jar
* gradle/wrapper/gradle-wrapper.properties

If change this setting to `Specified location` and specify gradle path, IntelliJ will never auto create wrapper files.

So we should use `Specified location` to avoid this case.
