### ISSUE TITLE
Fix the weird behavior of the snackbar component

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#2041]
~~1. Manager will have two notifications at the same showing the same exact error when fails to connect to configurator (Gateway Timeout)~~ Fix in #2702 

2. The notification sometimes keeps displaying the same error message multiple times (looks like in an infinite loop? Need to dig a bit further) which cannot be removed from the screen when the cross button

**Comment by konekoya** [comment]
cc @wu87988622

**Comment by wu87988622** [comment]
> cc @ wu87988622

Ok 
I will handle this issue

**Comment by konekoya** [comment]
@wu87988622 The first issue was fixed (see the description). Can you verify if the second issue is still there and should be addressed? If not, this issue can be closed then

**Comment by wu87988622** [comment]
This error is due to the infinite loop caused by React's interaction with useState in the use of useEffect.
Is fix in #2229
