### ISSUE TITLE
README.md 檔案需要修改啟動 configurator container 的指令

### ISSUE THREAD

**Issue by jackyoh** [oharastream/ohara#205]
目前在 README.md 裡啟動 configurator container 的指令如下：
```
docker run --rm -p 12345:12345 oharastream/configurator:0.2-SNAPSHOT --port 12345
```
因為現在的 configurator 可以連到 ohara agent 的每台 node, 因此需要把每台 node 的資訊暴露給 configurator 的 /etc/hosts, 不然會收到 UnknowHost 的 exception, 所以在 README.md 啟動 configurator container 的指令應該需要修改成如下：

```
docker run --rm -p 12345:12345 --add-host ${NodeHostName}:${NodeHostIP} oharastream/configurator:0.2-SNAPSHOT --port 12345 --node ${UserName}:${Passwod}@${NodeHostName}:${Port}
```

**Comment by chia7712** [comment]
+1. We should remind user to add related host information to configurator.

**Comment by jackyoh** [comment]
那我把給 host 的資訊加到 README.md 裡

**Comment by chia7712** [comment]
@jackyoh Is this still legal?

**Comment by jackyoh** [comment]
目前文件已經沒有寫在 README.md 裡了, 啟動 configurator 的指令在以下的連結裡：
https://ohara.readthedocs.io/en/latest/user_guide.html#execute-configurator

所以這個議題已經不是 legal 了

**Comment by chia7712** [comment]
> 所以這個議題已經不是 legal 了

thanks. let me close this one.
