### ISSUE TITLE
Replace query parameter by http body

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#206]
Some objects demand the cluster name as query parameter. This is inconsistent with other APIs. We should substitute body for query parameter.

before:
POST topics/cluster=aaa
{
  "name"="a"
}

after
POST topics
{
  "name"="a",
  "cluster"="aaa"
}

**Comment by jackyoh** [comment]
所以前端也要去修改查詢的方式

**Comment by chia7712** [comment]
> 所以前端也要去修改查詢的方式

absolutely. However, manager, IIRC, uses "cluster" on log and pipeline only. Hence, this changes don't kill us.

**Comment by jackyoh** [comment]
I got it.

**Comment by chia7712** [comment]
This is duplicate to #518
