### ISSUE TITLE
Update the javadoc and scaladoc

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#2062]
Since our Jenkins QA will check documents also after #2055, we need to fix this ASAP...

1. - [x] ease up the warnings of javadoc and scaladoc (@saivirtue) (#2069)
1. - [x] QA should highlight the warnings of both javadoc and scaladoc (@chia7712) (#2067)

**Comment by chia7712** [comment]
The warnings of javadocs and scaladocs are just warnings. It does not fail our QA now :)

**Comment by saivirtue** [comment]
> The warnings of javadocs and scaladocs are just warnings.

Do we plan to strict our jenkins for javadoc warnings? our it just check "rst warnings" only?

**Comment by chia7712** [comment]
> Do we plan to strict our jenkins for javadoc warnings? our it just check "rst warnings" only?

Yep. Wrong format of docs should be rejected by QA :)

**Comment by saivirtue** [comment]
OK. I will move this task to TODO list, and accomplish it when QA complain the docs warning :)

**Comment by chia7712** [comment]
@saivirtue in fact, this issue need to be resolved before QA starts to reject the wrong code docs :)

**Comment by chia7712** [comment]
@saivirtue we all are fed up with writing docs so I divide this issue into three sub tasks. And would you please fix the docs for scala code?

@eechih could you help us to complete the docs for java code?

I'm about to enable QA to show the warnings of both javadoc and scaladoc.

**Comment by saivirtue** [comment]
> would you please fix the docs for scala code?

Sure

**Comment by saivirtue** [comment]
>@saivirtue we all are fed up with writing docs so I divide this issue into three sub tasks. And would you please fix the docs for scala code?
@eechih could you help us to complete the docs for java code?

It seems a little bit code need to be modified. Let me fix the javadoc and scaladoc in one PR.
