### ISSUE TITLE
an new Pipeline API used to cleanup nonexistent object from flows

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#2090]
Pipeline APIs offered a cryptic but useful function that it cleanup nonexistent objects from pipeline when pipeline APIs is invoked. The function introduces a embarrassing issue that the GET/LIST APIs produce changes to data, so we had removed the "cleanup" (see #1655).

However, I'm cognizant that Ohara Manager relies on it, and I feel alienating our APIs user is not a good news. Hence, I plan to add an new API for the "cleanup". The URL form is shown below:
```
"/v0/pipelines/${name}/cleanup?group=${group}
```

The URL is similar to other "action" APIs (start, stop and so on).

**Comment by chia7712** [comment]
@konekoya @wu87988622 any suggestions?

**Comment by wu87988622** [comment]
> @konekoya @wu87988622 any suggestions?


聽起來不錯,
我有一個問題 cleanup 是馬上就會執行的嗎？ 
或者是我們需要透過何種方式去確認。

**Comment by chia7712** [comment]
>我有一個問題 cleanup 是馬上就會執行的嗎？
> 或者是我們需要透過何種方式去確認。

All "actions" in ohara are async, and hence you have to call "get" to check the result :)

**Comment by wu87988622** [comment]
> > 我有一個問題 cleanup 是馬上就會執行的嗎？
> > 或者是我們需要透過何種方式去確認。
> 
> All "actions" in ohara are async, and hence you have to call "get" to check the result :)

ok thank you.

**Comment by konekoya** [comment]
+1 for this :)
