### ISSUE TITLE
Delete topic api is not really working

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#2093]
**Describe the bug**
When delete a topic successfully, any new topic creation with same name will get exeption.

**To Reproduce**
1. create topic (/v0/topics)
```json
{
   "name": "fromTopic",
   "numberOfPartitions": 1,
   "numberOfReplications": 1
}
```
1. start topic (/v0/topics/fromTopic/start)
1. stop topic (/v0/topics/fromTopic/stop)
1. delete topic (/v0/topics/fromTopic)
1. create same name topic
```json
{
   "name": "fromTopic",
   "numberOfPartitions": 1,
   "numberOfReplications": 1
}
```
1. start topic, but throw exception
```
{
    "code": "org.apache.kafka.common.errors.TopicExistsException",
    "message": "Topic 'default-fromTopic' already exists.",
    "stack": "org.apache.kafka.common.errors.TopicExistsException: Topic 'default-fromTopic' already exists.\r\n"
}
```

**Comment by chia7712** [comment]
```
.exist(topicInfo.name)
```
the "name" should be replaced by "key.topicNameOnKafka()" :(

**Comment by saivirtue** [comment]
> he "name" should be replaced by "key.topicNameOnKafka()"

Yep :)
