### ISSUE TITLE
Change stream api prefix from "stream" to "streams"

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#2115]
Consistency is very important in our api. And it should use the same rule in stream api.
```diff
Topic : /v0/topics
Node: /v0/nodes
- Stream: /v0/stream
+ Stream: /v0/streams
```

Requirements:
1. `rest-stream.rst` need to rename to `rest-streams.rst`
2. all reference link `rest-streamXXX` need to rename to `rest-streamsXXX`

**Comment by saivirtue** [comment]
/cc @konekoya @wu87988622 
This task will be last part of #1544. I separate this issue because it may be hard to finish all tasks of #1544 in current release.

**Comment by vitojeng** [comment]
@saivirtue Just remind.
Since #2095 already completed, the stream api content move to /docs/src/rest-stream.rst
Due to the rst file name follow the api naming, so `rest-stream.rst` need to rename to `rest-streams.rst` too.

**Comment by chia7712** [comment]
+1

**Comment by saivirtue** [comment]
> so rest-stream.rst need to rename to rest-streams.rst too.

Thanks for the reminding :)
