### ISSUE TITLE
Need a flexible way to extend SettingDef

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#2124]
We design a basic class `SettingDef` to define a object definition. However, we should make the custom type and checker of sub class to be extendable from this class.

**Comment by chia7712** [comment]
@saivirtue let me take over this one to move it on to 0.7

**Comment by chia7712** [comment]
I have files another issue (#2200) to address a task similar to this one. the checker() method in SettingDef is already a overridable method. And the true target to this issue should be how to promote the type to all subclasses.

**Comment by saivirtue** [comment]
This issue is too old to be discussed with...will close now.
