### ISSUE TITLE
add helper method to RouteUtils to accept custom action

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#2130]
#2090 is about to add a route to process custom action. The current route utils is not able to address it. As a conscientious utils, RouteUtils should have a way to inject custom route to process any kind of action request.

- [x] a bit refactor for RouteUtils (#2155)

**Comment by chia7712** [comment]
@konekoya @wu87988622 I’m going to remove payload from all action requests. Is  Manager ready to meet this change?

**Comment by konekoya** [comment]
> @konekoya @wu87988622 I’m going to remove payload from all action requests. Is Manager ready to meet this change?

So it's basically, start/stop/delete right? If so, I think it's pretty safe now to remove the payload from them

**Comment by chia7712** [comment]
reopen to do a bit cleanup
