### ISSUE TITLE
stream should not seek worker cluster via group of jar

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#2151]
stream route seek the worker cluster via group of jar. It is really really really weird ...

1. - [x] add explicit argument - broker name - to Stream APIs (#2344)
1. - [x] check the jar key for both creation request and update request (#2717)
1.  ~- [ ] take the new Stream APIs for manager~ (move to #2695)
1. - [x] Give up to take worker cluster from jar's group (#2736)
1. - [x] Update docs to fit the new rules for stream (#2737)

**Comment by saivirtue** [comment]
> stream route seek the worker cluster via group of jar

Good catch. I think it is time to let "group of stream" playing :)

**Comment by chia7712** [comment]
>  I think it is time to let "group of stream" playing :)

the "group" is not supported by cluster now. 

What I want to do is to make StreamClusterInfo to take broker cluster according to input topic keys rather than the group of jar ...

**Comment by saivirtue** [comment]
> What I want to do is to make StreamClusterInfo to take broker cluster according to input topic keys 

That's OK also.

**Comment by chia7712** [comment]
@konekoya @wu87988622 The streamapp is going to require the broker cluster name (and it is located at definition). However, it may be weird to require user to enter the broker cluster name for UI users, since they are in "pipeline" page.

A suitable way is that the definition to broker cluster has a reference called BROKER_CLUSTER. And Manager auto-fill the field for user (this case is similar to connector's worker cluster).

any feedback?

**Comment by saivirtue** [comment]
A little discussion:
Could we use the `?group=` and pass the workspace name to it instead of using reference of settings?
I think it is better that we use less special case "reference" since the broker_cluster is only used in streamApp only...

**Comment by chia7712** [comment]
> Could we use the ?group= and pass the workspace name to it in manager instead of using reference of settings?

workspace is a tern used by manager only. Stream APIs have no idea about it.

> I think it is better that we use less special case "reference" since the broker_cluster is only used in streamApp only...

the reference is a hint that the value should be mapped to what kind of resource. It is a similar case to connector. I'm ok to keep the NONE in reference if @konekoya @wu87988622 are on the same page. BTW, I have added the related tasks.

**Comment by saivirtue** [comment]
> workspace is a tern used by manager only. Stream APIs have no idea about it.

My mistake. It should be "worker cluster name". The reason I want to apply it to group is that we can use different streamApp name in different workspace.

> the reference is a hint that the value should be mapped to what kind of resource. It is a similar case to connector.

Got it.
