### ISSUE TITLE
Apply TopicKey to Stream APIs

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#2158]
The Stream APIs still use deprecated interface of Topic object ...

1. - [x] for 0.8 (#2282)
1. - [x] for 0.7 (#2306)

**Comment by saivirtue** [comment]
Is there any plain to backport 0.7?
I think there are a lot of changes needed to be accomplish after topicKey apply to 0.7. Could we use a hadcode prefix to 0.7 version? I think it may reduce the task effort for frontend.

**Comment by chia7712** [comment]
> Could we use a hadcode prefix to 0.7 version?

Let us fix the group for streamapp in 0.7. I don't think the hard code to fix group for streamapp is a easy way :(

**Comment by chia7712** [comment]
@konekoya @wu87988622 We are going to file PR to enable streamapp to accept topic key in 0.7. Please take a look at #2306

**Comment by konekoya** [comment]
I'll add a new task in #2209 to address this
