### ISSUE TITLE
Fix the url parser for StreamCollie

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#2160]
On account of #2156 changing the format of file url, StreamCollie fail to parse the file url now. StreamCollie should not assume the format of url so we will enable StreamCollie to handle TopicKey and FileInfo (see #2158). #2158 will be a big change so I'm going to file a hot-fix in this issue.

**Comment by saivirtue** [comment]
> On account of #2156 changing the format of file url, StreamCollie fail to parse the file url now. 

Since this PR was merged at last night, I cannot get the point of this change:
```diff 
- "http://$hostname:$port/${ConfiguratorApiInfo.V0}/$DOWNLOAD_FILE_PREFIX_PATH/$group/$name")
+ "http://$hostname:$port/${ConfiguratorApiInfo.V0}/$DOWNLOAD_FILE_PREFIX_PATH/${key.name()}?$GROUP_KEY=${key.group()}"
```

Is it because unifying the url format of all API?

**Comment by chia7712** [comment]
> Is it because unifying the url format of all API?

Yep

> IMHO, this download url is not really open to user now. 

In fact, I feel it is time to open it :)

> And if the change was must have, please wait the #810 refactor done since there are a lot of things change and some of the conflict codes are hard to do now...

Sure.

**Comment by chia7712** [comment]
seems some tools (ex. wget) prefer to save the file with name from url. Let me revert a part of changes of #2156 to resolve this issue.
