### ISSUE TITLE
Remove "workerClusterName" from Pipeline with manager

### ISSUE THREAD

**Issue by wu87988622** [oharastream/ohara#2166]
Ref #1897

**Comment by chia7712** [comment]
@wu87988622 Please add a subtask to #1897 than open another issue in the future. Collecting them to the same issue is more readable.

**Comment by wu87988622** [comment]
> @wu87988622 Please add a subtask to #1897 than open another issue in the future. Collecting them to the same issue is more readable.

ok i will close this issue and add a subtask to #1897 
thanks
