### ISSUE TITLE
StreamApp can't be used in manager's pipeline

### ISSUE THREAD

**Issue by HarryChiang143** [oharastream/ohara#2167]
**Describe the bug**
使用v0.6.0 的ohara-quickstart-vm，在Pipeline中無法添加已上傳的streamApp

**To Reproduce**
1. 匯入ohara-quickstart-vm
2. 啟動configurator、manager
3. 建立node、workspace，創建topic及上傳streamapp
4. 建立pipeline，添加streamapp，跳出streamapp doesn't exist錯誤
![螢幕快照 2019-08-07 上午10 49 50（2）](https://user-images.githubusercontent.com/46185836/62592642-855e4180-b906-11e9-8fb6-cc19ec9afce9.png)
5. 砍掉pipeline，嘗試從workspace清除已上傳streamapp失敗
![螢幕快照 2019-08-07 上午10 50 26（2）](https://user-images.githubusercontent.com/46185836/62592704-b2aaef80-b906-11e9-9f32-1f68f384beeb.png)

**Expected behavior**
1. streamapp上傳後應可在pipeline中正常使用。
2. 沒有pipeline使用該streamapp時應可正常刪除。

**Screenshots**
reference logs from ohara-configurator:
First Error msg:
![螢幕快照 2019-08-07 上午10 52 28](https://user-images.githubusercontent.com/46185836/62592971-c014a980-b907-11e9-8fb8-34171ad7241c.png)

Second Error msg:
![螢幕快照 2019-08-07 上午10 52 39](https://user-images.githubusercontent.com/46185836/62593004-dc184b00-b907-11e9-9b63-2718aecaa416.png)

刪除失敗的log msg:
![螢幕快照 2019-08-07 上午10 53 04](https://user-images.githubusercontent.com/46185836/62593034-f18d7500-b907-11e9-954d-6e7f5431184b.png)

**Operation System (please complete the following information):**
 - Backend OS & Version: CentOS 7.3
 - Frontend OS & Version: CentOS 7.3
![螢幕快照 2019-08-07 上午11 32 22](https://user-images.githubusercontent.com/46185836/62592794-133a2c80-b907-11e9-9fc9-895b81d5480e.png)
 - Browser & Version : Google Chrome , 版本 75.0.3770.100 (正式版本) (64 位元)

**Comment by saivirtue** [comment]
thanks for reporting, I will take a look later.

**Comment by saivirtue** [comment]
It is due to the error message response from api cannot be parsed in manager when streamApp is not starting yet.
Since we are going to release 0.7, is it urgent for you to fix it in 0.6?

**Comment by HarryChiang143** [comment]
I think this issue fix in later version is ok , plz fix it before 1.0 release.

**Comment by vitojeng** [comment]
@saivirtue Can we fix this issue in v0.7 ?

**Comment by saivirtue** [comment]
> @saivirtue Can we fix this issue in v0.7 ?

Sure :)

**Comment by saivirtue** [comment]
@HarryChiang143 
This should be fixed in 0.7. Could you help me to verify if resolved?

**Comment by HarryChiang143** [comment]
@saivirtue I think this bug already fixed in 0.7

**Comment by HarryChiang143** [comment]
@saivirtue 

我發現第二個預期的behavior仍然未能運作。

- [ ]沒有pipeline使用該streamapp時應可正常刪除。

**Comment by chia7712** [comment]
> 我發現第二個預期的behavior仍然未能運作。

你是指streamapp "jar"嗎

**Comment by saivirtue** [comment]
> 你是指streamapp "jar"嗎

@HarryChiang143 的意思是streamApp jar 即使在pipeline刪除後依然不能delete

**Comment by chia7712** [comment]
> 的意思應該是streamApp jar 即使在pipeline刪除後依然不能delete

我記得0.7在刪除pipeline時"不會"清除底下的物件(例如streamapp, connector)，所以該jar無法刪除是合理的，因為"仍然"有streamapp在使用該jar

FYI @konekoya @wu87988622

**Comment by HarryChiang143** [comment]
As discussion before, i will check this scenario on v0.8

**Comment by konekoya** [comment]
Yep. This issue will be addressed in 0.8. Please follow the issue here #2321

**Comment by chia7712** [comment]
@HarryChiang143 Could we close this issue?

**Comment by HarryChiang143** [comment]
@chia7712  Sure, i will track last issue on #2321
