### ISSUE TITLE
Support settings field for cluster

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#2191]
For all the clusters in ohara (zk, bk, wk, stream,...), we need a way to get the definitions and display on UI. A new API will be required: (stream for example)
`PUT /v0/stream/{name}/definition`
The payload
```
{
  "definitions": {
    "imageName": "oharastream/stream:0.7.0-SNAPSHOT",
    "jarKey": {
      "group": "default",
      "name": "aaa.jar"
    }
    ...
  }
}
```
This API will return ALL the definition for current base (image).

Address the following tasks:
1. ~- [ ] Move definition checking to RouteUtils~
1. - [x] Support settings field for zookeeper (@saivirtue ) (#2531)
1. - [x] Support settings field for broker (@saivirtue ) (#2550)
1. - [X] Support settings field for worker (@chia7712 ) (#2505)
1. - [x] tweak settings field for worker (@chia7712 ) (#2515)
1. ~- [ ] Implement definition api (move to #2520)~
1. ~- [ ] Using environment variables to set container configuration for zookeeper~
1. ~- [ ] Using environment variables to set container configuration for broker~
1. ~- [ ] Using environment variables to set container configuration for worker~
1. ~- [ ] Using environment variables to set container configuration for stream~

**Comment by chia7712** [comment]
I changed the description that the change to APIs broken is moved to #2438. We should focus on the new fields for this issue.

**Comment by chia7712** [comment]
@saivirtue do you plan to add "settings" to all cluster info in this issue?

**Comment by saivirtue** [comment]
> @saivirtue do you plan to add "settings" to all cluster info in this issue?

Yep. add some description to make more clearly.

**Comment by chia7712** [comment]
> add some description to make more clearly.

got it. Let me take over it for Worker :)

**Comment by chia7712** [comment]
> - move the environments in worker.sh into definition

The dynamically envs to container should be moved to another issue. We force our attention on definition and setting for all clusters :)

**Comment by chia7712** [comment]
@saivirtue Could you take over the sub task about broker APIs if you have free cycles? the issues include this one, #2438 and #2243
