### ISSUE TITLE
Refactor checker of SettingDef

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#2198]
This is follow-up of #1765

We should add a infra to check input settings according to SettingDerf. The rules are shown below.
1. auto-add the default value (if defined) to input settings (if nonexistent)
2. check the value according to type.
3. Reject the null value if the setting definition does not say it is optional.

**Comment by chia7712** [comment]
what do you want to do for streamapp?

**Comment by saivirtue** [comment]
> what do you want to do for streamapp?

Please see the description :)

**Comment by chia7712** [comment]
>  if there were default values, it should be checking

Not really. We should add a infra to check input settings according to SettingDerf. The rules are shown below.
1. auto-add the default value (if defined) to input settings (if nonexistent)
1. check the value according to type.
1. Reject the null value if the setting definition does not say it is optional.
