### ISSUE TITLE
Bump Scala version to 2.12.9

### ISSUE THREAD

**Issue by vitojeng** [oharastream/ohara#2204]
[Scala 2.12.9](https://github.com/scala/scala/releases/tag/v2.12.9) already released.
Brings another 5% ~ 10% improvement in compiler performance, improved compatibility with JDK 11/12/13

**Comment by vitojeng** [comment]
Done.

**Comment by vitojeng** [comment]
Also rebuilded **oharastream/ohara:deps** and **oharastream/ohara:ci** docker images, too.

**Comment by chia7712** [comment]
@vitojeng Could you please remove the scala 2.12.8 jar from our worker images? I have add a sub task to the description.

**Comment by vitojeng** [comment]
> @vitojeng Could you please remove the scala 2.12.8 jar from our worker images? I have add a sub task to the description.

Thank you for remind, will do.

**Comment by chia7712** [comment]
@saivirtue Please close this issue if you are going to fix the image in another issue :)

**Comment by saivirtue** [comment]
> @saivirtue Please close this issue if you are going to fix the image in another issue :)

mistake ping?

**Comment by chia7712** [comment]
> mistake ping?

my bad :(

ping @vitojeng

**Comment by vitojeng** [comment]
Move to #2433
