### ISSUE TITLE
Remove the support to "jars" and "jar"

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#2216]
Both "jars" and "jar" are deprecated by #1711. The replacements are "files" and "file". 

1. first commit (#2428) 
1. revert commit (#2428)
1. final commit (#2429)

**Comment by chia7712** [comment]
@wu87988622 @konekoya Could I put this to 0.7?

**Comment by konekoya** [comment]
Hmm, I know @wu87988622 has made some changes about this but still unclear if we have more work that is related to this. It's safer if we move this to 0.8. Sorry about this :(

**Comment by chia7712** [comment]
>  It's safer if we can move this to 0.8. Sorry :(

no problem at all :)

**Comment by chia7712** [comment]
@wu87988622 @konekoya please double check :)

**Comment by konekoya** [comment]
> @wu87988622 @konekoya please double check :)

Sorry for the late reply. Confirmed this with @wu87988622 yesterday. It should safe to remove them now :)
