### ISSUE TITLE
Complete setting definition of docs

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#2219]
After #810 done, we need to complete the streamApp docs also.
- Add docs of StreamDefinitions
- Add docs of SettingDef

**Comment by chia7712** [comment]
What is introduced here?

**Comment by saivirtue** [comment]
> What is introduced here?

I'm edit description now...this is the doc follow-up of #810

**Comment by chia7712** [comment]
The SettingDef is common component now. It is worth having a independent document file.

**Comment by saivirtue** [comment]
SettingDef is "how to define"
In this issue, I want to finish the part of "how to use in streamApp"
Let me address a sub-task to finish the common part.

**Comment by vitojeng** [comment]
@saivirtue It's awesome.
We really need a page for how to use setting definition.
