### ISSUE TITLE
[Question] the "Basic info" does not show all used images

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#2227]
![註解 2019-08-12 151740](https://user-images.githubusercontent.com/6234750/62850075-6e5b8d00-bd14-11e9-8b55-ff0809dae983.png)

It seems to me that users should be able to see all "used" images.

**Comment by chia7712** [comment]
FYI @wu87988622 @konekoya

**Comment by konekoya** [comment]
Hmm, I remember we've discussed this before but somehow forgot why we ended up with only showing the worker images. @eechih could you recall this...

**Comment by konekoya** [comment]
@wu87988622 what do think about this?

**Comment by wu87988622** [comment]
> > It seems to me that users should be able to see all "used" images.
> 
> +1 I'm basically okay to display all the used images here.
> 
> @wu87988622 what do think about this?

+1 so we need show Zookeeper, Broker ,Worker and StreamApp ?

**Comment by eechih** [comment]
> Hmm, I remember we've discussed this before but somehow forgot why we ended up with only showing the worker image in this section.

Me too.  QQ~

> It seems to me that users should be able to see all "used" images.

+1

**Comment by chia7712** [comment]
@wu87988622 @konekoya @eechih please someone makes the conclusion and PR. (of course, please tag the resolved version as well). thanks

**Comment by konekoya** [comment]
@wu87988622 could you file a new PR to tackle this :)

**Comment by wu87988622** [comment]
> @wu87988622 could you file a new PR to tackle this :)

ok

**Comment by wu87988622** [comment]
this question are update to #2297
