### ISSUE TITLE
Get definition of streamApp should skip quote of url also

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#2231]
#2214 solved the parsing url problem of streamApp.
However, the definition is still have the same problem...

The proper way to pass the `java.net.URL` is:
`new URI(url.getProtocol, url.getUserInfo, url.getHost...).toASCIIString`

[Oracle URI](https://docs.oracle.com/javase/7/docs/api/java/net/URI.html) explains the detail about "encode each part of url"

we need a proper way to pass the encoded-url to docker.
- [x] use URI constructor instead of URL for parsing url to server (#2248)

**Comment by chia7712** [comment]
If the "quote" is something magic in streamapp, it would be better to lock it in the box than exposing it.

**Comment by saivirtue** [comment]
> If the "quote" is something magic in streamapp, it would be better to lock it in the box than exposing it.

It is not required in streamApp. It's just a missing change in #2214 :(

**Comment by saivirtue** [comment]
It seems still not working, re-open it.
