### ISSUE TITLE
The nodeNames should represent what user input rather than the alive nodes

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#2243]
There are two disadvantages of making nodeNames represent active nodes.
1. a weird scenario: a node exists on both nodeNames and deadNodes
1. user can't "see" the origin input
1. it is hard to associate "nodeNames" to "active nodes"

updated: 
1. the nodeNames is what user input. 
1. the deadNodes is the (nodeNames - nodes hosting running container)

~the aliveNodes is the nodes having running container~

~Noted: the size of nodeNames may be bigger than (deadNodes + aliveNodes) since the removed containers don't display on (deadNodes + aliveNodes).~

1. - [x] redefine the nodeNames and deadNodes for Stream cluster. the nodeNames is what user input. And deadNodes is the (nodeNames - nodes hosting running container) (#2439)
1. - [x] redefine the nodeNames and deadNodes for Zookeeper cluster. the nodeNames is what user input. And deadNodes is the (nodeNames - nodes hosting running container) (#2553)
1. - [x] redefine the nodeNames and deadNodes for Broker cluster. the nodeNames is what user input. And deadNodes is the (nodeNames - nodes hosting running container) (@saivirtue ) (#2554)
1. - [x] redefine the nodeNames and deadNodes for Worker cluster. the nodeNames is what user input. And deadNodes is the (nodeNames - nodes hosting running container) (#2541)

**Comment by saivirtue** [comment]
> There are two disadvantages of making nodeNames represent active nodes.

Do you mean stream route here?

**Comment by chia7712** [comment]
> Do you mean stream route here?

for all cluster services.

**Comment by saivirtue** [comment]
> for all cluster services.

IIRC, in the `ClusterCollieImpl`, the containers object is **all containers include the dead node**
In other words, each cluster will set the nodeNames as all containers node is as same as user request, right?

**Comment by chia7712** [comment]
> IIRC, in the ClusterCollieImpl, the containers object is all containers include the dead node

yep

> In other words, each cluster will set the nodeNames as all containers node is as same as user request, right?

almost. However, it would be better to "save" the nodeName passed by user rather than guessing it via containers.

**Comment by saivirtue** [comment]
got it. It seems we can pass the nodeNames to environment?

**Comment by chia7712** [comment]
>  It seems we can pass the nodeNames to environment?

yep. the containers are hosted by ohara configurator. It is ok to put stuff to envs.
