### ISSUE TITLE
Ohara 0.7.0 product testing report

### ISSUE THREAD

**Issue by wu87988622** [oharastream/ohara#2254]
## 測試項目

<details>
<summary><b>1. 基本測試</b></summary>

- [x] 確認畫面（UI）與設計稿（Design）是否一致
  - 顏色、字型、符號、圖片、...
- [x] 檢查所有畫面的 Title 名稱是否正確
- [x] 所有連結是否有前往正確頁面
- [x] 切換視窗大小時，有無跑版情形
- [x] 切換視窗大小後，文字與圖形是否竄行
- 表單
  - [x] 任何一個必填欄位未填寫，不能送出
  - [x] 表單送出中，應該明確表達正在處理中的訊號
  - [x] 表單送出中，應該要凍結表單（除非有提供取消功能）
  - [x] 任何表單至少要有 CTA 及 Cancel 兩類按紐 (CTA: Call-To-Action)
- 訊息
  - [x] 成功訊息，應該要明確指出完成對象
  - [x] 錯誤訊息，應該要明確指出錯誤對象
  - [x] 確認訊息
    - [x] 刪除確認，應該要明確指出欲刪除對象
- 按鈕
  - [x] 任何一個刪除按鈕，都要有刪除確認提示
- 鼠標
  - [x] 移動到所有可以點擊的元素，要出現 pointer cursor
      - Button, Link icon, Link text, ...
</details>

<details>
<summary><b>2. 功能測試: <a href="https://github.com/oharastream/ohara/wiki/Test-case:-Normal-case">Normal case</a></b></summary>

- [x] Create a new workspace with three nodes
- [x] Create two topic and upload a stream app jar into the workspace
- [x] Create a new pipeline and add some components into pipeline
- [x] 連接 FTP Source -> Topic 1 -> Stream App -> Topic 2 -> HDFS Sink
- [x] 連接 Perf Source -> Topic 
- [x] Prepare required folders and test data on the FTP server
- [x] Start all connectors and stream app
- [x] Verify which test data was successfully dumped to HDFS
</details>

<details>
<summary><b>3. 安裝測試:<a href="https://github.com/oharastream/ohara/wiki/Test-case:-Install-case">Install case</a></b></summary>

- [x] Confirm your use the hardware specification
- [x] Confirm your use version
- [x] Install the kubernetes
- [x] Running the Ohara Configuration service
- [x] Running the Ohara Manager service

</details>
### 設計稿：
- #642 As a developer, I need a proposal to understanding the overall design to enable metrics

### 測試環境：
- Ohara
  - Mode: k8s 
  - Version: 0.7.0-SNAPSHOT
  - Build date: 2019-08-17 17:09:26
- 測試工具
  - 瀏覽器：Chrome  76.0.3809.100 
  - 最小螢幕寬度：1200

### 基本測試：
 - Pipeline graph failed icon link to logs page url workers is undefined #2347 
 - New topic modal CTA button is different other modal #2348 
 - Address unnecessary requests that are made in react hooks based API #2229

### 功能測試：
 - Cluster showing "failed" at first fetch by api #2346 
-  Stop pipeline streamApp graph always Running #2350 
 - Graph start connector no update after pipeline stop connector #2375
 - Connector has multiple node metrics have duplicate value #2376
 - Stream property form cannot be updated properly #2382
  - Cannot remove a graph from the pipeline graph #2401

**Comment by DavidMi-1** [comment]
## 測試項目

<details>
<summary><b>1. 基本測試</b></summary>

- [ ] 確認畫面（UI）與設計稿（Design）是否一致
  - 顏色、字型、符號、圖片、...
- [ ] 檢查所有畫面的 Title 名稱是否正確
- [ ] 所有連結是否有前往正確頁面
- [ ] 切換視窗大小時，有無跑版情形
- [ ] 切換視窗大小後，文字與圖形是否竄行
- 表單
  - [ ] 任何一個必填欄位未填寫，不能送出
  - [ ] 表單送出中，應該明確表達正在處理中的訊號
  - [ ] 表單送出中，應該要凍結表單（除非有提供取消功能）
  - [ ] 任何表單至少要有 CTA 及 Cancel 兩類按紐 (CTA: Call-To-Action)
- 訊息
  - [ ] 成功訊息，應該要明確指出完成對象
  - [ ] 錯誤訊息，應該要明確指出錯誤對象
  - [ ] 確認訊息
    - [ ] 刪除確認，應該要明確指出欲刪除對象
- 按鈕
  - [ ] 任何一個刪除按鈕，都要有刪除確認提示
- 鼠標
  - [ ] 移動到所有可以點擊的元素，要出現 pointer cursor
      - Button, Link icon, Link text, ...
</details>

<details>
<summary><b>2. 功能測試: <a href="https://github.com/oharastream/ohara/wiki/Test-case:-Normal-case">Normal case</a></b></summary>

- [ ] Create a new workspace with three nodes
- [ ] Create two topic and upload a stream app jar into the workspace
- [ ] Create a new pipeline and add some components into pipeline
- [ ] 連接 FTP Source -> Topic 1 -> Stream App -> Topic 2 -> HDFS Sink
- [ ] Prepare required folders and test data on the FTP server
- [ ] Start all connectors and stream app
- [ ] Verify which test data was successfully dumped to HDFS
</details>

## 測試所發現的問題紀錄

### 設計稿：
- (設計稿 Issue Number 紀錄在此)

### 測試環境：
- Ohara
  - Mode: (ssh or k8s)
  - Version: xxx
  - Build date: xxx
- 測試工具
  - 瀏覽器：xxx
  - 最小螢幕寬度：xxx

### 基本測試：
- (基本測試所發現的問題，紀錄在此)

### 功能測試：
- (功能測試所發現的問題，紀錄在此)

**Comment by jackyoh** [comment]
## 測試項目

<details>
<summary><b>1. 基本測試</b></summary>

- [x] 確認畫面（UI）與設計稿（Design）是否一致
  - 顏色、字型、符號、圖片、...
- [x] 檢查所有畫面的 Title 名稱是否正確
- [x] 所有連結是否有前往正確頁面
- [x] 切換視窗大小時，有無跑版情形
- [x] 切換視窗大小後，文字與圖形是否竄行
- 表單
  - [x] 任何一個必填欄位未填寫，不能送出
  - [x] 表單送出中，應該明確表達正在處理中的訊號
  - [x] 表單送出中，應該要凍結表單（除非有提供取消功能）
  - [x] 任何表單至少要有 CTA 及 Cancel 兩類按紐 (CTA: Call-To-Action)
- 訊息
  - [x] 成功訊息，應該要明確指出完成對象
  - [x] 錯誤訊息，應該要明確指出錯誤對象
  - [x] 確認訊息
    - [x] 刪除確認，應該要明確指出欲刪除對象
- 按鈕
  - [x] 任何一個刪除按鈕，都要有刪除確認提示
- 鼠標
  - [x] 移動到所有可以點擊的元素，要出現 pointer cursor
      - Button, Link icon, Link text, ...
</details>

<details>
<summary><b>2. 功能測試: <a href="https://github.com/oharastream/ohara/wiki/Test-case:-Normal-case">Normal case</a></b></summary>

- [x] Create a new workspace with three nodes
- [x] Create two topic and upload a stream app jar into the workspace
- [x] Create a new pipeline and add some components into pipeline
- [x] 連接 FTP Source -> Topic 1 -> Stream App -> Topic 2 -> HDFS Sink
- [x] Prepare required folders and test data on the FTP server
- [x] Start all connectors and stream app
- [x] Verify which test data was successfully dumped to HDFS
</details>

## 測試所發現的問題紀錄

### 設計稿：
- #642 As a developer, I need a proposal to understanding the overall design to enable metrics

### 測試環境：
- Ohara
  - Mode: k8s
  - Version: 0.7.0-SNAPSHOT
  - Build date: 2019-08-19 08:22:22
- 測試工具
  - 瀏覽器：Chrome 76.0.3809.100
  - 最小螢幕寬度：1920

### 基本測試：

### 功能測試：
