### ISSUE TITLE
Ohara 整合測試增加 JDBC Source Connector - Postgresql

### ISSUE THREAD

**Issue by jackyoh** [oharastream/ohara#2261]
使用 postgresql database 在 IT 的環境上啟動 docker container, 然後整合測試程式使用 QA 的環境變數連到整合測試的 postgresql 的 Database

- [ ] test "testNameOfTestClasses" should skip to check the class name of abstract class. (@chia7712) (#2459)

**Comment by chia7712** [comment]
Is there official postgresql image?

**Comment by jackyoh** [comment]
之前有做一個內部用的 postgresql dockerfile 如下連結：
https://bitbucket.org/is-land/ohara-env/src/master/postgresql/

**Comment by jackyoh** [comment]
image 有在 islandsystems/postgresql:9.2.24 裡

**Comment by jackyoh** [comment]
關於 PostgreSQL database 的整合測試,  是在 IT 的節點上執行 backend.yml 的 docker compose 裡面放執行 postgresql container 的設定, 並且會動態設定 postgresql database 的 port 給環境變數。

測試程式就會取得 QA  設定的環境 port, 當測試跑完之後會把 postgresql 的 container 刪除掉。

**Comment by chia7712** [comment]
reopen since the PR breaks our tests
