### ISSUE TITLE
Refactor the path type of com.island.ohara.kafka.connector.storage.Storage

### ISSUE THREAD

**Issue by eechih** [oharastream/ohara#2267]
Clear path types can avoid confusion, so I prefer to use java.nio.file.Path instead of String type.

- Refactor the type of input parameter "path" to java.nio.file.Path in all methods
- Refactor the type of result list to java.nio.file.Path in the **list()** method

e.g.
- boolean exists(String path) -->  boolean exists(Path path)
- Iterator\<String> list(String path) --> Iterator\<Path> list(Path path)

**Comment by chia7712** [comment]
@eechih 麻煩要考慮一個階段停一下先把完成的設計相關文件完成 否則後面會變成一次要寫很多文件會搞得自己很痛苦

**Comment by eechih** [comment]
> 先把完成的設計相關文件完成

Okok

**Comment by eechih** [comment]
redesigned by #2572, so close this issue.
