### ISSUE TITLE
Stream app cannot be started due to a topic is not running

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#2268]
I'm running into an issue which blocks me from starting the stream app after adding a stream app into the pipeline. See the reproduce steps:

> I've skipped the cluster, pipeline creation part for the sake of briefly

Req: __POST__ v0/stream

```json
{
   "jarKey":{
      "group":"fakewkcluster0",
      "name":"ohara-streamapp.jar"
   },
   "name":"dsfsdfdf"
}
```

And then, update the prop form which adds two topics like the following:

Req: __PUT__ v0/stream/dsfsdfdf

```json
{
   "from":[
      "fromTopic"
   ],
   "to":[
      "toTopic"
   ],
   "instances":1
}
```

Finally, start stream app.

Req:  __PUT__ v0/stream/dsfsdfdf/start

with the above request, i'm getting the following error:

```json
{
   "code":"java.util.NoSuchElementException",
   "message":"topic:[fromTopic] is not running",
   "stack":"java.util.NoSuchElementException: topic:[fromTopic] is not running\n\tat com.island.ohara.configurator.route.StreamRoute$.assertParameters(StreamRoute.scala:159)\n\tat com.island.ohara.configurator.route.StreamRoute$.$anonfun$hookOfStart$7(StreamRoute.scala:289)\n\tat scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)\n\tat scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)\n\tat scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\n"
}
```

/cc @saivirtue and @chia7712

**Comment by chia7712** [comment]
It is caused by that streamapp does not support TopicKey yet. We should do a bit hard-code for this case before supporting TopicKey for streamapp.

**Comment by konekoya** [comment]
@chia7712 could we also backport this to 0.7 as well?

**Comment by chia7712** [comment]
> could we also backport this to 0.7 as well?

see #2158
