### ISSUE TITLE
Prepare mock SMB server for testing

### ISSUE THREAD

**Issue by eechih** [oharastream/ohara#2275]
Prepare mock SMB server for testing

- [x] Survey a suitable SMB docker image
  - [dperson/samba](https://hub.docker.com/r/dperson/samba)
- [x] Add to backend.yml (docker-compose file) #2356 
- [x] Survey a suitable SMB client library 
  - [jcifs-ng](https://github.com/AgNO3/jcifs-ng)
    - License: LGPL
    - Github starts: 105
    - Latest release: **jcifs-ng-2.1.3** at 2019/7/20
    - Latest commit: 2019/8/3
  - [smbj](https://github.com/hierynomus/smbj)
    - License: APL
    - Github starts: 224
    - Latest release: **v0.9.1** at 2018/12/11
    - Latest commit: 2019/5/28
- [x] Use the 3-party lib **smbj** to implement SmbClient #2357

**Comment by eechih** [comment]
@chia7712 @jackyoh There are no suitable embedded SMB server in JAVA, so we have to test SAMBA connector in the IT environment.

**Comment by chia7712** [comment]
> There are no suitable embedded SMB server in JAVA, so we have to test SAMBA connector in the IT environment.

too bad :(

Could you find fitting docker images and then add it to our backend.yml (docker-compose file)?

**Comment by eechih** [comment]
> Could you find fitting docker images and then add it to our backend.yml (docker-compose file)?

No problem.

**Comment by chia7712** [comment]
@eechih Could you please write our discussion on this issue? It helps readers to understand the trade-off we have met.

**Comment by eechih** [comment]
> @eechih Could you please write our discussion on this issue? It helps readers to understand the trade-off we have met.

ok

**Comment by eechih** [comment]
SMB Client 有兩個 java 版本的 library，分別是 jcifs-ng 及 smbj，我們基於以下幾點原因而決定優先採用 jcifs-ng，第一點 [jcifs.org](https://www.jcifs.org/) 推薦使用，第二點主要開發者持續維護中（可降低或避免因 Mircosoft 調整 SMB 而造成的 Bug），基於 jcifs-ng 使用 LGPL license，導致我們必須採用動態連結的方式來使用 jcifs-ng，這會讓開發變得相對困難。不管如何，我們還是決定先採用 jcifs-ng，開發過程中再持續評估開發的難度及複雜度，如果演變到一發不可收拾的話，再來討論切換到 smbj。
