### ISSUE TITLE
StreamApp should use the runtime nodeNames to create cluster

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#2286]
Since streamApp is using actual node by (nodeName, instances) in start phase, we should consider update the nodeNames in settings to fix this problem.

- [x] for 0.8 (#2289)
- [x] for 0.7 (#2290)

The better way have two options:
1. remove the instances in streamApp. This will cause a lot of changes but we got consistency cluster behavior.
2. remove nodeNames fields in ClusterInfo. Since we are able to define nodeNames in dynamic field "settings", it is OK to remove this.

**Comment by chia7712** [comment]
Pardon me. What problem you meet

**Comment by saivirtue** [comment]
1. The StreamClusterInfo has duplicated `nodeNames` defined:
```json
{
  "nodeNames": [],
  "settings": {
    "nodeNames": []
  }
}
```
Since stream allow user to use either `instances` or `nodeNames`, the actuall nodeNames is defined in runtime.
When using collie to create cluster, the order of method calling will cause nodeNames may be null:
`creator.settings().nodeNames()` => nodeNames() will overwrite the node in settings()
`creator.nodeNames().settings()` => node in settings() will overwrite the nodeNames()

2. jarUrl could not parser in k8s mode
```
Seq(StreamCollie.MAIN_ENTRY, s"""${StreamDefinitions.JAR_KEY_DEFINITION.key()}="${jarInfo.url.toString}""""))
```
server complain no protocol found...

**Comment by chia7712** [comment]
Seems both bugs are not similar. Could you put them on different issue? Otherwise, this title is too unclear.

For the first issue, Personally, “instances” is a weird argument to me since it cause conflict settings to server. For example, instances=3 is against nodeNames=[aa]. The overwrite caused by call order is interesting. Does it mean the origin setting have defined the nodeNames? Otherwise,why creator.settigns() is able to overwrite nodeNames.

The second issue is easy to fix.

**Comment by saivirtue** [comment]
> Could you put them on different issue? 

OK

> Does it mean the origin setting have defined the nodeNames? Otherwise,why creator.settigns() is able to overwrite nodeNames.

nodeNames and instainces are both open to user. We create a empty nodeNames for user if user doesn't define it.
It is because the "actual" nodeNames is define in start phase, and nodeNames in data.settings is from user, not from stream decided.

**Comment by chia7712** [comment]
> It is because the "actual" nodeNames is define in start phase, and nodeNames in data.settings is from user, not from stream decided.

that is the cryptic stuff to me. Why we don't pick up the nodeNames for user in creation/update phase if user define the instances than "nodeNames"? It seems to me "instances" is another kind of "nodeNames" so the setting of streamapp should contain one of them. For example, Using instance = 1 to send creation can get the response nodeNames=["a"]. Of course, the instances is removed from setting after the nodes is chosen.

**Comment by saivirtue** [comment]
> Why we don't pick up the nodeNames for user in creation/update phase if user define the instances than "nodeNames"? 

That is the story of #2288. Please move the discussion to there.
This issue is aim to fix the bug that streamApp could not start normally.
