### ISSUE TITLE
Typo in the user interface

### ISSUE THREAD

**Issue by vitojeng** [oharastream/ohara#2307]
There are some typo in UI:

- Workspace > **TOPICS** tab > **New Topic** window
  - `SAVE` button should be `ADD`

**Comment by vitojeng** [comment]
@konekoya , @wu87988622 
Could we fix these type in the v0.7 ?

**Comment by konekoya** [comment]
I'm with backporting this to 0.7, but the first two items were fixed a while ago. Do you still see these in your UI?

**Comment by vitojeng** [comment]
My bad. I saw these typo in demo env(v0.6).
I would take a look in qa2 env and then update the issue. :)

**Comment by vitojeng** [comment]
Updated the issue, let we bypass v0.7.0, only fix in v0.8.0
