### ISSUE TITLE
Record and store failing manager's E2E test videos

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#2311]
This can better assist frontend devs to debug and ping point the fail E2E tests on CI.

- [x] Store the failing E2E test videos on Jenkins
- [x] Enable cypress to record the videos (#2313)

**Comment by konekoya** [comment]
@chia7712 All you need to know is where we store these videos, right :)

**Comment by chia7712** [comment]
> All you need to know is where we store these videos, right :)

yep. please give me related path to the video.

**Comment by konekoya** [comment]
Will do 👌

**Comment by konekoya** [comment]
@chia7712 `ohara/ohara-manager/client/cypress/videos`

**Comment by chia7712** [comment]
@konekoya is there a pr for me to test jenkins?
