### ISSUE TITLE
Connector client does not package the group to creation request

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#2333]
It means the creation request submitted via our client code is unable to set group...

1. - [x] for 0.8 (#2335)
1. - [x] for 0.7 (#2336)

**Comment by chia7712** [comment]
@wu87988622 This is a critical bug to our APIs so I plan to backport it to 0.7

**Comment by wu87988622** [comment]
> @wu87988622 This is a critical bug to our APIs so I plan to backport it to 0.7

OK thanks.
