### ISSUE TITLE
Cluster showing "failed" at first fetch by api

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#2346]
Currently, we assume a cluster is dead if all of containers in cluster were "not running". This will cause a weird behavior in creation phase that the containers are still creating but we assume dead.

The cluster state rules
 1. RUNNING: all of the containers have been created and at least one container is in "running" state
 2. FAILED: all of the containers are terminated and at least one container has terminated failure
 3. PENDING: one of the containers are in creating phase
 4. UNKNOWN: other situations
 5. None: no containers

- [x] for 0.7 branch (#2351)
- [x] for 0.8 branch (#2349)

**Comment by chia7712** [comment]
This issue is not only for streamapp. Please fix it for all cluster services.
