### ISSUE TITLE
Stop pipeline streamApp graph always Running

### ISSUE THREAD

**Issue by wu87988622** [oharastream/ohara#2350]
In pipeline 
FTP connector -> topic -> stremaapp -> HDFS connector
1. Start pipeline
2. All Connector and streamapp status is Running
3. Stop pipeline
4. All Connector status is Stop
4. Streamapp status is Running

**Comment by konekoya** [comment]
@wu87988622 I'll need a bit more description before I can confirm it's indeed a bug. Could you add some description or provide steps to reproduce the bug?

**Comment by wu87988622** [comment]
> @wu87988622 I'll need a bit more description before I can confirm it's indeed a bug. Could you add some description or provide steps to reproduce the bug?

ok

**Comment by konekoya** [comment]
Moving to new UI
