### ISSUE TITLE
Apply the "restartPolicy" to podSpec

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#2360]
Conclusions:

1. Enable K8sClient to accept restartPolicy field
2. Apply same restart policy for both docker and k8s environment
3. Use default `restartPolucy=None`

-----

In #2346, I introduce the cluster state:
> The cluster state rules
> 1. RUNNING: all of the containers have been created and at least one container is in "running" state
> 2. FAILED: all of the containers are terminated and at least one container has terminated failure
> 3. PENDING: one of the containers are in creating phase
> 4. UNKNOWN: other situations
> 5. None: no containers

And excerpt from [kubernetes pod restart policy](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#restart-policy) :

> Pod is running and has one Container. Container exits with failure.
> - If restartPolicy is:
> - - Always: Restart Container; Pod phase stays Running.
> - - OnFailure: Restart Container; Pod phase stays Running.
> - - **Never: Pod phase becomes Failed.**

> Container 1 is not running, and Container 2 exits:
> - If restartPolicy is:
> - - Always: Restart Container; Pod phase stays Running.
> - - OnFailure: Restart Container; Pod phase stays Running.
> - - **Never: Pod phase becomes Failed.**

I think the `restartPolicy: Never` is more suitable for our cluster state, has any idea?

**Comment by chia7712** [comment]
@saivirtue Is this issue about flaky "testFailedClusterRemoveGracefully"? I fail to get the relation.

**Comment by chia7712** [comment]
"restart" is a part of failure tolerance to ohara. I don't think we have enough cycles to discuss it now. So +1 to @saivirtue

**Comment by saivirtue** [comment]
> @saivirtue Is this issue about flaky "testFailedClusterRemoveGracefully"? I fail to get the relation.

Since in k8s env, the default restartPolicy is `Always`. This will cause the test "testFailedClusterRemoveGracefully" failed because:
1. k8s try to create a fake jar streamApp, and failed to create
2. since restartPolicy is always, k8s try to create again.
3. the pod will output the following json object
```json
{
  "phase": "Running",
  "containers":[
     ...
    "state": "Exited"
}
```
4. Since the pod status is decided by `phase` for now, we should consider apply restartPolicy for `none`, the tests will never get the "exited" status...

And BTW, the default restart policy is none in docker mode, I feel sad they have different default value...

**Comment by chia7712** [comment]
@saivirtue thanks for the explanation. +1 again :)

**Comment by saivirtue** [comment]
thanks for feedback @chia7712 :)
Let me summarize the conclusion in later daily-scrum.

**Comment by chia7712** [comment]
> Let me summarize the conclusion in later daily-scrum.

please sync the "conclusion" to github also. We doon't want to bully the guys who don't join the scrum :)
