### ISSUE TITLE
New ohara node 不能按 save 按鈕

### ISSUE THREAD

**Issue by jackyoh** [oharastream/ohara#2361]
**Describe the bug**
Ohara manager 使用 K8S Mode

UI 在建立 node 時，如果沒有輸入 Port, User 和 Password 時，按下 Test Connection 會顯示，
Test has passed! 但是 SAVE 的案鈕，是 disable 的狀態不能 SAVE。

**Comment by wu87988622** [comment]
will fix in #1631
