### ISSUE TITLE
the port generated by CommonUtils.availablePort() may be smaller than 1024

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#2370]
We frequently assign the random port generated by CommonUtils.availablePort() to the cluster services for IT tests. The port is a free value in local and we expect that it is also free in remote. Unfortunately, our QA is in root mode and the root is able to get the port smaller than 1024, and cluster services is NOT in root so the port is protected.

1. - [x] for 0.7 (#2372)
1. - [x] for 0.8 (#2371)

**Comment by saivirtue** [comment]
good catch!
