### ISSUE TITLE
Add Duration value type support in manager

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#2373]
The following format should be used in the API request/response:

```json
"key": "value unit"
```

For example:
```json
"frequncy": "10 secondes" 
```

The unit part will be hardcoded in the frontend and for now, we will only add three units:
- millisecond
- secondes
- minutes

1. - [x] convert the value of duration to "number unit" for setting definition (@chia7712) (#3427)
2. - [ ] Add duration value type component in manager (@konekoya)

**Comment by chia7712** [comment]
@konekoya Should we fix it in 0.9?

**Comment by konekoya** [comment]
@wu87988622 is currently working on this

**Comment by konekoya** [comment]
Fix in #3408
