### ISSUE TITLE
Assert cluster failed even if container exited in docker mode

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#2388]
In BasicCollieImpl:
```
// exists one container in dead state, and others are in exited state means cluster failed
else if (containers.exists(_.state == ContainerState.DEAD.name) &&
           containers.forall(c => c.state == ContainerState.EXITED.name ||
            c.state == ContainerState.DEAD.name))
Some(ClusterState.FAILED)
```

In some circumstance, container may run into `exited` state (for example, a thrown exception from container inside) and we should assert the cluster is failed in this situation.

**Comment by chia7712** [comment]
It seems to me the states of a cluster consists of 
1. PENDING (one of nodes is in running)
1. RUNNING (no pending && one of nodes is in running)
1. FAILED (other cases)

There are too many failed cases so we should only recognize the whitelist :)

**Comment by saivirtue** [comment]
> There are too many failed cases so we should only recognize the whitelist :)

That is OK except PENDING and RUNNING rules.
In docker mode, a state `Created` is used to indicate that a container had been created but not start yet, I think we can rely on it and make the rules more simple:
1. PENDING (one of nodes is in created)
RUNNING (no pending && one of nodes is in running)

**Comment by chia7712** [comment]
> PENDING (one of nodes is in running)

my bad. typo: running -> created/pending

**Comment by chia7712** [comment]
> PENDING (one of nodes is in created)

+1
