### ISSUE TITLE
stabilize the ITs for collie

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#2393]
~I'd say that those IT tests are more stable in my local than our QA. I guess the root cause is our jenkins are too busy to host multiples QA at the same time (most failure are caused by timeout and connection failure)~

~It seems to me the flaky IT should be retried via gradle than we enter a bunch of code to "eliminate" the error. However, the "retry" is unsupported by gradle (see https://github.com/gradle/gradle/issues/1283).~

~At any rate, the eligible way (or the only way) is to click my keyboard to write a bunch of scripts on jenkins to parse report and then retry ...~

My previous comment is not correct since those flaky is indeed flaky. The related PRs are shown below, and we keep digging in them until the green QA come home.
1. - [x] tweak the checks of existence of cluster for IT tests (#2397)
1. - [x] fix flaky TestK8SStreamApp (see [here](https://builds.is-land.com.tw/job/PreCommit-OHARA/4923/testReport/)) (#2488)
1. - [x] disable all connector ITs (#2585)
1. - [x] move the public port and public hostname to IntegratedIT interface
1. - [x] fix flaky TestSshStreamApp.testDeadNodes (#2599)
1. - [x] updating metrics cache may be blocked by the non-connectable services and the timeout of getting metrics ensues (#2611)
1. - [x] the nodeNames is out-of-date after updating cache since the settings in previous container is out-of-date (#2617)

**Comment by chia7712** [comment]
@jackyoh I tried to fix the connector ITs but i observe there is a chaos in the hierarchy of connector IT. Hence, I will disable them before fixing. And, please, read the following suggestion and then re-arch connector ITs.

1. BasicTestConnectorCollie is a basic test BUT it has nothing about test cases. As a basic test, it should consist of test cases and "abstract" the method depending on specific impl.
1. the order of constructing objects is chaotic. Why you create both configurator and collie? Configurator has a collie, right?
1. not all objects are released. For example, configurator is not closed.
1. the port to configurator should use the port passed via env. Otherwise, the worker can't pull jar from configurator.

Feel free to leave comments for connector ITs.

**Comment by jackyoh** [comment]
謝謝 @chia7712 的建議，我會去修改以下幾點的建議。

我想確認第二點的部份，Configurator 已經有包含了 collie，所以就應該不用建立 collie，直接
使用 configurator 來建立 zk, bk 和 wk 的 cluster。

**Comment by chia7712** [comment]
> 我想確認第二點的部份，Configurator 已經有包含了 collie，所以就應該不用建立 collie，直接
使用 configurator 來建立 zk, bk 和 wk 的 cluster。

yep

**Comment by chia7712** [comment]
our IT gets stable now so I'm about closing this issue. the fix to flaky in the future will be resolved in individual issue.
