### ISSUE TITLE
Add converter interface for SettingDef

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#2400]
The SettingDef class has a lot of types, and we assume the value is in "json" format for checking. We should consider adding an infra to do the convert job for other data formats.
- refactor all docker files that are using "hard-core" variables

**for key part**
1. convert the string to be a readable string in docker env

**for value part**
1. any array -> JSON array
2. any time string -> java Duration

**Comment by chia7712** [comment]
@saivirtue Apart from the value "conversion", the key does also. The keys used to config (zk, bk, wk and streamapp) clusters normally has "dot" and the "dot" is not legal in bash env. For example, the key "broker.cluster.name" in streamapp is not accessible (yep, it is a bug but not critical).

**Comment by saivirtue** [comment]
We design a better way to pass the parameters to containers, this issue is stale now.
