### ISSUE TITLE
what is the relationship between CsvSinkTask and TextSourceTask

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#2407]
TextSourceTask plans to handle various "text" file for our source. By contrast, CsvSinkTask aims to process only csv? It is weird that it seems the connectors for both side should be consistent and should be extendable and eligible to handle various text input/output.

**Comment by chia7712** [comment]
ping @eechih

**Comment by eechih** [comment]
@chia7712 原本 TextSourceTask 設計要支援其他的文字格式，例如 JSON。很遺憾，這個想法在現階段可能需要暫停，只會支援單一格式(CSV)，我們需要先把整體的架構及功能補齊後，再來擴充支援其他格式。

已經建立一個 Issue 把 TextSourceTask 轉換成 CsvSourceTask。#2412

**Comment by chia7712** [comment]
@eechih thanks for explanation.
