### ISSUE TITLE
Change the log level from debug to trace when we meet the connectors which are not sub class of row connector

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#2425]
The connectors which are not subclass of row connector produce a bunch of debug info since our worker client notes it is not "standard". Given that there are kafka connectors, we should change the level from debug to trace to avoid noisy from our log files.

**Comment by konekoya** [comment]
@chia7712 is log lever a tech term in the backend or just a typo 🤔

**Comment by chia7712** [comment]
>  is log lever a tech term in the backend or just a typo 🤔

typo :(
