### ISSUE TITLE
[Manager] Display the connector name in the connector config form

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#2432]
Due to the group key was applied, the connector name is no longer showing in the config form. We should add the group support and display the name just like it used to be

**Comment by konekoya** [comment]
@chia7712 Looks like this was fixed in the backend?

**Comment by chia7712** [comment]
> Looks like this was fixed in the backend?

yep. Is frontend ready to show the connector key?

**Comment by konekoya** [comment]
Yep, we are ready to support connector key :)

**Comment by konekoya** [comment]
The group key support will be added in #2683. Closing this now
