### ISSUE TITLE
Introduce Quickstart VM

### ISSUE THREAD

**Issue by vitojeng** [oharastream/ohara#2440]
required by #1486

This VM used for quick start document to demonstrate how to rapidly build data pipelines using Ohara.
This VM should be generate automically and integrate with our Jenkins flow.

Todo
- [x] Generate Quickstart VM(#2592)
- [x] Preprepared service and data: ftp, database, csv files, tables(#2805)
- [x] Move related files into oharastream/ohara-quickstart
  - Init **ohara-quickstart** repo(oharastream/ohara-quickstart#1)
  - Delete related files from **ohara** repo(#2844)

Quickstart VM test environment:
* macOS Mojave(v10.14.5) + VirtualBox 6.0.12
* Ubuntu 18.04.03 LTS + VirtualBox 5.2.32
* macOS + VirtualBox 5.2.30

Test item:
- [x] Generate quickstart vm to OVA file automatically.
- [x] [Host] Import VM to VirtualBox
- [x] [VM] Login VM, auto pull docker image
- [x] [VM] Start Ohara configurator and manager
- [x] [Host] Open browser and link to Ohara Manager main page.

**Comment by vitojeng** [comment]
Document: 
https://ohara.readthedocs.io/en/latest/build_quickstart_vm.html

**Comment by vitojeng** [comment]
@eechih Thank you for help to finish this task. ^^

**Comment by eechih** [comment]
> Update docker image: oharastream/ohara:deps

想要將自動化建置 QuickStart VM 流程整合到 Jenkins 中的前提，是必須在 docker container 中運行 VirtualBox。

目前經過幾番試驗，仍無法成功。
```
$ systemctl status vboxdrv
● vboxdrv.service - VirtualBox Linux kernel module
   Loaded: loaded (/usr/lib/virtualbox/vboxdrv.sh; enabled; vendor preset: disabled)
   Active: inactive (dead)

$ VBoxManage list vms
WARNING: The vboxdrv kernel module is not loaded. Either there is no module
         available for the current kernel (3.10.0-957.1.3.el7.x86_64) or it failed to
         load. Please recompile the kernel module and install it by

           sudo /sbin/vboxconfig

         You will not be able to start VMs until this problem is fixed.
```

因此，建置 QuickStart VM ova 的工作，先交由 RM 安排在**某台**實體機上進行。

**Comment by chia7712** [comment]
> 因此，建置 QuickStart VM ova 的工作，先交由 RM 安排在某台實體機上進行。

或許我們可以切一個vm出來只負責建立quick vm?

**Comment by vitojeng** [comment]
@chia7712 目前的困擾在於 VM 裡無法去啟動另一個 VM, 這件事好像​只能在實體機裡上進行.
有更好的方式嗎?

**Comment by chia7712** [comment]
> 目前的困擾在於 VM 裡無法去啟動另一個 VM, 這件事好像​只能在實體機裡上進行.
有更好的方式嗎?

我以為只要能跑virtualbox就好了?

**Comment by vitojeng** [comment]
> > 目前的困擾在於 VM 裡無法去啟動另一個 VM, 這件事好像​只能在實體機裡上進行.
> > 有更好的方式嗎?
> 
> 我以為只要能跑virtualbox就好了?

不行. 在 VM or container 裡 virtualbox 能裝起來, 執行會有錯誤.

**Comment by chia7712** [comment]
> 在 VM or container 裡 virtualbox 能裝起來, 執行會有錯誤.

那找一台實體機? 然後掛到jenkins上並設計相關的jobs

**Comment by vitojeng** [comment]
嗯, 目前只能朝這個方向進行

**Comment by eechih** [comment]
> 那找一台實體機? 然後掛到jenkins上並設計相關的jobs

+1

**Comment by vitojeng** [comment]
剛查到 VirtualBox 6.0 開始支援 Nested Virtualization, 或許有機會解:
https://docs.oracle.com/cd/E97728_01/F12469/html/nested-virt.html

如果來不及, 我們這次 release 可以先手動 build.

**Comment by vitojeng** [comment]
Jenkins integration task move to oharastream/ohara-quickstart#5
issue close now.
