### ISSUE TITLE
Start Configurator before running e2e tests on CI

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#245]
Since we’re hitting the real APIs with our e2e tests, we need to start Configurator before running e2e tests on CI.

Required by #427

**Comment by eechih** [comment]
required by #427

**Comment by konekoya** [comment]
@eechih Ah, so `Required by` won't work?

**Comment by vitojeng** [comment]
@eechih , @konekoya the keyword only available in the first comment(description)

**Comment by konekoya** [comment]
@vitojeng Oh, okay. One more question. Does it work when capitalizing the first letter like `Required by #issue_number`

**Comment by vitojeng** [comment]
> @vitojeng Oh, okay. One more question. Does it work when capitalizing the first letter like `Required by #issue_number`

@konekoya  I'm not sure. I guess the keyword needs to be all lowercase.

**Comment by konekoya** [comment]
I think so, as GitHub's supported keywords are all in lowercase :) I'd use the lowercase from now on!

**Comment by chia7712** [comment]
#503 breaks our build. I will fix it on #515
