### ISSUE TITLE
Add group support in manager

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#2457]
#1734 added the group concept in the APIs, so now we should add the support in the frontend as well to avoid issues like #2411

- [x] Workspaces #2512 
- [x] Add group support in pipeline (#2581)

### These API should be added:
- [x] Workspaces #2512 
    - [x] stream jars
    - [x] topics
    - [x] plugin
    - [x] Filter GET List by group #2484 
- [x] Pipeline
    - [x] connectors
    - [x] topics
    - [x] stream jars

#### UPDATED:
After some more further discussion over this very topic:
- Under a workspace, the group name for each service should be:
    - stream jars: `workspaceName-streamjar`
    - topics: `workspaceName-topic`
    - plugins jars: `workspaceName-plugin`

- Pipeline should have a group name like: `workspaceName-pipelineName`
    - connectors: `workspaceName-pipelineName`
    - streamApps: `workspaceName-pipelineName`

**Comment by chia7712** [comment]
Connector and streamapp has similar issue.

BTW, what the relationship between pipeline and topic now? Does topic belong to pipeline or workspace? Is it ok for our UI to assign topic to different pipelines? Does it make sense to reassign a topic ,which was used by a deleted pipeline, to an new pipeline?

**Comment by konekoya** [comment]
> Connector and streamapp has similar issue.

These are included in the pipeline and workspace :)

> BTW, what the relationship between pipeline and topic now? Does topic belong to pipeline or workspace? Is it ok for our UI to assign topic to different pipelines?

Topics now belong to workspace. A topic can only be created under a workspace in the UI.

> Does it make sense to reassign a topic ,which was used by a deleted pipeline, to an new pipeline?

I think It's completely okay to do so (And this is how it actually behaves now in the UI). As topics belong to the workspace, not pipelines. So removing a topic from pipeline shouldn't remove it from the workspace.

**Comment by chia7712** [comment]
> I think It's completely okay to do so (And this is how it actually behaves now in the UI). As topics belong to the workspace, not pipelines. So removing a topic from pipeline shouldn't remove it from the workspace.

We are focusing on streaming and the offset controlis not exposed to user. Hence, the topic reassigned to a new pipeline is always a empty. So what the benefit of reusing the topic?

For another, does it make sense to assigned a topic to two different pipeline at the same time?

**Comment by konekoya** [comment]
Hmm, this is something I did not know. What do you mean by __the topic reassigned to a new pipeline is always a empty.__ ? When a topic is reused, it seems like the metrics are still there?

> For another, does it make sense to assigned a topic to two different pipeline at the same time?

I actually not sure about this. The current behavior was discussed and designed a long time ago. But I'm okay to change it if we need to do so in order to meet our new requirements :)

Thanks for raising these questions, should we open another issue to further discuss the topic (pun intended) since it feels like a bit off the topic for me :)

**Comment by chia7712** [comment]
> it seems like the metrics are still there?

The stuff in streaming is data than metrics. The empty stuff I mentioned is data than metrics.

> I actually not sure about it

It would be great that we all understand what we have written.

> should we open another issue

#2463
