### ISSUE TITLE
[Question] what the benefit from reusing topic 

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#2463]
Our UI puts the topics at the same level as pipelines. It implies the topics are reusable in a workspace. However, I failed to get the benefit of it. Users are unable to control offsets so reusing topics in the new pipelines have no readable data.

**Comment by vitojeng** [comment]
> Our UI put the topics at the level same to pipeline.

We can create topic at the [Workspaces > workspace > TOPIC] page. So I think we put the topics at the Workspace level, not Pipeline level.

In Ohara, all piplelines in the same workspace can be share the same topic, just like a topic can be share between different application in Kafka concept.
This could be an important that if user want to break a big pipeline into smaller parts, or different pipeline's owner want to share the same topic.

**Comment by vitojeng** [comment]
> Users are unable to control offsets so reusing topics in the new pipelines have no readable data.

Not sure your meaning, maybe we need a quickly meeting for this?

**Comment by chia7712** [comment]
We have a naming for the "reused" topic - it is called global topic. We are not prepared to create a graph consisting of multiples pipelines but the new UI still encourage user to create a topic used by different pipelines. I'm in wonder at this use case but maybe we need more time to see what global topic will be.
