### ISSUE TITLE
Fix eslint errors/warnings cannot be displayed right in the Vscode issue

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#2465]
After upgrading to eslint 6. The eslint errors and warnings are now not able to be displayed in the vscode (but is still able to be displayed in the CLI and Browser consoles). __A temp solution here is to open vscode from the `./client` dir instead of `./ohara-manager`.__ as suggested in https://github.com/microsoft/vscode-eslint/issues/696#issuecomment-508580721

It's actually a bug from the vscode plugin. See the issue thread here:
https://github.com/microsoft/vscode-eslint/issues/696

**Comment by konekoya** [comment]
Hmm, look thru the comment thread again and found out it's recommended to add a vscode config to address the issue in the readme...

https://github.com/microsoft/vscode-eslint/blob/master/README.md

We should give it a try then

**Comment by konekoya** [comment]
@wu87988622 @DavidMi-1 

There is an issue that causes prettier to fail in our project if you're using vscode

Make sure you turn this off for now as a temp workaround

```json
"prettier.eslintIntegration": false
```

More discussion here:
https://github.com/prettier/prettier-vscode/issues/870

**Comment by konekoya** [comment]
@wu87988622 @DavidMi-1 

Please add this option in your vscode's `settings.json` and see if it works okay(Open the project from `ohara/manager`)?

```json
  "eslint.workingDirectories": [
    "./client",
  ],
```

**Comment by wu87988622** [comment]
> Please report back after applying these settings. I might need to update the docs to includes these rules.

I setting eslint, everything is fine

**Comment by konekoya** [comment]
Since this issue has nothing to do with our source code, the docs will be added in #2603
