### ISSUE TITLE
[Question] UI should be able to display the logs of cluster for specific component

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#2466]
A large pipeline having many components has chance to meet various exception. UI should be able to show the logs (file or a special page) for the selected components. For example, the road from a connector to b topic seems to be frozen, and then I can right-click to dump related logs to trace the error.

**Comment by chia7712** [comment]
FYI @konekoya @vitojeng @eechih

**Comment by konekoya** [comment]
This is included in the new UI
