### ISSUE TITLE
Do not use the Enter button to add a Pipeline when no workspace is selected

### ISSUE THREAD

**Issue by eechih** [oharastream/ohara#2468]
NEW WORKSPACE -> 只填寫 pipeline name 後，就使用鍵盤 Enter 按鈕送出（沒有選擇任何一個 workspace），會發生出現錯誤訊息，如下：

{"group":"default","name":"undefined"} doesn't exist in com.island.ohara.client.configurator.v0.WorkerApi$WorkerClusterInfo

**Comment by eechih** [comment]
ping RM @wu87988622

**Comment by konekoya** [comment]
Thanks for reporting this @eechih! Can confirm it's indeed a bug. It's now up to @wu87988622 whether to backport this to 0.7 or not

**Comment by wu87988622** [comment]
I think this bug is not serious.
Thanks @eechih .
