### ISSUE TITLE
Prevent user from reusing a topic in pipeline

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#2469]
We don’t want to reuse a topic in different pipelines. However, it is hard to find the topic which is not included by any pipeline.

__UPDATED__: after the discussion. A temp solution is listed below:

1. A topic can only be used in a single pipeline. But can be reused if the topic is deleted from the pipeline (a side effect here is the data will be kept in the very same topic)
2. Display the topic  __is used__ by which pipeline in the topic list (inside the workspace)
3. Remove a topic from a pipeline is still not really __deleting__ it from the workspace. (Same as the current implementation, just point this out to avoid confusion)

Wireframe:

![Wireframe for display the topic used by pipeline](https://raw.githubusercontent.com/oharastream/images/master/issues/2469/OHARA-2469.png)

**Comment by konekoya** [comment]
As we discussed in the meeting today. The current solution to this is:

1. A topic can only be used in a single pipeline.
2. Display the topic __data count__ and __is used__ by which pipeline in the topic list (inside the workspace)

**Comment by eechih** [comment]
![Wireframe for display the topic used by pipeline](https://raw.githubusercontent.com/oharastream/images/master/issues/2469/OHARA-2469.png)

**Comment by konekoya** [comment]
@eechih Wow, that really fast. Should we also display the data count in the list as well :)

**Comment by eechih** [comment]
I think the data count and Metrics represent the same meaning (whether there is old data), we should choose one. Have any suggestions? @konekoya @chia7712 @vitojeng

**Comment by chia7712** [comment]
> I think the data count and Metrics represent the same meaning 

@eechih you are right.

as a temporary solution, I'm ok with it :)

**Comment by konekoya** [comment]
No problem. Thanks for the wireframe @eechih 👍

**Comment by vitojeng** [comment]
> as a temporary solution, I'm ok with it :)

+1

**Comment by konekoya** [comment]
@chia7712 could we use this issue as our implementation issue?

**Comment by chia7712** [comment]
> could we use this issue as our implementation issue?

Yep. Please put the conclusion to description :)

**Comment by konekoya** [comment]
> Yep. Please put the conclusion to description :)

Updated :)
