### ISSUE TITLE
Ohara user interface v1.0

### ISSUE THREAD

**Issue by vitojeng** [oharastream/ohara#2470]
So far, Ohara's user interface is still growing (e.g. Workspace, Upgrade worker plugins), and continues to include great libraries(e.g. MUI, JoinJS, React hooks) and more testing.

In order to have a better user experience, it's time to think about ​how to design a more complete and elegant user interface.

[WIP] Document: 
- [OharaStream product design v1.0](https://docs.google.com/document/d/1UwzXUuGsKKez9loAo6dcGiZU2P3FfvOV6olP4vmYTpk/edit?usp=sharing)

- [OhavaStream product mockup v1.0](https://app.zeplin.io/project/5dbf8137d688528346aa9f66)

**Comment by vitojeng** [comment]
Ohara v1.0 design already done. If there is any change to the mockup, please create a follow-up issue.
Close this issue now.

**Comment by eechih** [comment]
@vitojeng I have updated the link of Ohara v1.0 mockup
