### ISSUE TITLE
Ohara manager should handle 404 error properly

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#249]

**Comment by chia7712** [comment]
Is this covered by #2470?

**Comment by konekoya** [comment]
Nope.. @vitojeng @eechih is it possible that we can include a 404 (page not found) design in the new UI :)

**Comment by chia7712** [comment]
IIRC, I filed a comment about "the page for nonexistent resources". It would be better to address that as well.

**Comment by konekoya** [comment]
> IIRC, I filed a comment about "the page for nonexistent resources". It would be better to address that as well.

Yep. But that's the client route not managers. It will be handled in #1957 :)

**Comment by chia7712** [comment]
IIRC, @eechih has designed the page for 404. @konekoya Do you plan to address that in this issue? Or you had opened another one?

**Comment by konekoya** [comment]
> Or you had opened another one?

Yep. Closing this and in favor of #3180 :)
