### ISSUE TITLE
the configs written to cluster configuration file should be more flexible

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#2504]
All cluster container is run by a script file. The script file take specific env variables to generate configuration file to set up the process. All env variables are hard-code. For example:
```sh
if [[ -z "xxx" ]]; then
  echo "aaa.bbb=$xxx" > file
fi
```

the hard-code stop us from adding more configs to set up process without updating script files.

**Comment by saivirtue** [comment]
this is related to #2662 and should be resolved in that issue. Close this issue now.
