### ISSUE TITLE
Enable Ohara manager windows support

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#251]
Need to use cross-env to ensure that Windows machines know how to consume the environment variables that are passing in during the build time from CLI

**Comment by konekoya** [comment]
@wu87988622 would you like take a stab at this?

**Comment by chia7712** [comment]
Is this is for UI developers who fall in love with windows ?

**Comment by saivirtue** [comment]
> Is this is for UI developers who fall in love with windows ?

We should not shut developers out who love ohara running in their windows environment.
