### ISSUE TITLE
Implement the infrastructure for fetching definition from cluster

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#2520]
After the conclusion, the "fetch definition" process needs a flexible way to achieve the following tasks:
1. create a temporary container by the required official image
2. run the container with a specific helper (process)
3. fetch the definition from running container
4. delete the temporary container

The implementation is beyond this issue and I will address an infra in this issue.

There are two possible solutions, and will discuss later:

1. Let the temporary container controlled by API
   - create a temporary container for definition (The **jarUrl** field here is optional)
      `PUT /v0/definitions/zookeeper/0.8.0-SNAPSHOT`
      **Request**
       ```json
       {
         "jarUrl": "http://xxxx/abc.jar"
       }
       ```
      **Response** (http status code: 202)
      ```json
        "key": "abc123"
      ```
   - get definition
     `GET /v0/definitions/stream/abc123`
     **Response**
     ```
     {
       "className": "com.island.zookeeper",
       "definitions": [
         {
           "name": "xxx",
           ...
         }
       ]
     }
     ```
1. Predifine the support version of definitions and store in configurator
   - get all possible definitions for the specific type
     `GET /v0/definitions/zookeeper`
     **Response**
     ```
     [{
       "zid": "abc123",
       "className": "com.island.zookeeper",
       "definitions": [
         {
           "name": "xxx",
           ...
         }
       ]
     }]
     ```
   - get one definition for the specific type
     `GET /v0/definitions/zookeeper/$zid`
     **Response**
     ```
     {
       "className": "com.island.zookeeper",
       "definitions": [
         {
           "name": "xxx",
           ...
         }
       ]
     }
     ```

to be finished tasks:
- [ ] implement definition APIs infrastructure
- [ ] Apply definition api for stream
- [ ] Apply definition api for zookeeper
- [ ] Apply definition api for broker
- [ ] Apply definition api for worker
- [ ] Move definition checking to RouteUtils

thanks @chia7712 !

**Comment by saivirtue** [comment]
ping @oharastream/developer 
It may be a little complicated that getting a definition from a cluster needs two requests, but it is the better solution I can figure out for solving some async problems.
Feel free to leave your comments here :)

**Comment by chia7712** [comment]
First, please revise the title to make sure this issue is for all cluster services. We are working hard to improve all cluster services and make them consistent in “APIs” and “code”. A way working for only one cluster service is called “workaround”than solution.

> it may be a litter complicated

It seems to me that the APIs to fetch definitions for cluster should have the form: 

Url: /definitions/$service/$image_tag
Payload (optional): 
{
  “JarInfos”: []
}

And all official images should be embedded with a “angel process” to show the definitions for us. So configurator is able to file a request to a node to call our angel to give us the definitions.

The angel process not only show the definitions for cluster but also fetch the custom definitions from user application. Of course, we need to have a specific interface indicating the custom definitions for our angel process. (Fortunately, there is already a sample called WithDefinitions in connector.)

**Comment by saivirtue** [comment]
> It seems to me that the APIs to fetch definitions for cluster should have the form:

It is the difference that moves the require parameter to uil, so I'm ok with that.

> And all official images should be embedded with a “angel process” to show the definitions

I am not very sure what's the meaning of the angel process?

**Comment by chia7712** [comment]
> I am not very sure what's the meaning of the angel process?

sorry for using a weird tern :(

my point is that the official image should be embedded with a "specific" helper (process) to enable us to address something in the future. And, now, it is a good time to have this idea in our ohara - to fetch the definitions from the deployed deps :)

**Comment by saivirtue** [comment]
>  the official image should be embedded with a "specific" helper (process) to enable us to address something in the future

This should be the implementation tasks, so do you think it is OK that we use two APIs as described to fetch the definition?
Since either of which solution, the official image will be used to run a container in docker or k8s env.

**Comment by chia7712** [comment]
> Since either of which solution, the official image will be used to run a container in docker or k8s env.

Two-phases request may be in our road map. It is good but also introduces a lot of TODOs. Fetching definition via docker is not slow so a simple way (API) is suitable. However, it would be greater we adapt the two-phases request for the temporary stuff which needs time to produce.  At any rate, please re-arch your issue if you long for introducing another great infra for Ohara. By contrast, please revise you issue to take simple way for 0.8 :)

**Comment by saivirtue** [comment]
>  Fetching definition via docker is not slow so a simple way (API) is suitable.

I agree with that. It is just a small problem: the process is not slow but too quick to complete.
1. In docker env: I observe that if we run a container with "-d" and the container is too quick to complete, the later "container log" process will get nothing. (we can introduce an attach mode container to do a workaround)
2. In k8s env: Every pod has a lifecycle status "ContainerCreating", and if we try to fetch the log immediately after the pod created, it will get a weird 404 error. there is a [issue](https://github.com/kubernetes/kubernetes/issues/28746) describe this problem.

The main idea of using two-phase process is I try to solve the async problem of a single API may hit the above issue.

**Comment by chia7712** [comment]
> In docker env: I observe that if we run a container with "-d" and the container is too quick to complete, the later "container log" process will get nothing. (we can introduce an attach mode container to do a workaround)

do you means the container is "gone" than "exited" so you fail to fetch the log?

**Comment by saivirtue** [comment]
> do you mean the container is "gone" than "exited" so you fail to fetch the log?

Sorry for the misleading explanation. The container ran completed and the status was "exited", but the fetch log process needing a little "time wait" to get the docker generated log. It is more stable if we use an "attach mode" to run a container and the fetch log process will get the response.

**Comment by chia7712** [comment]
> The container ran completed and the status was "exited", but the fetch log process needing a little "time wait" to get the docker generated log. It is more stable if we use an "attach mode" to run a container and the fetch log process will get the response.

got it. thanks for the explanation. At any rate, those are implementation details and they are beyond this issue.

@saivirtue please have a conclusion for the this issue. be powerful or be simple :)

**Comment by chia7712** [comment]
#3091 offers a simple way to expose the definitions for cluster services. The multiples version support is too far so I'm going to close this large issue.
