### ISSUE TITLE
Perf connector config form not updating when switching between two Perf connectors

### ISSUE THREAD

**Issue by wu87988622** [oharastream/ohara#2526]

**Comment by konekoya** [comment]
@wu87988622 I'm unable to reproduce this behavior in 0.7... could you please provide more details on how to repro this?

**Comment by konekoya** [comment]
Sorry, It's indeed a bug. I will submit a PR to fix this :)

**Comment by konekoya** [comment]
Since 0.8 doesn't have this bug. The fix will only go into 0.7.1
