### ISSUE TITLE
Manager's E2E test should give the cluster name a prefix

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#2542]
The prefix to cluster name is installed in backend E2E. It helps jenkins to capture the orphan containers created by E2E and then file warning (or cleanup them automatically).

Backend take the prefix from the env variable "ohara.it.container.prefix", and the variable is generated by jenkins. It consists of "pr" and $PR_ID so it is a unique in our QA (unless you file two QA for IT...)

- [x] Add prefix to the services that are started from the UI (#2660)

**Comment by chia7712** [comment]
FYI @wu87988622 @konekoya

**Comment by konekoya** [comment]
@chia7712 Hmm, a prefix is certainly doable :) I will let you know when I'm ready to take a stab at this

**Comment by konekoya** [comment]
@chia7712 Could manager also use the env var that you mentioned in the above? Or you'd prefer we use a different env var name instead of "ohara.it.container.prefix"?

**Comment by chia7712** [comment]
> Could manager also use the env var that you mentioned in the above? Or you'd prefer we use a different env var name instead of "ohara.it.container.prefix"?

Using the same var is enough to QA :)

**Comment by konekoya** [comment]
@chia7712 There will be two services that we're not able to add this PR prefix. It's a limitation in the Frontend and I cannot think of a solution for now. I will keep this issue open as well as adding a new task to address the issue in the future.

**Comment by chia7712** [comment]
@konekoya not problem at all. Thanks for the efforts.

**Comment by chia7712** [comment]
>  I will keep this issue open as well as adding a new task to address the issue in the future.

As you have pushed a commit for this issue, please file a follow-up in order to close this one for 0.8.0 release.
