### ISSUE TITLE
Correct the document about the location of assembly file

### ISSUE THREAD

**Issue by NYOandQ** [oharastream/ohara#2543]
from [document](https://ohara.readthedocs.io/en/latest/how_to_build.html)

> the tar file is located at ohara-assembly/distributions

but actually directory is 

> ohara-assembly/**build**/distributions

which one is wrong?

**Comment by chia7712** [comment]
@NYOandQ nice finding. the later "ohara-assembly/build/distributions" is correct. Would you like to fix it?

**Comment by NYOandQ** [comment]
@chia7712 
sure, but I am new here, so I need some time to learn how to update the document, I'll update it as soon as possible.

**Comment by chia7712** [comment]
>sure, but I am new here, so I need some time to learn how to update the document, I'll update it as soon as possible.

feel free to file question to us. I will assign this issue to you :)

**Comment by vitojeng** [comment]
@NYOandQ 
If you want to build Ohara docs in your env, you need to setup `python 2.7+`,  `pip`, `sphinx` , `other modules`. Please reference [here](https://ohara.readthedocs.io/en/latest/contrib-docs/build_docs.html).

Thanks for the contribution.

**Comment by NYOandQ** [comment]
@vitojeng thanks, it is helpful to me.

**Comment by chia7712** [comment]
@NYOandQ thanks for contributions!
