### ISSUE TITLE
Can't mount the local data folder of Configurator

### ISSUE THREAD

**Issue by HarryChiang143** [oharastream/ohara#2565]
**Describe the bug**
I following the [user guide document ](https://ohara.readthedocs.io/en/0.7.0/user_guide.html)to lunch the ohara-configurator with mount folder on local , but got some Permission denied exception.

**To Reproduce**
1. run my command with 

_docker run --rm -v /home/ohara/data:/home/ohara/configurator  -p 5000:5000 --add-host ohara-test-node1:10.4.1.1 --add-host ohara-test-node2:10.4.1.2 --add-host ohara-test-node3:10.4.1.3 --add-host ohara-test-node4:10.4.1.4 oharastream/configurator:0.7.0 --port 5000 --hostname 10.4.1.1  --folder /home/ohara/configurator  --k8s http://10.4.1.1:8080/api/v1 >> logs/configurator.log_

2. See error
![螢幕快照 2019-09-05 上午11 34 16](https://user-images.githubusercontent.com/46185836/64310016-1f321080-cfd1-11e9-95d0-705f4b288266.png)

**Expected behavior**
when i use user:ohara to lunch this command , should started ohara-configurator success, cause every things are run on ohara's enviroment, the user:ohara already have Permission to run K8S & Docker.

**Operation System (please complete the following information):**
Backend OS & Version: CentOS 7.3
Frontend OS & Version: CentOS 7.3
Browser & Version : Google Chrome , 版本 75.0.3770.100 (正式版本) (64 位元)

@chia7712

**Comment by chia7712** [comment]
@HarryChiang143 please do the following checks.

1. /home/ohara/data is accessible to you
1. add ":Z" flag if your are using selinux (for example, /home/ohara/data:/home/ohara/configurator:Z)

BTW, please give us the docker version on you local :)

**Comment by chia7712** [comment]
@HarryChiang143 the issue you encountered is the permission blocked by UID. The root cause is that all official images contain the user called *ohara*, and its UID is 1000. Hence, you fail to mount a host folder which belongs to user having UID != 1000.

I have filed a issue (#2573) to document this root cause.
