### ISSUE TITLE
[Manager] Workspace name should allow less than 20 characters instead of 30 in the UI

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#2571]
This will cause the whole workspace creation process to fail

/cc @wu87988622

**Comment by konekoya** [comment]
Thanks @saivirtue for reporting this

**Comment by wu87988622** [comment]
i will fix in #2622

**Comment by konekoya** [comment]
@wu87988622 if this will be fixed in #2622 then you shouldn't add the fix version label in this issue since there won't be any PRs link to here :)
