### ISSUE TITLE
Use a dropdown to display timestamp instead of input in connector property forms

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#259]

**Comment by chia7712** [comment]
Is this covered by the new UI (#2470)?

**Comment by konekoya** [comment]
@wu87988622 is currently working on a UI component which is able to read/parse and then dynamically generate a form that entirely relies on the definition APIs :)

/cc @eechih @wu87988622

**Comment by konekoya** [comment]
@wu87988622 I'm not sure if this issue still relevant? Could you confirm this?

**Comment by konekoya** [comment]
Everything is now rendered by definition. So UI is no longer hardcoding this
