### ISSUE TITLE
[Manager] Don't start the topic when it's added into the workspace

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#2590]
It's better we move the start action to pipeline when the topic is actually used as when attempting to update a topic, it's required to stop the topic first than you can do the update. So starting the topic when it's added in the workspace doesn't seem to have much value and would cause problems if we want to update the topic

**Comment by chia7712** [comment]
Should we show the state of topic? Does user start only topic from pipeline?

**Comment by konekoya** [comment]
> Should we show the state of topic?


@chia7712 Yup, we should. It will be added in another issue #2480 

> Does user start only topic from pipeline?

Yep, do you think we should allow users to start topic from other places in the UI :)

**Comment by chia7712** [comment]
> Yep, do you think we should allow users to start topic from other places in the UI :)

absolutely :)

**Comment by konekoya** [comment]
Move to next milestone

**Comment by konekoya** [comment]
@chia7712 I think this issue can be closed by now? As the flow has been redesign and we need to start a topic whenever it's added into our UI

**Comment by chia7712** [comment]
sure :)
