### ISSUE TITLE
移除 k8s hostname 的 node name

### ISSUE THREAD

**Issue by jackyoh** [oharastream/ohara#2625]
因為目前 k8s 的啟動 pod 的 label內容，`spec.hostname` 過長容易超出 63 字元，因此需要將 hostname 裡面的 node name 移除掉。

**Comment by saivirtue** [comment]
This issue should affect zk, bk and wk only (stream already fixed in #2583)
Let me take over this issue.

**Comment by chia7712** [comment]
@jackyoh If you want to keep the node name, the hash in container name can be replaced by node name

**Comment by konekoya** [comment]
Thanks for the help everyone! Much appreciated!

**Comment by jackyoh** [comment]
> If you want to keep the node name, the hash in container name can be replaced by node name

我覺的 node name 要移除掉，因為很難預測使用者的 node name 的長度。

**Comment by vitojeng** [comment]
> @jackyoh If you want to keep the node name, the hash in container name can be replaced by node name

我想確認這裡講的 node name, 與 host name 是否為同一件事? 也就與UI 裡的 host name 是一樣的?

**Comment by jackyoh** [comment]
這裡說的 node name 是實體機或是 vm 的 host name。

> 也與UI 裡的 host name 是一樣的?
這裡所說的 host name 是指 UI pipeline 連結隔壁的 nodes 嗎？

**Comment by vitojeng** [comment]
在 Nodes 頁面裡:
![Screenshot from 2019-09-12 11-57-28](https://user-images.githubusercontent.com/475186/64753227-0687a480-d555-11e9-8621-5e502b636525.png)

**Comment by jackyoh** [comment]
這個部份也是只實體機或是 vm 的 host name, 我們不用 host name 的原因是因為 container info 裡面也有 host name 派會搞混。
