### ISSUE TITLE
[Question] why we have empty trait like HdfsFileSystem, FtpFileSystem and SmbFileSystem?

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#2642]
Do we plan to add native support APIs for them? If not, we should get rid of them.

**Comment by chia7712** [comment]
ping @eechih

**Comment by eechih** [comment]
> Do we plan to add native support APIs for them?

@chia7712 Not sure what you mean by **native support APIs**. Can explain it further?

**Comment by chia7712** [comment]
> Can explain it further?

I means are there APIs belonging to the subclass than interface (filesystem)?

**Comment by eechih** [comment]
@chia7712 
抱歉～我可能還沒掌握到你想表達的意思，哭哭～
等你明天進公司，我再找你討論。

**Comment by eechih** [comment]
This issue will be addressed in #2661
