### ISSUE TITLE
when run e2e test, sometimes can't add new topic at pipeline edit page

### ISSUE THREAD

**Issue by DavidMi-1** [oharastream/ohara#2652]
**Describe the bug**
Sometimes, at pipeline edit page's 'Add a new topic' popup, after select a topic, 'Add' button still disable while run e2e test.

**To Reproduce**
1. Run e2e tests
2. Go to 'Edit' pipeline
3. Click on 'Add a new topic''
3. select a topic
4. See 'Add' button still disable

**Expected behavior**
After select topic, 'Add' button should be available.

**Screenshots**
![image](https://user-images.githubusercontent.com/44669519/64942153-ef212200-d89a-11e9-8e54-ff67552eeb56.png)

**Operation System (please complete the following information):**
 - Backend OS & Version: CentOS 7.2
 - Frontend OS & Version: CentOS 7.2
 - Browser & Version : Chrome 77.0.3865.75

**Comment by konekoya** [comment]
@wu87988622 could you take a look at this issue?

**Comment by wu87988622** [comment]
> @wu87988622 could you take a look at this issue?

ok i will follow this issue

**Comment by konekoya** [comment]
I think this was fixed in one of our previous PR
