### ISSUE TITLE
Enable setting config for docker and k8s

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#2656]
We are facing more and more settings to define and run a single container, it is time to use a better way to accomplish this.
I want to introduce the function to achieve passing configuration to containers. This issue is preparing to do:
1. use a workaround command `docker volume` command for docker
    1. - [x] introduce docker volume to support add config operations (#2881)
2. introduce `/configmaps` API for k8s
    1. - [x] add config operation for k8s (#2885)
3. apply new config operations to agent
   1. - [x] adding config operation to zookeeper (#2950)
   1. - [x] adding config operation to broker (#3077)
   1. - [x] adding config operation to worker (#3089)

**Comment by chia7712** [comment]
Could you share more details to us? I failed to get the connection between configs and #2191

And for another, “docker configs” is used by swarm and it would be better to keep ssh mode simple since ssh mode is NOT for production. Precisely, ssh mode offers a way to “touch” docker technique without complicated preparation.

**Comment by saivirtue** [comment]
> Could you share more details to us? I failed to get the connection between configs and #2191

In #2191, the rest tasks are "how do we pass the settings to containers without hard-code variables in docker file?"
Two possible solutions: **env variables** or **external config command**

For the former option, it is hard to avoid adding duplicate "keys" in dockerfile since in the file we cannot figure out which variables should write to XXX config file. The only way is adding ALL envs to the config file.
For example, `zk.sh` has two files needed to be wrote, conf/zoo.cfg and $dataDir/myid
It is better that we move the "echo XXX >> abc" parts from dockerfile to collie, which leads to the latter option, using external config command.
This could also give us a flexible way to add custom configs to containers.

> “docker configs” is used by swarm

This is the hard part that we need to support "same function" but "different architecture". Since k8s has management concept, the pure docker (ssh) is not. I agree with that ssh mode is not for production, but if we want to apply these functions for our "support platfom", docker is one of this, we need to find a way to accomplish this (another solution is to use the `docker volume`, but I am not sure if this is a good idea since we expose the data  out of the box, could discuss latter about this)

**Comment by saivirtue** [comment]
As the discussion, I will edit the description and postpone this issue to the next available version to accomplish.

**Comment by saivirtue** [comment]
/cc @chia7712 @jackyoh 
after the PR #2950 merged (waiting for another PR #2970, which may produce conflict), the left tasks will need your help...
I will push the stream part task in this week.

**Comment by chia7712** [comment]
@saivirtue it is ok to merge #2950 to master first if it passes QA. I am focusing on 0.8 and it is fine with conflict caused by #2950

**Comment by saivirtue** [comment]
> @saivirtue it is ok to merge #2950 to master first if it passes QA. I am focusing on 0.8 and it is fine with conflict caused by #2950

OK, thanks.

**Comment by chia7712** [comment]
@saivirtue the concept of this design is great to me. A bit suggestion is that could you add a “type” called “-e”. The configs declares as “-e” is written to env variables rather then file.

For example, the command-line arguments is like “-e aaa=bbb”, and our scripts calls “export aaa=bbb” for that. This is useful to export the configs which is accessed by env variables.
