### ISSUE TITLE
[Manager] Save API tests video in another directory

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#2659]
We're using cypress to run both our E2E and API tests and they both record video. But when running them together. the previous ran videos will be removed as cypress will do a cleanup before recoding new tests.

Seems like we can add a new option when running the API tests
https://docs.cypress.io/guides/references/configuration.html#Folders-Files

@wu87988622 Would you like to submit a PR to address this issue?

**Comment by konekoya** [comment]
cc @saivirtue Could you also include this while writing new API tests :)

**Comment by saivirtue** [comment]
> cc @saivirtue Could you also include this while writing new API tests :)

Sure thing. Let me related this issue to #3028.

**Comment by konekoya** [comment]
@wu87988622 Please kindly provide some help while @saivirtue is tackling this issue 😉
