### ISSUE TITLE
In the QA environment, the worker cannot obtain the jar file created using ohara-it

### ISSUE THREAD

**Issue by wu87988622** [oharastream/ohara#2664]
worker download jar message:
`http://59a074eca457:26088/v0/downloadFiles/pr2631wkhi80m-plugin/ohara-it-sink.jar
Resolving 59a074eca457 (59a074eca457)... failed: Name or service not known.`

1. - [x] Resolving jar hostname to woker (#2664) (@saivirtue)
1. - [x] QA should define the hostname of tmp configurator for front-end E2E (@jackyoh)

**Comment by wu87988622** [comment]
Thanks @saivirtue help.

**Comment by chia7712** [comment]
@jackyoh please update the QA :)

**Comment by jackyoh** [comment]
OK, QA 的部份我來修改。

**Comment by saivirtue** [comment]
ping @jackyoh 
Do we finish the editing part of settings in Jenkins?

**Comment by jackyoh** [comment]
Jenkins 的設定已經修改完成了。
