### ISSUE TITLE
add Test annotation to testFailedClusterRemoveGracefully and testDeadNodes

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#2670]
their annotation was removed by #2602...

**Comment by chia7712** [comment]
@saivirtue was there a good reason to remove the annotation? Or it was just a mistaken?

**Comment by saivirtue** [comment]
> @saivirtue was there a good reason to remove the annotation? Or it was just a mistaken?

Sorry, it is a mistake :(
Thanks for point out.
