### ISSUE TITLE
add test to find out the test cases having no test annotation

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#2672]
inspired by #2670. Let us avoid the such accident in the future.

**Comment by saivirtue** [comment]
I am not sure if this is a good idea since we may add more and more ignore class if we "intentionally" to do so...
But it is a good practice that we should be responsible for the missing annotation of test cases :)

**Comment by chia7712** [comment]
> I am not sure if this is a good idea since we may add more and more ignore class if we "intentionally" to do so...

In fact, the ignored class should not exist since we all should follow ohara rule to develop to keep our code consistent and reach consensus.

At any rate, We have 100+ classes and there is only one exception. I feel it is good enough :)
