### ISSUE TITLE
Collie does not need to keep the settings

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#2677]
The settings of cluster is kept by Configurator now so collie is not responsible for returning the settings anymore. Hence, some refactor to collie can be addressed.

1. Add an new interface - ClusterStatus - to simplify the returned type for collie. The ClusterStatus consists of alive nodes, state, error and metrics. All info in ClusterStatus are fetched at runtime.
1. Collie returns ClusterStatus than ClusterInfo

This change also fix the issue about inconsistent settings after adding/removing nodes. Currently, settings is stored in container envs and we have no way to update it at runtime. Introducing the ClusterStatus enable Collie to get rid of putting/pollination  settings at runtime so the inconsistency get fixed.

1. - [x] remove collie IT since they are covered by other IT (#2752)
1. - [x] keep the alive nodes rather than dead nodes because the former is real (#2760)
1. - [x] WorkerCollie.workerClient(string) should be moved to Route's helper methods as it is unrelated to collie (#2765)
1. - [x] BrokerCollie.topicAdmin(string) should be moved to Route's helper methods as it is unrelated to collie (#2773)
1. - [x] remove collie.FakeZookeeperCollie, collie.FakeBrokerCollie and collie.FakeWorkerCollie (#2840)
1. - [x] Introduce ClusterStatus to Collie

**Comment by saivirtue** [comment]
Good refactor!
ClusterStatus should be : aliveNodes, deadNodes, state, metrics, and error

**Comment by chia7712** [comment]
> deadNodes

Ohara can’t give dead nodes since it will not be aware of “origin nodes”. Hence, the dead nodes will be placed at ClusterInfo than ClusterStatus since the former has settings (include the origin node names).

**Comment by saivirtue** [comment]
> Ohara can’t give dead nodes since it will not be aware of “origin nodes”

You mean, collie handle all the "runtime" fields except deadNodes?

**Comment by chia7712** [comment]
> collie handle all the "runtime" fields except deadNodes?

yep, the deadNodes are calculated by “nodeNames” and “aliveNodes”. Also, deadNodes is a part of ClusterInfo :)
