### ISSUE TITLE
Speed up frontend license check and apply gradle tasks

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#268]
I believe this has something to do with the node_modules

TODO: add more detail

**Comment by konekoya** [comment]
This seems like once manager has dependencies installed, The `licenseApply` task will become slower even that `node_modules` dirs are already excluded from the task. I'm closing this issue since even though running `licenseApply` is a lot slower. It's just a matter of 30 seconds (on my Mac).

/cc @chia7712

**Comment by chia7712** [comment]
ok
