### ISSUE TITLE
Increase the name and group field length limit for more flexibility

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#2682]
We use (group, name) as our object key in Ohara, and the most strict rule is cluster object:
1. name & group : [0-9], [a-z], [-]
2. name & group length <= 20

This is because we have to assemble a container name in clusters with the following format:
`{occl|k8soccl}_{$group}_{$name}_{zk|bk|wk|stream}_{HASH_VALUE}`

And k8s has a "resource name maximum length of 253 characters" restriction.

To simplify the rules and let the group be more flexibility to accept the "hierarchy-group" usage,
this issue will aim to the following tasks:

1. - [x] the sum of name and group length should less or equal than 100 in clusters (#2701)
    - name & group : [0-9], [a-z]
1. - [x] apply name and group rules to objects of UI used (#2722)
    - connector
    - pipeline
    - topic
    - node (only restrict length < 63)
1. - [x] fix the illegal object name in IT tests (@chia7712) (#2804)

Also see [Ohara Stream Key Restrictions](https://docs.google.com/document/d/1UwzXUuGsKKez9loAo6dcGiZU2P3FfvOV6olP4vmYTpk/edit?usp=sharing)

**Comment by chia7712** [comment]
The length limit to name is 60 as well?

**Comment by saivirtue** [comment]
> The length limit to name is 60 as well?

Only group part. Name field could be part of "group name" in some cases, so I prefer remain the name length <= 20:
For example, 
workspace: group=default, name=abc
pipeline: group=abc-mypipeline, name=mypipeline

**Comment by chia7712** [comment]
So rule easing is for UI? The group is made of “group” and name from other service?

If so, I prefer to limit the sum of “group length” and “name length”. The story of inconsistent limit(for group and name) is a bit mysterious to backend. BTW, using our json refiner to implement the limit should be ok.

**Comment by saivirtue** [comment]
> So rule easing is for UI? The group is made of “group” and name from other service?

Any rule here is to unify all restrictions to one. For API, we still need to handle duplicated name problems:
For example, we have two workspaces:
{"group": "abc", "name": "wk01"}, {"group": "abc", "name": "wk02"}
and
wk01 has two pipelines: p01, p02
- p01 contains connectors: c01, c02
wk02 has one pipeline: p01
- p01 contains connector: c02

The above samples could be accomplished by API or by UI, and should be successful.
However, the group for connector here should use the format `wk_name+pipeline_name` to avoid possible duplication

Anyway, if we have a solution to solve the above question without using "other service name", the length limit could be same for name and group field.

**Comment by chia7712** [comment]
> Anyway, if we have a solution to solve the above question without using "other service name", the length limit could be same for name and group field.

the limit is ok to me. My point was the story of "different limit" is too hard to understand. The rule to limit the sum of group and name is more suitable and it works for frontend and APIs user.

**Comment by saivirtue** [comment]
> The rule to limit the sum of group and name is more suitable

Finally, I got the point.
Since our UI uses a group format : `{wk_name} + {current_name}` to define the "group" value of pipeline. It is not actually could be controlled by "sum of group and name length" since the actual formula is
**wk_name + current_name * 2**

I think for the final discussion in the later meeting, we should have the following two rules:
1. name length <= 20
2. sum of group and name length <= 100

**Comment by chia7712** [comment]
> name length <= 20

this one is not necessary. otherwise, both rules equal the different limit to group/name :(

**Comment by saivirtue** [comment]
As the discussion of meeting, updating the description.

**Comment by chia7712** [comment]
reopen to fix IT error
