### ISSUE TITLE
ZookeeperRoute, BrokerRoute and WorkerRoute don't take all settings to run the cluster

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#2687]
```scala
          zkClusterInfo =>
            clusterCollie.zookeeperCollie.creator
              .clusterName(zkClusterInfo.name)
              .group(zkClusterInfo.group)
              .clientPort(zkClusterInfo.clientPort)
              .electionPort(zkClusterInfo.electionPort)
              .peerPort(zkClusterInfo.peerPort)
              .imageName(zkClusterInfo.imageName)
              .nodeNames(zkClusterInfo.nodeNames)
              .threadPool(executionContext)
              .create())
```

We neglect to assign the settings ...

1. fist commit (#2690)
1. revert (#2698) (due to incorrect commit message)
1. final commit (#2699)

**Comment by saivirtue** [comment]
Hmm...cluster does not run with custom settings for now (except stream). Do we encounter any bug?

**Comment by chia7712** [comment]
> Hmm...cluster does not run with custom settings for now (except stream). Do we encounter any bug?

the free ports are not assigned :(

We don't need to add method to Collie.Creator for each config. the optional stuff should be defined by settings(Map[String, JsValue], and free ports is a good example.

**Comment by saivirtue** [comment]
Maybe it is time to remove the "friendly" method in collie and leverage the api ``request.settings`?
It could help us to avoid missing something setting AND avoid duplicate setter.

**Comment by chia7712** [comment]
> Maybe it is time to remove the "friendly" method in collie and leverage the api ``request.settings`?
It could help us to avoid missing something setting AND avoid duplicate setter.

#2688

**Comment by chia7712** [comment]
reopen to fix the incorrect commit message
