### ISSUE TITLE
[Manager] Assign broker cluster name to stream application

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#2695]
When creating a stream app, if the broker cluster name is omitted. Stream app will try it's best to find a default stream app if there's one. But this behavior would cause trouble if there are many brokers. So it's best that we assign a specific broker cluster to the stream app when creating a new one.

/cc @saivirtue @wu87988622 

This causes the E2E to fail in #2438

**Comment by saivirtue** [comment]
Good issue, I will follow-up the stale logics of stream in #2151
