### ISSUE TITLE
[Manager] Add a test case to make sure that a topic can only be used in a pipeline

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#2714]
A topic can only be used with a pipeline. This logic was implemented in #2469. We will need to add a test case to guard against this behavior ensuring it's working as it should.

The test could roughly do the following steps:
1. Create a topic and pipeline
2. Use the topic in the pipeline we just created
3. In workspace's topics tab, assert the topic has the pipeline name listed in the __used by pipeline column__
4. Assert this topic cannot be selected in another pipeline (So you will need to add another pipeline). Note even though the topic cannot be selected again, but it should be __displayed__ in that pipeline with a disabled state

**Comment by konekoya** [comment]
@DavidMi-1 Do you want to tackle this after #2738 is done?

**Comment by DavidMi-1** [comment]
I think it's ok.
But.
what this's for ? 
I mean the detail description

**Comment by konekoya** [comment]
> I mean the detail description

Good question. I will update the description

**Comment by chia7712** [comment]
So our UI does disable user to pick up a topic used by other pipeline?

**Comment by konekoya** [comment]
> So our UI does disable user to pick up a topic used by other pipeline?

Yep. a topic can only be used by one pipeline

**Comment by konekoya** [comment]
Since the UI has been completely written. The behavior is a bit different now. I've added a few new tasks in #4049 which will guard against the topic are working as it should in the new UI
