### ISSUE TITLE
enable jenkins to cleanup orphan containers

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#2726]
The orphan containers can burn out our QA server ...

**Comment by jackyoh** [comment]
我們目前有 NodeCleaner 可以去清除殘留的 container，要實作其它的功能去清除 container 嗎？

**Comment by chia7712** [comment]
QA可以在最後走訪所有IT節點清除containers

**Comment by jackyoh** [comment]
OK, 了解。目前我們的 IT 跑完成 zk, bk 和 wk 的 container 都是由測試程式去刪除。還是有可能因為某些的原因造成漏刪掉 Container 的問題，所以在跑完測試之後 Jenkins 要呼叫 ssh 去刪除 IT 環境的 container。

我想到一個問題就是目前 IT 測試程式裡面，有一個 cleanup 的變數當設定 false 時 container 是
不會刪除，主要目的是用來執行 container 的 Debug 使用。是否也要修改成透過環境變數的方式
去控制此變數。這樣才不會有 cleanup 設定成 false 時，最後跑完之後 container 被 jenkins 
刪除的問題。

**Comment by chia7712** [comment]
其實不必要，因為一般人無法存取QA上的containers。而我們的IT結尾都會把所有containers的log印出來。

那個cleanup比較是用在自己電腦debug用

**Comment by jackyoh** [comment]
OK，那這個 issue 交給我來做。

**Comment by chia7712** [comment]
@jackyoh thanks!

**Comment by jackyoh** [comment]
@chia7712 我已經完成了，執行完整合測試刪除 container 的部份。Please review shell script in PreCommit job setting.

**Comment by chia7712** [comment]
@jackyoh I'm good with the script. thanks for that!

**Comment by jackyoh** [comment]
我已經在 shell script 的最下面加上 exit 0 了。避免在執行刪除 container 發生無法預期的錯誤，造成  QA failed.

測試沒問題之後，我再將此 issue 關閉掉
