### ISSUE TITLE
Connectors are not displayed immediately after a workspace is created

### ISSUE THREAD

**Issue by eechih** [oharastream/ohara#273]
The problem here is that even though a workspace is created. The connectors are not guaranteed to be present in the workspace's overview page.  

One possible solution here would be to retry on the overview page, so the box (connector overview information) would wait/retry until the data is ready or just display a loading indicator letting the users know the data is not ready yet.

**Comment by konekoya** [comment]
@eechih I'm taking over this issue since it belongs to frontend :)

**Comment by konekoya** [comment]
This could also lead to pipeline E2E test failure since connectors are required when using the pipeline
