### ISSUE TITLE
Cluster APIs should honor cluster key rather than cluster name

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#2731]
cluster accept group now but our APIs still require user to pass name rather than key...

ObjectKey's json parser is about to accept following json representation.
```json
"key": {
  "group":"g",
  "name":"n"
}
```
```json
"key": {
  "name":"n"
}
```
```json
"key": "n"
```
Hence, the "default group" to all objects should be identical to make a global json parser for key type.

The sub issues are listed below.

1. - [x] unify default group for all objects (#2754)
1. - [x] enable json parser of "key" to accept following type: {"group": "g", "name": "n"}, {"name":"n"} and "n" (#2764)
1. - [x] Broker APIs should honor cluster key (#2808)
1. - [x] remove zookeeperClusterName from Broker APIs (#2845)
1. - [x] Worker APIs should honor cluster key (#2817)
1. - [x] remove brokerClusterName from Worker APIs
1. - [x] Stream APIs should honor cluster key (#2800)
      ~- [ ] Stream does not handle the stale filed in definition (#2831)~
1. - [x] remove brokerClusterName from Stream APIs (#2834)
1. - [x] Collie should honor cluster key (#2839)

related to #2769

**Comment by saivirtue** [comment]
cluster accept creation without group specified. If we use key instead of group and name, how could we create an object with default group?

**Comment by chia7712** [comment]
> If we use key instead of group and name, how could we create an object with default group?

The Scala APIs accept the key and the json APIs take both key and name.

The former is for consistent in writing pure scala code. Converting key to name is a weird and ugly style across our project. 

The later take “key” but accept the key lacking of “group”. For example: the following requests are identical.

bkKey: {
group:default,
name:”a”
}

bkkey: a

**Comment by saivirtue** [comment]
> The Scala APIs accept the key and the json APIs take both key and name.

Since scala APIs are part of "client", this conclusion is very important for later developers/users.
Could you add this conclusion to the `key()` comment? :)

**Comment by chia7712** [comment]
> Could you add this conclusion to the key() comment? :)

sure, boss

**Comment by saivirtue** [comment]
/cc @oharastream/frontend 

The latest changes of cluster APIs are traced here, I will remove all the stale fields in this release (0.8).
If you had any problem, please let me know :)

**Comment by chia7712** [comment]
> The latest changes of cluster APIs are traced here, I will remove all the stale fields in this release (0.8).
If you had any problem, please let me know :)

![tumblr_m5hb570SOP1rq4q6jo1_500](https://user-images.githubusercontent.com/6234750/65845005-05cf7a80-e36b-11e9-8066-e70935be4613.gif)

**Comment by konekoya** [comment]
@saivirtue Embrace for the impact...

**Comment by saivirtue** [comment]
@oharastream/frontend 
All done! You can test the APIs of cluster :)
