### ISSUE TITLE
[Manager] Avoid using illegal characters in the UI

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#2735]
The name shouldn't include special char like dash (i.e. *-*)

Ref #2722

**Comment by konekoya** [comment]
@wu87988622 Do you have time to work on this? It seems now the group name cannot contain characters like dash. You can remove the part from nodes and workspaces pages I will then fire another PR or just add a commit in the same PR like what we have done in #2684 :)

**Comment by konekoya** [comment]
Or we can just resolve this in #2722 instead?

**Comment by saivirtue** [comment]
Thanks for your help, @konekoya @wu87988622 !

**Comment by wu87988622** [comment]
> @wu87988622 Do you have time to work on this? It seems now the group name cannot contain characters like dash. You can remove the part from nodes and workspaces pages I will then fire another PR or just add a commit in the same PR like what we have done in #2684 :)

ok but i need first finish #2719 .

**Comment by konekoya** [comment]
In favor of #2682, closing this
