### ISSUE TITLE
[Manager] Update unit tests packages

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#2746]
This includes:
@testing-library/react
@testing-library/cypress

**Comment by konekoya** [comment]
@wu87988622 would you like to give this a shot?

**Comment by wu87988622** [comment]
> @wu87988622 would you like to give this a shot?

ok I will finish this issue

**Comment by wu87988622** [comment]
This issue move to 0.9.

**Comment by wu87988622** [comment]
Next, manager will be re-established so the issue will not exist.
