### ISSUE TITLE
[Manager] E2E test creates a worker with a name includes undefined in it

### ISSUE THREAD

**Issue by DavidMi-1** [oharastream/ohara#2758]
**Describe the bug**
e2e test , when run before() add a worker, it created a worker named with undefined

**To Reproduce**
1. run  'e2e' test
2. run 'pipelineEditPage.test.js'

**Expected behavior**
A normal worker name without undefined

**Screenshots**
![image](https://user-images.githubusercontent.com/44669519/65477807-01faae80-deba-11e9-93e0-714de900a390.png)

**Operation System (please complete the following information):**
 - Backend OS & Version: CentOS 7.2
 - Frontend OS & Version: CentOS 7.2
 - Browser & Version : Chrome 77.0.3865.90

**Comment by chia7712** [comment]
"undefined" seems a cursed word to ohara :(

**Comment by konekoya** [comment]
> "undefined" seems to be a cursed word to ohara :(

It's like a woooops in the frontend...

**Comment by konekoya** [comment]
@DavidMi-1 Thanks for reporting. Could you help fix this issue?

**Comment by DavidMi-1** [comment]
> @DavidMi-1 Thanks for reporting. Could you help fix this issue? @wu87988622 could probably guide you thru the process :)

ok

**Comment by DavidMi-1** [comment]
Confirmed that worker name includ 'undefined' bc of prefix's value is 'undefined'.
Just add "servicePrefix" parameter setup in the config file 'cypress.env.json', and it's solved.
Case close.
