### ISSUE TITLE
Add default value to the keys 'task.total', 'task.hash' of CsvSourceConfig

### ISSUE THREAD

**Issue by eechih** [oharastream/ohara#2766]
as title.
- task.total 's default value is 1
- task.hash 's default value is 0

**Comment by chia7712** [comment]
Personally, it is a bit dangerous to have default value for them since both of them must be defined correctly to avoid race condition.

**Comment by eechih** [comment]
> Personally, it is a bit dangerous to have default value for them since both of them must be defined correctly to avoid race condition.

+1, I will revert this PR #2767
