### ISSUE TITLE
Apply cluster key to Topic, Connector, Query, Container, Log and Validation APIs

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#2769]
the cluster name is deprecated now. And those APIs use the key first and then apply default group + cluster name to seek the running cluster.

a example of validating hdfs
before:
```json
{
  "uri": "hdfs://xxx",
  "workerClusterName": "wk00"
}
```
after_0:
```json
{
  "uri": "hdfs://xxx",
  "workerClusterKey": "wk00"
}
```
after_1:
```json
{
  "uri": "hdfs://xxx",
  "workerClusterKey": {
    "group": "g",
    "name": "wk00"
  }
}
```

1. - [x] Validation APIs should honor the key rather than name (#2790)
1. - [x] remove clusterName from Validation APIs (#2794)
1. - [x] Connector APIs should honor the key rather than name (#2774)
1. - [x] remove workerClusterName from Connector APIs (#2797)
1. - [x] Query APIs should honor the key rather than name (#2784)
1. - [x] remove workerClusterName from Query  APIs (#2798)
1. - [x] Topic APIs should honor the key rather than name (#2788)
1. - [x] remove brokerClusterName from Topic APIs (#2803)
1. - [x] Container APIs should honor the key rather than name (#2789)
1. - [x] Log APIs should honor the key rather than name (#2796)
1. - [x] Node APIs should honor the key rather than name (#2830)

related to #2731

**Comment by chia7712** [comment]
@wu87988622 @konekoya This issue is going to break the APIs and please help me to migrate the APIs :)

**Comment by chia7712** [comment]
@wu87988622 @konekoya Does UI take fields from Connector/Topic settings now? I plan to remove the stale fields in this issue :)

**Comment by chia7712** [comment]
@konekoya @wu87988622 I have added the new field to all APIs and then I'm about to remove the stale stuff. Please help me to deal with the incompatible changes :)

**Comment by konekoya** [comment]
> @wu87988622 @konekoya Does UI take fields from Connector/Topic settings now? I plan to remove the stale fields in this issue :)

Not yet. But we will do our best to update our API calls, hopefully, finish this today :)

**Comment by chia7712** [comment]
> Not yet. But we will do our best to update our API calls, hopefully, finish this today :)

I didn't encounter any compatibility error when removing the stale fields. Please check the coverage of APIs compatibility test :)

**Comment by konekoya** [comment]
> I didn't encounter any compatibility error when removing the stale fields. Please check the coverage of APIs compatibility test :)

@chia7712 That's the same pitfall we ran into last time with stream app in API tests. Since our test only tests a set of services. So everything works okay as the default cluster is taken. But in production code, this will have a problem if we have multiple services running. What do you think if we remove this __default__ behavior from our API? This will make our API behave in the same way no matter how many services exist :)

**Comment by chia7712** [comment]
>What do you think if we remove this default behavior from our API?

So the cluster field is required?

**Comment by konekoya** [comment]
> So the cluster field is required?

Exactly

**Comment by chia7712** [comment]
> Exactly

see 2812

**Comment by wu87988622** [comment]
This will be done at 0.9.
