### ISSUE TITLE
Don't pick up a cluster automatically and the cluster field should be required 

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#2812]
see https://github.com/oharastream/ohara/issues/2769#issuecomment-535345924

1. - [x] remove the auto-completed cluster field from Validation APIs (#2928)
1. - [x] remove the auto-completed cluster field from Topic APIs (#2963)
1. - [x] remove the auto-completed cluster field from Connector APIs (#3027)
1. - [x] remove the auto-completed cluster field from Broker APIs (#3032)
1. - [x] remove the auto-completed cluster field from Stream APIs (#3054)
1. - [x] remove the auto-completed cluster field from Worker APIs (#3064)
1. - [x] remove the auto-completed cluster field from Query APIs (#3029)
1. - [x] add a object checker to make sure all required objects exist (#3046)

**Comment by chia7712** [comment]
Just discussed with @wu87988622, seems front-end has not migrated to new APIs (?)

I kick this issue out 0.8.

**Comment by wu87988622** [comment]
> Just discussed with @wu87988622, seems front-end has not migrated to new APIs (?)
> 
> I kick this issue out 0.8.

OK thanks we will in 0.9 finish this issue
