### ISSUE TITLE
At pipeline edit page, open 'Add a new topic' popup and  there is no topic to add

### ISSUE THREAD

**Issue by DavidMi-1** [oharastream/ohara#2816]
**Describe the bug**
At pipeline edit page, open 'Add a new topic' popup and  there is no topic to add.

**To Reproduce**
1. Go to 'Workspace --> Topics' page, add new topic
2. Make sure there is at least one topic or more.
3. Go to 'Pipelines' page
4. Click 'NEW PIPELINE' , and add a new pipeline
5. Click 'Edit xxx Pipeline' , go to pipeline edit page
6. Click 'Add a topic' icon, open 'Add a new topic' popup
7. There is no topic for selector ,and display 'You don't have any topics available in this workspace yet. But you can create one in here'

**Expected behavior**
At pipeline edit page, when you open 'Add a new topic' popup, there should be has topic for select.

**Screenshots**
![image](https://user-images.githubusercontent.com/44669519/65736509-c2c49b80-e10d-11e9-9e7c-4dbdabdd6a92.png)

**Operation System (please complete the following information):**
 - Backend OS & Version: CentOS 7.2
 - Frontend OS & Version: CentOS 7.2
 - Browser & Version : Chrome 77.0.3865.90

**Additional context**
There is no any error message show. Chrome tool, configurator......

**Comment by DavidMi-1** [comment]
I want post with Screenshots. But I couldn't. GIthub suddenly not allow me post image.

**Comment by konekoya** [comment]
Fixed in #2820
