### ISSUE TITLE
fix flaky tests in TestK8SSimpleCollie

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#2821]
In this test class, some results fetched immediately after creating clusters, we should "wait and fetch" the result.

**Comment by chia7712** [comment]
duplicated to #2818?

**Comment by saivirtue** [comment]
> duplicated to #2818?

Not really.

In this test class, some result fetched immediately after creating clusters, we should "wait and fetch" the result.

**Comment by chia7712** [comment]
@saivirtue thanks for explanation. please update the description for this issue.
