### ISSUE TITLE
[Question] How to save our IT?

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#2824]
QA does not include IT by default so as to speedup our PR flow. However, it delay us to detect the bugs happening in IT and the chaos ensues.

There are two solutions to us now.

1. QA always run QA for backend changes. the side effect is that we don't have enough resources to hold a bunch of IT. A lot of timeout exception may ensue.

1. add an new Post job to jenkins to run the IT periodically. It can't point to the issue producing bugs but it is a hint to us to start to dig in IT.

@oharastream/developer any suggestions?

**Comment by saivirtue** [comment]
I prefer the former with **A queue for IT tests**

It is a good habit to ensure the changes don't break our IT. If the timeout exception was too hard to avoid, maybe we could pending the tests when QA is busy ?

**Comment by chia7712** [comment]
> A queue for IT tests

seems to be available to our jenkins :)

**Comment by chia7712** [comment]
the IT get stable now since we have 
1. reduced the number of parallel
1. fix a lot of flaky ITs
1. separate the IT to different group to make it be retryable
