### ISSUE TITLE
Remove JAR_KEY, CONNECTOR_KEY and TOPIC_KEYS from definitions since they should be replaced by Reference

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#2833]
there are two attributes to guide user to "fill" the fields. the "type" indicates the "form" of request, and the "reference" indicates the relationship between this field and another existent resources.

for example, we attributes "type:ObjectKey" and "reference:BROKER_CLUSTER" to a field, and then we assume the request to this field should be 
```json
  "field": {
    "group": "g",
    "name": "cc"  
  }
```

and there is a existent broker cluster having group:g and name:cc

Since all key-related type have ifentical form, we don't need JAR_KEY, CONNECTOR_KEY and TOPIC_KEYS at all.

We should remove them to simplify our definitions :)

1. - [x] remove CONNECTOR_KEY (#2835)
1. - [x] remove JAR_KEY and add Reference.JAR (#2838)
this PR will break the compatibility :(
1. - [x] replace TOPIC_KEYS by OBJECT_KEYS and reference: TOPIC (#2853)
this PR will break the compatibility :(
1. - [ ] [Manager] Remove JAR_KEY, CONNECTOR_KEY

**Comment by wu87988622** [comment]
This will be done at 0.9.
