### ISSUE TITLE
PR 只修改文件時 containers cleanup 是黃點

### ISSUE THREAD

**Issue by jackyoh** [oharastream/ohara#2846]
開 PR 如果只有改文件時  containers cleanup 是黃點，因此不能 merge 進 master 裡.

連結如下：
https://github.com/oharastream/ohara/pull/2832

ping @chia7712 我想嘗試來修改看看這個問題，有哪些地方需要注意的嗎？

**Comment by chia7712** [comment]
> 我想嘗試來修改看看這個問題，有哪些地方需要注意的嗎？

溫柔一點（x）

把清理container的script放在final block以確保一定會貼上status

**Comment by jackyoh** [comment]
OK, 我再來修改看看

**Comment by chia7712** [comment]
@jackyoh 狀況如何?

**Comment by jackyoh** [comment]
目前已經改了， 還在測試。程式碼需要要重新 rebase 在測試嗎？

**Comment by chia7712** [comment]
不用 #2832沒問題的話就可以關閉了

**Comment by jackyoh** [comment]
ok, 等這個 issue 完成後, 我就會關閉 #2832
