### ISSUE TITLE
Rename "Cluster"XXX to "Service"XXX

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#2859]
The "ClusterCollie" hosts not only multi-nodes services but also "single-node" services. The word "cluster" is not a fitting prefix. This issue will substitute "service" for "cluster". The following classes are impacted.
1. ClusterCollie
1. ClusterCache
1. ClusterState

**Comment by saivirtue** [comment]
> The "ClusterCollie" hosts not only multi-nodes services but also "single-node" services.

A "cluster" still could represent "a cluster with single node", I think?

But **Service** is still a good prefix because of cluster implies "zk, bk and wk" in our Ohara, we actually have "stream" and "shanbondi".

**Comment by chia7712** [comment]
> A "cluster" still could represent "a cluster with single node", I think?

“Cluster” is weird to the service which cannot be cluster-able. It obstructs us from introducing the collie for the single-node service since the interface will be totally different to the cluster-able collie.

**Comment by saivirtue** [comment]
> “Cluster” is weird to the service which cannot be cluster-able. 

+1
