### ISSUE TITLE
Enable the latest tag for all images

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#2867]
The latest tag is the default tag to docker images. It is useful to not only guys who want to pull the "latest" images but also our document which guides people to operate our ohara.

There are some articles saying the latest tag is anti-pattern since many people DON'T keep it latest. Fortunately, our CD works well so it is easy to keep the latest image :)

This issue includes following changes.

1. update CD to push both tags (xxx-SNAPSHOT and latest if it is in master branch)

**Comment by saivirtue** [comment]
Good issue!
Finally, we can get rid of the redundant tag if we just want the "latest" images...

**Comment by vitojeng** [comment]
Finally...

**Comment by chia7712** [comment]
the CD pushes both xxx-SNAPSHOT and latest tag for master branch now :)
