### ISSUE TITLE
[Manager] Connector should display the node it contains instead of the node in workspace

### ISSUE THREAD

**Issue by wu87988622** [oharastream/ohara#2901]
- [x] 0.8 #2911 
- [x] 0.9 #2909

**Comment by chia7712** [comment]
@wu87988622  see https://ohara.readthedocs.io/en/latest/rest/rest-connectors.html for  the "tasksStatus"

**Comment by wu87988622** [comment]
> @wu87988622 see https://ohara.readthedocs.io/en/latest/rest/rest-connectors.html for the "tasksStatus"

OK thanks
