### ISSUE TITLE
[JDBC] Meaningful exception message when password incorrect

### ISSUE THREAD

**Issue by jackyoh** [oharastream/ohara#291]
在 JDBCSourceConnector 頁面中 jdbc url 或 user 或 password 時, 都會產生相同的的訊息:

Test failed, please check you configs and try again later!
建議將 jdbc url 以及 user/password 以二種不同的錯誤訊息的訊息做區隔, 讓使用者更明白.

另外, backend 內部的 log 也沒有顯示 sql exception, 可能錯誤訊息被吃掉了 ?

**Comment by chia7712** [comment]
any update?

**Comment by jackyoh** [comment]
因為這個議題有點久了， backend 的服務已經被移除了，UI 也被改過很多次了，所以這個議題沒有要更新了。

我先把此議題關閉掉
