### ISSUE TITLE
[Question] Document of install K8S env should using superuser : ohara ?

### ISSUE THREAD

**Issue by HarryChiang143** [oharastream/ohara#2926]
在這次v0.8的測試時參考[ohara官方提供的安裝文件](https://github.com/oharastream/ohara/blob/master/docs/testcase/ohara-installation.md)
採用root身份進行安裝，但是在啟動Configurator的時候掛載本地目錄資料夾時回饋的信息是要求我必須掛載的是Linux UID = 1000的ohara身份。
![螢幕快照 2019-10-07 上午11 17 53](https://user-images.githubusercontent.com/46185836/66282974-2e6bed00-e8f4-11e9-85d5-34849c6c3f96.png)

且就我的經驗來看，在客戶端使用時通常也不太會直接採用root身份進行安裝，大多會採用具有一定權限的使用者來進行(例如擁有可執行kubectl與docker指令權限的ohara使用者)

建議安裝文件修改為具Admin權限的ohara身份進行後續安裝步驟，才不會造成使用者以為可以掛載root身份的本地目錄的誤解。

- [x] 修改 kubernetes 的文件， 說明為何使用 root 使用者安裝 Kubernetes
- [x] 寫文件說明要如何解決，啟動 configurator UUID permission denied的問題

**Comment by chia7712** [comment]
@jackyoh any suggestions?

**Comment by jackyoh** [comment]
+1
Kubernetes 安裝的 shell script 確實有必要使用 admin 的 user 安裝，因為 root 有些作業系統不建議使用，而且管理上也是使用 admin user 比較常看到。之前我有試過使用 sudo 安裝是沒問題。

這個議題就交給我修改, 主要做以下幾件事：
1. kubernetes 安裝文件的修改

2. shell script 也有可能要修改並測試

**Comment by vitojeng** [comment]
我個人的話, 剛好相反.
若是我看到文件特別建議用不同的帳號去安裝, 我可能會誤認為這個工具支援分別安裝在不同的 account.

因此我的想法是, 若是用戶有特別的考量, 我想用戶應該有足夠的能力去做這件事(用 root 以外的帳號). 因為文件使用 root 已經算足夠的 "明示" 用戶要有管理員權限. XD

若用戶沒什特別的需​求, 直接用 root 安裝即可. 也比較簡單.

**Comment by chia7712** [comment]
看起來是有兩個議題，一個是安裝的事後要否用root；一個則是啟動configurator遇到的權限問題。

針對前者，或許我們可以加上適量的註解來解釋為何"建議"使用root安裝

針對後者，我們可以加上一份文件來說明如何處理，並在該例外訊息中顯示該文件的連結

**Comment by jackyoh** [comment]
> 一個是安裝的事後要否用root
是指 K8S 的指令操作嗎？

**Comment by chia7712** [comment]
> 是指 K8S 的指令操作嗎？

不是操作，是安裝的部份。

https://github.com/oharastream/ohara/blob/master/docs/testcase/ohara-installation.md

**Comment by jackyoh** [comment]
了解，我支持用 admin user。如果 user 硬要 root 我們可以丟警告訊息，說不建議的安裝方式

**Comment by chia7712** [comment]
> 如果 user 硬要 root 我們可以丟警告訊息，說不建議的安裝方式

我覺得用root安裝是個方便快速的方式，或許補上足夠的註解說明一下為何我們用root安裝

**Comment by jackyoh** [comment]
ok, 我再把註解加到 shell script 和文件裡

**Comment by chia7712** [comment]
@jackyoh Could you also write the document about how to resolve the UID issue ?

**Comment by jackyoh** [comment]
OK, No problem. I am trying to write how to resolve the UID issue.

**Comment by chia7712** [comment]
> OK, No problem. I am trying to write how to resolve the UID issue.

thanks for contributions. BTW, please update the descriptions to include related sub tasks.

**Comment by jackyoh** [comment]
descriptions 已經更新了

**Comment by jackyoh** [comment]
ping @HarryChiang143 
在這個議題裡，已經有在 K8S 的安裝文件上寫使用 root 安裝的原因以及在啟動 configurator 的 container 說明 permission denied 的原因了。

這個議題還有其他建議嗎？

**Comment by HarryChiang143** [comment]
none, it's good for me :)

**Comment by jackyoh** [comment]
OK, 那我把這個 PR 先關閉，如果有遇到問題再 reopen。
