### ISSUE TITLE
JsonIn connector cast Integer to BigDecimal type

### ISSUE THREAD

**Issue by HarryChiang143** [oharastream/ohara#2937]
**Describe the bug**
使用REST post API寫入JsonIn connector時，如果帶的欄位是Integer，寫入Topic時會變成BigDecimal，導致後面用Java開發的StreamApp在接收資料時產生java.lang.ClassNotFoundException: scala.math.BigDecimal 的Exception

**To Reproduce**
1. 透過K8S的方式啟動Configurator及Manager
2. 透過Manager UI建立Workspace及Pipeline
3. 在Pipeline中使用JsonIn接收資料並寫入Topic，
4.接著使用Java開發的StreamApp嘗試串接該Topic資料，
5.開始透過Rest POST API寫入資料，寫入的資料格式有 String、Int
6.UI上呈現StreamApp Failed，觀察該StreamApp的pod log看到錯誤
![螢幕快照 2019-10-07 下午4 15 56](https://user-images.githubusercontent.com/46185836/66295391-c8945b00-e91d-11e9-949d-145a20d6bfbc.png)

**Expected behavior**
寫入時帶的欄位型態應該一致。

**Operation System (please complete the following information):**
- Backend OS & Version: CentOS 7.6
- Frontend OS & Version: CentOS 7.6
- Browser & Version : Google Chrome , 版本 75.0.3770.100 (正式版本) (64 位元)

**Additional context**
後來將該欄位型態改成String寫入，StreamApp就可以正常接收了。
![螢幕快照 2019-10-07 下午4 18 29](https://user-images.githubusercontent.com/46185836/66295551-2f197900-e91e-11e9-8fe9-61d8c517a38d.png)

<img width="741" alt="螢幕快照 2019-10-07 下午4 18 51" src="https://user-images.githubusercontent.com/46185836/66295559-33459680-e91e-11e9-92a5-c93e3de373e0.png">

**Comment by HarryChiang143** [comment]
@chia7712  c.c

**Comment by chia7712** [comment]
@HarryChiang143 Json的資料型別吃的就是"數字" 我們無法得知使用者是希望用"float", "double"或是哪種整數來存放。對於streaming上的任何一個節點它要事先認知"會傳來什麼型別並且根據該行別做對應的處理"

因此我覺得這個不是個issue反而比較是StreamApp需要去實做處理BigDecimal (例如JsonOut就有特別處理BigDecimal)

**Comment by HarryChiang143** [comment]
@chia7712 所以你的意思是我們原生的ostream lib就需要去支援處理BigDecimal嗎？
因為對於我的StreamApp邏輯來看，並沒有需要處理數字的需求，是在資料讀進來做篩選要Count的欄位時撞到的。
![螢幕快照 2019-10-07 下午4 51 00](https://user-images.githubusercontent.com/46185836/66297653-a9e49300-e922-11e9-936b-8c14c8a4db7c.png)
對使用者來講特別去處理他並不會實際碰到的資料格式感覺怪怪的。
這個議題是否應該拉Sam近來討論？
ping @saivirtue

**Comment by saivirtue** [comment]
> 因此我覺得這個不是個issue反而比較是StreamApp需要去實做處理BigDecimal (例如JsonOut就有特別處理BigDecimal)

這裡的問題不在於StreamApp需要實作什麼資料型態 - 對StreamApp而言，資料都是`row`的型態。
主要原因是因為StreamApp的環境是基於"java"與"必須的Kafka library"來運行，如果使用者的程式或是資料需要其他的library(如這裡的`BigDecimal`)，我想解法分兩塊：
- 使用者自行包裝他會需要用到的libraries
- 我們的stream image需要把scala libs包裝進來 (覺得這點是使用者比較無法察覺的)

**Comment by chia7712** [comment]
我的意思是"pipeline的使用者要自己意識到在資料流裡面的型別有哪些"

今天你前面串的source或任何一個元件會產生哪些"型別的資料"是pipeline使用者必須自己有先了解，並在了解的基礎上去串"合適"的元件，而非預期每個元件都可以吃任何一個元件吐出來的資料。

以這個議題來說，example裡面的count就是無法吃scala.BigDecimal，這是事實不是bug（當然我們可以發個議題來讓它支援，如上面@saivirtue提到的)，而JsonIn輸出就是scala.BigDecimal，而pipeline的使用者要知道這件事情並且實做streamapp或sink時要能吃scala.BigDecimal

**Comment by HarryChiang143** [comment]
了解，所以我是否可這樣理解為如果使用 JsonIn寫入資料到Pipeline，且資料型態有包含數字，則後面負責處理的StreamApp就必須要可以處理scala.BigDecimal型態的資料。

但如果這樣的話，是否就沒辦法單純使用Java API去開發StreamApp?? 畢竟都要去實作處理scala.BigDecimal了。

**Comment by vitojeng** [comment]
整個來說, JsonIn 是資料提供的上游, StreamApp 在下游就須要知道上游提供的格式是什麼.
然後進一步處理. 因此就這個情形, 我想是這樣沒錯.

**Comment by chia7712** [comment]
> 但如果這樣的話，是否就沒辦法單純使用Java API去開發StreamApp?? 畢竟都要去實作處理scala.BigDecimal了。

如@vitojeng所言。不過這次可以開一個特例讓我們把JsonIn的number轉成Java，因為功夫不大。不過對其他connector或streamapp而言，我們不會讓他們背上要吃各個元件資料型態的十字架

**Comment by chia7712** [comment]
@HarryChiang143 Feel free to open more topics for this issue. Or close this issue if the current solution is fine to you :)

**Comment by chia7712** [comment]
@HarryChiang143 Could we close this one?
