### ISSUE TITLE
[Manager] Should handle topic starting error

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#2942]
Ref: https://github.com/oharastream/ohara/issues/2869#issuecomment-539283984

We're not handling errors from starting a topic. An easy way to reproduce this behavior is simply to create a topic with the following config from our UI:

__Topic name__: t1
__Paritions__: 0
__Replication factor__: 0

With the above config, you can create a topic without problems. But it's in fact failed in the start topic step (we swallow the error). And eventually causes issues when using the topic in pipeline or somewhere else since it's not a running topic

- [x] 0.8 (#2947)
- [x] 0.9 (#2944)

cc @wu87988622

**Comment by chia7712** [comment]
Our APIs should reject the zero as well... I will file a issue for that.
