### ISSUE TITLE
修改整合測試 container prefix 後面的 number

### ISSUE THREAD

**Issue by jackyoh** [oharastream/ohara#2967]
目前 jenkins 在執行整合測試時，會指定 ohara.it.container.prefix 參數為 PR Number。在執行完測試無論是整合測試或是 UT 都會連到 IT Cluster 清除 container。這樣會有一個問題就是同時跑 UT 和 IT, 當 UT 跑完之後有可能會把 IT 正在執行的 container 刪除。

因此需要把 PR Number 修改成 Build number

**Comment by jackyoh** [comment]
因為下午要做 0.8 的 release，目前有很多 task 在執行。怕 jenkins 被改壞，所以等 release 完之後我再修改

**Comment by chia7712** [comment]
@jackyoh thanks for that !

**Comment by jackyoh** [comment]
jenkins 的設定已經修改完成了我先把此議題關閉
