### ISSUE TITLE
the length of container host name is too long

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#2970]
container.name format : {prefixKey}-{group}-{clusterName}-{service}-{index}
which is guarantee < 255 length

container hostname required the length <= 63, we should random a string for it (since it is used internally) instead of using container.name.

**for docker**

using random string for command: `docker -h {RANDOM_STRING}`

**for k8s**

using random string for json:
```json
"spce": {
  "hostname": "{RANDOM_STRING}"
}
```

**Comment by chia7712** [comment]
@saivirtue Let me take over this one :)

**Comment by chia7712** [comment]
I remove the 0.8 from fixed version since this is not a critical bug. Also, the changes is too big to be a hot fix :(
