### ISSUE TITLE
When start a connector with incorrect connect info on UI , it should be fail. But it keep display nothing wrong with got state "UNASSIGNED" 

### ISSUE THREAD

**Issue by DavidMi-1** [oharastream/ohara#2997]
**Describe the bug**
When start a connector with incorrect connect info on UI , it should be fail. But it keep display nothing wrong with got state "UNASSIGNED" 

**To Reproduce**
1. Create a New pipeline 'xxx' , go to 'xxx' pipeline edit page
2. Add a ftp source connector , and click on the connector's graph
3. Click on 'CORE' tab at right side, and select topic
4. Click on 'COMMON' tab , fill in some unable to connect info with correct form 
5. Click on 'Start pipeline' button
6. See no error, untill get reponse with state 'UNASSIGNED'
7. Keep get connector's state 'UNASSIGNED'
8. On k8s workspace's log saw 'Connection timed out' exception
9. On configurator console , there is no error or exception info

**Expected behavior**
When connector start fail, should response back to front end

**Screenshots**
![image](https://user-images.githubusercontent.com/44669519/66733672-deac9900-ee92-11e9-9748-e1aea4f3e1e6.png)

workspace log : 
![image](https://user-images.githubusercontent.com/44669519/66733702-f1bf6900-ee92-11e9-9a94-1fcbb556e86d.png)
![image](https://user-images.githubusercontent.com/44669519/66733708-f5eb8680-ee92-11e9-8b4e-3877a12f380c.png)

**Operation System (please complete the following information):**
 - Backend OS & Version: CentOS 7.2
 - Frontend OS & Version: CentOS 7.2
 - Browser & Version : Chrome 77.0.3865.90

**Comment by DavidMi-1** [comment]
It seems ok now.
![image](https://user-images.githubusercontent.com/44669519/66737305-31d81900-ee9e-11e9-8d14-8222dc830305.png)

Close the issue

**Comment by DavidMi-1** [comment]
建立第一個 workspace 後操作, 大機率會得到正確的結果, 
但是如果是建立使用第二個以後的 workspace, 基本上都會得到錯誤的結果, 也就是會得到 state = "UNASSIGNED";
另外使用 ssh mode 時, 第一個 workspace 操作就會得到錯誤的結果

**Comment by chia7712** [comment]
close as it is inactive.
