### ISSUE TITLE
Can't run more than one streamApp in single pipeline

### ISSUE THREAD

**Issue by HarryChiang143** [oharastream/ohara#2999]
**Describe the bug**
在單一Pipeline中無法運行兩個StreamApp(第一個可以正常運行，第二個無法啟動)

**To Reproduce**
1. 啟動K8S環境下的configurator及manager
2. 新增一個ohara node, 新創建一個workspace:wk1
3. 新增3個topic(為了串接StreamApp)
4. 新建一條Pipeline，並添加JsonIn Connector、3 Topic及兩個StreamApp
5. 分別運行各元件，當運行第二個StreamApp時啟動失敗
<img width="1440" alt="螢幕快照 2019-10-14 下午4 39 35" src="https://user-images.githubusercontent.com/46185836/66738940-34d50880-eea2-11e9-8d9e-b5fdc1ff8033.png">

**Expected behavior**
在Pipeline中應該可以同時運行多個StreamApp元件，尤其每個StreamApp元件都是由不同的jar產生的。

**Logs Screen**
![螢幕快照 2019-10-14 下午4 40 45](https://user-images.githubusercontent.com/46185836/66739041-72399600-eea2-11e9-8f5c-6c660bb32d2d.png)
![螢幕快照 2019-10-14 下午4 39 35（2）](https://user-images.githubusercontent.com/46185836/66739080-867d9300-eea2-11e9-8c01-592d8c441912.png)

**Configurator Logs File**
[configurator.log](https://github.com/oharastream/ohara/files/3723653/configurator.log)

**My StreamApp**
[streamApp.zip](https://github.com/oharastream/ohara/files/3723659/streamApp.zip)

**Operation System (please complete the following information):**
- Backend OS & Version: CentOS 7.6
- Frontend OS & Version: CentOS 7.6
- Browser & Version : Google Chrome , 版本 75.0.3770.100 (正式版本) (64 位元)

**Additional context**
None.

Ping @vitojeng @chia7712

**Comment by chia7712** [comment]
interesting...

**Comment by vitojeng** [comment]
@HarryChiang143 
Does the filename of the second streamapp jar is **columncount2.jar** ?

**Comment by HarryChiang143** [comment]
@vitojeng yes. the columncount2.jar and columncount3.jar is the same jar, i just rename to separation each other.

**Comment by saivirtue** [comment]
就我看來，這兩個StreamApp似乎都沒有正常啟動 (metrics的資料都是空的)。
如果資料還有保留的話，是否方便提供：
1. workspace:wk1的Log
2. StreamApp: app1 & app2的Log

**Comment by HarryChiang143** [comment]
@saivirtue 釐清一下，第一個StreamApp是有正常啟動的，只是我前面貼圖僅重現部署並執行StreamApp的畫面，並沒有真正的流資料進去，下面這張圖是我實際運行的畫面，可看到第一個StreamApp:app1是有正常運作的。
<img width="1248" alt="螢幕快照 2019-10-15 下午1 50 16" src="https://user-images.githubusercontent.com/46185836/66803695-03684580-ef53-11e9-9f78-c47fe0c303bf.png">

**Comment by HarryChiang143** [comment]
附上這次運行的log
[logs.zip](https://github.com/oharastream/ohara/files/3727533/logs.zip)

**Comment by chia7712** [comment]
@HarryChiang143 Could you share the image version?

**Comment by HarryChiang143** [comment]
<img width="446" alt="螢幕快照 2019-10-15 下午2 16 17" src="https://user-images.githubusercontent.com/46185836/66805001-7d4dfe00-ef56-11e9-886e-03b525516828.png">

**Comment by HarryChiang143** [comment]
Should i use the 0.8.0 release version to try again?

**Comment by chia7712** [comment]
> Should i use the 0.8.0 release version to try again?

yep

**Comment by HarryChiang143** [comment]
@chia7712 , it's seem the same trouble on 0.8.0 version
<img width="536" alt="螢幕快照 2019-10-15 下午2 49 49" src="https://user-images.githubusercontent.com/46185836/66807392-85f50300-ef5b-11e9-9b24-7abcd5409ec2.png">


<img width="448" alt="螢幕快照 2019-10-15 下午2 47 14" src="https://user-images.githubusercontent.com/46185836/66807246-6f4eac00-ef5b-11e9-94e3-ee44ca5e5b95.png">
<img width="1440" alt="螢幕快照 2019-10-15 下午2 46 52" src="https://user-images.githubusercontent.com/46185836/66807275-737ac980-ef5b-11e9-9b28-b7505940b4fb.png">

**Check out these logs for v0.8.0**
[logs.zip](https://github.com/oharastream/ohara/files/3727703/logs.zip)

**Comment by chia7712** [comment]
@HarryChiang143 我用你的jar嘗試啟動了一下(如下圖) 沒遇到錯誤，請問一下你提供的方式是每次都能觸發錯誤嗎?
![註解 2019-10-15 212812](https://user-images.githubusercontent.com/6234750/66835832-cc198900-ef92-11e9-8d6b-0f7dc060c312.png)

**Comment by HarryChiang143** [comment]
@chia7712 我先前分別用0.8.0-SNAPSHOT及0.8.0 release版本都是同樣的行為每次均觸發錯誤，

對了我的Configurator是額外mount到本地端的資料夾，不知道這點跟你的測試操作是否相同?

不過我可以再用0.8.1-SNAPSHOT嘗試看看

**Comment by HarryChiang143** [comment]
@chia7712 很遺憾的，在0.8.1-SNAPSHOT也遭遇到了同樣的錯誤。
<img width="1440" alt="螢幕快照 2019-10-16 下午2 52 14" src="https://user-images.githubusercontent.com/46185836/66895345-206d4900-f025-11e9-9c1d-0001cdc8cf30.png">

<img width="451" alt="螢幕快照 2019-10-16 下午2 52 18" src="https://user-images.githubusercontent.com/46185836/66895282-f4ea5e80-f024-11e9-848d-814c402717c0.png">

![螢幕快照 2019-10-16 下午2 52 14（2）](https://user-images.githubusercontent.com/46185836/66895390-3d098100-f025-11e9-9c34-3a7f4a2276b5.png)


**Please check the relate logs**
[logs.zip](https://github.com/oharastream/ohara/files/3732826/logs.zip)

**Comment by HarryChiang143** [comment]
@chia7712 is there any feedback?

**Comment by vitojeng** [comment]
@HarryChiang143 Can you use Ohara Demo to try out again?

**Comment by HarryChiang143** [comment]
@chia7712 It's look likes fine on Ohara Demo env..
![螢幕快照 2019-10-18 上午10 20 37](https://user-images.githubusercontent.com/46185836/67060838-06507980-f191-11e9-952e-e19525365dc6.png)


目前想到主要的行為差異應該只有Configurator是否有額外mount data to local folder.

**Comment by vitojeng** [comment]
Ohara Demo 環境確認有用 mount folder, 因此排除此因素.

**Comment by HarryChiang143** [comment]
@chia7712 

這邊回報一下，在0.8.2-SNAPSHOT的版本仍然撞到這個問題，
當透過UI啟動第二隻streamApp時，Configurator就無法提供正常服務了。
![error](https://user-images.githubusercontent.com/46185836/68455959-8a010180-0237-11ea-9032-f10c43a3f8cd.png)


測試版本：
<img width="446" alt="螢幕快照 2019-11-08 下午2 49 27" src="https://user-images.githubusercontent.com/46185836/68455802-32629600-0237-11ea-979b-329cf70490d7.png">

查看後台的APP 還活著，進去看log也是繼續在運行。
![螢幕快照 2019-11-08 下午2 49 52](https://user-images.githubusercontent.com/46185836/68455847-4a3a1a00-0237-11ea-82a3-17217f3ec84c.png)

**Comment by chia7712** [comment]
@HarryChiang143 我會在0.9測試看看

**Comment by chia7712** [comment]
@HarryChiang143 我看妳強調mount folder，是否沒有mount就不會遇到此問題?

**Comment by HarryChiang143** [comment]
沒有mount的情境還沒測過，之前是我以為Demo環境是採用預設的container內部folder，所以才提出來。

不過現在看起來Demo環境也是採用mount folder的方式

**Comment by chia7712** [comment]
close as it is inactive.
