### ISSUE TITLE
[Study] Quick adoption to be a front-end developer

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#3006]
- [x] [React](https://reactjs.org/docs/getting-started.html)
- [x] [Cypress](https://docs.cypress.io/guides/overview/why-cypress.html#In-a-nutshell)
- [x] [Nodejs](https://www.nodebeginner.org/index-zh-tw.html)
- [x] [Styled-components](https://www.styled-components.com/docs)
  - not recommend topic, see **CSS** instead.
- [x] [React Final form](https://final-form.org/docs/react-final-form/getting-started)
- [x] [Mui](https://material-ui.com/)
- [x] [Lodash](https://lodash.com/docs/4.17.15)
  - helper library, see **ES6** features instead.

**Comment by konekoya** [comment]
@saivirtue I think you can omit

1. Lodash: it's just a helper library, and I'd always recommend using ES6 features instead
2. Styled-components: there's no much you need to know about this. In fact, you should probably study CSS instead of this

Just my two cents :)

**Comment by saivirtue** [comment]
> * Lodash: it's just a helper library, and I'd always recommend using ES6 features instead
> * Styled-components: there's no much you need to know about this. In fact, you should probably study CSS instead of this

Thanks for the suggestion:)
I will update the study list by your comment.

**Comment by saivirtue** [comment]
As a good developer, learning never ended.
Close this issue now since there are no more prepare works/
