### ISSUE TITLE
Disable user to restart Configurator via different mode

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#3024]
Configurator has three modes - ssh, k8s and fake. Those modes may produce different data and those data are not compatible to each other. Hence, we should disable user to "change" the mode of Configurator.

**Comment by jackyoh** [comment]
configurator 除了啟動的時候可以指定 ssh, k8s 和 fake 模式，還有哪個時機可以修改 configurator 的  mode?

**Comment by chia7712** [comment]
> configurator 除了啟動的時候可以指定 ssh, k8s 和 fake 模式，還有哪個時機可以修改 configurator 的 mode?

重新啟動

**Comment by jackyoh** [comment]
了解， Thank you.

**Comment by chia7712** [comment]
```scala
          req.nodeNames.foreach { nodeName =>
            val images = nodesImages.find(_._1.hostname == nodeName).map(_._2).getOrElse(Seq.empty)
            if (!images.contains(req.imageName))
              throw new IllegalArgumentException(
                s"$nodeName does not have image:${req.imageName}. It has images:${images.mkString(",")}"
              )
          }
```
we have checked the images for all nodes, and this process includes the availability for nodes. Hence, I'm going to close this issue
