### ISSUE TITLE
Refactor docker client

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#303]
required by #427

This issue consists of three PRs.
1. Extract ContainerCreator from DockerClient and introduce FakeDockerClient (#440)
1. Refactor ContainerCreator so as to reuse most of code in FakeDockerClient and DockerClientImpl   (#470)
1. Complete all tests for ContainerCreator (#472)

**Comment by saivirtue** [comment]
required by #427

**Comment by saivirtue** [comment]
required by #427

**Comment by saivirtue** [comment]
required by #427

**Comment by saivirtue** [comment]
Since some UT tests use DockerClient requiring installed docker, we refactor the DockerClient to support such UT cases.

**Comment by chia7712** [comment]
@saivirtue Good patch. Let me address more refactor.

**Comment by chia7712** [comment]
All PRs are completed. close this issue now.
