### ISSUE TITLE
Performance benchmark tool for official connectors

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#3030]
We all love to read the performance reports from a system. It seems to me connectors are worthy of showing the performance since they are totally in streaming core and we have a lot of official connectors for user.

The purposed tasks are shown below.

1. benchmark tool. this tool accepts a config file to turn the data set in streaming. Also, it generates a performance reports.
1. a jenkins job used to execute the benchmark tool and then show the reports on web site
1. display the reports on github readme
1. prepare a "production" envs to jenkins (make the performance reports more credile)

All sub-tasks are shown below.

1. - [x] write the script of building a min hdfs cluster (@jackyoh )(#3417)
1. - [x] write the script of building a single oracle database (@jackyoh ) (#3460)
1. - [x] Introduce the basic benchmark flow (@chia7712) (#3422)
1. - [x] Introduce performance test for JsonOut (@chia7712) (#3438)
1. - [x] Introduce performance test for JDBCSourceConnector (@jackyoh )(#3486 )
1. - [x] Introduce performance test for HDFSSink (@jackyoh) (#3449)
1. - [x] Introduce performance test for FtpSource (@chia7712) (#3458)
1. - [x] Introduce performance test for FtpSink (@jackyoh ) (#3615 )
1. - [x] add an new filed "megabytesOfInputData" to control the size of pre-added data (@chia7712) (#3440)
1. - [x] write the script of building a single ftp server (@jackyoh )(#3544)
1. - [x] add the routes to Configurator in order to avoid UnknownHostException (#3448)
1. - [x] write the script of building a single smb server (@jackyoh )(#3583 )
1. - [x] Integration all shell script to start hdfs, oracle database, ftp and smb server (@jackyoh )
1. - [x] add prefix "ohara.it.performance" to all setting keys (#3464)
1. - [x] Introduce performance test for Samba (@jackyoh)(#3605)
1. - [x] expose the init heap and max heap (@chia7712) (#3587)
1. - [x] add new fields "valueInPerSec" to ohara metrics(#3858 )

**Comment by chia7712** [comment]
@jackyoh Could you please take over the 1) and 2) tasks?

**Comment by jackyoh** [comment]
Ok, No problem。我會再跟你討論實作細節

**Comment by chia7712** [comment]
@jackyoh 

Given that we have ftp connector and smb connector, could you also design the script/dockerfile for them. It would be better to integrate all extra storage via script, and then we can remove the backend image :)

**Comment by jackyoh** [comment]
OK, No Problem. 一樣是放在 ohara-it 的 docker 資料夾下嗎？

**Comment by chia7712** [comment]
> 一樣是放在 ohara-it 的 docker 資料夾下嗎？

yep. feel free to organize the folder :)

**Comment by jackyoh** [comment]
OK, No problem.

**Comment by chia7712** [comment]
@jackyoh Is it ok to close this one? which issue tracing the new functions?

**Comment by jackyoh** [comment]
我先把此 issue 關閉。另外我再開一個 issue 來追蹤目前修改的功能, 在 issue #4053
