### ISSUE TITLE
Something crash when start to run streamApp on pipeline 

### ISSUE THREAD

**Issue by HarryChiang143** [oharastream/ohara#3031]
**Describe the bug**
建好的Pipeline分別運行JsonIn及JsonOut Connector一天後，當第二天開始運行第一個StreamApp時系統就無法提供正常的畫面顯示。
![螢幕快照 2019-10-17 下午3 48 39](https://user-images.githubusercontent.com/46185836/66989064-36970a00-f0f6-11e9-9aa9-cc287f11e36c.png)

**原本的Pipeline示意圖**
P.S : 因為沒辦法截到當下的圖，只好拿先前同樣的Pipeline圖來代表。(本次是剛啟動App1的時候就掛了，App2還沒有啟動。)
<img width="1440" alt="1" src="https://user-images.githubusercontent.com/46185836/66989839-afe32c80-f0f7-11e9-8e2c-8d84e7e17edf.png">

**To Reproduce**
1. 啟動K8S環境下的configurator及manager，其中configurator是把資料掛載到本地目錄下
2. 新增一個ohara node, 新創建一個workspace:wk1
3. 新增3個topic(為了串接StreamApp)
4. 新建一條Pipeline，並添加JsonIn Connector、3 Topic及兩個StreamApp
5. 先啟動JsonIn Connector及JsonOut Connector元件，並持續運行超過一天
6.第二天開始運行第一個StreamApp時發生Error:Service Unavailable
7.看到[Oops ... 的畫面]
8.重新整理後就再也沒辦法看到目前的Pipeline、Node及Workspace頁面了。

**My StreamApp**

[streamapp.zip](https://github.com/oharastream/ohara/files/3738048/streamapp.zip)

**My Logs**

[logs.zip](https://github.com/oharastream/ohara/files/3738059/logs.zip)

**Screenshots**
***pods看起來運行正常***
![螢幕快照 2019-10-17 下午3 54 24](https://user-images.githubusercontent.com/46185836/66989507-1582e900-f0f7-11e9-98df-e685037a1373.png)
***configurator及manager看起來也運行正常***
![螢幕快照 2019-10-17 下午3 54 38](https://user-images.githubusercontent.com/46185836/66989574-30edf400-f0f7-11e9-850d-e2432444c093.png)

**Operation System (please complete the following information):**
- Ohara Stream Version: 0.8.0 (Release version)
- Backend OS & Version: CentOS 7.6
- Frontend OS & Version: CentOS 7.6
- Browser & Version : Google Chrome , 版本 75.0.3770.100 (正式版本) (64 位元)

**Additional context**

Ping @vitojeng @chia7712

**Comment by HarryChiang143** [comment]
sure.

**Comment by HarryChiang143** [comment]
另外重建一個新的環境，這次建完Pipeline就馬上啟動，StreamApp1 運行是正常的。

**現在已知的兩次測試行為，唯一的變因是系統待機時間。**

![螢幕快照 2019-10-17 下午5 09 42](https://user-images.githubusercontent.com/46185836/66995189-28022000-f101-11e9-83ba-b97d6366f0c1.png)

**Comment by chia7712** [comment]
@HarryChiang143 所以是說configurator放置一天後就無法使用了嗎

**Comment by HarryChiang143** [comment]
@chia7712 應該說，放一天後我重新打開UI還可以看到正常運行的Pipeline，但是當我開始啟動StreamApp的時候就掛了。

**Comment by chia7712** [comment]
> "當我開始啟動StreamApp的時候就掛了。"

了解

**Comment by HarryChiang143** [comment]
@vitojeng 我今天在Ohara Demo environment測試執行StreamApp可以正常運行，
![螢幕快照 2019-10-18 上午9 52 44](https://user-images.githubusercontent.com/46185836/67059863-46156200-f18d-11e9-892c-1105ae645433.png)

測試的行為同樣是待機一天後才啟動StreamApp。

目前想到唯一的不同點就只有Configurator是否有額外mount data to local folder。

**Comment by vitojeng** [comment]
Ohara Demo 環境確認有用 mount folder, 因此排除此因素.

**Comment by chia7712** [comment]
close as it is inactive.
