### ISSUE TITLE
[Manager] Enable windows support for build.gradle

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#3058]
There are some gradle DSL `commandLine` which used to execute **yarn** command, but it should support windows environment.
From [gradle doc of exec](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.Exec.html)
> //on windows:
> commandLine 'cmd', '/c', 'stop.bat'
> //on linux
> commandLine './stop.sh'

**Comment by chia7712** [comment]
Is it able to test Manager on windows?

**Comment by saivirtue** [comment]
Yep. After installing the required packages of [Ohara Manager Developer Guilde](https://ohara.readthedocs.io/en/latest/manager_dev_guide.html#initial-machine-setup)
Using the windows format (`commandLine 'cmd', '/c', 'yarn' ...`) could run successfully.
