### ISSUE TITLE
streamapp image should be based on deps image

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#3082]
copy-and-paste is the easiest way to maintain code :)

**Comment by chia7712** [comment]
@saivirtue IIRC, we discussed this issue before. Any suggestions for this one?

**Comment by saivirtue** [comment]
Go ahead to use the base image, it is OK now (since the image size is not a problem for current design, I think)

**Comment by chia7712** [comment]
> Go ahead to use the base image, it is OK now (since the image size is not a problem for current design, I think)

Thanks for the confirmation.
