### ISSUE TITLE
Added autostart service for the Kubernetes API proxy server

### ISSUE THREAD

**Issue by jackyoh** [oharastream/ohara#3084]
目前在整合測試環境, QA2, Demo 環境的 K8S API proxy service 在重新開機時，需要手動的去啟動 api proxy service, 需要改成在重新啟動 server 時就會自動啟動 K8S API proxy service

**Comment by jackyoh** [comment]
這邊不會動到原始碼，但是我會在 kubernetes 的資料夾下面放啟動 k8s api proxy service 的設定檔，這樣其他人也可以拿來用，所以文件也會增加說明如何使用。

**Comment by chia7712** [comment]
> 這邊不會動到原始碼，但是我會在 kubernetes 的資料夾下面放啟動 k8s api proxy service 的設定檔，這樣其他人也可以拿來用，所以文件也會增加說明如何使用。

got it :)
