### ISSUE TITLE
[Manager] Refactor tests of /v0/info API to adapt new structure

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#3093]
#3091 has added /v0/info/configurator to replace /v0/info, and this issue aims to complete the API migration.

- [x] add tests for zookeeper, broker, worker and configurator (#3110)
- [x] add tests for stream (move to #3028)

**Comment by chia7712** [comment]
@wu87988622 @konekoya @saivirtue I noticed that /v0/info is already in APIs test so #3091 did not break the APIs.

**Comment by konekoya** [comment]
@wu87988622 @konekoya @saivirtue I noticed that /v0/info is already in APIs test so #3091 did not break the APIs.

I think we can adapt the new API now as it's not used in the UI yet and the API tests are being rewritten, cc @saivirtue

**Comment by saivirtue** [comment]
> @wu87988622 @konekoya @saivirtue I noticed that /v0/info is already in APIs test so #3091 did not break the APIs.

Please notice me after the #3091 closed.

**Comment by chia7712** [comment]
> Please noticing me after the #3091 closed.

ping @saivirtue  :)

**Comment by saivirtue** [comment]
All the relative tasks are done in #3028, close this issue now.
