### ISSUE TITLE
The name of keys in json object should avoid using "dot"?

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#3105]
For example, 
/api/v0/workers:
```json
{
  "name": "wk00",
  "group": "default",
  "clientPort": 12345,
  "jmxPort": 12346,
  "freePorts": [],
  "brokerClusterKey": "preCreatedBkCluster",
  "group.id": "abcdefg",
  "config.storage.topic": "configTopic",
  "config.storage.replication.factor": 1,
  "offset.storage.topic": "offsetTopic",
  "offset.storage.replication.factor": 1,
  "offset.storage.partitions": 1,
  "status.storage.topic": "statusTopic",
  "status.storage.replication.factor": 1,
  "status.storage.partitions": 1,
  "nodeNames": [
    "node00"
  ]
}
```

the "keys-with-dotted" are hard to be parsed in front-end.

**Comment by saivirtue** [comment]
/cc @chia7712
In a quick discussion with @konekoya and @wu87988622 , we could have a workaround that converting all the "." to be another symbol (ex, "_") in each API payload.
Do you have any suggestions?

**Comment by chia7712** [comment]
> we could have a workaround that converting all the "." to be another symbol (ex, "_") in each API payload.

Do you mean the response generated Configurator should replace dot by another symbol ? It is terrible to connector developer if they can’t see what they write.

**Comment by saivirtue** [comment]
> Do you mean the response generated Configurator should replace dot by another symbol ? 

Let me explain more clearly.
We can replace each "dot" from configurator API payload, and replace back to "dot" to configurator.

**Comment by chia7712** [comment]
The APIs is a part of public stuff. We can’t change user-defined stuff arbitrarily. (Especially, the dot is common char to backend developers)
