### ISSUE TITLE
streamApp should allow empty topics in creation

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#3107]
In StreamApi:
```
 final class Creation()
...
.requireKey(StreamDefUtils.FROM_TOPIC_KEYS_DEFINITION.key())
.rejectEmptyArray(StreamDefUtils.FROM_TOPIC_KEYS_DEFINITION.key())
.requireKey(StreamDefUtils.TO_TOPIC_KEYS_DEFINITION.key())
.rejectEmptyArray(StreamDefUtils.TO_TOPIC_KEYS_DEFINITION.key())
```

In UI, drag a streamApp to pipeline may not have the information of topics.

**Comment by saivirtue** [comment]
/cc @chia7712 
IIRC, we allow API to input empty array of from/to topics?

**Comment by chia7712** [comment]
> IIRC, we allow API to input empty array of from/to topics?

Yep. It was ok to create streamapp with empty topic.

It is ok to delay the checks to START phase if UI flow is hard to avoid empty topics.

**Comment by saivirtue** [comment]
> It is ok to delay the checks to START phase if UI flow is hard to avoid empty topics.

So, should we remove the `rejectEmptyArray` part in StreamApi to allow this?

**Comment by chia7712** [comment]
> So, should we remove the rejectEmptyArray part in StreamApi to allow this?

Yep. This rule should be applied to connector also (for consistency)

**Comment by chia7712** [comment]
#3155 is binding definition with json refiner so this feature is included.
