### ISSUE TITLE
[Manager] Create node dialogs

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#3139]
1. - [x] Implement node list dialog and add node dialog (@konekoya)(#3159)
1. - [x] Ensure that the test connection behaves correctly (@konekoya) (#3175)
1. - ~[ ] Implement add node dialog for k8s mode~
1. - [x] Implement node detail page (@saivirtue )(#3551)
1. - [x] Add the ability to filter node list (@saivirtue )(#3578)
1. - [x] [Backend] provide default resources (CPU, Memory) in node api (@chia7712 ) (#3559)
1. - ~[ ] Create a custom table to display node list~
1. - [x] Implement edit and delete node dialog (@saivirtue )(#3582)

Related: #582, #3148

**Comment by konekoya** [comment]
@eechih I'm adding you as one of the assignees since you'll be helping with some of the tasks here :)

**Comment by konekoya** [comment]
@jackyoh We will need the new API, in order to get the "k8s node list", if you already have an issue opened, I can refer to it in this issue :)

**Comment by jackyoh** [comment]
> We will need the new API, in order to get the "k8s node list", if you already have an issue opened, I can refer to it in this issue :)

我這週就會開始實作這一部份，可以參考 issue #582

**Comment by chia7712** [comment]
>我這週就會開始實作這一部份，可以參考 issue #582

please describe the APIs format.

**Comment by jackyoh** [comment]
> please describe the APIs format.

OK, 我會再想看看 API 的格式。明天在跟你討論

**Comment by konekoya** [comment]
@wu87988622 Please help check off tasks that were tackled by you in another issue :)

**Comment by saivirtue** [comment]
ping @chia7712 
I have added a sub-task in description :)

**Comment by chia7712** [comment]
@saivirtue thanks for the description :)

**Comment by saivirtue** [comment]
All done :)
close this issue.

**Comment by konekoya** [comment]
Super duper :)
