### ISSUE TITLE
Remove sbt build configuration

### ISSUE THREAD

**Issue by vitojeng** [oharastream/ohara#3144]
Following testing code works well in the Sbt shell:
```scala
class TestShabondiServer extends OharaTest with Matchers {
...
}
```

But add more trait for test route, just like:
```scala
class TestShabondiServer extends OharaTest with Matchers with Suite with ScalaFutures with ScalatestRouteTest {
...
}
```

All test methods will be ignored in the Sbt shell.
All test methods works well from Gradle.

**Comment by chia7712** [comment]
我們壞念它
