### ISSUE TITLE
Add a few new fileds in the nodes API

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#3148]
Cores, CPU, Memory, and Disks. These are the new column/info for the new UI. /cc @chia7712 :)

_See the design mockup below_

1. - [x] add new field "resources" to Node APIs (@chia7712) (#3210)
1. - [x] enable ssh mode to offer resources to Node APIs (@chia7712) (#3211)
1. - [x] enable k8s mode to offer resources to Node APIs (@jackyoh) (#3266)

**Comment by konekoya** [comment]
![Node list](https://www.dropbox.com/s/3dg0oyvy6u34vli/node-list.png?raw=1)

**Comment by chia7712** [comment]
The format is shown below.

Node APIs
```json
{
  resources: [
    {
      "name": string (the name of this resource),
      "number": number (the number of this resource),
      "unit": string (the unit of this resource),
      "used": option[number]
    }
  ]
}
```

the format enables us to increase/decrease the accessible resources from backend.

@oharastream/frontend Could we show the resources dynamically (no hard-code to specific resource) ?
