### ISSUE TITLE
remove deprecated field "required" from definition

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#3166]
@oharastream/frontend 

I'm going to deprecate the field "required" and use "necessary" to replace it.

necessary offers more information about "value". It includes

1. REQUIRED -> this field has no default and user MUST define something for it.
1. OPTIONAL -> this field has no default and user does NOT need to define something for it.
1. OPTIONAL_WITH_DEFAULT -> this field has a fixed default value
1. OPTIONAL_WITH_RANDOM_DEFAULT -> this field has a "random" default value

I will remove the deprecated field "required" in another issue :)

_Originally posted by @chia7712 in https://github.com/oharastream/ohara/issues/3155#issuecomment-549010021_

**Comment by saivirtue** [comment]
Does this mean when we use `necessary: REQUIRED`, the `defaultValue: XXX" has no effect?

**Comment by chia7712** [comment]
> Does this mean when we use necessary: REQUIRED, the `defaultValue: XXX" has no effect?

Yep
