### ISSUE TITLE
Disable user to enter value in blacklist and show the recommended values to user

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#3167]
This issue will add new fields -
 1. blacklist (array string) - the illegal words to value
1. recommended (array string) - it is similar to whitelist but we still accept custom values

I think those field will need some love from UI :)

_Originally posted by @chia7712 in https://github.com/oharastream/ohara/issues/3155#issuecomment-549019193_

**Comment by chia7712** [comment]
FYI @oharastream/frontend

**Comment by wu87988622** [comment]
Manager is finish this issue with #3466
