### ISSUE TITLE
[Manager] Provide better faling test error from API test

### ISSUE THREAD

**Issue by wu87988622** [oharastream/ohara#3170]
Making it easier to troubleshoot and consume from CI  

- [x]  Extend type assertion of API tests to be more informative (#3263)
- ~[ ] using console.log() or console.warn() to print the tests progress~
It is not a good solution for now since cypress has the following issues are not resolved
-- https://github.com/cypress-io/cypress/issues/448
-- https://github.com/cypress-io/cypress/issues/300
-- https://github.com/cypress-io/cypress/issues/4245
- ~[ ] collect the console log to file~

**Comment by konekoya** [comment]
@wu87988622 I recall we have talked about this on the other day. We can print out the log (console.error or console.warn emitting from Cypress) while running the test. And after the test is done, collect the log can write to a file which can be used by Jenkins later

**Comment by saivirtue** [comment]
As the description says, we don't have a good solution to print out the console log. Close this issue now.
