### ISSUE TITLE
Remove FtpInfo, JdbcInfo and HdfsInfo APIs

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#3212]
As we are embracing the dynamical settings (definition), it is hard to match user-defined settings with those pre-stored information. Should we just get rid of them?

ping @oharastream/developer

**Comment by saivirtue** [comment]
It depends on how we use them. And since it is unused in new UI now, I'm OK with getting rid of them :)

**Comment by chia7712** [comment]
@eechih Any suggestions about using those APIs?

**Comment by eechih** [comment]
> It depends on how we use them. And since it is unused in new UI now, I'm OK with getting rid of them

+1

**Comment by chia7712** [comment]
ok. let me cleanup it
