### ISSUE TITLE
the images checker should not assume all nodes have required images

### ISSUE THREAD

**Issue by HarryChiang143** [oharastream/ohara#3224]
**Describe the bug**
在Demo環境測試運行streamapp，在啟動時前端UI呈現該台機器無streamapp image的錯誤訊息，實際確認該台機器已部署streamapp image，就算砍掉該docker image 並重新拉下來仍然無法執行。

**To Reproduce**
1. 建pipeline
2. 部署streamapp
3. 啟動streamapp

**Expected behavior**

**Screenshots**
Error msg:
![1](https://user-images.githubusercontent.com/46185836/68457804-1ca39f80-023c-11ea-992d-c907e9b7cfb6.png)

Check image:
![2](https://user-images.githubusercontent.com/46185836/68457836-36dd7d80-023c-11ea-86ff-02f452a36557.png)

**Operation System (please complete the following information):**
- OharaStream Version: v0.8.1
![螢幕快照 2019-11-08 下午3 29 19](https://user-images.githubusercontent.com/46185836/68457960-950a6080-023c-11ea-9617-907ef26d3012.png)

 - Backend OS & Version: Ohara Demo Site
 - Frontend OS & Version: Ohara Demo Site
 - Browser & Version :Google Chrome , 版本 75.0.3770.100 (正式版本) (64 位元)

**Additional context**

**Comment by HarryChiang143** [comment]
ping 0.8 RM : @konekoya QQ

**Comment by chia7712** [comment]
@HarryChiang143 這是後段檢查邏輯的問題

你要先順利運作的話，就把該image部屬到"所有節點上"

**Comment by vitojeng** [comment]
> @HarryChiang143 這是後段檢查邏輯的問題
> 你要先順利運作的話，就把該image部屬到"所有節點上"

意思是 Ohara Demo 環境裡, streamapp image 沒有佈署到所有的 node 嗎?

**Comment by chia7712** [comment]
> 意思是 Ohara Demo 環境裡, streamapp image 沒有佈署到所有的 node 嗎?

ping @HarryChiang143

**Comment by chia7712** [comment]
@jackyoh the workaround works well so this issue does not touch 0.8

**Comment by jackyoh** [comment]
> the workaround works well so this issue does not touch 0.8

OK, 收到。我會再找時間跟你討論這個問題
