### ISSUE TITLE
fix flaky stream api tests

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#3245]
```diff
export const create = async (params, body) => {
  body = body
    ? body
-    : await inspect.getStreamsInfo({
+    : await inspect.getFileInfo({
        group: params.jarKey.group,
        name: params.jarKey.name,
      });
  const requestBody = requestUtil(params, stream, body);
  const res = await axiosInstance.post(url, requestBody);
  return responseUtil(res, stream);
};
```

**Comment by chia7712** [comment]
FYI @oharastream/frontend

**Comment by chia7712** [comment]
@oharastream/frontend could you please fix it asap since this test assumes Configurator does not throw exception even if you try to inspect an nonexistent resource :(

**Comment by saivirtue** [comment]
Do you encounter any issue?
We have another task to handle the error case (#3170).
And if jar non-existed, the create will fail (since we cannot generate the body by the empty jar definition)

**Comment by chia7712** [comment]
> Do you encounter any issue?

yep. Inspecting a stream with an nonexistent key should get error. However, the test code pass jar key rather than "stream" key so Configurator fails to seek the related stream. #3244 tried to throw exception when users try to inspect an nonexistent resource but the change break the APIs tests. That is way I file this issue.

**Comment by saivirtue** [comment]
>  #3244 tried to throw exception when users try to inspect an nonexistent resource but the change break the APIs tests.

Got it. Let me fix it right away.
