### ISSUE TITLE
[Manager] Using a better way to check configurator is available

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#3253]
Since we depend on specific URL to check configurator is ready or not (`/inspect/configurator`)

It is hard (at least, for me) to find out that we have a breaking change that influences the checking logic.

I found a npm package could help us to check the (ip, port) is reachable or not:
[is-port-reachable](https://www.npmjs.com/package/is-port-reachable)
```js
const isPortReachable = require('is-port-reachable');
 
(async () => {
    console.log(await isPortReachable(80, {host: 'google.com'}));
    //=> true
})();
```

Should we apply this package to our code base?

related to #3251

**Comment by saivirtue** [comment]
/cc @wu87988622 @konekoya 
How do you think about this?

**Comment by konekoya** [comment]
Good call @saivirtue :)

**Comment by konekoya** [comment]
Same author, but I don't know the differences. May worth a try since this one has more npm downloads :) 
https://github.com/sindresorhus/get-port#readme

**Comment by saivirtue** [comment]
> Same author, but I don't know the differences. May worth a try since this one has more npm downloads :)
> https://github.com/sindresorhus/get-port#readme

This module seems for generating random port :)

**Comment by konekoya** [comment]
> This module seems for generating random port :)

Ooops, that's why the same author 😅

**Comment by konekoya** [comment]
@saivirtue could we close this issue now :)
