### ISSUE TITLE
Displaying the definitions of connectors on the Inspect APIs

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#3255]
When using the current inspect API to obtain a jar file, the returned response doesn't include its __version__, info(See the response body below). But in the new UI, we're displaying this info when creating a new workspace (in upload new jar step). I know it's probably due to that the worker hasn't started yet. But just want to know if it's possible that we can obtain this info while creating a new workspace :)

API: __GET__ `v0/inspect/${kind}/${name}?group=${group}`

```json
{
   "classes":[
      {
         "classType":"sink connector",
         "className":"com.island.ohara.it.connector.DumbSinkConnector",
         "settingDefinitions":[

         ]
      }
   ]
}
```

**Comment by chia7712** [comment]
@konekoya Is there a page using connector definitions before setting up a worker cluster?

**Comment by konekoya** [comment]
> @konekoya Is there a page using connector definitions before setting up a worker cluster?

cc @wu87988622 :)

**Comment by wu87988622** [comment]
> @konekoya Is there a page using connector definitions before setting up a worker cluster?

yes, two page 
1. create workspace quick
2. create workspace expert

we need show connect version.

**Comment by chia7712** [comment]
> we need show connector version.

got it. We need a way to show the definitions of connectors even if there is no running worker ...

**Comment by chia7712** [comment]
@wu87988622 @konekoya It is possible that we "fail" to seek the definitions from a jar. Is it ok to handle nothing?

**Comment by wu87988622** [comment]
> @wu87988622 @konekoya It is possible that we "fail" to seek the definitions from a jar. Is it ok to handle nothing?

ok, thanks you .

**Comment by konekoya** [comment]
> @wu87988622 @konekoya It is possible that we "fail" to seek the definitions from a jar. Is it ok to handle nothing?

+1 :)
