### ISSUE TITLE
limit parameter seems not working as expected in inspecting topic data

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#3258]
Using `POST /inspect/topic/{TOPIC_NAME}?group={TOPIC_GROUP}`
=> get all data (no matter how many data in topic)

Using `POST /inspect/topic/{TOPIC_NAME}?group={TOPIC_GROUP}&limit=10`
=> get all data (no matter how many data in topic)

Using `POST /inspect/topic/{TOPIC_NAME}?group={TOPIC_GROUP}&timeout=5000&limit=10`
=> get exactly 10 records

**Comment by chia7712** [comment]
Nice finding. I will fix it ASAP
