### ISSUE TITLE
Add a new duration field in the files API

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#3265]
This field can be very useful in the new UI since we need to upload temporary jar files so the detailed information can be obtained and displayed :)

/cc @chia7712 @wu87988622 @eechih

**Comment by chia7712** [comment]
我確認一下情境喔。

使用者上傳一個檔案，然後前端希望Configurator去看檔案的內容，但同時希望這個檔案「不要被存起來」

是這樣嗎

**Comment by konekoya** [comment]
對，這個情境有點複雜，因為在新 UI 的 workspace 建立過程中，我們需要讓使用者知道上傳的 Jar 裡面的內容並且也 allow 使用者去編輯其他的設定，而其中一項設定是 workspace 的名稱，而我們會拿 workspace 的稱來當作上傳 jar 時候的 group name，所以一旦使用者按我們的 UI 流程走到上傳 Jar 步驟並上傳一個 jar 後，我們其實已經把這個 Jar 使用前幾步驟中的 workspace name 當做 group name "上傳了"，如果這時候使用者回頭去改 workspace name，並再按 UI 流程走回到 Jar 的頻驟，我們就需要再用新的 workspace name 上傳一個新的 Jar 並且刪舊的 Jar。

如果我們加上的 duration 這個新參數，那我們只需要每次在建立新 Jar 的時候，隨機使用一個 group name 並帶個像是 30 秒的 druation 來拿 Jar 的內容，這樣就不用擔心還要做上面這種清除的動作，而且最後當真的一個 workspace 建立起來時，我們再拿最後使用者決定的 worksapce name 去當這個 Jar 的 group name 就可以了

cc @eechih @wu87988622 in case i misunderstand or missed anything :)

**Comment by chia7712** [comment]
> 而且最後當真的一個 workspace 建立起來時，我們再拿最後使用者決定的 worksapce name 去當這個 Jar 的 group name 就可以了

可是這個過程中上傳的檔案都有貼duration的話，代表一段時間後檔案都有可能被刪除。這樣還附和你們的情景嗎

**Comment by eechih** [comment]
> 而且最後當真的一個 workspace 建立起來時，我們再拿最後使用者決定的 worksapce name 去當這個 Jar 的 group name 就可以了

@konekoya @chia7712 我們再拿最後使用者決定的 worksapce name 去當這個 Jar 的 group name 重新上傳（不貼 duration）就可以了

**Comment by chia7712** [comment]
> 我們再拿最後使用者決定的 worksapce name 去當這個 Jar 的 group name，重
新上傳（不貼 duration）就可以了

所以是過程中需要"只"看某個檔案的內容，但不希望它被保存在Configurator上面嗎?

**Comment by konekoya** [comment]
> @konekoya @chia7712 我們再拿最後使用者決定的 worksapce name 去當這個 Jar 的 group name，重
新上傳（不貼 duration）就可以了

Yep. :)

> 所以是過程中需要"只"看某個檔案的內容，但不希望它被保存在Configurator上面嗎?

Exactly. We just want to "peek" the jar file that's about to upload and ditch it right away

**Comment by konekoya** [comment]
I'm writing down the final conclusion we just reached. 

Instead of adding a new field like duration in the files API, we will be using a query parameter to get jar info. (i.e. `/v0/files/myfile?temp=true`) And so essentially, we won't upload the jar file to the Configurator at all. 

/cc @chia7712 @wu87988622 @eechih

**Comment by chia7712** [comment]
> Instead of adding a new field like duration in the files API, we will be using a query parameter to get jar info. (i.e. /v0/files/myfile?temp=true) And so essentially, we won't upload the jar file to the Configurator at all but the file info can still be obtained and displayed in the UI.

I prefer to, now, change the Inspect APIs to "inspect a  uploaded file"

**Comment by chia7712** [comment]
this issue is replaced by #3285.
