### ISSUE TITLE
Export specific icons to SVG files

### ISSUE THREAD

**Issue by eechih** [oharastream/ohara#3278]
Icons:
- [Plugin + Plus.svg](https://raw.githubusercontent.com/oharastream/images/master/issues/3278/Plugin%20%2B%20Plus.svg)
- [Topic + Circle + Shared.svg](https://raw.githubusercontent.com/oharastream/images/master/issues/3278/Topic%20%2B%20Circle%20%2B%20Shared.svg)
- [Topic + Circle.svg](https://raw.githubusercontent.com/oharastream/images/master/issues/3278/Topic%20%2B%20Circle.svg)
- [Topic + Plus.svg](https://raw.githubusercontent.com/oharastream/images/master/issues/3278/Topic%20%2B%20Plus.svg)
- [Topic + Shared.svg](https://raw.githubusercontent.com/oharastream/images/master/issues/3278/Topic%20%2B%20Shared.svg)

**Comment by eechih** [comment]
@konekoya I have exported the icons to SVG files, please take a look, thanks :)

**Comment by konekoya** [comment]
Thanks! Will try them out today :)
