### ISSUE TITLE
Rename streamApp to stream

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#3280]
Farewell streamApp 😢 

/cc @vitojeng @wu87988622 

1. - [x] rename the docker image from oharastream/streampp to oharastream/stream (#3297)
1. - [x] rename c.i.o.s.StreamApp to c.i.o.s.Stream (#3296)
1. - [x] Rename streamApp to stream in the UI (#3303)

**Comment by konekoya** [comment]
also @oharastream/frontend if you guys are using streamApp, please rename it to stream, please 🙏

**Comment by vitojeng** [comment]
@oharastream/backend 
後端要不要在這個 issue 搭同一班車? XD

**Comment by chia7712** [comment]
> @oharastream/backend
後端要不要在這個 issue 搭同一班車? XD

Yep. I believe the “app” is also in our restful APIs. However, all changes should be in single PR so as to see green QA.

@konekoya @wu87988622 @saivirtue feel free you eliminate the word from backend. I will check the PR.

**Comment by konekoya** [comment]
No problem, let's do it in a single PR :)

**Comment by chia7712** [comment]
@konekoya let me file a PR to rename the stuff which don't break APIs :)

**Comment by chia7712** [comment]
@konekoya let me file a PR to rename the stuff which don't break APIs :)

**Comment by chia7712** [comment]
@vitojeng could you open an new image repo to store oharstream/stream image?
