### ISSUE TITLE
[Question] ohara.it.keep.containers 設定 true 不能保留所有測試的 container

### ISSUE THREAD

**Issue by jackyoh** [oharastream/ohara#3311]
整合測試程式有 ohara.it.keep.containers 參數可以設定保留 container，主要目的是拿來 debug 使用。目前在執行完一個測試方法之後會呼叫像是 zk_delete, bk_delete 和 wk_delete 方法，直接把 container 刪除， 無法保留一些測試的 container。

是否需要在 xx_delete 的方法內加入判斷，決定是否要把 container 刪除？

**Comment by chia7712** [comment]
> 是否需要在 xx_delete 的方法內加入判斷，決定是否要把 container 刪除？

We need a way to verify the "deletion" in IT, and hence it is weird to "disable" the deletion when developers do write the test code for deletion.

**Comment by jackyoh** [comment]
了解，那我先把此議題關閉了。
