### ISSUE TITLE
upgrade the base OS from CentOS 7.6 to CentOS 7.7

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#3312]
as title :)

1. - [x] update code (#3313) (reverted due to incorrect content)
1. - [x] update code (#3315)
1. - [x] update images manually

**Comment by jackyoh** [comment]
那 oharastream/ohara:ci 有需要更新嗎？

**Comment by chia7712** [comment]
> 那 oharastream/ohara:ci 有需要更新嗎？

absolutely. I will update them after merging the PR :)

**Comment by jackyoh** [comment]
> absolutely. I will update them after merging the PR :)

Thank you.
