### ISSUE TITLE
add "sinceSeconds" to Log APIs to fetch logs since relative time

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#3317]
As title.

For now, it seems we could query full logs only for all services?

For example,
`GET /logs/zookeeper/{NAME}?group=abc`

**Comment by saivirtue** [comment]
the related wireframe is here:
https://zpl.io/29zQvdY

**Comment by chia7712** [comment]
It is necessary to UI so ... YES .. Configurator should offer this function :)

**Comment by chia7712** [comment]
> Could you link the related issue to this one?

let me address it in this one :)
