### ISSUE TITLE
Added PENDING status to the toStatus function for ZookeeperCollie, BrokerCollie and WorkerCollie

### ISSUE THREAD

**Issue by jackyoh** [oharastream/ohara#3325]
目前在執行 K8S 的整合測試時，呼叫到 addNode 方法時會去 await node 的建立， 這時如果 await 時間很長時，container 會重複被建立起來。主要的原因是因為 K8S 狀態會先 PENDING 然後再 RUNNING。目前的程式發現 RUNNING 才會認定為 alive node，因此在 K8S 環境的資源繁忙時，很容易重複建立到 container 而造成在相同 node 使用一樣的 port，然後就發生 container error。

修改程式的方式，是在 toStatus 的方法再加上 PENDING 的狀態。

**Comment by chia7712** [comment]
@jackyoh nice finding!!!

**Comment by vitojeng** [comment]
Great!
