### ISSUE TITLE
remove validationReport from Node APIs

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#3334]
the field "validationReport" is a workaround to previous UI flow to trace/verify nodes. Is it still useful to our new UI?

After discussing offline, the field "validationReport" is useless so I'm going to remove it :)

**Comment by chia7712** [comment]
ping @oharastream/frontend

**Comment by saivirtue** [comment]
IIRC, we need to test the node connection of [SSH mode](https://zpl.io/aN5r7GZ), which is using the validation API.

**Comment by konekoya** [comment]
>IIRC, we need to test the node connection of SSH mode, which is using the validation API.

I think @chia7712 is referring to the validate report which contains the latest test result?

> the field "validationReport" is a workaround to previous UI flow to trace/verify nodes. Is it still useful to our new UI?

Seems like it's not needed anymore (at least not I'm aware of)

**Comment by konekoya** [comment]
Ping @eechih for some feedback on this  :)

**Comment by chia7712** [comment]
@oharastream/frontend seems the validation APIs is used by UI. Could you remove the usage first?

**Comment by chia7712** [comment]
> @oharastream/frontend seems the validation APIs is used by UI. Could you remove the usage first?

I put the APIs back to validation APIs and I will complete the cleanup in #3351
