### ISSUE TITLE
Integrate DockerClient and K8sClient

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#3339]
Integrating them can simplify the collie implementation since we can use the interface rather than the implementation and reduce the usage on the different methods.

1. - [x] move ContainerName from ohara-configurator to ohara-agent (#3341)
1. - [x] DockerClient/K8SClient should ignore the containers created by other one (#3343)
1. - [x] document the specific label which is added to the container created by Ohara (#3385)
1. - [x] change the "ssh" to "docker" (#3386)
1. - [x] remove flag "removeContainerOnExit" since we need to trace the logs for dead containers as well (#3390)
1. - [x] Disable DockerClient/K8SClient to remove/stop containers unrelated to ohara (#3401)
1. - [x] remove network bridge and volume mapping from DockerClient (#3405)
1. - [x] Introduce ContainerClient (#3413)

**Comment by jackyoh** [comment]
所以是做成一個 trait 給 K8sClient 和 DockerClient 繼承使用嗎？

**Comment by chia7712** [comment]
> 所以是做成一個 trait 給 K8sClient 和 DockerClient 繼承使用嗎？

沒錯。讓Collie去操作該介面，只在"少數的地方"轉型成特定實作。這樣我們就可以把K8sXXXCollie和SSHxxxCollie刪掉了

**Comment by jackyoh** [comment]
之後的 Collie 就應該不會管平台的實做細節像是 k8s 或是 docker。

**Comment by chia7712** [comment]
> 之後的 Collie 就應該不會管平台的實做細節像是 k8s 或是 docker。

理想上啦，可能有些地方還是要casting一下。不過至少不需要像現在還分ssh/k8s impl

**Comment by jackyoh** [comment]
未來 Collie 應該就是在專注於 zookeeper, broker, worker 和 stream 的管理

**Comment by chia7712** [comment]
> 未來 Collie 應該就是在專注於 zookeeper, broker, worker 和 stream 的管理

U are right. Collie should not care for the container communication and impl

**Comment by saivirtue** [comment]
About the no.2 description :
> DockerClient/K8SClient should ignore the containers created by other one (#3343)

It seems we will use `--label` to filter containers of under management. Should we also add this description into `user_guide.rst` ?

**Comment by chia7712** [comment]
> Should we also add this description into user_guide.rst ?

Sure, boss
