### ISSUE TITLE
Migrate the PostCommit from our jenkins to Github actions

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#3349]
the github actions support the logs now so I feel it is time to reduce the loading from our jenkins.

example: https://github.com/chia7712/ohara/actions

1. - [x] add config to trigger Github Action for PostCommit (#3350)
1. - [x] remove PostCommit from our jenkins (@jackyoh)

**Comment by chia7712** [comment]
@jackyoh could you backup and then remove the PostCommit from our jenkins?

**Comment by jackyoh** [comment]
目前已經在 issue #3353 建立 jenkins job 設定檔的備份了

**Comment by chia7712** [comment]
@jackyoh are you ready to remove PostCommit from jenkins?

**Comment by jackyoh** [comment]
OK, 我明天早上來移除掉。

**Comment by chia7712** [comment]
@jackyoh any update?

**Comment by jackyoh** [comment]
已經刪除了

**Comment by jackyoh** [comment]
ping @chia7712 這個 issue 應該可以關閉了
