### ISSUE TITLE
備份 jenkins 的 Job 設定檔

### ISSUE THREAD

**Issue by jackyoh** [oharastream/ohara#3353]
QA 有很多 Job，像是 PreCommit-OHARA, PreTest-OHARA, PostCommit-OHARA... 等等的 job，這些設定檔需要做備份，因此會撰寫 shell script 和 cronjob 定期做設定檔的備份。設定檔會放在內部的 ftp     server 裡。

**Comment by chia7712** [comment]
@jackyoh thanks for the contributions!

**Comment by jackyoh** [comment]
Thank you!

**Comment by jackyoh** [comment]
目前已經將 jenkins 設定的備份檔放在以下的 url 裡了：
ftp://ftp-rnd/jenkins/
