### ISSUE TITLE
Unify the form of url resource for Zookeeper, Broker, Worker and Stream Inpsect APIs

### ISSUE THREAD

**Issue by eechih** [oharastream/ohara#3411]
Return the error message "Unsupported API: inspect/broker/***"

- [x] [Manager] Adapt the new inspect API structure (@saivirtue ) (#3414)

/cc @chia7712

**Comment by saivirtue** [comment]
This issue will require front-end change, let me edit the description.

**Comment by chia7712** [comment]
> This issue will require front-end change, let me edit the description.

the previous APIs are NOT removed so I guess UI can keep current way.

**Comment by saivirtue** [comment]
> > This issue will require front-end change, let me edit the description.
> 
> the previous APIs are NOT removed so I guess UI can keep current way.

Yep. But still, need to unify the form of front-end also.
