### ISSUE TITLE
An new gradle task used to generate a file containing version details in json format

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#3423]
#1888 has added a file which contains manager's version information under the path: `/home/ohara/default/bin/ohara_version`. However, since this file is generated from the Backend source and thus is only available when staring manager with docker not starting manager from its source code (which is how we developing the frontend). 

Is it possible that we can add a new Gradle command in which we can generate the file and so manager can access the file even when starting from the source code :)

/cc @chia7712

**Comment by konekoya** [comment]
related #3180

**Comment by chia7712** [comment]
@konekoya 

the new command is ```gradle versionFile```, and the file containing json string is located at ```ohara/ohara-common/build/generated/ohara_version```

Is it ok to you?

**Comment by konekoya** [comment]
> the new command is gradle versionFile, and the file containing json string is located at ohara/ohara-common/build/generated/ohara_version

Was expecting this to be located in manager's root. But put it inside oharar-common should work just fine too. Thanks :)

**Comment by chia7712** [comment]
> Was expecting this to be located in manager's root. 

As the task (version generator) is included by ohara-common, and it is weird to modify something of "another" module :(

**Comment by konekoya** [comment]
> As the task (version generator) is included by ohara-common, and it is weird to modify something of "another" module :(

No problem. Thanks for the help :)
