### ISSUE TITLE
Introduce new Object APIs enabling Manager to temporarily store worker data

### ISSUE THREAD

**Issue by eechih** [oharastream/ohara#3452]
Worker 在 Running 時，UI 無法暫存任何資料到 tags 下。因此，需要有另一個方式可以暫存。

/cc @chia7712

**Comment by chia7712** [comment]
An new route - object route - it offers the CRUD and all settings are stored by Configurator. For example,

POST /v0/objects/aaa?group=b
```json
{
  "k": "v"
}
```

GET /v0/objects/aaa?group=b

DELETE /v0/objects/aaa?group=b
