### ISSUE TITLE
The error folder of csv connector should be optional so users are able to ignore the error

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#3456]
the error folder is used to store the files which connector can't process. In some cases, users want to "ignore" the failed files and the error folder is ignored. However, we declared the field as "required" so user MUST define a folder for it.

We should change it to optional and just ignore the failed files when there is no error folder.

**Comment by chia7712** [comment]
@eechih any suggestions :)

**Comment by eechih** [comment]
@chia7712 Right you are! :)
