### ISSUE TITLE
Make necessary adjustments to definitions API in order to meet the UI requirements

### ISSUE THREAD

**Issue by wu87988622** [oharastream/ohara#3466]
1. - [x] add an new flag "updatable" to definition to protect the value (@chia7712) (#3470)
1. - [x] Display console warning of API request in development environment only (@saivirtue )(#3692)
1. - [x] Change "GROUP"'s internal to true so it won't display in the UI @wu87988622 #3556 
1. - [x] Change "ZOOKEEPER_CLUSTER", "BROKER_CLUSTER", and "WORKER_CLUSTER"'s  internal to true so they won't display in the UI @wu87988622  #3556 
1. - [x] Add new flag "updatable" and regular to manager #3564 
1. - [x] Disable user to enter value in blacklist and show the recommended values to user (#3167) #3564

**Comment by chia7712** [comment]
@oharastream/frontend I have opened another issue to merge "editable" and "updatable" (see #3480). It is going to break the compatibility so please ping me if you are ready to be in new APIs world :)

**Comment by saivirtue** [comment]
All subtasks were done, close this issue now.
