### ISSUE TITLE
Integrate "editable" with "updatable"

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#3480]
We have two action used to "modify" a field - create and update. Hence, we should have totally three conditions rather than (boolean, boolean).

1. - [x] Introduce permission field - it consists of READ_ONLY, CREATE_ONLY and EDITABLE (#3482)
1. - [x] remove "editable" field (#3579)

**Comment by chia7712** [comment]
@oharastream/frontend 

我補充一下新的參數說明:

1. READ_ONLY -> BJ4
1. CREATE_ONLY -> 第一次建立後就不能修改
1. EDITABLE -> 你想怎樣都可以

**Comment by wu87988622** [comment]
@chia7712 Manager has been updated to the latest rule #3466 , you can remove "editable", thanks

**Comment by chia7712** [comment]
@wu87988622 thanks for the contributions :)
