### ISSUE TITLE
執行 benchmark 的測試和啟動外部系統的 Job 需要拆開

### ISSUE THREAD

**Issue by jackyoh** [oharastream/ohara#3487]
目前在執行 performance 的測試時，會在 QA 的同一個 job 裡執行啟動外部系統和 performance 測試的部份，經過討論之後以上二個工作應該要拆分成二個 job 來執行，主要的好處如下：
* 保持 benchmark 的簡單性
* 可以使用其他方式來執行外部系統
* 減少外部系統執行少花費的時間，像是 oracle database container 就會花費較長的時間

**Comment by chia7712** [comment]
Does this issue touch our source code? If not, please remove the fix version :)

**Comment by jackyoh** [comment]
這個 issue 不會跟 source code 相關。我把版本號移除掉

**Comment by jackyoh** [comment]
目前在 QA 上已經有，Performance-OHARA 和 Performance-env-OHARA 二個 job 了
