### ISSUE TITLE
[Manager] Update serialize-javascript to fix GitHub's security warning

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#3493]
1. As the plugin is only used [in the build time](https://github.com/facebook/create-react-app/pull/8102#issuecomment-562709045) (running`yarn build` to generate static assets), it seems we're pretty safe and won't be affected by this issue. 

2. And because serialize-javascript is not a direct dependency of Manager but create-react-app, we will need to wait for their update 😕

Ref: https://github.com/facebook/create-react-app/issues/8100#issue-533964870

- [x] Fix yarn.lock file being updated by running yarn install (#3901)

**Comment by konekoya** [comment]
The fix has been merged and scheduled in the next release of CRA

**Comment by chia7712** [comment]
@konekoya should we attach "v0.10.0" label to this issue?

**Comment by konekoya** [comment]
Right, we should do so :)

**Comment by konekoya** [comment]
Reopened as re-run `yarn install` will update the yarn.lock file... 🤷‍♂
