### ISSUE TITLE
[Manager] Design the data structure of worker, broker and zookeeper for UI

### ISSUE THREAD

**Issue by eechih** [oharastream/ohara#3520]
一般而言，我們需要打很多不同的 API，才能拿到足夠的資訊用來呈現一個 UI。而且，一個好的資料結構，是有助於加快 UI 的效能。

一個名為 abc 的 worker，我們會打 3 個 API，最後組出一個 UI 顯示用的物件，例如：

- v0/workers/abc?group=worker
```
{
	"settings": {
		"name": "abc",
		"group": "worker",
		"nodeNames": ["dev1"],
		...
	} 
}
```
- v0/inspect/worker/abc?group=worker
```
{
	"settingDefinitions": [{...}],
	"classInfo": [{...}],
	"imageName": "oharastream/connect-worker:0.9.0-SNAPSHOT",
}
```
- v0/objects/abc?group=worker
```
{
	"stagingSettings": {
		"name": "abc",
		"group": "worker",
		"nodeNames": ["dev1", "dev2"],
		...
	} 
}

```

combine the results to an object:
```
{
	"settings": {
		"name": "abc",
		"group": "worker",
		"nodeNames": ["dev1"],
		...
	}, 
	"stagingSettings": {
		"name": "abc",
		"group": "worker",
		"nodeNames": ["dev1", "dev2"],
		...
	},
	"settingDefinitions": [{}, ...],
	"classInfo": [{...}],
	"imageName": "oharastream/connect-worker:0.9.0-SNAPSHOT",
}
```

/cc @konekoya @wu87988622 @saivirtue

**Comment by chia7712** [comment]
@eechih 所以是希望讓v0/workers/abc?group=worker這隻也要回傳settingDefinitions嗎?

**Comment by eechih** [comment]
> 所以是希望讓v0/workers/abc?group=worker這隻也要回傳settingDefinitions嗎?

@chia7712  Nice to have~ 可以少打一個 API :)

**Comment by chia7712** [comment]
> Nice to have~ 可以少打一個 API :)

我是不建議合併這兩種資訊在同一隻API，因為在APIs實作上，get worker 和 get definitions是完全不同的操作，要碰觸不同的外部系統，以及操作不同的外部系統APIs，換言之對使用者而言除非他真的需要全部的資訊，否則這隻API會產生"意想不到的錯誤"，例如只是想要看某個worker的參數，但會噴出無法連線worker client的錯誤。同時也會有"意想不到的延遲"

另外一個隱憂而是，現在這個合併的需求是因為現在某個UI畫面而需要，就如同pipeline即將面對的命運，UI畫面變更後可能又不需要合併definitions，到時候會否因為額外的延遲導致我們又必須把這隻API拆開呢? (事實上inspect的出現就是要避免額外的延遲在一隻過度肥厚的APIs)。例如，之後出現一個畫面是需要很快地review worker參數，但是我們將definition合併到get worker後導致該APIs會產生一定的延遲，那麼此時我們是否有要開一隻API來get worker但又不要definition呢?

**Comment by eechih** [comment]
非常贊同。API 盡量簡單並維持單一功能，是良好的設計原則～ :)

**Comment by eechih** [comment]
Resolved by #3542
