### ISSUE TITLE
Replaces Pipeline.Flow by Pipeline.Endpoint

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#3530]
the flow is too hard to be used by our Manager, and we have purposed a new structure "endpoint" which consists of "group", "name" and "kind" to replace flow.

1. - [x] Introduce Pipeline.Endpoit (#3533)
1. - [x] remove Pipeline.Flow (#3608)

blocked by #3572

**Comment by chia7712** [comment]
FYI @oharastream/frontend

**Comment by wu87988622** [comment]
@chia7712 you can remove Pipeline.Flow manager is ready.

**Comment by chia7712** [comment]
> you can remove Pipeline.Flow manager is ready.

Roger that :)

**Comment by saivirtue** [comment]
Sorry for the late reply...there are some front-end api tests are using old structure. We will update them in #3572.

**Comment by chia7712** [comment]
> Sorry for the late reply...there are some front-end api tests are using old structure. We will update them in #3572.

ok :)
