### ISSUE TITLE
performance  test 使用的 ftp docker image 修改成 apache ftpserver

### ISSUE THREAD

**Issue by jackyoh** [oharastream/ohara#3541]
目前 performance test 使用的 ftp server 為 pure ftp server，如果在寫大量的資料時 connection 容易發生 failed，主要的原因有可能 ftp server 的 data port 沒有被 release。因此需要修改 ftp server 的 docker image, 改成 apache 的 ftp server

**Comment by chia7712** [comment]
related to #3030
