### ISSUE TITLE
Saving graph in manager pipeline 

### ISSUE THREAD

**Issue by wu87988622** [oharastream/ohara#3572]
1. [x] save connector,topic,stream in pipeline. #3607 
1. [x] save graph in pipeline. #3645

**Comment by wu87988622** [comment]
@chia7712 this issues i will use pipelineApi endpoints, thanks.

**Comment by chia7712** [comment]
> this issues i will use pipelineApi endpoints, thanks.

thanks, boss :)

related to #3530
