### ISSUE TITLE
Flatten cluster settings to the first level

### ISSUE THREAD

**Issue by eechih** [oharastream/ohara#3574]
將物件的 settings 資料，攤平到物件的第一層，可以直接享受 Patch Update 的好處。
受影響的物件有 Zookeeper, Broker, Worker, Topic, Connector。

感謝 @chia7712

1. - [x] flatter cluster settings and keep the deprecated "settings" (#3581) (@chia7712)
1. - [x] remove "settings" from all json response  (@chia7712) (#3647)
1. - [x] [Manager] removing "settings" in all api tests (@saivirtue) (#3646)
1. - ~[ ] [Manager] apply flatten settings to api and refactor cluster api functions (@saivirtue) (#3598)~
   <details open="true"><summary></summary>
   <p>

   This change will be applied to the following objects:
   1. - zookeeper
   1. - broker
   1. - worker
   1. - stream
   1. - topic
   1. - connector
   1. - workspace

   The basic supported APIs:
   1. get: fetch data & get from object api
   1. getAll: fetch data list & get from object api
   1. create: create data & save to object api
   1. update: update data
   1. stage: update object api
   1. delete: delete data & object api
   1. start: start service
   1. stop: stop service

   Response data:
   ```json
   {
     "settings": {
     },
     "stagingSettings":{
     },
     "settingDefinitions":[
     ],
     "other_runtime_fields"
   }
   ```
   </p>
   </details>

**Comment by chia7712** [comment]
@eechih great idea :)

**Comment by saivirtue** [comment]
@oharastream/frontend 
Please see the description of sub-task 3 for the conclusion.
Let me know if I was misunderstand something :)

**Comment by chia7712** [comment]
@oharastream/frontend I fail to catch the progress of removing the "settings". Is it a good time to remove the "settings"?

**Comment by saivirtue** [comment]
> @oharastream/frontend I fail to catch the progress of removing the "settings". Is it a good time to remove the "settings"?

Ongoing. Will fire a PR in late today.

**Comment by saivirtue** [comment]
ping @chia7712 
Front-end is ready to accept no settings world, you can remove it :)

**Comment by chia7712** [comment]
all tasks are completed :)
