### ISSUE TITLE
nodenames in streamApi should support empty array

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#3597]
Since adding stream in UI flow will allow users to decide which node should be used, we should use an empty array for initial creation.

Thanks @chia7712

**Comment by chia7712** [comment]
@saivirtue We can assume this is a specific case to API changes. Other services APIs still require the "node names" in creating :)

**Comment by saivirtue** [comment]
> Other services APIs still require the "node names" in creating :)

True. We can add some notes in the changes.
