### ISSUE TITLE
Can't run the multiple pipeline with different workspace

### ISSUE THREAD

**Issue by HarryChiang143** [oharastream/ohara#3601]
**Describe the bug**
When i create two pipeline on each workspace, and run the second pipeline's streamApp , the system will crash.

**To Reproduce**
1. Create two workspace on different ohara-node
<img width="1232" alt="螢幕快照 2019-12-23 下午5 52 55" src="https://user-images.githubusercontent.com/46185836/71351259-33b10d80-25ae-11ea-8864-850d97007c75.png">
2. Create two pipeline on each workspace
<img width="1244" alt="螢幕快照 2019-12-23 下午5 51 19" src="https://user-images.githubusercontent.com/46185836/71351277-3c094880-25ae-11ea-862f-20a8451fa240.png">
<img width="1238" alt="螢幕快照 2019-12-23 下午5 53 00" src="https://user-images.githubusercontent.com/46185836/71351291-475c7400-25ae-11ea-969c-ed24ba0a74fe.png">
<img width="1251" alt="螢幕快照 2019-12-23 下午5 54 19" src="https://user-images.githubusercontent.com/46185836/71351298-4b889180-25ae-11ea-89fc-01735f5033b7.png">
3. Start the first pipeline
<img width="1311" alt="螢幕快照 2019-12-23 下午5 54 39" src="https://user-images.githubusercontent.com/46185836/71351370-6fe46e00-25ae-11ea-9e58-e025653ebd4e.png">
4. Start the second pipeline, then see error
<img width="1380" alt="螢幕快照 2019-12-23 下午5 56 31" src="https://user-images.githubusercontent.com/46185836/71351381-796dd600-25ae-11ea-93a5-2431a29bd6e8.png">
<img width="773" alt="螢幕快照 2019-12-23 下午6 13 14" src="https://user-images.githubusercontent.com/46185836/71351953-f483bc00-25af-11ea-993f-1ce46f716cbd.png">

**Expected behavior**
理論上不同workspace裡面的pipeline應該可以個別成功執行，且特別是不同workspace已經部署在不同的node上面，應該不會互相干擾。

**Operation System (please complete the following information):**
 - Test env : Ohara Demo環境 
<img width="455" alt="螢幕快照 2019-12-23 下午6 06 23" src="https://user-images.githubusercontent.com/46185836/71351558-f8630e80-25ae-11ea-9cc6-fbf186278371.png">

**Comment by HarryChiang143** [comment]
manager log 
[manager.log](https://github.com/oharastream/ohara/files/3994506/manager.log)
configurator log 
[configurator.log](https://github.com/oharastream/ohara/files/3994507/configurator.log)

**Comment by HarryChiang143** [comment]
c.c @vitojeng , @jackyoh , @chia7712

**Comment by chia7712** [comment]
this is the deprecated UI ... Could you reproduce this issue via restful APIs?

**Comment by HarryChiang143** [comment]
So you mean this issue is relate on UI ?

**Comment by chia7712** [comment]
@HarryChiang143 as discussed, I'm going to close this :)

**Comment by HarryChiang143** [comment]
I will retry this scenario on v0.9 release. this issue will be pending now.
