### ISSUE TITLE
TestPerformance4FtpSink, TestPerformance4HdfsSink and TestPerformance4SambaSink expose illegal public method

### ISSUE THREAD

**Issue by jackyoh** [oharastream/ohara#3674]
TestPerformance4FtpSink, TestPerformance4HdfsSink, TestPerformance4SambaSink 實做的 afterStoppingConnector 方法沒有加到 protected，在跑 postCommit 會出現 failed

1. - [x] add arguments to BasicTestPerformance#afterStoppingConnectors so as to not be viewed as test case (#3678 )

**Comment by chia7712** [comment]
怪怪，之前的QA怎麼沒有噴錯

**Comment by jackyoh** [comment]
我剛才也跟 @saivirtue  討論也覺得很怪，我們的 QA 應該要出錯。不過這是我的程式問題我先開 PR, QA 的部份我再找時間研究。

**Comment by chia7712** [comment]
> 我剛才也跟 @saivirtue 討論也覺得很怪，我們的 QA 應該要出錯。不過這是我的程式問題我先開 PR, QA 的部份我再找時間研究。

可否先隨便開支PR測看看是否QA有抓到此問題

**Comment by jackyoh** [comment]
OK, 我再隨便開支 PR 來測試看看

**Comment by chia7712** [comment]
> OK, 我再隨便開支 PR 來測試看看

我已經開了(see #3677)

**Comment by jackyoh** [comment]
Thank you

**Comment by chia7712** [comment]
@jackyoh 該錯誤是從ohara-assembly的測試中拋出來的，應該是當時的PR只有碰到ohara-it的程式碼，因此沒有跑ohara-assembly的測試，導致該錯誤沒有被QA偵測到。因此解法應該是要調整QA邏輯，只要有動到後端的程式碼就一定要跑ohara-assembly的測試

@jackyoh 因為你已經把議題指定給你自己了，或許你嘗試改改看QA流程? 有問題的話我們再討論?

**Comment by jackyoh** [comment]
OK, 我來嘗試改看看. 如果有遇到問題我再跟你討論

**Comment by chia7712** [comment]
reopen since scala protected method is compiled to java public method, and the public method is illegal in our testing infra :(

**Comment by jackyoh** [comment]
我已經把 assembly 的檢查，放在如果只修改 ohara-it 的程式碼也會跑 assembly 的檢查。我想問過問題，如果 assembly 沒過，需要再跑其他的 it 測試嗎？

**Comment by chia7712** [comment]
> 如果 assembly 沒過，需要再跑其他的 it 測試嗎？

要喔，我們的原則是全部都要跑然後一次秀出有哪些失敗的測試

**Comment by jackyoh** [comment]
> 要喔，我們的原則是全部都要跑然後一次秀出有哪些失敗的測試

OK, 了解。目前已經將 assembly 的檢查加上去了
