### ISSUE TITLE
Increase data size of input data for performance test

### ISSUE THREAD

**Issue by jackyoh** [oharastream/ohara#3679]
目前使用 QA 環境在執行 TestPerformance4Topic 的測試時，測試程式如果沒有呼叫 sleepUntilEnd 方法，metrcis 的 csv 檔不會產生而造成圖表不能顯示

**Comment by chia7712** [comment]
> 測試程式如果沒有呼叫 sleepUntilEnd 方法

嗯？該測試應該有呼叫sleep吧？

**Comment by chia7712** [comment]
更正：該測試是把資料灌到topic，所以相關的metrics應該會更新才對。

**Comment by jackyoh** [comment]
metrcis 更新應該會產生 csv 的檔案，我在 local 的環境上測試有產生，但是放在 QA 的環境跑卻沒有 csv 的檔案，我再查看看原因好了

**Comment by jackyoh** [comment]
測試之後發現在 produce 的資料量太小，會使 metrics 在短時間內沒辦法更新資料，後來把 ohara.it.performance.data.size 從 100 調成 1000, 不用呼叫 sleep 就會產生 csv 的資料

**Comment by chia7712** [comment]
> ohara.it.performance.data.size 從 100 調成 1000,

來個PR吧

**Comment by jackyoh** [comment]
ok, 我來開 PR.

**Comment by chia7712** [comment]
> ok, 我來開 PR.

Could we close this issue?

**Comment by jackyoh** [comment]
Please review the PR #3686
