### ISSUE TITLE
重構 TestPerformance4FtpSink, TestPerformance4HdfsSink 和 TestPerformance4SambaSink 的 afterStoppingConnectors 實作

### ISSUE THREAD

**Issue by jackyoh** [oharastream/ohara#3688]
因為目前 BasicTestPerformance 的 afterStoppingConnectors 已經暴露了，connectorInfos 和 topicInfos 參數，所以在實作面不用使用 var 去存放 topicInfo 的變數。直接使用 afterStoppingConnectors 的參數就可以知道 topicInfo, 然後將 sink 產生的資料夾刪除。

**Comment by chia7712** [comment]
nice idea :)
