### ISSUE TITLE
[Manager] Unable to get correct group when changing workspace

### ISSUE THREAD

**Issue by eechih** [oharastream/ohara#3705]
as title

- [x] for 0.10 (#3727)
- [x] for 0.9 (#3740)

**Comment by saivirtue** [comment]
Will this issue merge to `0.9` before today noon?
If not, please help me to move this issue to `0.10` :)

**Comment by eechih** [comment]
move to 1.10

**Comment by saivirtue** [comment]
@eechih 
I've updated the description since this issue will back port to 0.9 also :)
