### ISSUE TITLE
Change the link of docs to latest

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#3726]
As discussed with @vitojeng, we will use the following rules to link the docs branch:

**Before Release**
1. master branch -> doc using `latest` keyword in url -> the actual link is redirect to `previous stable version`
2. Candidate release branch -> doc using `latest` keyword in url is OK since we are not released yet

**After Release**
1. master branch -> doc using `latest` keyword in url -> the actual link is redirect to `release version`
2. Release branch -> doc using `latest` keyword in url -> the actual link is redirect to `release version`

TL;DR

We DON'T need to change any version of docs (ex: README.md) in any time.

Additional tasks to make this flow more straightforward:
- [x] Remove redundant path of url in docs if it meant to be root of url (#3729)

**Comment by chia7712** [comment]
> Release branch -> doc using latest keyword in url -> the actual link is redirect to release version

不太確定我是否有看懂。

以docker image為例子好了，假設要釋出0.9.0，然後doc有一個敘述是:
```請使用oharastream/configurator:0.9.0```

在這支issue是想要將上述例子改成什麼樣子?

**Comment by saivirtue** [comment]
> 在這支issue是想要將上述例子改成什麼樣子?

這個issue的目的是將"連結"到文件的網址簡單化。未來只需要使用latest這個關鍵字就好，後台會做管理latest要連到哪裡去。
而docker image的版本號我們會使用`gradle.properties`裡面的變數動態去改，因此release還是會有需要修改這一部分

**Comment by chia7712** [comment]
> 這個issue的目的是將"連結"到文件的網址簡單化。未來只需要使用latest這個關鍵字就好，後台會做管理latest要連到哪裡去。

有沒有一個例子?

**Comment by saivirtue** [comment]
以這次0.9為例

Release 0.9之前
master branch:  `README.md`的https://ohara-quickstart.readthedocs.io 實際上會指到stable的版本 : 0.8.x (https://ohara-quickstart.readthedocs.io/en/0.8.x)
0.9.x branch -> `README.md`的https://ohara-quickstart.readthedocs.io 實際上會指到stable的版本 : 0.8.x (https://ohara-quickstart.readthedocs.io/en/0.8.x) ; 但這部分因為還未release，所以不影響

Release 0.9之後
master branch:  `README.md`的https://ohara-quickstart.readthedocs.io 實際上會指到release的版本 : 0.9.x (https://ohara-quickstart.readthedocs.io/en/0.9.x)
0.9.x branch -> `README.md`的https://ohara-quickstart.readthedocs.io 實際上也會指到release的版本 : 0.9.x (https://ohara-quickstart.readthedocs.io/en/0.9.x)

**Comment by chia7712** [comment]
@saivirtue 就"程式碼"來看，好像沒有改變不是嗎? 通通都是指到latest?

> 這個issue的目的是將"連結"到文件的網址簡單化。未來只需要使用latest這個關鍵字就好，後台會做管理latest要連到哪裡去

我看PR的內容反而是把"latest"這個字眼移除掉了?

**Comment by chia7712** [comment]
另外一個疑問則是: quickstart現在有維護不同版本了嗎? 如果有的話，為何在url上沒有區分? 如果沒有的話，我們是否該開始把它排入RM的工作之一?

**Comment by vitojeng** [comment]
> 我看PR的內容反而是把"latest"這個字眼移除掉了?

由 document 網站的行為來看, 若是只輸入網站 url(ex: https://ohara.readthedocs.io),
此時會有一個 redirect 的行為轉換到 latest 的版本.

因此把 latest 拿掉, 就是意味著 latest 的版本.

**Comment by saivirtue** [comment]
PR的名稱命名不是很好...這個issue是提出目前docs連結網址的邏輯，但PR要將多餘的url拿掉，只留root url
讓我改一下PR的名稱

**Comment by chia7712** [comment]
> 因此把 latest 拿掉, 就是意味著 latest 的版本.

所以是指現在的"程式碼"裡面提到文件都統一用"https://ohara.readthedocs.io"?

換言之，使用者從程式碼裏頭都是連接到latest的文件網站，然後再自行去切換到對應版本(例如0.9.0)嗎?

**Comment by vitojeng** [comment]
目前的概念是在 /README.md 裡, 文件的連結引導使用者連結到最近一次發佈的版本應該會比較好.

文件的 latest 版本可以在後台指定要對應的 branch, 不用修改 repo.
因此只要某個版本正式 release 後, 就可以設定這個版本為 latest.

不過若有需要 "指定" 的話, 那當然 url 裡就要給出那個 branch 了...

**Comment by chia7712** [comment]
> 因此只要某個版本正式 release 後, 就可以設定這個版本為 latest.

因此之後文件網站的"預設"是顯示某個release而不是指向最新的snapshot?

**Comment by vitojeng** [comment]
yes.

之前 latest 是指到 master **branch**
現在 latest 調整成最近 release 的 **branch**
若要看 master branch 要手動切換.
