### ISSUE TITLE
JDBC Source Connector 需要支援時區的設定

### ISSUE THREAD

**Issue by jackyoh** [oharastream/ohara#373]
Source 的 Database 是 UTC+8 的時區, 使用的 Worker connector 是 UTC+0 的時區, 這樣會造成資料撈不到的問題, 而使得資料無法寫入到 Topic 內.

**Comment by chia7712** [comment]
@jackyoh any update?

**Comment by jackyoh** [comment]
目前是使用 database 的時間，所以沒有要更新了。我把此議題關閉
