### ISSUE TITLE
[Question] 在建立workspace的時候顯示預設的名字

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#3739]
這樣可以幫助無腦下一步

![註解 2020-01-08 102251](https://user-images.githubusercontent.com/6234750/71945116-d6999680-3200-11ea-8e29-33216140beff.jpg)

ping @oharastream/frontend

**Comment by saivirtue** [comment]
如果提供預設名稱(例如：wk1, wk2, wk3....)，使用者在進入這個頁面後會不會看到Next就一直往下點，忽略我們提供的預設值而沒注意到建立的名稱是什麼?

**Comment by chia7712** [comment]
> 忽略我們提供的預設值而沒注意到建立的名稱是什麼?

這就是這個功能的目的 可以無腦下一步 :)

畢竟都是quickstart了

**Comment by saivirtue** [comment]
> 這就是這個功能的目的 可以無腦下一步 :)

應該至少還是要選node :)

忽略預設名稱，建立後應該還是可以找的到。
但我又想到另一個問題：如果我們預設的名稱與現有的已經重複了，目前的機制不會在輸入名稱就擋下，而是在啟動階段才拋錯誤...

**Comment by chia7712** [comment]
> 但我又想到另一個問題：如果我們預設的名稱與現有的已經重複了，目前的機制不會在輸入名稱就擋下，而是在啟動階段才拋錯誤...

如果無法先list一下在遞增名字的話，那就加個postfix來避免重複 (例如myspace0, myspace1)

**Comment by saivirtue** [comment]
postfix 還是會有重複的狀況，使用者可以自己先建立myspace0
但先list現有的workspace名稱來擋掉接下來的動作似乎是個不錯的主意，不知道其他人覺得如何?

**Comment by eechih** [comment]
無腦再進階 +1
default + postfix，在 list 發現重複，postfix 再加 1

**Comment by konekoya** [comment]
> 這樣可以幫助無腦下一步

+1 

> 在 list 發現重複，postfix 再加 1

Yep, I think this check is still necessary.
And the prefix could be something "quickworkspace"?

**Comment by saivirtue** [comment]
I will fire another issue to add prefix: "quickworkspace" + random number as default workspace name

**Comment by chia7712** [comment]
> I will fire another issue to add prefix: "quickworkspace" + serial number as default workspace name

thanks :)
