### ISSUE TITLE
[Question] 在pipeline頁面的時候展開工具(source, stream, sink)的時候可否自動捲動到展開的工具

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#3741]
![1](https://user-images.githubusercontent.com/6234750/71945916-1bbec800-3203-11ea-9bf8-a8e9c5eecb8d.jpg)

上圖的部分是還沒展開sink的時候

![2](https://user-images.githubusercontent.com/6234750/71945937-2a0ce400-3203-11ea-8948-a1acfb691a3f.jpg)

上圖展開了sink，出現了卷軸但沒有捲到"我剛剛展開的項目"

FYI @oharastream/frontend

**Comment by konekoya** [comment]
Good suggestion :) I'm + 1 for this. 

Thoughts @oharastream/frontend ?

**Comment by saivirtue** [comment]
Could we scroll the bar to fit the "sink section at top position" if the class list of "source" has a fewer numbers?

**Comment by konekoya** [comment]
> Could we scroll the bar to fit the "sink section at top position" if the class list of "source" has fewer numbers?

Sorry @saivirtue could you elaborate this a bit more? I'm not quite follow 😅

**Comment by konekoya** [comment]
@chia7712 we have discussed this issue a bit further. I will let @eechih leave the conclusion here :)

**Comment by eechih** [comment]
@chia7712 在這種情況下，我個人不建議採用會自動捲動的設計，但是我又找不到一個好的解釋來說明為什麼不好。我只能找一個典範給你看，像是 Sketch 這不會自動捲動 Scrollbar ...

![Imgur](https://raw.githubusercontent.com/oharastream/images/master/issues/3741/Screen%20Shot%202020-01-08%20at%202.37.19%20PM.png)

**Comment by chia7712** [comment]
> 像是 Sketch 就不會自動捲動 Scrollbar

所以沒有特別的原因，我們就只是模仿sketch嗎?

此外我覺得兩個案例不太一樣，你貼的圖是已經"焦點"在某個東西上了，所以卷軸不動是合理的。但我提的例子上沒有任何**焦點**，那麼為何此時點選某個項目要展開的時候，自動把該項目視為焦點是不好的?

**Comment by vitojeng** [comment]
以我自己操作其他工具的習慣來想的話...

這個動作我可能會有兩種不一樣的操作情境:
一個是展開後要使用裡面的項目，因此展開後不會收起來.
另一個是我只是想暫時看一下裡面有什麼，並沒有要使用裡面的項目，展開後很快就會再收起來.

以這個想法來看, 自動捲動有可能不是我要的行為.
我會傾向這裡不要加入額外"自動捲動"的行為, 交由使用者自己決定.

**Comment by eechih** [comment]
> 所以沒有特別的原因，我們就只是模仿sketch嗎?

沒有特意模仿 sketch，很多工具都有類似的設計，像是 Google Calendar, IDE 的 File explorer, ...

![Imgur](https://raw.githubusercontent.com/oharastream/images/master/issues/3741/Screen%20Shot%202020-01-08%20at%203.44.15%20PM.png)

**Comment by chia7712** [comment]
看來自動跳轉不太受歡迎，那就保留目前的行為 :)

**Comment by chia7712** [comment]
補充一下，如果可以的話，在被詢問為什麼的時候要盡量要能講出這個設計的原因(或者一些想法)會比較好，因為找正反例子是一件很容易的事情，例如intellij在展開的時候就會自動移動卷軸
![0](https://user-images.githubusercontent.com/6234750/71960732-b1bd1780-3230-11ea-9f4d-9e13f6a0ba45.jpg)
![1](https://user-images.githubusercontent.com/6234750/71960730-b1248100-3230-11ea-866c-a4e99b259aca.jpg)

我的想像就是我特別展開了它就代表我想看到它，因此卷軸自動幫我移動會是一個很貼心的功能。

BTW, @vitojeng 有提了一個想法，那個也是一個解釋

**Comment by vitojeng** [comment]
咦? 我的 intellij 好像不會自動捲...

**Comment by chia7712** [comment]
> 咦? 我的 intellij 好像不會自動捲...

真假? 我有套用Material Theme UI，不知道是不是該套件的行為
