### ISSUE TITLE
[Question] 尚未連接任何topics的connectors, streams是不可能正常運作，但我們依然允許使用者去"啟動"，以及回傳的錯誤訊息不夠清楚

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#3743]
![3](https://user-images.githubusercontent.com/6234750/71946189-0c8c4a00-3204-11ea-9211-fc3301c9b6c3.jpg)

FYI @oharastream/frontend

**Comment by konekoya** [comment]
> 尚未連接任何topics的connectors, streams是不可能正常運作，但我們依然允許使用者去"啟動"

Yep, we can disable these buttons?

/cc @oharastream/frontend 

> 以及回傳的錯誤訊息不夠清楚

The error is now coming directly from the backend. A custom message is possible but If we choose to disable these action buttons, then I don't think this part is necessary :)

**Comment by chia7712** [comment]
> The error is now coming directly from the backend. A custom message is possible but If we choose to disable these action buttons, then I don't think this part is necessary :)

我的意思是只能看到"部分"錯誤訊息 (如圖)，如果可以看到完整的訊息就能知道少填寫什麼瑞

**Comment by konekoya** [comment]
> 我的意思是只能看到"部分"錯誤訊息 (如圖)，如果可以看到完整的訊息就能知道少填寫什麼欄位

~The error is now coming directly from the backend.~ You're right, the message is already alerted in the frontend. But this is intentional, we wrapped the backend API response and display a brief message so the user is easier to read the message as the toast only show up for 5 secs. A more detail message can be read in the event log

**Comment by chia7712** [comment]
> in the event log

這個功能是我們UI的一部分嗎?

**Comment by konekoya** [comment]
> 這個功能是我們UI的一部分嗎?

Yes, in the future release. But for this very release, it's unfortunately not included...

**Comment by chia7712** [comment]
> Yes, in the future release. But for this very release, it's unfortunately not included...

ok

**Comment by konekoya** [comment]
In favor of #3814
