### ISSUE TITLE
[Manager] Early avoid duplicated workspace name when creating a new one

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#3746]
We could leverage the benefit of workspace context to avoid duplicate name before we "actually" create one...

- [x] for 0.10 (#3757)
- [x] backport to 0.9 (#3761)

releated to #3739

**Comment by chia7712** [comment]
Is this related to #3739?

**Comment by saivirtue** [comment]
> Is this related to #3739?

Yes. Let me link them.
