### ISSUE TITLE
[Manager] Add default workspace name in quick mode

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#3752]
Add a default workspace name for user to create workspace more quickly.

rules:
1. prefix: "quickworkspace" + serial number
2. if duplicated, serial number +1

related to #3739

- [x] v0.10.0 (#3773 )
- [x] v0.9.0 (#3774 )

**Comment by eechih** [comment]
@saivirtue I will assign this issue to me :)

**Comment by saivirtue** [comment]
@eechih 
You can keep going on this issue since #3746 has been merged :)
