### ISSUE TITLE
the sinceSeconds does not work since we calculate the duration by incorrect unit

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#3770]
```scala

            CommonUtils.current() - sinceSeconds 
```

:(

1. - [x] for 0.10.0 (#3771)
1. - [x] for 0.9.0 (#3772)

**Comment by saivirtue** [comment]
> ```scala
>             CommonUtils.current() - sinceSeconds 
> ```
> 
> :(

Good catch...It explains a lot
