### ISSUE TITLE
the run-time information of creating node is incorrect - it is always unavailable and resources are empty

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#3785]
from https://github.com/oharastream/ohara/issues/3706#issuecomment-571862957

1. - [x] for 0.10.0 (#3790)
1. - [x] for 0.9.0 (#3791)

**Comment by saivirtue** [comment]
It is due to async problem. Let me take over this issue.

**Comment by chia7712** [comment]
> It is due to async problem. Let me take over this issue.

the APIs don't generate correct runtime information as well. Please add extra task to this issue if you are going to fix something for UI :)
