### ISSUE TITLE
enable to dynamically configure the web site of downloading kafka/zookeeper binary

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#3828]
the web site, sometimes, is unstable and then we have to change another better one. However, we don't give the such function. I plan to expose a variable called "web" to enable us to change the location of downloading binary. the benefit is that we keep the long-live site in our dockerfile and we is able to change it to the faster one dynamically to speedup our build.

**Comment by vitojeng** [comment]
**binary** means Ohara's docker images?

**Comment by chia7712** [comment]
> binary means Ohara's docker images?

kafka/zookeeper binary

**Comment by chia7712** [comment]
ref this https://github.com/chia7712/ohara/commit/35e3ed2dc90f3c4c0a0458fa07652127066ad152

**Comment by vitojeng** [comment]
Got it!
