### ISSUE TITLE
[Question] About Execute Configurator and Restart problem

### ISSUE THREAD

**Issue by CT-C** [oharastream/ohara#3831]
Hi ! 
I am trying to start a Oharastream on centos 7, and i have some issue about Execute Configurator.
My environment is CentOS (cluster with two machine node01 and node02)with only docker Oharastream.
When i execute the configurator without folder it will successfully open but if i add the folder it will start showing error when build the workspace as the picture below(node01 and node02 both have the folder in correct path)

![123](https://user-images.githubusercontent.com/59589182/72405284-45439a80-3793-11ea-9dd6-742fff2ec710.PNG)

and my command is :
docker run --rm -p 5000:5000 --add-host node01:ip --add-host node02:ip oharastream/configurator:0.8.2-SNAPSHOT --port 5000 --hostname ip --folder /home/ohara/configurator

Question 2 
Use the only docker Ohara stream, if i want to restart the environment i have to manually kill all the docker run at node02 before i restart. otherwise it will cause error when i build the workspace. 
is there other way to restart the environment? 

thanks !

**Comment by chia7712** [comment]
hi @CT-C 

Thanks for this report. Unfortunately, the 0.8 is dead since we have introduced the new UI design and it also includes the incompatible changes. Please migrate to 0.9.0-SNAPSHOT which is more beautiful and powerful version :)

**Comment by vitojeng** [comment]
Hi, @CT-C 
> Use the only docker Ohara stream, if i want to restart the environment i have to manually kill all the docker run at node02 before i restart.

Do you mean that you already built a workspace and want to restart the service in the workspace(e.g. zookeeper/broker/worker) ?

**Comment by CT-C** [comment]
Hi, thanks for the reply 
@chia7712 

thanks ! I decide to change to 0.9.0 version.

@vitojeng 

thanks for reply! Sometime i wrote a bad stream app (found a bug after i upload and run), oharastream web UI will crash. when this happened i have to restart the oharastream from terminal, after that if i want to restart the oharastream i have to manually kill all the docker on node02(zk, broker, worker, streamapp) one by one (docker kill xxxxxxx).

**Comment by chia7712** [comment]
> i have to manually kill all the docker on node02(zk, broker, worker, streamapp) one by one (docker kill xxxxxxx).

there are two "official" ways to destroy the services. 
1. UI enables us to remove "workspace" consisting of zk, bk, and wk. 
1. send request DELETE one by one

BTW, killing Configurator doesn't mean that all services have to be killed as well since ohara supports to update service individually.

**Comment by CT-C** [comment]
OK thanks!
