### ISSUE TITLE
[Question] The meaning of `routes` setting definition

### ISSUE THREAD

**Issue by vitojeng** [oharastream/ohara#3848]
Can someone explain the meaning of setting definition of `routes` ? :)

com.island.ohara.client.configurator.v0.package.scala

```scala
  private[v0] def routesDefinition: SettingDef.Builder => SettingDef =
    _.key(ROUTES_KEY).documentation("the extra routes to this service").optional(Type.TAGS).build()

```

**Comment by chia7712** [comment]
the extra "routes" to services. It is used to manually config the routes used by services.

For example, you want to add a route node00 -> 1.0.2.3 to worker, and then you can add the **route** Map("node00" -> "1.0.2.3") to the creation request.

**Comment by vitojeng** [comment]
Thanks for reply.
Does "routes" also as parameter for Kubernetes or Docker?

**Comment by chia7712** [comment]
> Does "routes" also as parameter for Kubernetes or Docker?

yep. Both k8s and docker support to define custom routes :)

**Comment by vitojeng** [comment]
Cool! 
Thanks @chia7712 !
