### ISSUE TITLE
add new fields "valueInPerSec" to ohara metrics

### ISSUE THREAD

**Issue by jackyoh** [oharastream/ohara#3858]
因為 performance 的測試以及未來在 UI 有可能呈現 xxxxPerSec 的 metrics 需求，所以在 connector 的部份需要增加 message.numberPerSec 和 message.sizePerSec 的 metrics, 讓圖表可以更清楚的描述 connector 每秒能處裡多少的資料量。

1. - [x] add new fields "valueInPerSec" to ohara metrics (#3865)
1. - [x] record all metrics periodically for performance tests (#3888)
1. - [x] display the xxxInPerSec by jenkins (@jackyoh)

**Comment by vitojeng** [comment]
> 因為 performance 的測試需求

@jackyoh 目前確實是因為 performance testing 有需要, 但我想未來在 UI 也會需要呈現這類 metrics.

**Comment by jackyoh** [comment]
那我 description 來修改

**Comment by chia7712** [comment]
@jackyoh 可否麻煩你在我把程式碼改好後把新的參數 (valueInPerSec) 加到jenkins上面? 我已經開了一個sub task並且指定給你了 :)

**Comment by vitojeng** [comment]
valueInPerSec 是每秒有多少個 message 的意思嗎?

**Comment by jackyoh** [comment]
OK,收到。我會在把參數加到 performance job 的設定裡

**Comment by chia7712** [comment]
> valueInPerSec 是每秒有多少個 message 的意思嗎?

valueInPerSec是一個新的欄位，例如
```json
{
  "value": 123,
  "unit": "messages",
  "valueInPerSec": 10.3,
  "startTime": 111,
  "lastModified": 133
}
```

就代表目前總共有123的messages，平均吞吐量則是10.3

**Comment by jackyoh** [comment]
那 valueInPerSec 應該會自動寫入到 performance 測試的 csv 檔，應該不用再改 performance 的測試程式。

另外剛剛看了 PR 後, 發現 valueInPerSec 加到 jenkins 上面是指圖表顯示的部份嗎?

**Comment by chia7712** [comment]
> 那 valueInPerSec 應該會自動寫入到 performance 測試的 csv 檔，應該不用再改 performance 的測試程式。

這部分我在#3865有做了

> 發現 valueInPerSec 加到 jenkins 上面是指圖表顯示的部份嗎?

沒錯

**Comment by jackyoh** [comment]
> 這部分我在#3865有做了

有在 PR 上看到了。

**Comment by jackyoh** [comment]
使用了 #3865 的 PR 執行 performance 的測試，產生的 csv 檔案格式如下:
```
"ignored.message.number(inPerSec)","ignored.message.size(inPerSec)","ignored.message.number","message.number(inPerSec)","message.size(inPerSec)","message.size","ignored.message.size","message.number","lastModified"
0.0,0.0,0.0,0.0,7.282483710233806E-4,19710.0,0.0,270.0,1.579663673096E12
```
我再把 xxx(inPerSec) 加入到 jenkins 的圖表設定裡

**Comment by vitojeng** [comment]
> 就代表目前總共有123的messages，平均吞吐量則是10.3

@chia7712 這裡 "平均吞吐量" 的意思就是每秒平均多少的概念嗎?

**Comment by chia7712** [comment]
> 這裡 "平均吞吐量" 的意思就是每秒平均多少的概念嗎?

you are right :)
