### ISSUE TITLE
align the dependencies with kafka 2.4.0

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#3869]
1. scalatest 3.0.5 -> 3.0.8
1. junit 4.12 -> 4.13
1. slf4j 1.7.25 -> 1.7.28
1. scalaLogging 3.9.0 -> 3.9.2
1. guava 22.0 -> 27.1-jre
1. scalatest 3.0.5 -> 3.0.8
1. rocksdb 5.15.10 -> 5.18.3
1. jackson 2.9.8 -> 2.10.0

- [x] update gradle from 5.6.3 to 5.6.4 (#3873)

related to #1614

**Comment by vitojeng** [comment]
Thanks @chia7712 

這樣的話, 年後我預計進行 #1614, 主要是升級 Akka, 目前覺得 Ohara 維持在 Akka 2.5.x 可能比較好.
Akka 2.6.x 的變動比較大, 還是以後再看看.

**Comment by chia7712** [comment]
reopen to update gradle from 5.6.3 to 5.6.4
