### ISSUE TITLE
add more performance cases

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#3881]
考慮到顯示更完整的source到sink會比較符合實際應用，因此我們應該提供相關效能數字

1. - [x] add performance case of transferring data from database to hdfs (@jackyoh) #3887
1. - [x] add performance case of transferring data from ftp to hdfs (@jackyoh ) #3889 
1. - [x] add generator data function to sleepUntilEnd function for performance test (@jackyoh) #3918

**Comment by chia7712** [comment]
@jackyoh 麻煩把已經提交的任務點選完成喔

**Comment by jackyoh** [comment]
ok, 收到。

**Comment by chia7712** [comment]
@jackyoh https://github.com/oharastream/ohara/pull/3888#discussion_r372943739

如你上面提到的部分，我覺得是個不錯的主意，看你要否開個sub task來做 :)

**Comment by jackyoh** [comment]
OK, 那等到 #3888 合併之後，我就來做。另外我把這個部份加到 description 裡

**Comment by chia7712** [comment]
@jackyoh seems all cases are completed. Could we resolve this issue?

**Comment by jackyoh** [comment]
這個部份已經完成了，我先 close 掉
