### ISSUE TITLE
remove the reports of performance test from Topic

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#3884]
We can't customize metrics of topics and it obstructs us from designing our tests reports. There are already connector metrics which are able to replace kafka metrics so it is ok to remove the reports of topic.

1. - [x] remove the data series of Topic from jenkins (@jackyoh)
1. - [x] remove the performance test of Topic (It is replaced by connectors performance tests) (#3886)

**Comment by chia7712** [comment]
@jackyoh 如剛剛聊到，還是把這個我們無法客制化的部分拿掉，用connector的來取代就好，這樣之後我們發展也比較方便

**Comment by chia7712** [comment]
@jackyoh jenkins的部分再麻煩你幫忙，我已經有tag你了(見上方描述)

**Comment by jackyoh** [comment]
OK, 收到。

那我把所有 performance 圖表，關於 topic 的部份全部移除掉。
