### ISSUE TITLE
remove ohara-assembly since Ohara consists of many different assembly for different module

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#3904]
There are 4 modules having their custom assembly - configurator, manager, stream and shabondi. Hence, we don't need the "single" assembly anymore :)

1. - [x] move the configurator assembly to ohara-configurator (#3906)
1. - [x] move the manager assembly to ohara-manager (#3917)
1. - [x] remove the debug code in ohara-manager/build.gradle (introduced by #3917) (#3922)
1. - [x] remove ohara-assembly (#3923)

**Comment by chia7712** [comment]
FYI @vitojeng

**Comment by vitojeng** [comment]
Thanks @chia7712 !

Does that means we never need to include the asset `ohara-assembly-xxx-uber.jar` in the Release page?

**Comment by chia7712** [comment]
> Does that means we never need to include the asset ohara-assembly-xxx-uber.jar in the Release page?

you are definitely right :)

I will revise the documentation in the final sub-task (remove ohara-assembly)
