### ISSUE TITLE
Inspect API: query topic returns an empty array

### ISSUE THREAD

**Issue by vitojeng** [oharastream/ohara#3905]
**Describe the bug**
Use ohara consumer(com.island.ohara.kafka.Consumer), I can fetch many records from consumer.
For example:
```scala
    val consumer = Consumer
      .builder()
      .keySerializer(Serializer.ROW)
      .valueSerializer(Serializer.BYTES)
      .offsetFromBegin()
      .topicName(topicName)
      .connectionProps(brokers)
      .build()
    val records = consumer.poll(Duration.ofSeconds(timeoutSecond), expectedSize).asScala
```

Use Inspect API, the response contain empty array without any execption.
```
http://{{hostname}}:{{port}}/v0/inspect/topic/topic0?group=default&timeout=10000&limit=100
```

May I missing something or occur a bug?

**Comment by chia7712** [comment]
@vitojeng Could you share your test case to us?

**Comment by chia7712** [comment]
BTW, Our topic name is encoded with "group" and "name". For example, the URL you posted has name "topic0" and group "default" so the actual name of kafka topic is "default-topic0".

**Comment by vitojeng** [comment]
> BTW, Our topic name is encoded with "group" and "name". For example, the URL you posted has name "topic0" and group "default" so the actual name of kafka topic is "default-topic0".

Oops...It's my bad. 😢 
Shabondi just use the topic name without group to produce/consume topic.

**Comment by vitojeng** [comment]
file a bug #3907, close this issue.
