### ISSUE TITLE
Move v0.2 wireframe to Dropbox

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#391]
All of the v0.2 wireframes were discussed, drawn and store in Jira. As we already moved to GitHub, and Jira is a private service. There should be a way to reference these wireframes in GitHub. Therefore, a public Dropbox folder to store them.

**Comment by vitojeng** [comment]
I think this issue should label as `in progress`

**Comment by konekoya** [comment]
Done. They're now all moved to Dropbox :)

https://www.dropbox.com/home/OharaStream/design/wireframe

**Comment by vitojeng** [comment]
@konekoya Thanks!
