### ISSUE TITLE
[Question] UI behavior weird in current stream creation flow

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#3911]
For creating a stream object by api `POST /streams`, the following fields are required:
1. name
2. group
3. jarKey
4. nodeNames

Since the creation flow is a little difference between UI and API, the flow of a stream creation will look like:
1. drag a stream class to paper (the `jarKey` will be defined by us)
2. type the name of stream (fill the `name` field)
3. create the stream (call a POST request)

The steps of UI flow seems to conflict with the required fields of API, we need to discuss:
a. Could we update a `jarKey` if stream object is already created? (link to #3924)
~b. Could we support an empty array for nodeNames or make it optional?~
b. The nodeNames could be ignore during creation phase, but we could not update the nodeNames with empty array? (link to #3914)

**Comment by saivirtue** [comment]
/cc @oharastream/developer 
Feel free to leave your comment :)

**Comment by chia7712** [comment]
> Could we update a jarKey if stream object is already created?

why not? Configurator will check the class availability after updating the jar key

> Could we support an empty array for nodeNames or make it optional?

it is already optional (#3597)

**Comment by saivirtue** [comment]
> > Could we support an empty array for nodeNames or make it optional?
> 
> it is already optional (#3597)

My bad :(
It's another issue...I've updated the description.

**Comment by saivirtue** [comment]
> > Could we update a jarKey if stream object is already created?
> 
> why not? Configurator will check the class availability after updating the jar key

For UI user, they could not "see" the jarKey used for. It's decided when they drag the stream component.
For my two cents, I prefer to move this field into `internal`

**Comment by chia7712** [comment]
> The nodeNames could be ignore during creation phase, but we could not update the nodeNames with empty array?

IIRC, APIs accept the empty array for both Creation and Updating. Is there any issue?

**Comment by chia7712** [comment]
> For my two cents, I prefer to move this field into internal

 it is a part of core setting so the hardcode is ok to me

**Comment by konekoya** [comment]
> it is a part of core setting so the hardcode is ok to me

@chia7712 Did you mean hardcoded in the Frontend?

**Comment by saivirtue** [comment]
> > The nodeNames could be ignore during creation phase, but we could not update the nodeNames with empty array?
> 
> IIRC, APIs accept the empty array for both Creation and Updating. Is there any issue?

`PUT /streams/xxx` with 
```json
{
  "nodeNames": []
}
```

will produce

```
{
    "code": "spray.json.DeserializationException",
    "message": "nodeNames cannot be an empty array!!!",
    "stack": "spray.json.DeserializationException: nodeNames cannot be an empty array!!!\n\tat com.island.ohara.client.configurator.v0.JsonRefiner$ArrayRestriction.$anonfun$rejectEmpty$1(JsonRefiner.scala:580)\n\tat com.island.ohara.client.configurator.v0.JsonRefiner$ArrayRestriction.$anonfun$rejectEmpty$1$adapted(JsonRefiner.scala:578)\n\tat com.island.ohara.client.configurator.v0.JsonRefiner.$anonfun$arrayRestriction$3(JsonRefiner.scala:479)\n\tat com.island.ohara.client.configurator.v0.JsonRefiner.$anonfun$arrayRestriction$3$adapted(JsonRefiner.scala:479)\n\tat scala.collection.immutable.List.foreach(List.scala:392)\n\tat com.island.ohara.client.configurator.v0.JsonRefiner.$anonfun$arrayRestriction$2(JsonRefiner.scala:479)\n\tat com.island.ohara.client.configurator.v0.JsonRefiner.$anonfun$arrayRestriction$2$adapted(JsonRefiner.scala:479)\n\tat com.island.ohara.client.configurator.v0.JsonRefiner.$anonfun$requireJsonType$2(JsonRefiner.scala:408)\n\tat 
```

**Comment by chia7712** [comment]
> Did you mean hardcoded in the Frontend?

"jarKey" is still in definition. The "internal" is hardcode to me since it is "beyond" the rule and compatibility.

**Comment by saivirtue** [comment]
> > Did you mean hardcoded in the Frontend?
> 
> "jarKey" is still in definition. The "internal" is hardcode to me since it is "beyond" the rule and compatibility.

+1
Open a new issue to change this?

**Comment by chia7712** [comment]
> Open a new issue to change this?

@konekoya any concern?

**Comment by konekoya** [comment]
Nope, +1  :)

**Comment by saivirtue** [comment]
All the questions are resolved, close this issue.
