### ISSUE TITLE
Improve SettingDef.Necessary

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#3933]
Necessary與default value互相搭配可以組合出下列情境:

1. 此欄位沒有預設值，使用者一定要定義 (necessary -> required, default -> null)
1. 此欄位沒有預設值，但使用者也可以不用定義 (necessary -> optional, default -> null)
1. 此欄位有預設值 (necessary -> optional_with_default, default -> xxx)
1. 此欄位的預設值是隨機產生 (necessary -> optional_with_random_default, default -> xxx)

其中有幾個點需要改善:

1. - [x] remove OPTIONAL_WITH_DEFAULT since it duplicates to defaultValue (#3934)
1. - [x] rename OPTIONAL_WITH_RANDOM_DEFAULT to RANDOM_DEFAULT (#3941)

**Comment by saivirtue** [comment]
What happened for the following combinations?
1. necessary -> required ; default -> xxx
2. necessary -> optional_with_default ; default -> null
3. necessary -> optional_with_random_default ; default -> null

And also, could we give users some hints if the combination is invalid?

**Comment by chia7712** [comment]
> necessary -> required ; default -> xxx

this is "acceptable" since the trouble is only a unused default value :)

> necessary -> optional_with_default ; default -> null

this weird setting will be resolved by this issue. the optional_with_default will be removed

> necessary -> optional_with_random_default ; default -> null

this is legal since the default value is defined when you do create the object. Hence, the definition is unable to show the default value :)

> And also, could we give users some hints if the combination is invalid?

We encourage *developers* to use our friendly APIs to create definition, and our APIs don't make the chaos.

**Comment by saivirtue** [comment]
It seems we have some works to do for front-end
/cc @wu87988622

**Comment by chia7712** [comment]
> It seems we have some works to do for front-end

you are right :)

I have added some changes to frontend (#3934). please take a look :)

**Comment by vitojeng** [comment]
Great improvement, thanks @chia7712 !

BTW, It would be great if we handle following case:
necessary -> required, default -> **xxx**,
**xxx** must be the one item of recommendedValues list.

**Comment by chia7712** [comment]
> necessary -> required, default -> xxx,

Normally, developer CAN'T generate this case via our APIs :)

> xxx must be the one item of recommendedValues list.

The "must" is too hard to keep compatibility if developer change the either recommendedValues or defaultValue in the future. It results in the previous request that can't work with newer definitions.

**Comment by vitojeng** [comment]
> The "must" is too hard to keep compatibility if developer change the either recommendedValues or defaultValue in the future. It results in the previous request that can't work with newer definitions.

Thanks for the explaination.
