### ISSUE TITLE
[Manager] Change Paper element layout

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#3979]
1. Move element menu from its right side to its bottom and this time, it should be placed inside the element.
2. It now only displays a single metics item if the metrics settings is set to "on" and displays the connector status when it's set to "off"
3. The menu will be displayed when a mouse over event is triggered by users over the element

**Comment by konekoya** [comment]
cc @eechih

**Comment by eechih** [comment]
Thanks @konekoya
