### ISSUE TITLE
Gradle version too old may cause strange problem during the build

### ISSUE THREAD

**Issue by vitojeng** [oharastream/ohara#4005]
There are possibility cause some "strange issue" during gradle build if gradle version too old.
Does there have a graceful solution for this?

If not, maybe we add **jenkins gradle version** value into **gradle.properties** and display this gradle version when gradle execution to hint user?

For example: 
```text
$ gradle clean build -x test -PskipManager
Hint: Your gradle verion is 5.4.2 and Ohara gradle version is 5.6.3
----------------------------------------------------------------
> Task :ohara-shabondi:compileScala
Pruning sources from previous analysis, due to incompatible CompileSetup.
<====---------> 34% EXECUTING [5s]
> :ohara-shabondi:compileScala
:    :    :
```

**Comment by chia7712** [comment]
It seems to me the gradle wrapper is more suitable for this issue.

**Comment by vitojeng** [comment]
> It seems to me the gradle wrapper is more suitable for this issue.

We can add gradle wrapper for sure, this is a good choice.
But how about if user still use `gradle` rather than `gradlew` just forgot or didn't realize ?

**Comment by chia7712** [comment]
> But how about if user still use gradle rather than gradlew just forgot or didn't realize ?

Users should NOT use gradle instead of gradlew if the later is supported formally. Also, the build command in our document should use gradlew rather than gradle.

**Comment by jackyoh** [comment]
不太確定像是 Intellij IDE 的編輯器是否能用 gradlew，因為使用者將程式碼 import 到 IDE 上執行時也會進行 gradle build code 的動作，版本不相容也有可能會 build 失敗。

**Comment by chia7712** [comment]
> 不太確定像是 Intellij IDE 的編輯器是否能用 gradlew，因為使用者將程式碼 import 到 IDE 上執行時也會進行 gradle build code 的動作，版本不相容也有可能會 build 失敗。

the priority of gradlew is the highest by default.

**Comment by chia7712** [comment]
![註解 2020-02-12 110838](https://user-images.githubusercontent.com/6234750/74299568-0a2f8980-4d88-11ea-88af-d95912160010.jpg)

**Comment by jackyoh** [comment]
了解，等 code merge 進去之後。我來修改 IDE 的設定
