### ISSUE TITLE
[Manager] Shared topic is not aligned properly with the rest of items in the Toolbox

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#4020]
As the snapshot, the topic name seems to be aligned left, which may be a little weird.

![image](https://user-images.githubusercontent.com/8088616/74395212-b2f1ed80-4e49-11ea-9f5d-6c919f845462.png)

/cc @wu87988622 @konekoya

**Comment by konekoya** [comment]
@saivirtue Thanks for reporting. Will take a look :)
