### ISSUE TITLE
JsonRefiner need check required key when definition is internal

### ISSUE THREAD

**Issue by vitojeng** [oharastream/ohara#4022]
Currently, JsonRefiner will ignore required key validation if definition is internal.
JsonRefiner need check required key whether definition is internal or not.

**Comment by vitojeng** [comment]
ping @oharastream/backend

**Comment by vitojeng** [comment]
I guess that it is a breaking change.

**Comment by chia7712** [comment]
The internal key is always ignored by frontend. By contrast, it is defined by backend so it always fails if json refiner tries to "check" the existence of the internal and required key.

**Comment by vitojeng** [comment]
So...It seems I need add this checking at somewhere by myself

**Comment by chia7712** [comment]
> So...It seems I need add this checking at somewhere by myself

Could you share the use case with me? The "internal" key means you don't want to anyone to "tocuh" it since you control it totally.

**Comment by vitojeng** [comment]
In Shabondi, there have a definition for "server class".

This definition must provide from frontend **developer** but not used by user.
This definition is both required and internal(not-display)

**Comment by chia7712** [comment]
> developer but not used by user.

our APIs does NOT distinguish "frontend developer" and "user". Or both of them are users to APIs.

It seems to me "server class" should be a public field and it has recommendedValues.

**Comment by vitojeng** [comment]
> It seems to me "server class" should be a public field and it has recommendedValues.

yes, it have recommendedValues. But I don't think this should be visible.

**Comment by chia7712** [comment]
> But I don't think it should be visible.

it is NOT "visiable" to which one? Be a backend developers, the field is "configured" by request, right? So it must be visible to any APIs users.

For another, it is NOT backend developers' business if you don't want to make it "visible" to UI user.

**Comment by vitojeng** [comment]
> it is NOT backend developers' business if you don't want to make it "visible" to UI user.

Sorry about I cannot agree with you.  :)
It should be depend on design, not frontend or backend person.
We have "internal" definition when we not want to display this field.

Shabondi provide only two server classes and not provide any custom mechanism to user to extend new server class. This is very different with connector or steam.

In my design, I cannot find any reason we need to make it "public" and "configurable" through the view. This case more like an "internal" field and it is also a required field.

**Comment by vitojeng** [comment]
> In my design, I cannot find any reason we need to make it "public" and "configurable" through the view. This case more like an "internal" field and it is also a required field.

This just my personal idea. BTW, I am fine with make this field "public". :)

**Comment by chia7712** [comment]
>It should be depend on design, not frontend or backend person.
We have "internal" definition when we not want to display this field.

the "internal" is NOT equal to "non-visible". UI decides to NOT show the internal field to UI user. For example, UI is able to show the "internal" to user. The principle to our APIs is that the internal fields are configured by backend. Both users and developers CAN'T touch it.

**Comment by chia7712** [comment]
> In my design, I cannot find any reason we need to make it "public" and "configurable" through the view. This case more like an "internal" field and it is also a required field.

We expect user to pick up one of case (shabondi source and shadondi sink) to run, right? The case to me is equal to pick up a "class" to run. We can throw exception if user input a nonexistent case. Those rules are equal to conenctor and stream.

**Comment by vitojeng** [comment]
Ohara expose connector or stream "class" to user to run because we allow user to write their own connector or stream. 

For Shabondi, we not allow user develop their own Shabondi "class". User should not need to care how Shabondi implement or which server class should be. Further more, once expose the Shabondi server class, this will limit Shabondi's development in the future because we cannot change the server class name anymore. For this case, we should protect server class information to not expose.

**Comment by chia7712** [comment]
首先，更改class名稱會破壞的東西很多，因此需要一個機制來處理，絕非你提到的這麼簡單。

我一直想講的重點是，做系統非做案子，不能想開特例就開特例，這只是不斷在養技術債。一個很殘酷的案例就是之前的stream設計，跟前段綁死死，隨便一個更動就爆炸，還無法享有ohara框架下帶來的一堆好處。最後幾乎把stream程式碼砍掉重寫。簡而言之。為了要程式不斷變大的狀況下能提供更多服務，我們需要訂定一個「一致」的流程來給所有服務，而非為了誰在規格上不斷的開特例。

例如Definitions的存在就是一個規格，他作為「服務」所有可參數的物件，而身為開發者我們要避免的是為了其中一個物件開特例然後產生很多彆手彆腳的代碼。

internel的性質就是作為伺服器端掌控的參數，前端要如何「顯示」這是前段的事情。這就是組織架構的分工，責任清楚不互相猜測。

至於為何我說要訂定class -> definitions的概念？因為這個大帽子（規格）可以涵蓋我們所有服務的行為，透過這個大帽子我們可以對外（使用者或前段）提供一致的體驗。

跟我想像一下，對任何人而言要使用ohara上的任何服務，都可以正規成下面流程

1. 查詢有哪些class以及對應的definitions
1. 根據definitions去填寫參數或是建立需要依賴的物件（回到上述步驟）
1. 儲存設定
1. 啟動

Shabondi的class只有兩個所以就要開特規嗎？答案絕對不是yes，更適合且成熟的做法是套用到一致的規則下。

**Comment by vitojeng** [comment]
首先, 澄清一個點, 我沒有想要開什麼特規, 只是在想要怎麼做比較會好罷了. 沒有什麼設計是絕對的好或絕對不好, 都是在不同角度裡做出選擇罷了.

目前在 Shabondi 這段面臨的不是只有 internal 的情形而己, 面對許多不同的"特例", 我花了不少去瞭解 SettingDef, JsonRefiner...等等的內部實作, 在想怎配合架構, 要怎麼加需要邏輯進去才符合 "架構", 又能滿足這些 "特例" 的需要. 不是不明究理地就隨便丟出一個 "感覺" 來說.

> internel的性質就是作為伺服器端掌控的參數，前端要如何「顯示」這是前段的事情。這就是組織架構的分工，責任清楚不互相猜測。

我在這個 issue 提出的情形是 internal 不能變成 necessary, 在後端無法用運用現有的架構去防範. 只能某處另外塞入額外的邏輯去擋, 這個跟前端怎麼呈現無直接關係.

另外, 請問 internal 當初設計的用意是什麼? 為什麼需要加入, 難道不是讓 SettingDef 有機會不顯出在畫面上嗎? 若我弄錯, 麻煩告知一下有什麼方式可以做到這點?

目前前端的現況是照 SettingDef 的值來決定是否呈現, 因此雖然表面上是說前端負責呈現, 因此從程式碼層來來看, 實質上 "要不要" 呈現某個 SettingDef, 其決定權己經是交到後端去.

**Comment by chia7712** [comment]
> 另外, 請問 internal 當初設計的用意是什麼? 為什麼需要加入, 難道不是讓 SettingDef 有機會不顯出在畫面上嗎? 若我弄錯, 麻煩告知一下有什麼方式可以做到這點?

internal的用意是，有些參數是元件所需，但是提供者是伺服器端而非使用者，也就是
1. 元件可以使用該參數
1. 伺服器端要負責為該參數產生值
1. 使用者可以看到該參數，但無法更改

舉個例子，connector的serializer就是internal，因為目前序列化還不開放自訂，但元件需要知道是用哪種序列化，而伺服器會給定序列化的實作，使用者可以看到目前的序列化實作，但不能更動

> 目前前端的現況是照 SettingDef 的值來決定是否呈現, 因此雖然表面上是說前端負責呈現, 因此從程式碼層來來看, 實質上 "要不要" 呈現某個 SettingDef, 其決定權己經是交到後端去.

如上面提到，internal的意思是該參數是內部(後端)所給定，前端可以"顯示"但提醒說這個值是內部給定，或者乾脆不顯示反正後端會處理，這就是UI可以自行決定如何呈現。

**Comment by vitojeng** [comment]
我想問的是, 需要在 UI 不顯示一個 SettingDef, 現在要怎麼做?
現在我知道的只有使用 internal 的方式還有其他的嗎? 若沒有, 那麼這個需要也只能用 internal.

**Comment by chia7712** [comment]
> 我想問的是, 需要在 UI 不顯示一個 SettingDef, 現在要怎麼做?

如前面提到，definition沒有讓UI不顯示的規範。頂多頂多只能說，現在UI在處理internal definition目前是「不顯示」。

如果你真的很想控制UI顯示不顯示，那麼正確的做法是要有一個新的標籤來說明這個參數不該顯示在UI上面。

ping @konekoya @eechih @saivirtue @wu87988622

**Comment by chia7712** [comment]
另外一個需要釐清的問題是，是什麼情況需要讓一個參數從UI上消失，然後你又要用definition去規範？對我而言這是矛盾的狀況，因為你一方面想要它消失，卻又希望透過definition去暴露它？那為何不乾脆不要寫該參數的definiton？

**Comment by vitojeng** [comment]
在 Web UI, 使用 form 來呈現時, 可以決定那些 input field 需要 hidden, 這是 html 的規範.
https://www.w3schools.com/tags/att_input_type_hidden.asp

有許多參數是暴露給 WebUI 開發者, 但不希望曝露給使用者(操作畫面的使用者). 一直都有這種需要, 也有這種做法.

**Comment by chia7712** [comment]
> 在 Web UI, 使用 form 來呈現時, 可以決定那些 input field 需要 hidden, 這是 html 的規範.
https://www.w3schools.com/tags/att_input_type_hidden.asp


等下，怎麼突然話題跑到html了? 我們應該是在討論definition吧?

> 有許多參數是暴露給 WebUI 開發者, 但不希望曝露給使用者(操作畫面的使用者). 一直都有這種需要, 也有這種做法.

definition面對的backend開發者，為何又突然講WebUI 開發者? 如我前面提到的事情，對definition而言我們沒有去區分"WebUI 開發者"或"使用者"

**Comment by vitojeng** [comment]
OharaManager(WebUI) 目前也是 definition 的用戶, 因此我只是舉個例子, 說明這種需求其實很常見.

> 對definition而言我們沒有去區分"WebUI 開發者"或"使用者"

這點我知道

**Comment by chia7712** [comment]
@vitojeng 如剛剛討論的結果，再麻煩你看看是否還有要討論的~
