### ISSUE TITLE
Drop JDK 8 support and migrate to JDK 11

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#4026]
jdk 11 is the latest LTS release and the projects we are tracing are migrating to jdk 11. Ohara leverages the container technique so the run-time jdk is NOT problem to us. JDK 11 is backward-compatible to jdk 8 so the existent binary/source code should work well.

Kafka, Hadoop and HBase are on the road to jdk 11. Why not Ohara?

**Comment by chia7712** [comment]
ping @jackyoh @vitojeng @saivirtue @eechih

**Comment by saivirtue** [comment]
Any benefit for Ohara of migrating jdk11?

**Comment by chia7712** [comment]
> Any benefit of migrating jdk11 for Ohara?

We all like the newest technique :) 

the most important thing is jdk 8 support is going to end and most modern java projects "have to" migrate to jdk 11. Ohara is an new project and we don't need to care for the compatibility now so the migration is NOT a big issue to us. It means almost zero cost to Ohara :)

see https://docs.microsoft.com/zh-tw/azure/java/jdk/reasons-to-move-to-java-11 for other benefit

**Comment by jackyoh** [comment]
+1。 因為 jdk 8 出來已經 6 年有點久了，有可能會終止維護，所以我覺得有升級的必要。

但不太確定目前 ohara 使用的 library jdk 11 是否都有 support

**Comment by chia7712** [comment]
> 但不太確定目前 ohara 使用的 library jdk 11 是否都有 support

java的優點(也是負擔)就是在相容性上做得很好，因此這點我們應該不太需要擔心。不過一些deprecated APIs應該還是會遇到，這個在開議題清一清就好

**Comment by vitojeng** [comment]
+1

**Comment by vitojeng** [comment]
> Any benefit of migrating jdk11 for Ohara?

For me, the most important feature is container integration:
https://www.docker.com/blog/improved-docker-container-integration-with-java-10/

**Comment by chia7712** [comment]
> For me, the most important feature is container integration:

It had been backport to jdk 8. (https://blogs.oracle.com/java-platform-group/java-se-support-for-docker-cpu-and-memory-limits)
