### ISSUE TITLE
Cannot save the connector's TABLE data

### ISSUE THREAD

**Issue by eechih** [oharastream/ohara#4064]
**Describe the bug**
<img width="968" alt="Screen Shot 2020-02-19 at 11 08 07 AM" src="https://user-images.githubusercontent.com/703126/74798789-b5e95400-5309-11ea-9cb5-669ef5c3a600.png">
<img width="962" alt="Screen Shot 2020-02-19 at 11 08 27 AM" src="https://user-images.githubusercontent.com/703126/74798822-d0233200-5309-11ea-8027-e6ab801711b1.png">

**Comment by chia7712** [comment]
the "tableData" is illegal since its value is "object". The supported type is "string"

**Comment by eechih** [comment]
> the "tableData" is illegal since its value is "object". The supported type is "string"

@chia7712 我想再確認一下，前端應該要將 tableData 轉成 String 的型態，對否？

**Comment by chia7712** [comment]
> 前端應該要將 tableData 轉成 String 的型態，對否？

yep

for another, what is "tableData"?

**Comment by wu87988622** [comment]
I will fix this issue

**Comment by eechih** [comment]
> for another, what is "tableData"?

@chia7712  ㄛ ㄛ ~ 這是前端的 UI 顯示所需的資料。我們會將這類多餘的資料過濾掉，不會存到後端。

> I will fix this issue

Thanks @wu87988622

**Comment by wu87988622** [comment]
Ref #4105
