### ISSUE TITLE
[Question] Naming of Type.PORT?

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#4078]
From the documentation:
> **Type.PORT**
Port is a common property to connector. For example, the ftp connector needs port used to connect to source/target ftp server. Inputting a illegal port can destroy connector easily. Declaring your type of value to Port involve a check that only the port which is small than 65536 and bigger than zero can be accepted. Other port value will be rejected in starting connector.

> **Type.BINDING_PORT**
This type is similar to Type.PORT except that the value mapped to BINDING_PORT has a extra check to the availability on the target nodes. For example, you define value 5555 as a BINDING_PORT, and you will get a exception when you try to deploy your code on the node which is using port 5555 as well. The legal value of binding port is between [0, 65535].

We have two different types which could be used to define "port". However, for a user who want to define a "port", the situation should be:
1. assign a port that will be bound in the running node.
2. assign a port that is used in a remote machine.

For situation 1, we should encourage our users to use "BINDING_PORT" since it has an extra checking in backend.
and for situation 2, we don't have to check the connection, the only possible type should be PORT.
Should we change the naming from **PORT** to **REMOTE_PORT**?

**Comment by chia7712** [comment]
> Should we change the naming from PORT to REMOTE_PORT?

+1

**Comment by chia7712** [comment]
@saivirtue I feel this issue needs to touch both backend and fronent code. Could you take over this one? Also, this issue should be toward both 0.9 and 0.10 for consistency.

**Comment by saivirtue** [comment]
Sure.
But I need more feedback from other guys :(

**Comment by chia7712** [comment]
> But I need more feedback from other guys :(

ping @vitojeng @jackyoh @eechih @konekoya @wu87988622

**Comment by jackyoh** [comment]
+1, good idea. 可以明確的區分 port 的類型，避免 confusion

**Comment by eechih** [comment]
+1 把 PORT 換成 RRMOTE_PORT 可以避免使用者很直覺（想都不想）的使用，在名稱上做的區別，讓使用者在選擇時會猶豫一下，好好的去看文件。

**Comment by konekoya** [comment]
+1 :)

**Comment by chia7712** [comment]
no objection. the vote passes.

@saivirtue Please activate this issue :)

**Comment by saivirtue** [comment]
New issue in #4110
