### ISSUE TITLE
[Question]About Steams upload problem

### ISSUE THREAD

**Issue by chuntsekevin** [oharastream/ohara#4083]
Hi,
I update my 0.9.0-SNAPSHOT images today and i got the streams upload problem.
When i success upload my app but the UI toolbox won't show, i can't use streams in pipeline.

![2](https://user-images.githubusercontent.com/60953697/74997047-2fab4a00-5490-11ea-97f1-f9f5ff79aa98.PNG)

![3](https://user-images.githubusercontent.com/60953697/74997100-4c478200-5490-11ea-883a-4341409d3147.PNG)

![1](https://user-images.githubusercontent.com/60953697/74997111-523d6300-5490-11ea-938e-032cf1d3a0cc.PNG)

Thanks!

**Comment by saivirtue** [comment]
Could you provide the source code of your stream jar (`app1.jar`, `app2.jar`)?

**Comment by chuntsekevin** [comment]
okay i got it ! Thanks
