### ISSUE TITLE
[Manager] Un-added shared topic will be removed after reload page

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#4087]
![image](https://user-images.githubusercontent.com/8088616/75011977-ecff6700-54bb-11ea-8b2b-7ce26539d738.png)

/cc @wu87988622 @konekoya 

- [x] 0.10 #4128
- [x] 0.9 #4130

**Comment by konekoya** [comment]
@wu87988622 We should also consider backporting this to 0.9 if the bug also exists on 0.9

/cc @chia7712

**Comment by wu87988622** [comment]
I will fix this bug~
