### ISSUE TITLE
Worker exception: ERROR: Plugin class loader for connector: 'x.x.x.x' was not found

### ISSUE THREAD

**Issue by vitojeng** [oharastream/ohara#4094]
worker version:
![screenshot 20](https://user-images.githubusercontent.com/475186/75023468-cf89c780-54d2-11ea-9c31-220514723211.jpg)

worker exception:
![screenshot 21](https://user-images.githubusercontent.com/475186/75023603-0e1f8200-54d3-11ea-9b92-7eea35c1cacf.jpg)

**Comment by jackyoh** [comment]
Please refer:
https://github.com/apache/kafka/pull/7964

**Comment by vitojeng** [comment]
I think we can ignore this error.
Thanks @jackyoh.
