### ISSUE TITLE
[Manager] Tweak the same name warning message if users attempt to create a connector, stream or topic where its name is already taken

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#4097]
- [x] 0.9 (#4137)
- [x] 0.10 (#4136)

**Comment by saivirtue** [comment]
Thanks @konekoya ! ❤️

**Comment by vitojeng** [comment]
Thanks @konekoya !
This could be reduce the user misunderstanding. It would be better back port to 0.9.x, if not, also ok.  ping @chia7712 WDYT?

**Comment by chia7712** [comment]
+1 to backport

**Comment by konekoya** [comment]
As per our discssion, we will only tweak the warning message (via snackbar) so it better tells users why they cannot add a same name connector/stream/topic into the pipeline. And I will update the description.

/cc @oharastream/frontend
