### ISSUE TITLE
Cannot control the stream component after stopping

### ISSUE THREAD

**Issue by chuntsekevin** [oharastream/ohara#4101]
When Pipeline running, streams individual component Stop will cause this stream can't control 

![image](https://user-images.githubusercontent.com/60953697/75126156-9f6d3f00-56f3-11ea-86df-2a5e4d6925cc.png)

- [x] for 0.10 (#4104)
- [x] backport to 0.9 (#4106)

**Comment by saivirtue** [comment]
Strange behavior...Let me take a look

**Comment by saivirtue** [comment]
Thanks for reporting, it's a bug indeed :)

**Comment by vitojeng** [comment]
Is it similar with https://github.com/oharastream/ohara/issues/4099#issuecomment-590154794 ?

**Comment by saivirtue** [comment]
> Is it similar with #4099 (comment) ?

Not exactly.
The problem with this issue is the menu buttons were disabled after stopping, but in #4099, it is the exception not be handled normally.
I will update the reason in #4099 later.

**Comment by saivirtue** [comment]
/cc @chuntsekevin 
Please help me to verify this, thanks :)

**Comment by chuntsekevin** [comment]
@saivirtue everything works perfectly ! thanks
