### ISSUE TITLE
OBJECT_KEYS and TABLE save has some strange behavior

### ISSUE THREAD

**Issue by wu87988622** [oharastream/ohara#4105]
- [x] pick tableKeys with settingDefinitions 
- [x] change keyWord **topicKeys**, **to** and **from** to **OBJECT_KEYS** and reference is **TOPIC**
- [x] put has **OBJECT_KEYS** value need update link (remove, change link)

- [x] 0.10 #4103 
- [x] 0.9 #4129

**Comment by chia7712** [comment]
>  change keyWord topicKeys, to and from to OBJECT_KEYS and reference is TOPIC

the type of "topicKeys" (connector), "to" (stream) and "from" (stream) are "OBJECT_KEYS". Do I misunderstand anything?

**Comment by wu87988622** [comment]
> > change keyWord topicKeys, to and from to OBJECT_KEYS and reference is TOPIC
> 
> the type of "topicKeys" (connector), "to" (stream) and "from" (stream) are "OBJECT_KEYS". Do I misunderstand anything?

原本ui 是指使用key來判斷 現在改為用valueType來判斷
