### ISSUE TITLE
Failed to inspect topic Info when open new window

### ISSUE THREAD

**Issue by vitojeng** [oharastream/ohara#4109]
**Description**

Developer tools -> "TOPICS"

Fetch topic data(ex: T1 topic) in the panel works fine, but have error message if open in a new window.

> Fetch topic works fine in panel:

![screenshot 27](https://user-images.githubusercontent.com/475186/75127839-51106e00-56fc-11ea-8e04-1da3eb73350f.jpg)

> open in a new window:

![screenshot 28](https://user-images.githubusercontent.com/475186/75127923-a8aed980-56fc-11ea-9113-5b9c54c406ba.jpg)

Error message:
![screenshot 25](https://user-images.githubusercontent.com/475186/75127797-17d7fe00-56fc-11ea-95dd-e1c9cafb4394.jpg)

 - [x] for 0.10 (#4193)
- [x] backport to 0.9 (#4194)

**Comment by chuntsekevin** [comment]
Hi, 
I just found out broker and worker log can't open in a new window . 

![image](https://user-images.githubusercontent.com/60953697/75409619-3afcea80-5954-11ea-9f49-763d6cda291c.png)

![image](https://user-images.githubusercontent.com/60953697/75409534-ee191400-5953-11ea-8c91-d8f0e3b1d796.png)
![image](https://user-images.githubusercontent.com/60953697/75409560-06892e80-5954-11ea-8a1c-1861cff73ba6.png)

Thanks!

**Comment by saivirtue** [comment]
Thanks for reporting, I will look into these two problems.

**Comment by chia7712** [comment]
thanks for this fixing !
