### ISSUE TITLE
Create connector will keeps generating popup warning message : [Service Unavailable]

### ISSUE THREAD

**Issue by HarryChiang143** [oharastream/ohara#411]
Ohara Version : 0.2.0
When i creating a connector on pipeline page, it will  popup the  [Service Unavailable] message again and again ,  until I press the test connection . 
![螢幕快照 2019-03-11 上午10 42 39](https://user-images.githubusercontent.com/46185836/54097762-8a1cd900-43ec-11e9-80cf-beca05501ab7.png)

**Comment by konekoya** [comment]
This is probably due to the slow HTTP connection. We currently don't have a solution for this in v0.2. But this will be fixed in v0.3! Thanks for reporting :)

**Comment by HarryChiang143** [comment]
This issue already fixed on v0.3.
