### ISSUE TITLE
檢查 connector 的 metrics 是否正確

### ISSUE THREAD

**Issue by jackyoh** [oharastream/ohara#4112]
目前在執行 performance 測試程式時，發現 input data 的速度和 connector 的速度差距很大。數據如下：
Input Data

Duration | messageNumber | messagesSize
|-- | -- | --
|302 | 8088000 | 2660952000|
|602 | 16028000 | 5273212000|
|934 | 23464000 | 7719656000|
|1538 | 38212000 | 12571748000|
|2143 | 53152000 | 17487008000|
|2750 | 67928000 | 22348312000|
|3357 | 82562000 | 27162898000|
|3657 | 89774000 | 29535646000|

FTP Source Connector

duration | ignored.message.number(inPerSec) | ignored.message.size(inPerSec) | ignored.message.number | message.number(inPerSec) | message.size(inPerSec) | message.size | ignored.message.size | message.number
-- | -- | -- | -- | -- | -- | -- | -- | --
270 | 0 | 0 | 0 | 118.371 | 54096.444 | 14624000 | 0 | 32000
590 | 0 | 0 | 0 | 132.103 | 60371.619 | 35646000 | 0 | 78000
887 | 0 | 0 | 0 | 130.714 | 59736.475 | 53012000 | 0 | 116000
1186 | 0 | 0 | 0 | 128.106 | 58544.66 | 69464000 | 0 | 152000
1395 | 0 | 0 | 0 | 127.557 | 58293.824 | 81346000 | 0 | 178000
1781 | 0 | 0 | 0 | 120.118 | 54894.032 | 97798000 | 0 | 214000
2084 | 0 | 0 | 0 | 122.833 | 56134.856 | 116992000 | 0 | 256000
2678 | 0 | 0 | 0 | 118.737 | 54262.909 | 145326000 | 0 | 318000

所以需要來確認 connector 的 metrics 是否正確

**Comment by jackyoh** [comment]
目前執行 performance 測試程式的程式碼在 PR #4066

**Comment by chia7712** [comment]
@jackyoh 可否麻煩你安裝小資料 先確認一下"數字有正確"，如果數字有正確，那我們再來看是否是效能問題

**Comment by jackyoh** [comment]
OK， 我先把 input data 縮小，確認執行出來的資料是正確

**Comment by jackyoh** [comment]
使用大約 10 MB 的資料來測試，FTP Source 到 HDFS Sink 的部份，在 input data 的部份輸出如下

duration | messageNumber | messageSize
-- | -- | --
161 | 32000 | 10528000

總共為 3200 筆的資料，檔案的大小 10.04 MB，有到 FTP Server 確認資料確實為 32000 筆，另外總共有 16 個檔案，每個檔案為 660.1 KB 所以總共檔案大小約為 10 MB 左右，因此原始資料的統計應該沒有問題。

另外有到 FTP Source Connector 和 HDFS Sink Connector 的 metrics 確認資料筆數如下:
FTP Source Connector:

duration | ignored.message.number(inPerSec) | ignored.message.size(inPerSec) | ignored.message.number | message.number(inPerSec) | message.size(inPerSec) | message.size | ignored.message.size | message.number
-- | -- | -- | -- | -- | -- | -- | -- | --
10 | 0 | 0 | 0 | 3149.606 | 1440646.242 | 14624000 | 0 | 32000
8 | 0 | 0 | 0 | 2911.915 | 1332199.684 | 10968000 | 0 | 24000
2 | 0 | 0 | 0 | 1600.64 | 675036.928 | 914000 | 0 | 4000


HDFS Sink Connector:

duration | ignored.message.number(inPerSec) | ignored.message.size(inPerSec) | ignored.message.number | message.number(inPerSec) | message.size(inPerSec) | message.size | ignored.message.size | message.number |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
119 | 0 | 0 | 0 | 266.784 | 1654111.526 | 14624000 | 0 | 32000 |  
59 | 0 | 0 | 0 | 533.894 | 1654111.526 | 14624000 | 0 | 32000 |  
8 | 0 | 0 | 0 | 3619.5 | 1654111.526 | 14624000 | 0 | 32000 |  
6 | 0 | 0 | 0 | 544.723 | 222533.257 | 1355005 | 0 | 3319 |  

看起來在小資料的情況下執行 performance 測試程式，資料統計的結果應該是沒問題的

**Comment by chia7712** [comment]
> 看起來在小資料的情況下執行 performance 測試程式，資料統計的結果應該是沒問題的

可否換個connector再測試一次? 如果確認metrics的數字沒問題，那麻煩關閉此議題並且開另一個議題來探討效能

**Comment by jackyoh** [comment]
ok, 我用 jdbc source connector 接hdfs sink connector 測試看看

**Comment by jackyoh** [comment]
使用 JDBC Source Connector 到 HDFS Sink Connector 測試約 10 MB 的資料, input data 的結果如下：

Duration | messageNumber | messages
-- | -- | --
183 | 34000 | 10880000

messageSize 比上面 comment 較大的原因，是因為另外有寫入 timestamp 的資料，然後使用 oracle database 查詢資料筆數一樣是 34000 筆資料


JDBD Source Connector 和 HDFS Sink Connector 的 metrics 結果如下：

JDBC Source Connector


duration | ignored.message.number(inPerSec) | ignored.message.size(inPerSec) | ignored.message.number | message.number(inPerSec) | message.size(inPerSec) | message.size | ignored.message.size | message.number
-- | -- | -- | -- | -- | -- | -- | -- | --
4 | 0 | 0 | 0 | 6931.702 | 3924943.912 | 19244000 | 0 | 34000
0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0



HDFS Sink Connector

duration | ignored.message.number(inPerSec) | ignored.message.size(inPerSec) | ignored.message.number | message.number(inPerSec) | message.size(inPerSec) | message.size | ignored.message.size | message.number
-- | -- | -- | -- | -- | -- | -- | -- | --
59 | 0 | 0 | 0 | 566.827 | 1912542.238 | 19244000 | 0 | 34000
10 | 0 | 0 | 0 | 3379.05 | 1912542.238 | 19244000 | 0 | 34000
7 | 0 | 0 | 0 | 758.249 | 464643.082 | 3388642 | 0 | 5492



以上的結果看起來不是 input data 和 connector metrics 統計資料的問題，有可能是效能的問題。我把此議題關閉，另外開一個關於效能的議題
