### ISSUE TITLE
The pipeline not working when i add streamapp 

### ISSUE THREAD

**Issue by HarryChiang143** [oharastream/ohara#412]
I create a { ftp source-topic1-streamapp-topic2-ftp sink } pipeline , then start the operate , it seems not working on stream app.
the stream app show status = stopped
and i check my output folder was empty.
![螢幕快照 2019-03-11 上午11 12 32](https://user-images.githubusercontent.com/46185836/54098313-13cda600-43ef-11e9-8e05-4f42d2dff29c.png)

and i restart the streamapp , it shows me [Cannot complete your action,please check your stream app settings]
the stream app show status = exited

![螢幕快照 2019-03-11 上午11 20 55](https://user-images.githubusercontent.com/46185836/54098493-d289c600-43ef-11e9-838a-9f9a9591f388.png)

My test streamapp jar : 
ohara/ohara-streams/src/test/java/com/island/ohara/streams/SimpleApplicationForOharaEnv.java

but when i choose { ftp source-topic3-ftp sink } pipeline , it work fine.
![螢幕快照 2019-03-11 上午11 23 06](https://user-images.githubusercontent.com/46185836/54098556-0fee5380-43f0-11e9-805f-e5981c600b2c.png)

**Comment by saivirtue** [comment]
The sample code `SimpleApplicationForOharaEnv.java` has some requirements
1. you need to assign the following format ("index, name, age") topic
2. your docker image should be the latest release version (oharastream/streamapp:0.2.0)

when starting the streamapp, there will run a container in one of the worker cluster node ; maybe next time you could post the container logs when running fail ?

**Comment by HarryChiang143** [comment]
Find the root cause.
Cause the streamapp use configurator's hostname to generate connection info(the default hostname are 0.0.0.0) in v0.2.0, if use default , system will through connect time out exception from configurator.

so when start configurator u needed add hostname like --hostname ${host}  

But i think the streamapp still show error on WebUI when start failed, that the user knows which component run failed.

**Comment by saivirtue** [comment]
Hi @HarryChiang143 
Since streamApp has a lot of features and fixes after v0.2 (current latest version is `v0.5`), could you help to verify if the problem was solved?

**Comment by chia7712** [comment]
the related version is inactive.

@HarryChiang143 feel free to open new issue if you encounter same error on the latest release
