### ISSUE TITLE
[Manager] Metrics data update resets Toolbox's scroll position

### ISSUE THREAD

**Issue by chuntsekevin** [oharastream/ohara#4122]
When metrics is on, toolbox will rest its scroll position every 5 seconds. If user doesn't choose  connector within the time, the scroll position will be reset.

![image](https://user-images.githubusercontent.com/60953697/75143076-563ae080-572f-11ea-8f62-82c955fb7e4b.png)

- [x] 0.9 #4163 
- [x] 0.10 #4160

**Comment by konekoya** [comment]
Thanks for reporting, I will look into this
