### ISSUE TITLE
[Manager] Tweak Paper's zoom levels

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#4123]
We currently allow users to zoom with the zoom in/out button ranging from 1, 3, 6, 12, 25, 50, 100, 200. And from the dropdown: 50, 100 and 200.

We will tweak this range to 25, 50, 67, 75, 80, 90, 100, 110, 125, 150. And from the dropdown: 50, 75, 100, 150.

/cc @eechih

- [x] 0.9 (#4189)
- [x] 0.10 (#4188)

**Comment by eechih** [comment]
Thanks @konekoya

**Comment by chia7712** [comment]
all PRs are merged. thanks!
