### ISSUE TITLE
Performance test 在 connector 設定多個 tasks，metrics data 會被覆寫

### ISSUE THREAD

**Issue by jackyoh** [oharastream/ohara#4125]
根據 issue #4119 的討論，connector 在執行多個 tasks 的情況下 metrics 的取得會被覆寫，造成 metrics 的資料錯誤 。

- [x] 0.9.x #4239
- [x] 0.10.0 #4212

**Comment by chia7712** [comment]
@jackyoh this is a bug so could you backport to 0.9.x ?

**Comment by jackyoh** [comment]
OK, I am going to backport to 0.9.x

**Comment by chia7712** [comment]
nice improvement!

**Comment by chia7712** [comment]
reopen since the QA for 0.10 is not completed

**Comment by jackyoh** [comment]
0.10 的測試都跑過了

**Comment by chia7712** [comment]
@jackyoh thanks for this contributions
