### ISSUE TITLE
Ftp source connector create incorrect completed directory after start

### ISSUE THREAD

**Issue by vitojeng** [oharastream/ohara#4138]
Ftp source connector folder settings:
* **input folder**: /vito/source1
* **complete folder**: /vito/source1/completed
* **error folder**: /vito/source1/error

After start ftp source connector, the result is all files in the **/vito/source1/completed** folder moved to **/vito/source1/error/completed**

1. - [x] for 0.10.0 (#4174)
1. - [x] for 0.9.0 (#4186)

**Comment by chia7712** [comment]
seems ftp connector fails to read the folder "/vito/source1/completed" and it just move the whole folder to error folder "/vito/source1/error"

**Comment by jackyoh** [comment]
是否因為目前的 ftp source connector, 設定 input 的資料夾下面只能有檔案，不能有其他資料夾。然後就把 complete 移到 error 的資料夾裡了

**Comment by vitojeng** [comment]
補充一下, 以下設定一樣會類似情形, 但又不完全一樣:
* input folder: /vito/source1/files
* complete folder: /vito/source1/completed
* error folder: /vito/source1/error

執行成功, 結果畫面:
![screenshot 32](https://user-images.githubusercontent.com/475186/75223580-c013c280-57e1-11ea-9d1b-8506f66aae53.jpg)

檔案自 /vito/source1/files 移動到 /vito/source1/error

**Comment by chia7712** [comment]
complete目錄下的檔案有跟著過去嗎

**Comment by jackyoh** [comment]
complete folder 會一起到 error folder 下面

**Comment by vitojeng** [comment]
> complete目錄下的檔案有跟著過去嗎

completed 目錄內原本就沒有放檔案, 所以不太確定
