### ISSUE TITLE
Failed to inspect topic info after delete topic

### ISSUE THREAD

**Issue by vitojeng** [oharastream/ohara#4139]
**Describe the bug**
Failed to inspect topic info after delete "pipeline-only" topic.

**To Reproduce**

1. Drag "Pipeline Only" to pipeline from Toolbox, topic T1 created.
2. Open Developer Tools and select "T1"
3. Close Developer Tools panel
4. Delete topic T1 in the pipeline
5. Open Developer Tools again, and message display following message: Failed to inspect topic T1 info

**Expected behavior**
Open Developer Tools again without any message

- [x] for 0.10 (#4154)
- [x] backport to 0.9 (#4161)

**Comment by chia7712** [comment]
Great job!

**Comment by vitojeng** [comment]
@saivirtue It look works fine. Thanks!
