### ISSUE TITLE
enable to change the default version of services used by Configurator image 

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#4144]
The default version of services used by Configurator image is same to "code version". We need a way to change the default version so our Manager can get IT on specific "default version".

1. - [x] for 0.10.0 (#4145)
1. - [x] for 0.9.0

**Comment by chia7712** [comment]
FYI @jackyoh @saivirtue

**Comment by saivirtue** [comment]
Thanks for helping!

**Comment by jackyoh** [comment]
目前我的想法是修改 build.yml 多一個 OHARA_VERSION 的 args, OHARA_VERSION: ${TAG:-0.10.0-SNAPSHOT}, 然後在修改每一個 dockerfile 有 gradlew build 的部份，都加上 -Pohara.version=$OHARA_VERSION, 這樣 build 出來的 version 應該就可以從外部指定。

**Comment by chia7712** [comment]
> 目前我的想法是修改 build.yml 多一個 OHARA_VERSION 的 args, OHARA_VERSION: ${TAG:-0.10.0-SNAPSHOT}, 然後在修改每一個 dockerfile 有 gradlew build 的部份，都加上 -Pohara.version=$OHARA_VERSION, 這樣 build 出來的 version 應該就可以從外部指定。

yep
