### ISSUE TITLE
[Manager] Multiple pipeline running problem

### ISSUE THREAD

**Issue by chuntsekevin** [oharastream/ohara#4148]
If i got two pipeline (p1and p2), p1 pipeline is running with a Perf-connector and a Topic. Select p2 pipeline will keep showing failed to stop topic error. p1 pipeline will disappear.

![image](https://user-images.githubusercontent.com/60953697/75237782-eeea6280-57fa-11ea-845b-ec6350f01c38.png)

![image](https://user-images.githubusercontent.com/60953697/75237759-e1cd7380-57fa-11ea-9218-609a71d32c08.png)

![image](https://user-images.githubusercontent.com/60953697/75238012-543e5380-57fb-11ea-89af-d31039e94850.png)

- [x] 0.9 #4168 
- [x] 0.10 #4167

**Comment by wu87988622** [comment]
@chuntsekevin  Thanks  i will follow this issue

**Comment by chia7712** [comment]
thanks for contribution.
