### ISSUE TITLE
Delete a Paper element should be confirmed

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#4152]
We should confirm before deleting

<img width="1212" alt="Screen Shot 2020-02-24 at 9 52 43 AM" src="https://user-images.githubusercontent.com/703126/75124723-04249b80-56ec-11ea-8133-542454cb1c99.png">

_Originally posted by @eechih in https://github.com/oharastream/ohara/issues/3706#issuecomment-590145012_

- [ ] 0.9 (#4201)
- [x] 0.10 (#4171)

**Comment by chia7712** [comment]
great!!!
