### ISSUE TITLE
pipelinename應該換成拼法正確的字，或者加上編號的單字 (如pipeline0)

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#4153]
![註解 2020-02-24 130628](https://user-images.githubusercontent.com/6234750/75130251-4065f500-5708-11ea-8a1a-b05fbc9b9e27.jpg)

pipelinename應該換成拼法正確的字，或者加上編號的單字 (如pipeline0)

_Originally posted by @chia7712 in https://github.com/oharastream/ohara/issues/3706#issuecomment-590171209_

**Comment by konekoya** [comment]
@chia7712 I'm not sure if this should be backported to 0.9? What's idea about this?

**Comment by chia7712** [comment]
It does not burn out ohara so 0.10 only is fine

**Comment by konekoya** [comment]
> It does not burn out ohara so 0.10 only is fine

I will keep it as is. Thanks :)

**Comment by konekoya** [comment]
Since I'm fixing some bugs that are related to this. I've therefore fixed it in #4175 :)
