### ISSUE TITLE
[Manager] Disable certain action buttons for different Paper element state

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#4173]
#### Some background
The action that are available: Link, start, stop, config and remove. For "Sink" connector, the Link action is removed since it doesn't have this ability by default. And for "Topic", only Link and remove action are available. So while in different state, the allowed action and unhallowed actions are both list here for clarity:

#### Connector and stream:

Stop: all actions are allowed expect if the connector doesn't have a connection to other elements, then the start action is disabled

Pending: everything is disabled during this phase. But it usually takes just about a sec or so to complete this action.

Running: both delete and config actions are not allowed

Failed: both delete and config actions are not allowed

/cc @eechih let me know if there's anything that I missed :)

- [x] 0.9 (#4201)
- [x] 0.10 (#4197)

**Comment by eechih** [comment]
很完整的規則，感謝 @konekoya

**Comment by chia7712** [comment]
thanks!!!
