### ISSUE TITLE
[Manager] Failed to start topic when there are not enough brokers

### ISSUE THREAD

**Issue by eechih** [oharastream/ohara#4175]
**Failed to create shared topic**

**Describe the bug**
建立 Shared Topic 遇到啟動失敗後，沒有出現在 Toolbox 或 Topics，也無法再次建立（使用相同名稱）。

**To Reproduce**
1. 新增 Shared Topic (Name: sharedtopic11, Partitions: 3, Replication factor: 3)
2. 錯誤訊息 "Failed to start topic sharedtopic11"

<img width="962" alt="Screen Shot 2020-02-26 at 1 46 24 PM" src="https://user-images.githubusercontent.com/703126/75315945-0c710800-589f-11ea-9a0a-dd4d9fb30eca.png">

3. 再次新增 Shared Topic (Name: sharedtopic11, Partitions: 1, Replication factor: 1) 
4. 錯誤訊息 "Failed to create topic sharedtopic11"

<img width="959" alt="Screen Shot 2020-02-26 at 1 46 56 PM" src="https://user-images.githubusercontent.com/703126/75315965-14c94300-589f-11ea-977c-ba57c82dfb06.png">

5. 刷新頁面後，Topic sharedtopic11 有出現在 Toolbox 上，加到 Pipeline 裡，它的狀態是 stopped，沒有啟動的 Topic 是無法使用

<img width="857" alt="Screen Shot 2020-02-26 at 2 59 12 PM" src="https://user-images.githubusercontent.com/703126/75320187-24e62000-58a9-11ea-8cb3-5e6a7b0b887b.png">

_Originally posted by @eechih in https://github.com/oharastream/ohara/issues/3706#issuecomment-591253744_

- [x] 0.9 (#4234)
- [x] 0.10 (#4220)

**Comment by eechih** [comment]
ping @wu87988622 
Feel free to take over this issue :)

**Comment by konekoya** [comment]
@wu87988622 I'll be working on this :)

**Comment by chia7712** [comment]
thanks for this fixing!
