### ISSUE TITLE
[Manager] Topics not added to the Pipeline should not appear in the edit properties

### ISSUE THREAD

**Issue by eechih** [oharastream/ohara#4176]
**沒有加入到 Pipeline 的 Topic，不應該出現在選單中**

<img width="958" alt="Screen Shot 2020-02-26 at 3 06 50 PM" src="https://user-images.githubusercontent.com/703126/75320669-27954500-58aa-11ea-8918-5fb7cbd966a8.png">

_Originally posted by @eechih in https://github.com/oharastream/ohara/issues/3706#issuecomment-591274507_

- [x] 0.9 (#4215)
- [x] 0.10 (#4214)

**Comment by eechih** [comment]
ping @wu87988622 
Feel free to take over this issue :)

**Comment by konekoya** [comment]
@wu87988622 I will give this a shot as most of my bugs are fixed by now

**Comment by chia7712** [comment]
nice!
