### ISSUE TITLE
[Manager] Failed to save properties after adjusting number of tasks

### ISSUE THREAD

**Issue by eechih** [oharastream/ohara#4177]
調整 number of task 後，存檔會失敗

<img width="956" alt="Screen Shot 2020-02-26 at 3 26 16 PM" src="https://user-images.githubusercontent.com/703126/75322056-0aae4100-58ad-11ea-810f-746cafd06c2a.png">
<img width="950" alt="Screen Shot 2020-02-26 at 3 26 33 PM" src="https://user-images.githubusercontent.com/703126/75322080-16016c80-58ad-11ea-9b45-4d75df60f0e6.png">

_Originally posted by @eechih in https://github.com/oharastream/ohara/issues/3706#issuecomment-591281078_

**Comment by eechih** [comment]
ping @wu87988622 
Feel free to take over this issue :)

**Comment by wu87988622** [comment]
Thanks @saivirtue fix #4187
