### ISSUE TITLE
Modifying a Stream that has already started will cause its status to fail

### ISSUE THREAD

**Issue by eechih** [oharastream/ohara#4178]
啟動中的 Stream，如果 Save Change 會造成 Stream 的狀態變成 Failed

<img width="1373" alt="Screen Shot 2020-02-26 at 4 41 23 PM" src="https://user-images.githubusercontent.com/703126/75327206-ef483380-58b6-11ea-8acf-b54b6b729546.png">

_Originally posted by @eechih in https://github.com/oharastream/ohara/issues/3706#issuecomment-591306771_

**Comment by eechih** [comment]
ping @saivirtue 
Feel free to take over this issue :)

**Comment by saivirtue** [comment]
The "running" component should not able to change settings after #4173.
I think we can assign this issue to be duplicated?

**Comment by eechih** [comment]
@saivirtue 是的，UI 可以用 #4173 的方式避開，不過 API 的使用者是否會遇到相同的問題？

**Comment by eechih** [comment]
因為我在 0.9.0 版本的 demo 環境上，使用 master 版本的 ohara-ut-stream.jar，造成 Stream 啟動後的狀態由 Running 變成 Failed，因此UI 呈現 Failed 是合理的

感謝 @saivirtue 大力幫忙，釐清原因
