### ISSUE TITLE
身為使用者，我希望能加入 custom connector 到 pipeline

### ISSUE THREAD

**Issue by eechih** [oharastream/ohara#418]
### Criteria
- [x] 提供下拉式選單，顯示 custom connector 的 package + classname
- [x] 選單要能區分 source 或 sink
- [x] 官方及客製化 connector 會放在同一個選單
- [x] 允許加入一個（含）以上的 custom connector
- [x] pipeline 要顯示被加入的 custom connector 的 graph

**Comment by eechih** [comment]
### Criteria
- [x] plugin 要包含 custom connector 還有 dependencies
- [x] 允許上傳多個 plugin
- [x] 副檔名必須為 .jar
- [x] content-type 必須為 application/java-archive
- [x] 列表顯示已經上傳的 plugin

**Comment by eechih** [comment]
### Criteria
- [ ] 提供下拉式選單，顯示 custom connector 的 package + classname
- [ ] 選單要能區分 source 或 sink
- [ ] 官方及客製化 connector 會放在同一個選單
- [ ] 允許加入一個（含）以上的 custom connector
- [ ] pipeline 要顯示被加入的 custom connector 的 graph

**Comment by vitojeng** [comment]
Thanks @konekoya & @chia7712 for the story, well done!
