### ISSUE TITLE
[Manager] Failed to inspect stream log

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#4180]
When clicking the log tab and select the stream, the UI will break to show the data.

Thanks @chuntsekevin 

- [x] for 0.10 (#4182)
- [x] backport to 0.9 (#4183)

**Comment by chia7712** [comment]
thanks for this issue !

**Comment by saivirtue** [comment]
/cc @chuntsekevin
Please help me to verify if the issue still existed after the image updated, thanks.

**Comment by chuntsekevin** [comment]
@saivirtue ok!
