### ISSUE TITLE
[Manager] Prevent workspace creation when no nodes are selected

### ISSUE THREAD

**Issue by eechih** [oharastream/ohara#4181]
Manager, Create Workspace issue

When i create workspace name, press enter will start create workspace(haven't select node).

![image](https://user-images.githubusercontent.com/60953697/75404395-5f9d9600-5945-11ea-9c83-b15500e22355.png)

Originally posted by @chuntsekevin in #4179

- [x] v0.10.0 (#4184 )
- [x] backport to v0.9.0 (#4185 )

**Comment by chia7712** [comment]
thanks for contribution!
