### ISSUE TITLE
[Manager] Convert to correct type of settings in pipeline component

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#4187]
- [x] for 0.10 (#4200)
- [x] backport to 0.9 (#4202)

**Comment by vitojeng** [comment]
> This issue should be fixed in #4187, could you help me to verify after merged?

@eechih message from https://github.com/oharastream/ohara/issues/3706#issuecomment-590720769 😄

**Comment by eechih** [comment]
在 master 上，已經沒有這個問題了，謝謝 @saivirtue 

/cc @vitojeng

**Comment by chia7712** [comment]
@saivirtue thanks for this contirbution!
