### ISSUE TITLE
Added sinceSeconds setting to get docker container log for the test

### ISSUE THREAD

**Issue by jackyoh** [oharastream/ohara#4191]
目前在執行 performance 測試程式時在 after 的結尾會把 container 刪除掉之前會取得 container 的 log，如果 log 太大會發生 OutOfMemory 的問題，所以需要修改 ServiceKeyHolder.scala 呼叫 client.log 這一段，設定 sinceSeconds 的參數。

- [x] 0.9  #4198
- [x] 0.10.0 #4192

**Comment by chia7712** [comment]
Please add links to PRs

**Comment by jackyoh** [comment]
OK， 我來加上去，順便開 0.9 的 branch
