### ISSUE TITLE
Manager failed to get zookeeper log

### ISSUE THREAD

**Issue by chuntsekevin** [oharastream/ohara#4203]
Manager can't get zookeeper log 
![image](https://user-images.githubusercontent.com/60953697/75648596-82081a00-5c8b-11ea-93d9-44d7886606d7.png)

![image](https://user-images.githubusercontent.com/60953697/75648725-e75c0b00-5c8b-11ea-913f-d7297dd17a4d.png)

**Comment by saivirtue** [comment]
Could you provide reproducible steps of this bug?

**Comment by chuntsekevin** [comment]
I found how to reproduce this bug, Add a PerfSource connector with a topic. Start both in a while(10-15 min) will show the bug.
Also i recorded my  machine memory 
![image](https://user-images.githubusercontent.com/60953697/75653274-3f990a00-5c98-11ea-8584-0f79704d41ed.png)

**Comment by chuntsekevin** [comment]
@vitojeng Quickstart VM testing already done. About 5 min will happened the same issue. It seems that only happened on docker mode.

**Comment by vitojeng** [comment]
@chuntsekevin Just import QuickstartVM and download the latest docker image in my machine, it seems work fine. Can you try again with the latest docker image?

**Comment by chia7712** [comment]
@chuntsekevin It seems to me this bug is related to resource limit. Could you share the env to us?

**Comment by chuntsekevin** [comment]
@chia7712  My QuickStartVM env 
![image](https://user-images.githubusercontent.com/60953697/76071133-bb64c080-5fd0-11ea-8a31-8ac1ec419517.png)
![image](https://user-images.githubusercontent.com/60953697/76071277-f535c700-5fd0-11ea-9699-3b54d1049016.png)

**Comment by chia7712** [comment]
@chuntsekevin Does VM run on SSD? BTW, could you increase the number of cores and then try again?

**Comment by chuntsekevin** [comment]
@chia7712 @vitojeng  After increase cores and memory, still have this issue for me. But this time it happened until 15 min. 
![image](https://user-images.githubusercontent.com/60953697/76073895-565f9980-5fd5-11ea-82a0-8e000ff7d6d7.png)

**Comment by chia7712** [comment]
@chuntsekevin ssd or hds?

**Comment by chia7712** [comment]
Please share your env to us. Vm host
