### ISSUE TITLE
Minor: a vertical line in the TOPICS tab.

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#4204]
Minor: a vertical line in the TOPICS tab.

![screenshot 33](https://user-images.githubusercontent.com/475186/75226114-bfc9f600-57e6-11ea-8aa6-b1e00d766197.jpg)

_Originally posted by @vitojeng in https://github.com/oharastream/ohara/issues/3706#issuecomment-590731706_

- [x] for 0.10 (#4205)
- [x] backport 0.9 (#4206)

**Comment by chia7712** [comment]
thanks!
