### ISSUE TITLE
[Manager] Prevent Paper's dragging event interfering with Toolbox

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#4209]
Reported by @eechih 👍 

Normally, we capture the `pointermove` event and use `event.offsetX` and `event.offsetY` to calculate the correct paper translate values. But we moving onto Toolbox, the eventData is different and so the wrong offsetX and offsetY.

- [x] 0.9 (#4211)
- [x] 0.10 (#4210)

**Comment by chia7712** [comment]
thanks for this fixing!
