### ISSUE TITLE
測試 input data 檔案大小是否影響效能

### ISSUE THREAD

**Issue by jackyoh** [oharastream/ohara#4216]
目前執行 Ohara Connector 的 performance 測試發現 input data 的檔案大小會影響 connector 的效能，因此此議題主要測試總共 150 GB 的資料，每個檔案分別是 10 MB 和 100 MB 的二種情境，來測試檔案數量是否會影響 connector 執行的效能。

**Comment by chia7712** [comment]
@jackyoh 先開個議題紀錄"避免重複list files"喔 以免忘記

**Comment by jackyoh** [comment]
ok, 等等我來開

**Comment by jackyoh** [comment]
總共 150 GB 的資料量，每個檔案 10.5 MB, 在 ftp source connector 剛開始執行時平均每秒可以處裡 8246 筆資料。到了快 8 小時平均每秒可以處裡的資料筆數剩下 5983 筆資料

總共 150 GB 的資料量，每個檔案 105 MB, 在 ftp source connector 剛開始執行時平均每秒可以處裡 7843 筆資料。到了快 8 小時平均每秒可以處裡的資料筆數為 7859 筆資料

因此檔案的數量有可能會影響到 ftp source connector 的執行，會在 issue #4219 來處裡

**Comment by chia7712** [comment]
Could we close this issue as we have confirmed the performance issue?

**Comment by jackyoh** [comment]
小檔案會影響到 ftp source connector 的 performance，目前已經在 issue #4219 修改程式碼了，我先把此 issue 關閉。
