### ISSUE TITLE
[Manager] Event log 訊息太長時, row 高度會暴增, 建議將訊息截斷

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#4218]
Minor: Event log 訊息太長時, row 高度會暴增, 建議將訊息截斷
![screenshot 40](https://user-images.githubusercontent.com/475186/75333365-fecc7a00-58c0-11ea-8e6f-e93ce92a640f.jpg)

_Originally posted by @vitojeng in https://github.com/oharastream/ohara/issues/3706#issuecomment-591338785_

**Comment by konekoya** [comment]
@eechih do you think this is an issue? Should we fix this in both branches? Or just 0.10 :)

**Comment by eechih** [comment]
@konekoya We are going to fix it in 0.10.0

**Comment by konekoya** [comment]
@eechih I'm going to take a stab at this :)

**Comment by eechih** [comment]
Thanks @konekoya

**Comment by konekoya** [comment]
No problem, closing this and in favor of #5446
