### ISSUE TITLE
Node information 'CPU' and 'Memory' always 0

### ISSUE THREAD

**Issue by vitojeng** [oharastream/ohara#4224]
![screenshot 41](https://user-images.githubusercontent.com/475186/75754369-97eb0d00-5d67-11ea-9629-b2da518e2d3c.jpg)

![screenshot 43](https://user-images.githubusercontent.com/475186/75754433-b3eeae80-5d67-11ea-94b8-846dfded7ba8.jpg)

**Comment by saivirtue** [comment]
Does this in k8s mode?

**Comment by vitojeng** [comment]
yep

**Comment by eechih** [comment]
@vitojeng 有安裝 K8S metrics server 嗎？
https://ohara.readthedocs.io/en/master/user_guide.html#how-to-install-k8s-metrics-server

**Comment by vitojeng** [comment]
Oh...my bad.
It works fine after install metrics server. 👍
