### ISSUE TITLE
Change the log level of TopicPartitionWriter#rotateOnTime from INFO to DEBUG

### ISSUE THREAD

**Issue by jackyoh** [oharastream/ohara#4226]
在 csv connector 程式的 TopicPartitionWriter class 的 rotateOnTime function 裡有，Should apply scheduled rotation 的 log, 它有點 noisy 我想把它修改成 debug 等級，因為用 INFO 感覺效用不大，會擋到很多其它更重要的 log 資訊。
- [x] 0.9 (#4233)
- [x] 0.10.0 (#4231)

**Comment by chia7712** [comment]
@jackyoh could you backport this to 0.9.x ?

**Comment by jackyoh** [comment]
OK, No problem
