### ISSUE TITLE
[Manager] Remove the cleanup mechanism from Paper's init function 

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#4227]
- [x] 0.9 (#4241)
- [x] 0.10 (#4238)

**Comment by konekoya** [comment]
@eechih @wu87988622 We have come into an agreement: we won't do the cleanup during initializing the Paper (loading paper data from backend)

And new issue is filed for fully remove a topic thru UI #4237

**Comment by chia7712** [comment]
thanks for PRs!
