### ISSUE TITLE
[Manager] Property view's scrollbar doesn't work when developer tools are open

### ISSUE THREAD

**Issue by vitojeng** [oharastream/ohara#4232]
![screenshot 45](https://user-images.githubusercontent.com/475186/75767180-54030280-5d7d-11ea-99da-57f8bf7182c9.jpg)

**Comment by konekoya** [comment]
@vitojeng Did you mean that the property view is not shrinking (adjust the height according to the height taking up by the devTool pane?) properly 🤔

**Comment by konekoya** [comment]
@vitojeng I can confirm this is a bug. We will address this in 0.10. Thanks for raising this 🙏

**Comment by konekoya** [comment]
Fixed in #4267
