### ISSUE TITLE
[Manager] Paper elements' start button should be disabled if it's already running

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#4236]
![註解 2020-03-03 111536](https://user-images.githubusercontent.com/6234750/75739712-9fe38680-5d40-11ea-82db-b8564ec3e565.jpg)

已經啟動的connector依然可以再次啟動?

_Originally posted by @chia7712 in https://github.com/oharastream/ohara/issues/3706#issuecomment-593746169_

- [x] 0.9 (#4244)
- [x] 0.10 (#4242)

**Comment by chia7712** [comment]
great!
