### ISSUE TITLE
[Manager] Disable the delete button in topic's detail view if it's already used in a pipeline

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#4237]
~~Users are able to remove topics not only inside the pipeline but also in the workspace settings. And while doing so in the workspace settings, we didn't implement the logic for unlinking its connections as topics are often connected to other components like connectors or streams.~~

Update: We should disable the button as this logic is already implemented in the backend (the action is not allowed)

- [x] 0.9 (#4246)
- [x] 0.10 (#4245)

**Comment by konekoya** [comment]
@eechih @wu87988622 as per our discussion. Our Plan was to disable the delete button if the topic is already used in one of the pipeline, NOT to force delete the topic. And so i will update the issue title and description and backport this to 0.9

**Comment by eechih** [comment]
> @eechih @wu87988622 as per our discussion. Our Plan was to disable the delete button if the topic is already used in one of the pipeline, NOT to force delete the topic. And so i will update the issue title and description and backport this to 0.9

感謝 @konekoya。 原始設計是 disable，前幾天在討論時我卻忘記了，真的很抱歉～ 🙇‍♂️

**Comment by konekoya** [comment]
> 感謝 @konekoya。 原始設計是 disable，前幾天在討論時我卻忘記了，真的很抱歉～ 🙇‍♂️

No worries! We all forgot about this 🤣

**Comment by chia7712** [comment]
thank all!
