### ISSUE TITLE
[Manager]View node detail refresh question

### ISSUE THREAD

**Issue by chuntsekevin** [oharastream/ohara#4252]
Hi, 
Have a question about manager !
After finished pipeline and want to see the node detail, new services won't show on the node detail view. Have to refresh the whole page to see the new service. 
Is this problem only happened in my environment?

![image](https://user-images.githubusercontent.com/60953697/75960753-9e11f280-5efb-11ea-8aec-46c5a03295e1.png)

Thanks for reply

**Comment by wu87988622** [comment]
@chuntsekevin  Auto update will be added at 0.10.

**Comment by chuntsekevin** [comment]
@wu87988622 Ok, got it! Thanks
