### ISSUE TITLE
add "maximum.number.of.lines" to Csv Connector so it can slice large file in each loop

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#4253]
#### 用 FtpSourceConnector 測試大型 csv file
Env: 
* k8s mode
* 3 nodes, CPU 2 core, RAM 8 GB each node

Step:

0. 建立一個 workspace, 3 nodes.
0. 建立一個 pipeline, 並拉入: ftp source connector --> internal topic --> ftp sink connector
0. Start source and sink connector
0. 放一個 csv 小檔案(< 1 MB)到 input folder, 確認處理正常: 
    * input folder 移到 completed folder
    * sink connector 有寫入 file. 
    * source/sink component 的 Metrics 顯示正確
0. 再放一個 csv 小檔案到(< 1 MB) input folder, 確認處理正常. 同 step 3.
0. 放入一個 csv 大檔案(600MB+)到 input folder. 觀察情形:
    * Metrics: 前數分鐘, FtpSourceConnector 的 Property view 有顯示 Metrics, 但數字沒有更被新. 過更久的時間後, Metrics 即不再顯示(component 顯示 **No metrics data available** )
    * input folder 的 csv 檔案仍然存在
    * 用 Developer Tools/LOGS 觀察三個 node 的 worker, 沒有看到不正常的 exception.
0. 此時再放一個 csv 小檔案, 發現也不會被處理了.

_Originally posted by @vitojeng in https://github.com/oharastream/ohara/issues/3706#issuecomment-595080213_

Now, the "unit" of looping csv task is "file". If users input a large file, all ops to task will be suspended since it is busy at the single and large file.

**Comment by vitojeng** [comment]
Thanks @chia7712!
