### ISSUE TITLE
Enable to configure the hdfs replica in performance test

### ISSUE THREAD

**Issue by jackyoh** [oharastream/ohara#4257]
目前 hdfs sink connector 的 performance 測試程式 flush size 為 hard code 在測試上不太方便，因此需要增加參數，減少使用上的不方便。

**Comment by chia7712** [comment]
@jackyoh Are you testing performance based on 0.10.0? If not, please backport this to 0.9.0

**Comment by jackyoh** [comment]
目前的 performance 測試是 base 在 0.10.0 上。因為這是 improve 設定參數的部份，不像是改 bug 所以我就先不 backport 回 0.9.0

**Comment by chia7712** [comment]
> 目前的 performance 測試是 base 在 0.10.0 上。因為這是 improve 設定參數的部份，不像是改 bug 所以我就先不 backport 回 0.9.0

got it. close this issue now :)

**Comment by jackyoh** [comment]
Thank you.
