### ISSUE TITLE
[Manager] Move snackbar displaying position to screen's top right-hand corner

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#4268]
觀察 Snackbar 目前容易被忽略的因素: 一個是顯示在左下角, 另一個是顯示時間不長.
目前 layout 大部份操作都集中在畫面上半部, 使用者目光停留在上半部機會很高. 在高解晰度的大螢幕下, 左下角的 Snackbar 相信被忽略的機會大增. 因此建議 Snackbar 顯示在畫面中上方, 應該可以增加被使用者注意到的機會~ (希望可以 backport 到 0.9.x)

_Originally posted by @vitojeng in https://github.com/oharastream/ohara/issues/3706#issuecomment-595570704_

- [x] 0.9 (#4276)
- [x] 0.10 (#4275)

**Comment by chia7712** [comment]
thanks for this one!
