### ISSUE TITLE
身為開發人員，我希望能完成一些任務，以便讓我們的開發過程能更加順利

### ISSUE THREAD

**Issue by eechih** [oharastream/ohara#427]
### Criteria
- [x] Enable https on Jenkins (SSL)
- [x] Upgrade React to 16.7
- [ ] ~Commit Code 之前，需要進行第三方套件的弱點檢查~
- [x] Jenkins 進行自動化 UI E2E Testing
- [x] Refactor stream code to integrate the cluster collie (大約二週)
- [ ] ~使用新的 API 取得 brokers, workers, sources, sinks 資訊~

**Comment by vitojeng** [comment]
Thanks @eechih , @saivirtue , @konekoya for the great work!
