### ISSUE TITLE
[Manager] 如果現在UI嚴格限制只能1-to-1的話，那在連線後就應該把"連線"的按鈕遮掉

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#4278]
![註解 2020-03-09 143009](https://user-images.githubusercontent.com/6234750/76189118-d6277700-6214-11ea-892f-c2a32a60ac82.jpg)

如果現在UI嚴格限制只能1-to-1的話，那在連線後就應該把"連線"的按鈕遮掉...

_Originally posted by @chia7712 in https://github.com/oharastream/ohara/issues/3706#issuecomment-596356946_

- [x] 0.9 (#4288)
- [x] 0.10 (#4287)

**Comment by chia7712** [comment]
@konekoya thanks for this improvement!
