### ISSUE TITLE
身為一名剛加入 RD 的前端開發人員，為了能跟上 RD 團隊的步伐，我需要完成準備工作及相關學習

### ISSUE THREAD

**Issue by eechih** [oharastream/ohara#428]
### Criteria
- [x] 跑一次 PR 流程
- [x] 熟悉 OharaStream 整體架構
- [x] 熟悉前端架構
- [x] 建立開發環境 (VSCODE, Git, ...)
- [x] 在 VM 使用 Docker 啟動 Configurator
- [x] 學習 React, CSS, HTML5
- [x] 整合 Material-UI framework

**Comment by vitojeng** [comment]
great job! thanks @wu87988622 & @eechih for this story!
