### ISSUE TITLE
重構 K8SClusterCollieImpl class 的程式

### ISSUE THREAD

**Issue by jackyoh** [oharastream/ohara#429]
required by #425 

因為 K8SClusterCollieImpl 和 SshClusterCollieImpl 實作的程式相似度非常高, 因此需要重構程式, 把相同邏輯的部份抽到父類別裡, 降低程式碼相同的部份.

**Comment by saivirtue** [comment]
@jackyoh 
因為 #425 已經在上次進行Story Demo，並且確認完成了，請在下一次的Sprint把這個issue移動到另一個story下面喔~

**Comment by jackyoh** [comment]
ok, 我再來修改

**Comment by chia7712** [comment]
the refactor is almost completed
