### ISSUE TITLE
[Manager] Ensure the alignment is correct in DevTools' topic panel

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#4306]
![註解 2020-03-10 125154](https://user-images.githubusercontent.com/6234750/76288883-d8580700-62e2-11ea-847b-8a7a23874e09.jpg)

欄位"c"跑版了

_Originally posted by @chia7712 in https://github.com/oharastream/ohara/issues/3706#issuecomment-596940655_

- [x] 0.9 (#4309)
- [x] 0.10 (#4308)

**Comment by chia7712** [comment]
thanks!
