### ISSUE TITLE
Bintray has not been updated in a while.

### ISSUE THREAD

**Issue by vitojeng** [oharastream/ohara#4326]
https://bintray.com/beta/#/oharastream/ohara?tab=packages

It seems bintray has not been updated in a while.  
Anyone knows the reason?

**Comment by vitojeng** [comment]
I try to develop my own stream and got the dependency broken path in the build.gradle

**Comment by saivirtue** [comment]
We have a task shoul be done in the release candidate steps:
```
Build and Upload Ohara jars to Bintray repo
```

**Comment by vitojeng** [comment]
For testing purpose, how can I append `SNAPSHOT` dependencies? (e.g. 0.10.0-SNAPSHOT, 0.9.0-SHOTSNAP)

**Comment by chia7712** [comment]
> IIRC, we used to upload snapshot version?

the binary uploaded should be immutable so the "SNAPSHOT" is NOT a good idea. Personally, the guys who are trying the latest code ought to download, build and install ohara manually.

**Comment by vitojeng** [comment]
got it, will build ohara manually.
