### ISSUE TITLE
[Manager]Incorrect node items

### ISSUE THREAD

**Issue by vitojeng** [oharastream/ohara#4332]
It seems there have too much node items.

![screenshot 9](https://user-images.githubusercontent.com/475186/76716582-bdb2e180-676b-11ea-91ed-2c491209abb8.jpg)

- [x]  0.9 #4337 
- [ ]  0.10

**Comment by vitojeng** [comment]
ping @wu87988622

**Comment by wu87988622** [comment]
> ping @wu87988622

Thanks i will follow this issue

**Comment by chia7712** [comment]
@wu87988622 for 0.9.0 only?

**Comment by wu87988622** [comment]
> It seems there have too much node items.
> 
> ![screenshot 9](https://user-images.githubusercontent.com/475186/76716582-bdb2e180-676b-11ea-91ed-2c491209abb8.jpg)

- [ ]0.9  #4337 
- [ ] 0.10

**Comment by wu87988622** [comment]
> @wu87988622 for 0.9.0 only?

還有 0.10 要等另一隻，等pr上去會再標記，感謝

**Comment by wu87988622** [comment]
0.10 is fix in #4322
