### ISSUE TITLE
Introduce maven plugin to build.gradle

### ISSUE THREAD

**Issue by vitojeng** [oharastream/ohara#4335]
Use [maven plugin](https://docs.gradle.org/current/userguide/maven_plugin.html) to install jar to the local repository.

##### for example: install ohara-common-XXX.jar
```
[ohara]$ cd ohara-common
[ohara-common]$ gradle install
```

##### install all jars
```
[ohara]$ gradle install -PskipManager
```

**Comment by chia7712** [comment]
Does the plugin work well? If so, please close this issue :)

**Comment by vitojeng** [comment]
> Does the plugin work well? If so, please close this issue :)

Yes, the plugin work well. Close issue.
