### ISSUE TITLE
[Question] Ohara 的 Row 物件有可能需要支援 length 方法

### ISSUE THREAD

**Issue by jackyoh** [oharastream/ohara#4339]
目前 ohara 有支援 size 方法它可以讓我們知道 cell 總共有幾個，我覺得也需要支援 length 方法這樣我們就可以知道每一個 row 大約是幾 byte，這樣使用 Row 物件就可以不用另外去計算，每一個 row 使用多少的空間，增加使用上的方便性。

另外 performance 測試程式產生資料的部份目前也是用 Row 物件，如果有支援 length 方法。就可以不用在測試程式裡計算每一個 row 使用多少的空間

**Comment by chia7712** [comment]
row is NOT immutable so the *size* of row CAN'T be cached. In other words, the method to get size of row is calculated each time. It seems to me adding such helper method is ok. However, the size of custom serialized object is hard to calculate. We can use sometime tool to traverse the object to sum all primitive fields but it is too expensive...

**Comment by jackyoh** [comment]
我想得太簡單了以為只有 String 的長度計算，沒有考慮到 row 其實還可以接受一些自定義的序列化物件，這樣在計算 length 的難度就會增加而且不太確定是否會很佔資源。

> sometime tool to traverse the object to sum

有沒有推薦的工具或是 ohara 已經有使用的 library。 我來研究看看，如果太難我就先放棄這個議題。

**Comment by jackyoh** [comment]
之後會做有關於序列化的部份，在來做這個議題。我先把此議題關閉
