### ISSUE TITLE
add "nodeMetrics" instead of "metrics" to display metrics of each node

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#4346]
Currently, the metrics in different task/partition are merged into single field. It is wrong since not all number is able to be sum up.

before
```json
{
  "metrics": [],
  "taskStatus": []
}
```

after
```json
{
  "metrics": [],
  "taskStatus": [
    {
      "metrics": []
    }
  ]
}
```

**Comment by chia7712** [comment]
@oharastream/developer I'm going to change *metrics* from single element to array. For example,

```json
{
    "metrics": {
      "meters": []
    }
}
```
```json
{
    "metrics": [
       {
          "hostname": "abc",
          "meters": []
       }
    ]
}
```

I try to keep the compatibility but I have no idea about better naming. WDYT? metrics -> ???

**Comment by saivirtue** [comment]
`nodeMetrics` seems understandable to me, so I vote up.

**Comment by vitojeng** [comment]
`nodeMetrics` is great

**Comment by chia7712** [comment]
@oharastream/frontend Please link the issue of applying "nodeMetrics" to this one :)
