### ISSUE TITLE
[Manager] Cannot fetch manager info from API in container

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#4350]
Thanks @konekoya for finding this!

**Comment by chia7712** [comment]
It seems to me this should be backport to 0.9.0. Also, it would be better to make sure the version file is existent in the distribution file rather than docker image.

**Comment by saivirtue** [comment]
> It seems to me this should be backport to 0.9.0.

It's your call, boss :)

> Also, it would be better to make sure the version file is existent in the distribution file rather than docker image.

More explanation?

**Comment by chia7712** [comment]
> More explanation?

Currently, the version file exists only in the docker image. Users CAN'T see it from the distribution of ohara-manager. Hence, users can't get version info if they enter ```ohara.sh -v```.

**Comment by chia7712** [comment]
I have filed a ticket #4404
