### ISSUE TITLE
replace gradle-5.6.4-bin.zip by gradle-5.6.4-all.zip to include gradle sources and documentation

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#4372]
The source code and document helps us to trace our code of exercising gradle :)

1. - [x] for 0.10.0 (#4373)
1. - [x] for 0.9.0 (#4374)

**Comment by saivirtue** [comment]
Seems identical gradle version?

**Comment by chia7712** [comment]
> Seems identical gradle version?

my bad :( 

the title is updated
