### ISSUE TITLE
Improve Ohara README.md and Manager README.md 

### ISSUE THREAD

**Issue by wu87988622** [oharastream/ohara#438]
required by #428 

Manager README.md 指向 Configurator Setup
Ohara README.me 指向 Docker Setup

**Comment by chia7712** [comment]
橘色的標籤只有用在pr身上，此外該標籤會讓jenkins來幫忙標記

**Comment by konekoya** [comment]
@wu87988622 Please close an issue when its resolved/fixed in a PR :)
