### ISSUE TITLE
[Manager] Fix cypress is not able to be downloaded issue

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#4391]
- [x] 0.9 (#4394)
- [x] 0.10 (#4392)

/cc @chia7712

**Comment by chia7712** [comment]
@konekoya please share root cause to us :)

**Comment by konekoya** [comment]
> @konekoya please share root cause to us :)

I'm not entirely sure yet... It seems like some people does suffer from this issue but got away with different solutions. 

https://github.com/cypress-io/cypress/issues/6315
https://github.com/cypress-io/cypress/issues/4883

For us, I'm upgrading cypress and it seems fixed the issue 🤷‍♂

**Comment by vitojeng** [comment]
@chia7712 看起來 0.9.0 tag 己經建立了? 請問這個有影響到 release 0.9.0 嗎?

**Comment by chia7712** [comment]
> 看起來 0.9.0 tag 己經建立了? 請問這個有影響到 release 0.9.0 嗎?

整個卡住喔 因為下載cypress會噴掉導致無法建立images
