### ISSUE TITLE
Rename ohara-stream"s" to ohara-stream

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#4407]
#3280 removed the postfix "app" to get better naming. However, the name conflict is still exist since both "streams" and "stream" are across whole project. For example:

1. oharastream/stream:xxx
1. stream.dockerfile
1. ohara-streams
1. oharastream.ohara.streams 

@oharastream/developer Could we unify the naming? stream or stream"s"?

Votes pass: stream**s** -> stream

I tries to minimize the changes of this issue so only following "words" are included.

1. ohara-stream**s** -> ohara-stream
1. rest-stream**s** -> rest-stream
1. oharastream.ohara.stream**s** -> oharastream.ohara.stream
1. oharastream/ohara/stream**s** -> oharastream./ohara/stream

**Pull Requests**
1. - [x] for 0.10.0 (#4414)
1. - [x] for 0.9.0 (#4415)

**Comment by konekoya** [comment]
+1 for stream

**Comment by saivirtue** [comment]
For 1 and 2, the stream means the **stream component**; It is identical to other components in pipeline.
For 3 and 4, the streams means **package name**

I think the problem is if we change 3 and 4 to stream, it will look a little weird:
`oharastream.ohara.stream`

**Comment by chia7712** [comment]
> I think the problem is if we change 3 and 4 to stream, it will look a little weird:
oharastream.ohara.stream

the weird thing is that "stream" is just a part of "ohara" but we put it on our "org" ...

```oharastream.ohara.streams``` is weird also. Hence, I want to focus on the "stream" and streams" in this issue.

**Comment by saivirtue** [comment]
> the weird thing is that "stream" is just a part of "ohara" but we put it on our "org" ...

Until we find a better naming of "our stream component", I vote to **stream**

**Comment by vitojeng** [comment]
It's really hard to choice for me... 😄 

I would pick `stream` if we need to choice one.

**Comment by chia7712** [comment]
the reason I want to unify the naming is that I tried to build/push a incorrect image ```oharastream/streams:0.9.0``` ...

**Comment by vitojeng** [comment]
Does we should backport to 0.9.x ?

**Comment by saivirtue** [comment]
> the reason I want to unify the naming is that I tried to build/push a incorrect image `oharastream/streams:0.9.0` ...

In #3280 😆

**Comment by chia7712** [comment]
> Does we should backport to 0.9.x ?

As the name "stream" means the code paths are changed, the backport is necessary for bug fixes in the future.

**Comment by vitojeng** [comment]
> As the name "stream" means the code paths are changed

This is a break change for the user who write their own **stream** .
/cc @chuntsekevin

**Comment by jackyoh** [comment]
+1 for stream

**Comment by eechih** [comment]
stream +1

**Comment by chia7712** [comment]
thank all, let me complete this issue asap
