### ISSUE TITLE
the scala version used to build connectors should be equal to kafka

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#4416]
![註解 2020-03-22 021544](https://user-images.githubusercontent.com/6234750/77233537-11498300-6be3-11ea-8680-f37a68f67059.jpg)

the default scala version in ohara is updated to scala 2.12.11 (see #4353) but the kafka code used to run official connectors is 2.12.10 (see https://github.com/apache/kafka/blob/2.4.1/gradle/dependencies.gradle#L33). To put it another way, they are compiled with 2.12.11 from the 2.12.10 runtime...

**Comment by jackyoh** [comment]
這個議題看起來是 ohara 的 scala 版本升級到 2.12.11 之後，但是 kafka 的 scala 的版本沒有 2.12.11，而造成 scala compiler 和 runtime 版本不一致的問題。

那如果把 ohara 的版本升級到 2.13.1 還會有 compiler 和 runtime scala 版本不一致的問題嗎？

**Comment by chia7712** [comment]
> 那如果把 ohara 的版本升級到 2.13.1 還會有 compiler 和 runtime scala 版本不一致的問題嗎？

Currently, we follow the scala minor version of kafka :)

I have test a lot of function for our images and they work well. I'm going to close this issue as the is jdk 8 issue (see https://bugs.openjdk.java.net/browse/JDK-8161588).
