### ISSUE TITLE
the main class of shabondi does not exist

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#4422]
```
  elif [ "$service" == "shabondi" ]; then
    CLASS="oharastream.ohara.shabondi.Boot"
```

#4046 had removed oharastream.ohara.shabondi.Boot and the replacements are oharastream.ohara.shabondi.source.Boot and oharastream.ohara.shabondi.sink.Boot

**Comment by vitojeng** [comment]
Thanks for reporting.
This is known issue... QQ
