### ISSUE TITLE
Add route of validating connector

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#443]
This is a similar function to validation of {ftp, hdfs, node and rdb}

required by #421

**Comment by chia7712** [comment]
@konekoya @eechih Please take a look at [docs](https://paper.dropbox.com/doc/Configurator-APIs--AZJzk8SfAc0_EE6dL98t7wxFAQ-nYWQMqQLGsG0lffMaY7Xk)

**Comment by konekoya** [comment]
Thanks for putting this up @chia7712! I will try to give this a look today :)
