### ISSUE TITLE
[Question] Upload Streams problem

### ISSUE THREAD

**Issue by chuntsekevin** [oharastream/ohara#4440]
I use the latest ohara stream 0.9.0 docker mode . Face the same issue in #4083.
I can't use the streams in pipeline after uploaded.

**Comment by saivirtue** [comment]
Do you rebuild your jar by the latest version?
Since #4407 is a breaking change for the package name

**Comment by chuntsekevin** [comment]
Got it ! Thanks
It seems that's the reason.
