### ISSUE TITLE
the acceptable characters for group and name should be number, lowercase alphanumeric characters, or ‘.’

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#4441]
Group and Name are the index of object in ohara but Kafka does not support "group". Hence, we generate "kafka name" by concatenating group and name.
```json
{
  "group": "g",
  "name": "n"
}
```
The above object has kafka name called "g-n". 

The way we generate kafka name has a issue is we can't extract "group" from the kafka name correctly if the group includes character "-".

I remove the 0.9.1 since this change break the compatibility. Also, not sure whether any potential issues I don't observe...

**Comment by chia7712** [comment]
@oharastream/developer any suggestions?

"-" is still supported by the "name" field so it seems to me removing it from "group" field should be fine.

**Comment by jackyoh** [comment]
這個議題看起來像是 group 沒辦法接受 - 符號，因為在 parser 的時候沒辦法辨認出 name 的開頭在哪。

+1

**Comment by saivirtue** [comment]
> "-" is still supported by the "name" field 

I am surprised we still support "dash" in name field, since we only support [a-z0-9] in UI...

> The way we generate kafka name has a issue is we can't extract "group" from the kafka name correctly if the group includes character "-".

Do we have a use case needs to extract group?

**Comment by chia7712** [comment]
> Do we have a use case needs to extract group?

Converting the kafka data to ohara data need to extract group. for example, metrics, topic information and connector information.

**Comment by jackyoh** [comment]
昨天我忘記說到 K8S 的 pod name 不支援底線。

https://kubernetes.io/zh/docs/concepts/overview/working-with-objects/names/

**Comment by chia7712** [comment]
> 昨天我忘記說到 K8S 的 pod name 不支援底線。

Could you file a ticket for this case?

**Comment by jackyoh** [comment]
底線拿來內部使用我覺得可以，那之後的版本還會做修改嗎？因為感覺上會遇到版本相容性的問題。

**Comment by chia7712** [comment]
> 底線拿來內部使用我覺得可以，那之後的版本還會做修改嗎？因為感覺上會遇到版本相容性的問題。

當然就不能改了XDDD

**Comment by vitojeng** [comment]
是否可以將 name & group naming rule 寫入 api docs 裡?

**Comment by chia7712** [comment]
> 是否可以將 name & group naming rule 寫入 api docs 裡?

Sure

**Comment by chia7712** [comment]
測試了一下，

1. k8s不支援底線"_"
1. 但我們需要"-"來組合字串(原因同上)

綜合上述，等同於"-"和"_"都應該要禁止...

另外k8s支援dot "."，或許我們應該開放這個，一來"."也是常用字符、二來在使用hostname的時候"."很常出現...

**Comment by chia7712** [comment]
ping @oharastream/developer for more suggestions :)

**Comment by jackyoh** [comment]
點有可能會跟 hostname 有衝突

**Comment by chia7712** [comment]
> 點有可能會跟 hostname 有衝突

hoatname不是常常會使用"."嗎?

**Comment by jackyoh** [comment]
hostname 常常用點來命名。其他內部的地方應該就不能用到點了，因為 parser 會找不到正確的位置。

**Comment by chia7712** [comment]
> hostname 常常用點來命名。其他內部的地方應該就不能用到點了，因為 parser 會找不到正確的位置。

你說的沒錯，我的意思是把"."開放給使用者，然後把"-"和"_"收回來做為內部使用

**Comment by jackyoh** [comment]
OK, 了解。

**Comment by saivirtue** [comment]
+1

**Comment by wu87988622** [comment]
+1

**Comment by eechih** [comment]
> 你說的沒錯，我的意思是把"."開放給使用者，然後把"-"和"_"收回來做為內部使用

+1

**Comment by konekoya** [comment]
+1

**Comment by jackyoh** [comment]
+1

**Comment by vitojeng** [comment]
+1
