### ISSUE TITLE
[Question] K8SClient 是否要支援啟動 Ohara Configurator

### ISSUE THREAD

**Issue by jackyoh** [oharastream/ohara#4453]
目前 Ohara 的 Configurator service 是使用 Docker Client 在啟動 container。因為 K8SClient 和 DockerClient 是使用同一個 ContainerClient 的 interface, 所以理論上 configurator 的 container
應該也可以使用 K8SClient 來建立。

目前我有測試使用 K8SClient 來建立 configurator 的 container, 在建立的過程中會收到 no such file or directory: unknown。因為目前 configurator 都是用 docker client 來執行，所以不太確定是否要來解這個問題

**Comment by chia7712** [comment]
@jackyoh any update?

**Comment by vitojeng** [comment]
Question: 如果 configurator 能以 k8s 啟動, 是否意謂著未來 manager 可以做到透過 k8s api 啟動 configurator?

**Comment by jackyoh** [comment]
> @jackyoh any update?

目前還沒做進一步的研究此問題，我會再找時間來研究無法使用 K8SClient 來啟動 configurator 的原因。

**Comment by jackyoh** [comment]
> Question: 如果 configurator 能以 k8s 啟動, 是否意謂著未來 manager 可以做到透過 k8s api 啟動 configurator?

如果 ohara manager 可以直接連到 k8s 的 restful API，我覺得應該可以啟動 configurator container。但是我覺得這樣做有可能會破壞相容性，而導致有一些我們無法預期的問題，例如少塞到一些環境變數的設定, 或是改版時 manager 漏掉一些啟動 configurator 的設定。

因此任何操作都還需要透過 configurator api 統一的界面, 所以我認為 configurator 服務是 ohara 第一個要啟動的服務。

**Comment by vitojeng** [comment]
> 我覺得這樣做有可能會破壞相容性

我的理解是, 不論是對於 manager 或是 API user, "由 k8s 啟動 configurator" 這是新的功能, 所以應該沒有破壞相容性的疑慮. @jackyoh 覺得呢?

> 因此任何操作都還需要透過 configurator api 統一的界面, 所以我認為 configurator 服務是 ohara 第一個要啟動的服務。

是的, configurator 是第一個需要啟動的服務. 
目前只能用 docker 啟動, 未來若可能用 k8s 啟動的話, 就多了一個選項. 若是這樣的話, 我覺得 manager 用 k8s api 啟動 configurator 就變成可能.
=> 這樣的話, 就可以從 Ohara Manager 把 Ohara Backend 從無到有建立起來. 這樣的話, 對於"簡化 Ohara 後端建立的複雜度" 算是又往前進了一步.

以上純粹討論~ XDD

**Comment by jackyoh** [comment]
>  @jackyoh 覺得呢?

因為目前後端的 K8SClient 程式碼把所有 create container 的 json 設定都包裝起來了，如果 ohara manager 要直接透過 k8s api 啟動 configurator 的 container,  應該會再新建立一份 k8s 的 json 設定，這樣我們就會有二份 k8s api 的 json 設定，未來  K8SClient 有新增或修改一些 k8s json 的設定，前端的 k8s json 設定也要一起修改，才不會發生一些無法預期的錯誤。

>   對於"簡化 Ohara 後端建立的複雜度" 算是又往前進了一步.

+1

**Comment by chia7712** [comment]
@jackyoh 所以有找出為何啟動失敗的原因了嗎

**Comment by jackyoh** [comment]
目前還沒有找到真正的原因，但是看起來是找不到檔案，我印象中 @saivirtue 很像有做 K8S 的重構，那時很像有放一些檔案，不太確定是否跟跟這個問題相關，我會在研究程式碼。

**Comment by chia7712** [comment]
#4481會處理掉k8s啟動configurator的議題

**Comment by jackyoh** [comment]
Thank you. 

我有實際的把 #4481 的 PR 拉下來,，然後寫一段簡單的測試，使用 ContainerClient 的方式建立 Ohara Configurator 在 k8s 的環境執行，已經可以執行了。

我分享程式碼如下：
```
    val containerClient: ContainerClient    = K8SClient.builder
      .apiServerURL("http://ohara-k8s-master:8080/api/v1")
      .namespace(sys.env.getOrElse(K8S_NAMESPACE_KEY, "default"))
      .build()

    val serviceNameHolder: ServiceKeyHolder = ServiceKeyHolder(containerClient, false)
    val configuratorContainerKey        = serviceNameHolder.generateClusterKey()
    val configuratorContainerName: String =
      s"${configuratorContainerKey.group()}-${configuratorContainerKey.name()}"
    val configuratorHostname: String        = "ohara-k8s-master"
    val imageName = s"oharastream/configurator:${VersionUtils.VERSION}"
    val configuratorPort: Int               = CommonUtils.availablePort()

    result(
      containerClient.containerCreator
        .nodeName(configuratorHostname)
        .imageName(imageName)
        .portMappings(Map(configuratorPort -> configuratorPort))
        .arguments(
          Seq(
            "--hostname",
            configuratorHostname,
            "--port",
            configuratorPort.toString
          )
        )
        .name(configuratorContainerName)
        .create()
    )
```
另外我有二個問題：
1. 因為 PR #4481 我研究很久，只看到修改 K8SJson.scala 就解了，K8SClient 不能啟動 configurator pod 的問題，真正的問題我還沒捕捉到

2. 既然我們都可以使用 K8SClient 執行 configurator 的 pod, 那要不要把 WithRemoteConfigurator k8s 的部份也改成 ， 使用 K8SClient 來啟動 configurator 的 pod （因為目前是使用 Docker Client 來啟動 configurator）

**Comment by jackyoh** [comment]
我剛剛沒注意到， 目前 PR 啟動 configurator 的部份，k8s 的部份已經從 docker client 改成了 k8sclient 了

**Comment by jackyoh** [comment]
這個議題已經在 PR #4481 解了，我先關閉此議題。
