### ISSUE TITLE
ContainerPlatform should support custom mode which accepts an existent Configurator service

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#4487]
ContainerPlatform is in charge of manage remote configurator service. In developing ohara, we, sometimes, are want to set up a long-run custom configurator to run all changes with IT. In order to resolve above issue, ContainerPlatform should be able to accept a "custom" Configurator env (hostname and port).

**Comment by chia7712** [comment]
FYI @vitojeng @jackyoh

**Comment by chia7712** [comment]
概念上，我想增加一個參數ohara.it.configurator，值的形式為```hostname:port```

當此參數存在時，ContainerPlatform依照該參數值建立，並且"不會"去嘗試建立任何configurator，換言之也不會去嘗試初始化任何節點。也就是說，該既存的configurator必須已經儲存好可用的nodes

**Comment by jackyoh** [comment]
看起來像是 configuration 是一個可以事先建立好的服務，然後只要指定 configuration 的 hostname 和 port ，就可以跑 IT 測試，增加了啟動 configuration 的選擇性。

**Comment by chia7712** [comment]
> 看起來像是 configuration 是一個可以事先建立好的服務，然後只要指定 configuration 的 hostname 和 port ，就可以跑 IT 測試，增加了啟動 configuration 的選擇性

沒錯，由於現在我們介面陸續到位(ContainerClient and ContainerPlatform)，許多細節都可以封裝起來給後續IT使用，新增一個custom模式也不會太麻煩

**Comment by vitojeng** [comment]
那 `ohara.it.hostname` & `ohara.it.port` 是否就沒有需要了?

**Comment by jackyoh** [comment]
那要去限制 0.10.0 版本的整合測試程式碼，使用 0.9.0 版本的程式啟動 configurator container 嗎？

**Comment by jackyoh** [comment]
> 那 ohara.it.hostname & ohara.it.port 是否就沒有需要了?

我是覺得已經沒有需要了，另外在 IntegrationTest 的 publicHostname 和 publicPort 都可以移除掉了，很像沒有用到了。
