### ISSUE TITLE
Update gradle from 5.6.4 to 6.3.0

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#4491]
Kafka is going to update gradle to 6.3.0. Let us follow in kafka's footsteps.

**Comment by vitojeng** [comment]
@oharastream/developer 
Gradle 版本準備大躍進啦

**Comment by chia7712** [comment]
結果噴出一堆OOM，真詭異...還需要測試一下

**Comment by vitojeng** [comment]
> 結果噴出一堆OOM，真詭異...還需要測試一下

看了 https://github.com/apache/kafka/pull/7677, 看起來 kafka 也還沒有搞定?
不論是 kafka 還是 gradle...
或許未來我們要避免升級到最後一碼是 0 的版本?  XD

**Comment by chia7712** [comment]
kafka那邊應該是快合併了，等他們測試完所有指令。

現在我覺得比較詭異的是記憶體問題，不知道是不是新版的zinc吃掉的記憶體超多，scala compilations的記憶體配置不往上拉的話一定會噴出OOM
