### ISSUE TITLE
[Design] Ohara 0.10.0 mockup

### ISSUE THREAD

**Issue by eechih** [oharastream/ohara#4498]
Related to #4468 

- Workspace Settings
  - [x] New Layout
  - [x] Topics
  - [x] Worker Nodes
  - [x] Worker Plugins
  - [x] Broker Nodes
  - [x] Zookeeper Nodes
  - [x] Stream Jars
- Restart Workspace 
  - [x] Confirm Dialog
  - [x] Progress Dialog
- Rollback Workspace 
  - [x] Confirm Dialog
  - [x] Progress Dialog
- Delete Workspace 
  - [x] Confirm Dialog

**Comment by eechih** [comment]
![Services](https://user-images.githubusercontent.com/703126/78656993-b8742d00-78fa-11ea-81f9-f7760c42e144.png)

**Comment by eechih** [comment]
![Services](https://user-images.githubusercontent.com/703126/78738515-a4750d80-7984-11ea-9b64-beea11424fd4.png)
![Nodes](https://user-images.githubusercontent.com/703126/78738526-a939c180-7984-11ea-85c5-ce7317e32f53.png)
![Plugins](https://user-images.githubusercontent.com/703126/78738531-ab9c1b80-7984-11ea-8da8-f58f487e62b6.png)

**Comment by eechih** [comment]
![Services](https://user-images.githubusercontent.com/703126/78752139-20338200-79a6-11ea-8d49-f6271cb2833a.png)

**Comment by eechih** [comment]
![Services](https://user-images.githubusercontent.com/703126/78769158-87a9fb80-79bf-11ea-9c35-778a39be51e3.png)

**Comment by eechih** [comment]
![Topic in this workspace](https://user-images.githubusercontent.com/703126/78803195-46324400-79f1-11ea-85db-094df5b02930.png)
![Delete this workspace](https://user-images.githubusercontent.com/703126/78803202-48949e00-79f1-11ea-95d8-f9ea972ec77c.png)
![Restart this workspace](https://user-images.githubusercontent.com/703126/78803207-49c5cb00-79f1-11ea-97e2-88c3eada79d7.png)

**Comment by eechih** [comment]
![Open](https://user-images.githubusercontent.com/703126/78869597-673d7800-7a77-11ea-9f26-73e4e4b9157d.png)

**Comment by eechih** [comment]
![Start](https://user-images.githubusercontent.com/703126/78906572-1a2ac780-7ab2-11ea-9c32-214b84efe7b9.png)
![Stop](https://user-images.githubusercontent.com/703126/78906589-1dbe4e80-7ab2-11ea-9170-0708d10b0b6c.png)
![Failed](https://user-images.githubusercontent.com/703126/78906597-20b93f00-7ab2-11ea-9f29-d2cbc5e383a1.png)

**Comment by eechih** [comment]
![Start + Detail](https://user-images.githubusercontent.com/703126/78957414-d8346c80-7b17-11ea-8afc-e845391b9c2f.png)
![Suspend + Detail](https://user-images.githubusercontent.com/703126/78957421-dc608a00-7b17-11ea-81bd-43ede1566a60.png)
![Failed + Detail](https://user-images.githubusercontent.com/703126/78957424-dec2e400-7b17-11ea-8aba-8576d2cd99f1.png)
![Rollback Confirm](https://user-images.githubusercontent.com/703126/78957431-e1253e00-7b17-11ea-9d8f-afa9db2936f7.png)
![Rollback Start](https://user-images.githubusercontent.com/703126/78957437-e4202e80-7b17-11ea-8aee-31dfa7ae240c.png)

**Comment by saivirtue** [comment]
使用者期望的"Suspend"是按下去的當下就暫停吧?
如果是，以我們目前的架構應該做不到 (因為API都是async，已經發出去的request無法暫停)
這樣的話是否將進度條改為只有深色條(已完成)就好而不要有淺色條 (目前正在執行中的狀態)?
也就是說**正在進行停止的service無法被暫停**

**Comment by eechih** [comment]
@saivirtue 感謝你思考這麼周全，這是我沒考慮到的細節。 我會針對這部份進一步思考。
