### ISSUE TITLE
fix nonexistent dependencies in building ohara-manager

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#4502]
#4441 incorrectly introduced changes to ```yarn.lock```...

**Comment by konekoya** [comment]
@chia7712 could your share a bit more info about this... I wonder why the lock file is not updated 🤔

**Comment by chia7712** [comment]
> So you the PR did change the yarn.lock file. Did you happen to run yarn install something

只是手殘不小心改到而已==

**Comment by konekoya** [comment]
> 只是手殘不小心改到而已==

Oh okay @@~ Thanks for fixing it ❤️
