### ISSUE TITLE
Remove JsonIn and JsonOut

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#4515]
The replacement *shabondi* is on production almost so it is time to remove stale connectors :)

**Comment by chia7712** [comment]
FYI @vitojeng

**Comment by vitojeng** [comment]
Maybe we can wait until all taks of shaondi are completed before removing JsonIn/JsonOut ?

**Comment by chia7712** [comment]
> Maybe we can wait for shaondi's work to be completed before removing JsonIn/JsonOut ?

the main reason I want to remove them ASAP is that the IT is flaky. It seems to me that tracing the stale connectors is a bit meaningless :_

**Comment by vitojeng** [comment]
Got it.

**Comment by vitojeng** [comment]
ping @chuntsekevin
