### ISSUE TITLE
Add a new RESTful API to list reference data

### ISSUE THREAD

**Issue by eechih** [oharastream/ohara#4555]
UI 根據 Definition 動態呈現表單內容，對於 reference 的支援不夠強健
當 Definition 定義新的 reference 時，UI 都必須要調整程式碼
有鑑於此，我們需要一隻專門取得各種類型 reference 資料的 API

1. - [x] Rename Reference.ZOOKEEPER_CLUSTER to Reference.ZOOKEEPER, Reference.BROKER_CLUSTER to Reference.BROKER and Reference.WORKER_CLUSTER to Reference.WORKER (#5166)
1. - [x] Support to GET/DELETE object according to Reference (#5178)
1. - [x] UI @eechih  -> Tracked by another issue #5369

**Comment by chia7712** [comment]
@eechih Will this new APIs be used by Manager in 0.10.0?

**Comment by eechih** [comment]
> @eechih Will this new APIs be used by Manager in 0.10.0?

@chia7712 It will be used in the next milestone.

/cc @vitojeng

**Comment by chia7712** [comment]
> It will be used in the next milestone.

it seems we should remove the 0.10.0 from label?

**Comment by eechih** [comment]
> it seems we should remove the 0.10.0 from label?

Yep

**Comment by chia7712** [comment]
@oharastream/frontend 相關的APIs已經上線，接下來看你們了

**Comment by chia7712** [comment]
@oharastream/frontend 如果前端還沒機會整合此新APIs，那麼麻煩另外開一個議題，我要準備關閉了

**Comment by eechih** [comment]
> @oharastream/frontend 如果前端還沒機會整合此新APIs，那麼麻煩另外開一個議題，我要準備關閉了

OK
