### ISSUE TITLE
Upgrade kafka from 2.4.1 to 2.5.0

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#4569]
as title.

see https://downloads.apache.org/kafka/2.5.0/RELEASE_NOTES.html for release note of kafka 2.5.0

**Comment by vitojeng** [comment]
關於 Kafka upgrade, 曾想過我們是否避免尾數是 0 的版本就足夠了 ?
例如只升 2.2.2 / 2.4.1 / 2.5.1 ,  不升 2.2.0, 2.3.0, 2.4.0, 2.5.0 之類的

有時看到 kafka 那種 rc 階段突然冒出的 blocking issue 實在是有些令人冒汗... XD

**Comment by chia7712** [comment]
> 有時看到 kafka 那種 rc 階段突然冒出的 blocking issue 實在是有些令人冒汗... XD

這個主意不錯，可以等到正式釋出後就放慢腳步，現階段先跟緊一點可以讓我們快速的反應kafka變更
