### ISSUE TITLE
Upgrade Scala 2.12.11 to 2.13.2

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#4630]
we are using kafka 2+ and it supports scala 2.13+ so it is time to bump up our scala support :)

**Comment by chia7712** [comment]
ping @vitojeng

**Comment by chia7712** [comment]
ping @jackyoh

**Comment by vitojeng** [comment]
走在時代的前端

**Comment by vitojeng** [comment]
剛剛發現 2.13.2 出來了⋯⋯ 🤣

**Comment by chia7712** [comment]
> 剛剛發現 2.13.2 出來了⋯⋯ 🤣

立刻更新...

**Comment by jackyoh** [comment]
+1
