### ISSUE TITLE
Upgrade all dependencies excluding hdfs

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#4635]
1. **akka** 2.5.26 -> 2.6.4
1. **scalatest** 3.0.8 -> 3.1.1
1. **javassist** 3.24.1-GA -> 3.27.0-GA
1. **slf4j** 1.7.28 -> 1.7.30
1. **Scala Java8 Compat** 0.9.0 -> 0.9.1
1. **commons-lang3** 3.7 -> 3.10
1. **wix-embedded-mysql** 4.1.2 -> 4.6.1
1. **mysql-connector-java** 8.0.12 -> 8.0.19
1. **commons-io** 2.4 -> 2.6
1. **com.google.guava** 27.1-jre 29.0-jre
1. **rocksdb** 5.18.3 -> 5.18.4
1. **jackson** 2.10.1 -> 2.10.2
1. **SMBJ** 0.9.1 -> 0.10.0

**Comment by chia7712** [comment]
ping @jackyoh @vitojeng

**Comment by chia7712** [comment]
akka brings a lot of deprecated methods so this issue will include a huge PR :_

**Comment by vitojeng** [comment]
> akka and scalatest brings a lot of deprecated methods so this issue will include a huge PR :_

Because Akka 2.5 & Akka 2.6 have a lot different.
I suggest pending the akka version bumping until to the next milestone.

**Comment by chia7712** [comment]
> I suggest pending the akka version bumping until to the next milestone.

In fact, I have completed the migration :)

Let me test the PR later.

**Comment by vitojeng** [comment]
OK
