### ISSUE TITLE
Worker list page cannot get the data from configurator

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#464]
## Steps to reproduce:
1. Navigate to `services/workers` page and use the _New cluster_ button to create a new worker cluster.
2. Reload the page or go to `services/workers` again. An error notification will be displayed with a message: Service Unavailable

**Comment by konekoya** [comment]
Thanks for investigating this!

**Comment by chia7712** [comment]
This issue is about deadlock...We apply global thread poll across code base. I will file a PR to fix it.

**Comment by konekoya** [comment]
Thanks @chia7712 :)
