### ISSUE TITLE
Create issue templates

### ISSUE THREAD

**Issue by vitojeng** [oharastream/ohara#469]
Help guest to create an issue.

**Comment by vitojeng** [comment]
@chia7712, @eechih, @saivirtue
Does this issue still need **Fix Version** label?

**Comment by chia7712** [comment]
The issue having PR committed to git repo must have fix version.

**Comment by vitojeng** [comment]
OK

**Comment by vitojeng** [comment]
reopen for wrong pull_request_template folder
