### ISSUE TITLE
Uploading a jar which has no stream to pipeline doesn't give response

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#4716]
how to reproduce this bug?

1. prepare a jar having no stream
1. upload it to pipeline (no response)

**Comment by chia7712** [comment]
FYI @oharastream/frontend

**Comment by saivirtue** [comment]
This issue seems not appear in `0.10`, I'll test the same scenario in `0.9`

**Comment by saivirtue** [comment]
Unfortunately, this is a bug :(
Do we need to fix this bug in `0.9.1`?

**Comment by konekoya** [comment]
I will do a more comprehensive test on this in 0.10 and report back :)

**Comment by saivirtue** [comment]
Since this issue will not backport to 0.9 and should be fixed after 0.10, I will close this issue later.
