### ISSUE TITLE
[Develop Tool] 無法查詢 Pipeline only topic 的資料

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#4722]
![image](https://user-images.githubusercontent.com/8088616/81135499-02e4da00-8f8b-11ea-99fc-f012847734cd.png)

/cc @eechih 
Let me take over this issue :)

- [x] for 0.11 (#4726)
- [x] backport to 0.10 (#4814)

**Comment by eechih** [comment]
@saivirtue ok, thanks.

**Comment by eechih** [comment]
>  for 0.10 (#4726)
 backport to 0.9

need to backport to 0.9 ?

**Comment by saivirtue** [comment]
> > for 0.10 (#4726)
> > backport to 0.9
> 
> need to backport to 0.9 ?

My bad :(
it's 0.10 and 0.11
