### ISSUE TITLE
[Manager] Prevent errors from swallowing by epics 

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#4731]
Currently we are catching all errors inside the epics. But this design also catches the errors coming from our code not API responses and since the errors coming our code won't have the format we're expecting, an empty snackbar is displayed as well as an empty item was written in event logs. A fix would be just handle the errors coming from API responses (the errors fall into the `catchError` block) and not handling the errors coming from our code (these should be fixed during the development)

Thanks @eechih for the proposing fix 

~~- [ ] 0.11~~
- [ ] 0.12

**Comment by saivirtue** [comment]
It looks like we could check the error object should be `instance of BasicResponse`, otherwise we throw an exception directly?

**Comment by konekoya** [comment]
Yep, this will do :) But @eechih was thinking moving the catchError operator to where it only handles (catches error) the API response. And leave the business logic (thing like calling paperAPI or transforming the data to fit UI's needs) without any error handling and so the errors could be seen and fix right away during the development
