### ISSUE TITLE
TYPE=OBJECT_KEY + REFERENCE=TOPIC is not working

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#4732]
測試0.9.0的時候發現

如果type設定成OBJECT_KEY，以及REFERENCE=TOPIC，在PIPELINE上可以使用選單，但選取topic後真正存到後端的資料不是OBJECT_KEY而是純文字，例如:
```
"another.topic": "T2",
```

**Comment by chia7712** [comment]
@oharastream/frontend 麻煩幫忙確認一下是否有發生在0.10.0

**Comment by saivirtue** [comment]
> @oharastream/frontend 麻煩幫忙確認一下是否有發生在0.10.0

OK, 感謝回報

**Comment by saivirtue** [comment]
After checking, the issue had been fixed after `0.10`.
I will close this issue and feel free to reopen it if you encountered the same problem in current version :)
