### ISSUE TITLE
[Manager] Shabondi nodeNames definition use reference setting

### ISSUE THREAD

**Issue by eechih** [oharastream/ohara#4736]
Shabondi 的 Node name list 的輸入方式目前有一個缺點，就是輸入 node name 後，必須要按下 Enter 才有效（目前沒有一個好方法提示使用者要去按 Enter），這樣的輸入方式對使用者而言是很不友善。

目前我們有支援下拉選單（多選）的輸入方式，只要 node name list 的 definition 設定 reference 就可以了。 /cc @vitojeng 

我認為選單會比字串輸入更友善。

- [x] 0.10.0 (#4772) (#4854 )

**Comment by vitojeng** [comment]
@eechih Issue title 似乎應該需要修改?

**Comment by eechih** [comment]
> @eechih Issue title 似乎應該需要修改?

done
