### ISSUE TITLE
Add endpoint definition for Shabondi service

### ISSUE THREAD

**Issue by vitojeng** [oharastream/ohara#4739]
目的: 提供在 Ohara Manager 裡, 顯示出該 Shabondi service 提供的 Restful API 的 Method & Endpoint

##### Definition for Shabondi Source

key = "shabondi.source.endpoint"
value = "POST http://$nodeName:$clientPort/"
permission = READ_ONLY

##### Definition for Shabondi Sink

key = "shabondi.sink.endpoint"
value = "GET http://$nodeName:$clientPort/groups/{gropuName}"
permission = READ_ONLY

##### Definition for Shabondi Source

key = "shabondi.endpoint"
value = "http://$nodeName:$clientPort/"
permission = READ_ONLY

##### Definition for Shabondi Sink

key = "shabondi.endpoint"
value = "http://$nodeName:$clientPort/groups/{gropuName}"
permission = READ_ONLY

- [ ] 0.10.x (#4842)
- [x] 0.11.x (#4834)

**Comment by vitojeng** [comment]
@eechih , @chia7712 
Please take a look. Any suggestion is welcome.

**Comment by eechih** [comment]
@vitojeng 或許可以由 api response 說明可支援的 method。value 欄位只放 url。

**Comment by vitojeng** [comment]
@eechih  不太確定你的意思, **api response** 是指?

**Comment by eechih** [comment]
舉個例子，假如 shabondi.source.endpoint 的 value = "http://demo:4567"，使用者也許會用 GET http://demo:4567 去打這個 API，此時 Api 應該要回應 405 Method Not Allowed，並說明只支援 POST 和範例。

**Comment by vitojeng** [comment]
了解, 謝謝

**Comment by vitojeng** [comment]
> 此時 Api 應該要回應 405 Method Not Allowed，並說明只支援 POST 和範例

目前想法是回應 405, 並提供 URL 連到 Shabondi docs (#4792)

**Comment by vitojeng** [comment]
@chia7712 , @eechih 這樣 OK 嗎?

**Comment by chia7712** [comment]
> 目前想法是回應 405, 並提供 URL 連到 Shabondi docs

+1

**Comment by eechih** [comment]
> 目前想法是回應 405, 並提供 URL 連到 Shabondi docs

👍

**Comment by vitojeng** [comment]
@eechih 

確認一下 endpoint 的 value, 你覺得 OK 嗎?

Example:
#### Source
```
{
  "shabondi.endpoint": "http://vito-node00:58456/"
}
```

#### Sink
```
{
  "shabondi.endpoint": "http://vito-node00:58458/groups/${groupName}"
}
```

**Comment by eechih** [comment]
> 確認一下 endpoint 的 value, 你覺得 OK 嗎?

👍

**Comment by eechih** [comment]
另外想問一個可能性，我們能提供一個 API 列出所有可能的 endpoint，例如 `http://vito-node00:58458/groups/`

```
{
  "shabondi.endpoints": 
  [
    "http://vito-node00:58458/groups/aaa", 
    "http://vito-node00:58458/groups/bbb", 
    "http://vito-node00:58458/groups/ccc"
  ]
}
```

**Comment by vitojeng** [comment]
${groupName} 是由使用者自訂的, 無法列出所有的可能

**Comment by vitojeng** [comment]
不過若是需要觀察目前所有 alive group, 這做得到.
有需要的話, 未來可以找時間做.

**Comment by eechih** [comment]
> 不過若是需要觀察目前所有 alive group, 這做得到.
有需要的話, 未來可以找時間做.

👍
