### ISSUE TITLE
[Manager] 輸入 Connector 的設定，停留 5 秒以上文字方塊的值會被清空

### ISSUE THREAD

**Issue by jackyoh** [oharastream/ohara#4767]
目前在測試 pipeline 時，輸入 connector 的設定時，停留 5 秒左右文字方塊的值會被清掉，如下圖輸入 password 之後過 5 秒左右 password 的值會變成空字串。

![2020-05-08 14-29-56 的螢幕擷圖](https://user-images.githubusercontent.com/15885064/81378340-b68bcc80-9139-11ea-8106-75025da51b73.png)

**Comment by eechih** [comment]
@jackyoh thanks for the reporting

**Comment by konekoya** [comment]
@jackyoh This has been fixed in #4727. The PR got merged this morning, could you pull down new images and test again see if it was fixed. Thanks :)

**Comment by jackyoh** [comment]
ok, 我重新再 pull 一次 manager 的 docker image，如果沒問題我就此 issue 關閉。

**Comment by jackyoh** [comment]
更新完 0.10.0-SNAPSHOT docker image 之後，設定 connector 的頁面就不會有清除值的問題了。我把此 issue 關閉
