### ISSUE TITLE
[Question] Could we support "filter" in topic data querying?

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#4780]
For debugging reason, users may want to trace the error raw had been processed or not. Have a basic filter (ex: `cell_1.value === XXX` or `cell_1.name === YYY`) may be a good start?

**Comment by chia7712** [comment]
聽起來不錯，我也喜歡這個功能 :)

**Comment by jackyoh** [comment]
+1

**Comment by vitojeng** [comment]
Any improvement for debugging is awesome.

**Comment by saivirtue** [comment]
針對這個功能有兩種方向：
1. 篩選功能由前端提供，後端會回傳完整的資料筆數
- pros: API不用修改，前端提供一個篩選Input即可
- cons:  當資料筆數過多，無法看到太早之前的資料(API有卡timeout，篩選只能針對部分資料)
2. 篩選功能由後端提供 (ex: `rowName=YYY&rowValue=XXX`)
- pros: 前端功能一致，不需要改太多；當資料筆數過多也可以只看想要的資料
- cons: API實作需要額外的consumer(?)，可能會有效能問題

**Comment by chia7712** [comment]
由後端來做喔，因為後端本來就有提供filter的義務

**Comment by saivirtue** [comment]
@chia7712 
Please help me close this issue if you opened a new task to do this :)

**Comment by chia7712** [comment]
see #4811
