### ISSUE TITLE
Apply Reference.NODE to all kind services

### ISSUE THREAD

**Issue by vitojeng** [oharastream/ohara#4786]
In #4736, we decide add a new reference type `NODE` and apply into Shabondi's _NODE_NAMES_DEFINITION_.

For consistence reason, we should apply the `NODE` reference to _NODE_NAMES_DEFINITION_(key is **nodeNames**) in following services
* zookeeper
* broker 
* worker 
* stream

**Comment by chia7712** [comment]
this is blocked by #4852

**Comment by vitojeng** [comment]
@eechih 
Just update description, please take a look.
Will submit after #4852 is done.

**Comment by vitojeng** [comment]
@chia7712 
I just noticed when creating or updating objects we use both **objectChecker.checkList#nodeNames()** and **objectChecker.checkList#references()**.

For example, in ShabondiRoute:

```scala
    objectChecker.checkList
      .nodeNames(creation.nodeNames)
      .brokerCluster(creation.brokerClusterKey)
      .references(creation.settings, creation.definitions)
      .check()
```

Does that means we perform the node validation twice? 
Just want to make sure I'm correct. That should not a big problem, IMO.

**Comment by chia7712** [comment]
> Just want to make sure I'm correct.
That should not a big problem, IMO. We can improve in the future.

當該key存在的時候，的確會執行兩次，這個要等到我們允許在creation階段檢查所有參數的時候再來調整，也就是只需要呼叫reference check就好了
