### ISSUE TITLE
[Bug] When the topic is running, the workspace restart will fail

### ISSUE THREAD

**Issue by eechih** [oharastream/ohara#4790]
如果pipeline裡面有topic的話，重啟workspace就一定會失敗。原因是topic在尚未stop之前，後端會擋掉任何嘗試關閉broker的請求

_Originally posted by @chia7712 in https://github.com/oharastream/ohara/issues/4539#issuecomment-626520960_

- [x] 0.10 #4862 
- [x] 0.11 #4863

**Comment by eechih** [comment]
> @eechih 我們這邊要幫使用者關閉所有的服務，還是要提示使用者必須先關閉？

@wu87988622 這 case 比較複雜，需要進一步討論

/cc @vitojeng

**Comment by vitojeng** [comment]
@eechih 
記得目前 UI 在建立 topic 時, 會替使用者會自動 start topic. 因此是不是也自動 stop topic?
詢問使用者 start or stop Topic 在前端操作來說似乎有點奇怪.

**Comment by eechih** [comment]
> 記得目前 UI 在建立 topic 時, 會替使用者會自動 start topic. 因此是不是也自動 stop topic?

同意，自動 Stop 才能與自動 Start 的行為一致。
