### ISSUE TITLE
Rename trait/object Agent to improve readability

### ISSUE THREAD

**Issue by vitojeng** [oharastream/ohara#481]
目前 Agent 預設實作是 ssh(應該暫時不會有其他的實作?)
可修改 Agent 以提高可讀性:
* trait com.island.ohara.agent.Agent --> com.island.ohara.agent.SshAgent
* object com.island.ohara.agent.Agent --> com.island.ohara.agent.SshAgent

**Comment by chia7712** [comment]
Agent is a pure interface so we should NOT name it "Ssh"Agent. The best place to "use" sshXXX is the implementation. For example, we can have a SshAgent class extending the Agent (interface).

**Comment by chia7712** [comment]
If we rename the pure interface from Agent to SshAgent, it is almost impossible to provide another implementation, which run the non-ssh connection, in the future.

**Comment by chia7712** [comment]
@vitojeng could we close this one?

**Comment by vitojeng** [comment]
Sure, thanks for reminder
