### ISSUE TITLE
Change imageName definition's permission to CREATE_ONLY

### ISSUE THREAD

**Issue by vitojeng** [oharastream/ohara#4816]
- [x] v0.10.0(#4888)
- [x] v0.11.0(#4876)

**Comment by vitojeng** [comment]
@oharastream/developer  
我想到後端開發時可能會需要改 imageName, 若是 CREATE_ONLY, 這樣至少能在 shabondi create 時指定不同的 imageName. 不能改 imageName 似乎會有點麻煩...

請問這個 imageName 的 permission 是否可以是 CREATE_ONLY ? 對使用者而言是不是等同 READ_ONLY 的效果?

**Comment by chia7712** [comment]
> 請問這個 imageName 的 permission 是否可以是 CREATE_ONLY ? 對使用者而言是不是等同 READ_ONLY 的效果?

就是不能update，一半一半吧XD

**Comment by vitojeng** [comment]
如果我沒理解錯的話, UI user 是使用 create 之後的 settings, 只要 Manager 在 create 時沒有去改 imageName, 那麼 user 應該就是不能更改 imageName.

所以我想若只要達到 user 不能修改 imageName 的目的, 用 CREATE_ONLY 就足夠了. 而直接使用 API 的情況下, 就可以在 create 階段指定自己要的 imageName.
==> 而這是所我期望的, 讓我在 Shabondi 開發階段有機會可以使用自己 build 出來的 image 做測試.

**Comment by chia7712** [comment]
> 所以我想若只要達到 user 不能修改 imageName 的目的, 用 CREATE_ONLY 就足夠了. 而直接使用 API 的情況下, 就可以在 create 階段指定自己要的 imageName.
==> 而這是所我期望的, 讓我在 Shabondi 開發階段有機會可以使用自己 build 出來的 image 做測試.

Yep 現階段使用create_only應該就足夠了

**Comment by vitojeng** [comment]
經討論確認 **imageName** definition permission 改為 CREATE_ONLY
