### ISSUE TITLE
Enable to configure the timeout of ssh connection

### ISSUE THREAD

**Issue by vitojeng** [oharastream/ohara#482]
Currently, agent not set login session timeout value. There will be use default timeout value: 
```java
// org.apache.sshd.client.simple.SimpleClientConfigurator
long DEFAULT_AUTHENTICATION_TIMEOUT = Long.MAX_VALUE;   // virtually infinite
```

We need to set session timeout to prevent **infinite** timeout and make the timeout value configurable.

1. - [ ] for 0.11.0 (#4897)
1. - [ ] for 0.10.0 (#4915)

**Comment by chia7712** [comment]
any update?

**Comment by vitojeng** [comment]
Sorry, not yet. Hope to finish at v0.9.0

**Comment by saivirtue** [comment]
Will this issue merge to `0.9` before today noon?
If not, please help me to move this issue to `0.10` :)

**Comment by vitojeng** [comment]
@saivirtue Thanks for remind!

**Comment by chia7712** [comment]
@vitojeng Let me address this for 0.10.0 as it does cause trouble to us :)

**Comment by vitojeng** [comment]
> @vitojeng Let me address this for 0.10.0 as it does cause trouble to us :)

Thanks for great support!!
