### ISSUE TITLE
Ftp sink connector will fail after expired some time

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#484]
**Describe the bug**
Ftp sink connector will fail after expired connection.max.idle.ms and throw exception

**To Reproduce**
1. Start Ohara Manager, edit pipeline as follows : {ftp source connector} -> topic -> {ftp sink connector}
2. add some data to ftp source connector input folder, will be fine
3. waiting some time and do nothing (now I expected this is equal to connection.max.idle.ms)
4. add some data again, and ftp sink connector will throw errors

**Expected behavior**
data will appear the output folder that ftp sink connector assigned

**Screenshots**
![image](https://user-images.githubusercontent.com/8088616/54515910-73502680-4998-11e9-88a6-13218bb7ebc5.png)

**Operation System (please complete the following information):**
 - Backend OS & Version: CentOS 7.6.1810 (Core)
 - Frontend OS & Version: Windows 10
 - Browser & Version Chrome 72.0.3626.121

**Comment by saivirtue** [comment]
@chia7712 @jackyoh @vitojeng 
這個是Ftp Sink Connector的錯誤，但我認為有使用到這個參數的元件應該都會有問題

**Comment by chia7712** [comment]
It is due to ftp timeout. FTP sink should catch this exception and then re-build connection. This is a bug absolutely.
