### ISSUE TITLE
Support to deploy JDBC source connector on multiple nodes

### ISSUE THREAD

**Issue by jackyoh** [oharastream/ohara#4847]
目前的 JDBC source connector 只支援 1 個 task, 去拉ㄧ個 table 的資料。 ohara 的其它 connector 都已經支援多個 tasks 了另外考慮到效能的問題，因此 JDBC source connector 也需要實作多個 task 去拉一個 table 的資料。

- [x] Multi task for the jdbc source connector (#5360 )

**Comment by jackyoh** [comment]
ping @vitojeng  今天會議結束時有跟 @chia7712 討論 jdbc source connector 實作多個 task 的問題，因為單個 task 有可能會影響到拉資料的效能，因此希望 0.11 能做這個功能。

**Comment by vitojeng** [comment]
@jackyoh 了解.
預計下周會安排會議討論 0.11 要優先進行的事, 到時請你提出來~

**Comment by jackyoh** [comment]
ok, 收到了。

**Comment by chia7712** [comment]
前兩天跟jack討論我才知道jdbc connector還不支援分散式，真是震驚尬

**Comment by jackyoh** [comment]
這個問題預計會在下個 Milestone 修改

**Comment by jackyoh** [comment]
JDBC source connector 的執行要從 1 個 task 修改成多個 task。目前整理執行邏輯如下：

1. 使用 timestammp 產生查詢資料的區間, 範圍從 offset 到 current time 的 timestamp。如果沒有 offset 的 timestamp 的資料，就從 table 裡面取出一筆最早的 timestamp 資料。

2. 將取得的時間範圍區間做切割，放入 queue 裡給不同的 task 做查詢資料使用。如果 queue 裡面的資料已經 consumer 完了之後，再從 memory 的 offset 到 current time 產生時間區間做切割。

舉例：如果目前的時間範圍是 2020-05-10 00:00:00 到 2020-05-14 00:00:00 (用 1 天去切割，切割的方式可以透過設定來決定），將時間轉換成 timestamp 然後切割完成的範圍如下：

```
1589040000000    1589126400000 => 2020-05-10 00:00:00.0    2020-05-11 00:00:00.0
1589126400000    1589212800000 => 2020-05-11 00:00:00.0    2020-05-12 00:00:00.0
1589212800000    1589299200000 => 2020-05-12 00:00:00.0    2020-05-13 00:00:00.0
1589299200000    1589385600000 => 2020-05-13 00:00:00.0    2020-05-14 00:00:00.0
```
之後把切割完成的資料放入 queue 給不同的 task, 做查詢的動作。類似 CsvSourceTask 的 fileNameCache 的作法

3. 每個 task 都會使用 jdbc 去做查詢資料
```
SELECT * FROM table WHERE timestamp > '2020-05-10 00:00:00.0' and timestamp <= '2020-05-11 00:00:00.0'
SELECT * FROM table WHERE timestamp > '2020-05-11 00:00:00.0' and timestamp <= '2020-05-12 00:00:00.0'
SELECT * FROM table WHERE timestamp > '2020-05-12 00:00:00.0' and timestamp <= '2020-05-13 00:00:00.0'
SELECT * FROM table WHERE timestamp > '2020-05-13 00:00:00.0' and timestamp <= '2020-05-14 00:00:00.0'
```
如果查詢資料的 timestamp 大於記憶體的 offset 就會做 memory offset 更新動作。

4. 把查詢到的資料 ResultSet 轉換成 OharaRow 做回傳

**Comment by vitojeng** [comment]
> 前兩天跟jack討論我才知道jdbc connector還不支援分散式，真是震驚尬

有可能因為 jdbc 本身 blocking 的關係, 比較難做吧... XD

**Comment by jackyoh** [comment]
我覺得之後一定會遇到這個問題，所以我來修改看看。

**Comment by chia7712** [comment]
> 你是說 confluent

我是指我們家的jdbc connector XD

我沒看過confluent的版本，@jackyoh 你知道嗎？

**Comment by jackyoh** [comment]
我很久以前有看過 confluent 的 jdbc source connector 的程式碼，如果我沒看錯程式碼的話它是 1 個 task 處裡 1 個 table 的資料。

**Comment by chia7712** [comment]
那看來我們有機會做出更棒的connector了

**Comment by vitojeng** [comment]
> 我很久以前有看過 confluent 的 jdbc source connector 的程式碼

不過那時差不多也二年了吧? XD
說不定已經不同了

**Comment by jackyoh** [comment]
對，差不多二年了。等有空之後我還會再看一次 confluent 的程式碼

**Comment by jackyoh** [comment]
上次設計的查詢資料邏輯因為沒有存放查詢到第幾比資料 (index) 的 offset, 所以 ResultSet 要一次全部走完 pollRecords() 的回傳值會有 OOM 的可能或是 connector 重新啟動之後無法知道之前寫入到第幾筆資料，因此重新想了一個邏輯如下：

1. 取得資料表第一筆 timestamp 資料, 為 start timestamp

2. 將 start timestamp 加上一個固定時間 (例如一天), 為 stop timestamp

3. 如果 start timestamp 和 stop timestamp 超過 current timestamp, pollRecords 的 RowSourceRecord list 回傳 empty

4. start timestamp 和 stop timestamp 是ㄧ個 partition, offset 主要會紀錄資料是否全部都寫入到 topic 裡的布林值 (isCompleted) 以及 index 目前寫入到第幾筆資料

5. 如果 start timestamp 和 stop timestamp 的 isCompleted offset 為 true 的話，就會繼續計算下一個 start timestamp 和 stop timestamp 的 partition, 另外也要確認 partition 的 hash code 不會被不同的 task 重複執行到。

6. 透過 jdbc 來查詢資料並取得 index 的 offset, 如果 offset index 的值小於 ResultSet 走訪 index 的值時，就會將資料取出轉成 OharaRow 把 RowSourceRecord list 回傳

**Comment by chia7712** [comment]
> 上次設計的查詢資料邏輯因為沒有存放查詢到第幾比資料 (index) 的 offset, 所以 ResultSet 要一次全部走完 pollRecords() 的回傳值會有 OOM 的可能或是 connector 重新啟動之後無法知道之前寫入到第幾筆資料，因此重新想了一個邏輯如下：

我先確認一下，這是分散式的邏輯嗎? 就是多個tasks同時啟動的邏輯?

**Comment by jackyoh** [comment]
對，是要做到分散是的架構。所以會把資料切割成多個查詢的區間 (start timestamp 和 stop timestamp), 然後給不同的 task 執行。因為怕查詢相同的 timestamp 資料太多，有可能還是會發生 oom 所以才會拿 index 當作 offset 使用。
