### ISSUE TITLE
[Manager] Event log relative minor bugs

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#4882]
- Event log notification is clear when page is refreshed Event log notification is loaded
- Event log panel is not loading and show nothing when opened

**Comment by saivirtue** [comment]
After some testing, I think the problem is related to the following section:
```
const getLogFromLocalForge$ = () =>
  defer(() => localForage.keys()).pipe(
    mergeMap(keys =>
      zip(...keys.map(key => defer(() => localForage.getItem(key)))),
    ),
    map(values =>
      values.map(value => ({
        key: get(value, 'key'),
        type: get(value, 'type'),
        title: get(value, 'title'),
        createAt: get(value, 'createAt'),
        payload: get(value, 'payload'),
      })),
    ),
  );
```

Since the `.keys()` and `.getItem()` is return `Promise`, we can not assert the data will show immediately when click the eventLog Pannel...

/cc @konekoya

**Comment by konekoya** [comment]
Good finding @saivirtue 👍
