### ISSUE TITLE
[Question] Should we move the Settings Dialog from react context to redux state?

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#4894]
I've faced a strange problem:
1. create workspace **w1** and **w2**
2. switch to workspace **w1**, and click `Settings`
3. Delete this workspace
4. UI will redirect to head workspace `/w2`, but the `Settings` Dialog will remain open (It is **w2** Settings Dialog)

Since I cannot close this dialog after epic finished, have no clue how to achieve this...

**Comment by konekoya** [comment]
> Since I cannot close this dialog after epic finished, have no clue how to achieve this...

I think we can and should probably move the state to redux, but this will need to change a lot of files and code. Maybe we could do this in 0.11? As for now, can we just pass settings dialog's close handler down to the progress bar dialog?

**Comment by saivirtue** [comment]
>  As for now, can we just pass settings dialog's close handler down to the progress bar dialog?

This is the problem I faced. Since the data flow of epic is by trigger an action, the close handler could not be triggered normally if we passed it down to the progress bar (it will close the Dialog immediately and do the delete works in the background...)

**Comment by konekoya** [comment]
Ah, you're right. Didn't think about that. So this issue still exist even after is merged, right 
https://github.com/oharastream/ohara/pull/4910

**Comment by saivirtue** [comment]
Sadly, yes 😞

**Comment by konekoya** [comment]
QQ... cc @eechih and @wu87988622

**Comment by eechih** [comment]
@saivirtue @konekoya 請參考 NodeListDialog.handleCreate 作法，看看是否有幫助？

**Comment by saivirtue** [comment]
恩...對，還有passing function的方法，我忘了XD
的確是可以暫時先將這個問題處理掉 👍 
只是希望之後還是可以將這類操作一併在Epic內解決，感謝 @eechih !

我先把這個issue留著做紀錄

**Comment by saivirtue** [comment]
This issue could not be reproduced after #5510, close now.
