### ISSUE TITLE
[Manager] Implement rollback for delete workspace process

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#4898]
- enable `rollback`, `resume` and `pause` in UI
- add tests of deleteWorkspace

**Comment by saivirtue** [comment]
Big thanks @eechih !

**Comment by eechih** [comment]
The deletion of workspace will not support rollback.

<img width="400" alt="螢幕快照 2020-06-22 下午3 13 01" src="https://user-images.githubusercontent.com/703126/85259067-f6fd9a80-b49a-11ea-9f45-1f4d5b677f51.png">
