### ISSUE TITLE
[Manager] Move Fullscreen dialog's close button to the right

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#4903]
> > 最上面背景藍色的往左箭頭改成"X"，並且放到右上方 (因為點選後目前都是回到"首頁")
> 
> And so the "Settings" would be removed and only a cross icon is displayed, right?

For a glance, like this:
![image](https://user-images.githubusercontent.com/8088616/82137456-d19dc100-984a-11ea-8bbf-f5c2535ae9ad.png)

_Originally posted by @saivirtue in https://github.com/oharastream/ohara/issues/4539#issuecomment-629750580_

- [x] 0.10 (#4907)
- [x] 0.11 (#4906)

**Comment by konekoya** [comment]
Hmm, are we going to apply this for all fullscreen dialogs or just this particular one? (settings)
@oharastream/frontend

**Comment by eechih** [comment]
為了一致性，應該要套用全部的 fullscreen dialogs :)
