### ISSUE TITLE
worker image doesn't package ohara.validator jar

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#491]
**Describe the bug**
Test connection button is not working as it should

**To Reproduce**
1. Create a new pipeline and add a new connector to the graph (e.g. FTP sink connector)
2. Fill in the connection settings and click on the Test connection button

**Expected behavior**
The test connection button should work as it should

**Screenshots**
Nope

**Operation System (please complete the following information):**
 - CentOS
 - MacOS
 - Chrome

**Additional context**
See the full error logs [here](https://paper.dropbox.com/doc/Validate-API-error-response--AZp2lvlnFaHnvsPcY5HJTpRQAQ-z3rUUVngvrDc8cxtIYiL3)

**Comment by chia7712** [comment]
#181 change the assembly from ohara-configurator to ohara-connector. BUT, the validator implementation is still in ohara-configurator. I feel it is good time to move validator from configurator to connector...I will file a PR to address it.

**Comment by konekoya** [comment]
Thanks for digging into this :)
