### ISSUE TITLE
[Manager] Prevent deletion of stream jar or plugin jar used by the pipeline

### ISSUE THREAD

**Issue by eechih** [oharastream/ohara#4960]
被 pipeline 使用的 stream jar, plugin, shared jar 不能被移除，相關的 file 也不能被刪除。

被 pipeline 使用 意味著該元件被拖到 paper 中（只出現在 toolbox 的話，就不算）。

_Originally posted by @eechih in https://github.com/oharastream/ohara/issues/4539#issuecomment-630680690_

**Comment by eechih** [comment]
@chia7712 Pipeline api 回傳的物件有一個 jarKeys，我可以拿這個資訊用來判斷某個 jar file 被 pipeline 所使用嗎？

<img width="554" alt="螢幕快照 2020-05-25 上午10 19 54" src="https://user-images.githubusercontent.com/703126/82772287-52734300-9e71-11ea-9959-4ce4509abda0.png">

**Comment by eechih** [comment]
@chia7712 我加入兩個 jar (ohara-it-source.jar, ohara-it-0.10.0-SNAPSHOT.jar) 重啟 workspace 後。再建立一個新的 pipeline，將 FtpSource 拖進 pipeline 後，我發現 jarKeys 會包含 ohara-it-source.jar, ohara-it-0.10.0-SNAPSHOT.jar，這不是我預期要的結果。因為 FtpSource 不屬於上述兩個 jar 的 class。

**Comment by chia7712** [comment]
> 我加入兩個 jar (ohara-it-source.jar, ohara-it-0.10.0-SNAPSHOT.jar) 重啟 workspace 後。再建立一個新的 pipeline，將 FtpSource 拖進 pipeline 後，我發現 jarKeys 會包含 ohara-it-source.jar, ohara-it-0.10.0-SNAPSHOT.jar，這不是我預期要的結果。因為 FtpSource 不屬於上述兩個 jar 的 class。

因為這個jar keys是純粹為前端服務，在實際應用上是要幹啥我已經不記得了

不過就程式碼來說，該jar keys的概念是包含:

1. stream jar 如果該stream被pipleine所引用
1. connector jar from a worker 如果該worker有被pipeline所引用

> 因為 FtpSource 不屬於上述兩個 jar 的 class。

物理上來說，我們很難得知該connector是從"哪一個jar"來，就如同streams裡面我們也無法得知該class是從哪一個jar來，因為java允許classpath上有重複的class，至於載入誰載入後，可能參考順序，也可能根據當下誰在記憶體

**Comment by eechih** [comment]
> 因為這個jar keys是純粹為前端服務，在實際應用上是要幹啥我已經不記得了

前端需要知道 pipeline 與 jar 的關係，例如哪些 pipeline 使用了哪些 jar。如果每個 jar 被 pipeline 所使用，照理講該 jar 應該不能從 worker 中移除。

> 2. connector jar from a worker 如果該worker有被pipeline所引用

一旦某個 pipeline 加入了**某個** connector jar from a worker，Pipeline Api 就會把**全部** 
 connector jar from a worker 放進 jarKeys，這會導致無法從 worker 移除沒有被使用的 jar。

最糟的情況是，如果想從 worker 移除某個 jar，就必須先把全部 pipeline 的全部 connector 都刪除。 :(

/cc @oharastream/developer

**Comment by chia7712** [comment]
> 最糟的情況是，如果想從 worker 移除某個 jar，就必須先把全部 pipeline 的全部 connector 都刪除。 :(

我先說一下後端的邏輯再更新jar的話的步驟

1. connectors必須先停掉
1. worker停掉
1. remove jars from worker
1. remove jars
1. upload new jars
1. add jars to worker
1. restart worker
1. restart connectors

對前端來說，當使用者很明確地想要刪除一個jar，我的想像是:

1. 提醒使用者要先停止所有connectors
1. 接著執行上述步驟

過程中最可能出現的問題是: 使用者把正在使用的connector class移除掉，那麼就會遇到啟動connector時噴出錯誤。這邊一個簡單的預防機制是用inspect去看看該jar是否有connector與pipleine上的"同名" (不一定被使用，但同名就有可能，這邊可以做個提醒)

**Comment by eechih** [comment]
@chia7712 你的意思是說前端不要用 pipeline 的 jarKeys 作為是否可以從 worker 移除 jar 的依據嗎？

**Comment by chia7712** [comment]
> 你的意思是說前端不要用 pipeline 的 jarKeys 作為是否可以從 worker 移除 jar 的依據嗎？

對，因為從物理意義上來說我們"很難確定"刪除該jar會否造成使用者的connector出問題，因此如我前一個留言所說，我們可以透過inspect APIs給一個"很有可能出問題"的提醒，而使用者如果堅持要刪那就是使用者自己的選擇

**Comment by eechih** [comment]
> 對，因為從物理意義上來說我們"很難確定"刪除該jar會否造成使用者的connector出問題，因此如我前一個留言所說，我們可以透過inspect APIs給一個"很有可能出問題"的提醒，而使用者如果堅持要刪那就是使用者自己的選擇

OK, I will fire another issue #5030 to resolve.

@chia7712 請你確認一下，假如 jarKeys 沒有用途，請移除這個資訊，避免誤用。

**Comment by chia7712** [comment]
> 假如 jarKeys 沒有用途，請移除這個資訊，避免誤用。

#5030做完後我會刪除多餘的jarkeys

**Comment by eechih** [comment]
Close this issue since it will resolved by #5030
