### ISSUE TITLE
[Manager] Error for using an existing name to create new element in Paper is not logged in event log

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#4972]

**Comment by konekoya** [comment]
Okay, this seems to be something we should discuss... I'm not sure what should be included in the error message throwing from components. Could we just throw an error with title?

@oharastream/frontend

**Comment by konekoya** [comment]
@eechih @saivirtue need some suggestions on this 🙏

**Comment by saivirtue** [comment]
> Could we just throw an error with title?

That sounds not bad...do you have a snapshot view of event logs about the duplicated name?

**Comment by konekoya** [comment]
In favor of #4988 #4989
