### ISSUE TITLE
[Question] Could we add an "Add autofill" button in the property dialog

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#4977]
And so users can link to settings' autofill page and create new autofill there?

/cc @eechih :)

**Comment by konekoya** [comment]
Ping @eechih 👋

**Comment by eechih** [comment]
Copy 有類似 `Add autofill` 的功能，如果再加一個 `Add autofill` button 是否會混淆使用者呢？

我的想法是應該要重新思考 Autofill，這個功能的重要性越來越高了 :)

<img width="198" alt="螢幕快照 2020-05-29 下午5 17 41" src="https://user-images.githubusercontent.com/703126/83243398-6a7bf700-a1d0-11ea-9ab7-d269318b09bc.png">

**Comment by konekoya** [comment]
Agree, didn't think too much about this XD. I will close this then. Thanks :)
