### ISSUE TITLE
[Manager] Shabondi Sink default value cannot display in Property Editor

### ISSUE THREAD

**Issue by eechih** [oharastream/ohara#4984]
Shabondi Sink defalut value cannot display in Property Editor.

![screenshot 15](https://user-images.githubusercontent.com/475186/82539483-180f5a80-9b80-11ea-9cc6-168cc23ae3e9.jpg)

_Originally posted by @vitojeng in https://github.com/oharastream/ohara/issues/4539#issuecomment-631958834_

**Comment by konekoya** [comment]
@eechih I can help on this one :)

**Comment by eechih** [comment]
@konekoya Thanks, 不過我已找到原因了 :)

**Comment by eechih** [comment]
@vitojeng 這個問題造成的原因可能是 UI 不認得 Shabondi Settings 的 Duration 格式。

我記得之前有討論過這個問題，後端要統一將 Duration 轉成 UI 約定好的格式，例如： 180000 milliseconds

- Shabondi Definitions
<img width="783" alt="螢幕快照 2020-05-22 上午10 16 46" src="https://user-images.githubusercontent.com/703126/82624622-a386fb00-9c15-11ea-9b51-ce8839e0a202.png">


- Shabondi Settings
<img width="651" alt="螢幕快照 2020-05-22 上午10 14 18" src="https://user-images.githubusercontent.com/703126/82624628-a84baf00-9c15-11ea-991a-9d56324e6a6a.png">

**Comment by vitojeng** [comment]
@eechih Okay, got it. Let me fix this.

**Comment by vitojeng** [comment]
this issue should be resolved by #4998
