### ISSUE TITLE
Replace assertException by Assert.assertThrows

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#5001]
Ohara don't need the duplicate function :)

**Comment by chia7712** [comment]
@jackyoh 有沒有興趣接手這個議題?

**Comment by jackyoh** [comment]
有興趣。那我把 Assignees 修改成我，我嘗試著來改看看

**Comment by jackyoh** [comment]
我會把 OharaTest#assertException 的方法移除掉， 然後全部改成 Assert.assertThrows
