### ISSUE TITLE
[Manager] Prevent users from using negative values in duration definition 

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#5015]
![擷取選取區域_011](https://user-images.githubusercontent.com/6234750/82757990-72294d80-9e16-11ea-8e69-e8dc7613c385.png)

duration應該總是>0

_Originally posted by @chia7712 in https://github.com/oharastream/ohara/issues/4539#issuecomment-633248061_

**Comment by konekoya** [comment]
Should also apply this to all form inputs that are not suppose to use negative values

**Comment by konekoya** [comment]
@chia7712 While working on this, I have noticed that some of the definitions should probably use positive number as well (not entirely sure, need your help on this...) For example:

__JDBC fetch size__, __JDBC flush size__. These two defs are using `INT` value type so both of them can be filled with negative number as well.

Similarly, FTP connector's __Rotate Interval(MS)__ uses `LONG` so it can accept negative number as well in our UI...

**Comment by chia7712** [comment]
數值的部分有分一般的和正整數

例如LONG 和 POSITIVE_LONG

對UI來說就是前者可以負數，後者不行
至於你提到的例子是後段寫connector選擇了不適當的定義

**Comment by konekoya** [comment]
> 例如LONG 和 POSITIVE_LONG

👌 

> 後段寫connector選擇了不適當的定義

No problem, should i open an issue to list these definitions :)

**Comment by chia7712** [comment]
> No problem, should i open an issue to list these definitions :)

@jackyoh 這個工作應該比較適合你 :)

**Comment by jackyoh** [comment]
ok, 我來處裡。

我來先確認一下議題，目前看起來是 connector definitions 定義錯誤，而造成前端可能會在操作數值方面可能會有問題，例如是正負數的問題。所以我應該要開個議題來修改 definitions 錯誤定義的部份。

**Comment by konekoya** [comment]
I'm closing this issue off since the PR has been merged. @jackyoh Feel free to open a new issue to address the problems we talked about 🙏 Many thanks!

**Comment by chia7712** [comment]
@konekoya 

duration這個類別不應該讓使用者輸入負數，這個有處理了嗎?

**Comment by chia7712** [comment]
現在跟數字有關的types中以下幾個都不該有負數的產生:

1. duration
1. POSITIVE_SHORT
1. POSITIVE_INT
1. POSITIVE_LONG
1. POSITIVE_DOUBLE

**Comment by konekoya** [comment]
Yep. These are all taken care of. We have set a min number for all these types.

**Comment by chia7712** [comment]
> Yep. These are all taken care of. We have set a min number for all these types.

確認一下，這是剛修復的嗎 (在我提出問題之後)

**Comment by konekoya** [comment]
只有 duration 是剛修復

**Comment by chia7712** [comment]
> 只有 duration 是剛修復

了解
