### ISSUE TITLE
Cannot convert duration type when shabondi image startup

### ISSUE THREAD

**Issue by vitojeng** [oharastream/ohara#5024]
![screenshot 26](https://user-images.githubusercontent.com/475186/82776676-4c379380-9e7e-11ea-9168-d757807509ae.jpg)

**Comment by vitojeng** [comment]
This root cause of this issue is the value of parameter contains whitespace character.
Example: ```shabondi.sink.poll.timeout=1500 milliseconds```

Whitespace character will lead `milliseconds` as another input parameter.

**Comment by chia7712** [comment]
我剛剛看了一下shabondi collie，裡面產生參數列表的地方沒有用雙引號，可以參考一下stream collie的寫法

**Comment by vitojeng** [comment]
shabondi collie 有參考 stream collie 的做法處理雙引號. 另外, 單純加上雙引號無法解這個 issue.
若不改 shell script , 目前似乎只能參考雙引的處理方式, 使用另一組 escape string.
不知是否還有更好的做法?

**Comment by vitojeng** [comment]
@chia7712 
* 似乎沒有看到 stream collie 裡有為參數加上雙引號. stream collie 有為雙引號做 escape, 這部份 shabondi 也有做.
* 參數加上雙引號, 你的意思是這樣嗎?
`"shabondi.sink.poll.timeout=1500 milliseconds"`

**Comment by vitojeng** [comment]
目前最簡單的做法似乎也是避免使用 whitespace, 所以也需要對 whitespace 做 escape.

**Comment by chia7712** [comment]
> 參數加上雙引號, 你的意思是這樣嗎?

k和v各自加上雙引號，參數的傳遞現在是透過參數列表而非環境變數，或許那個環境變數的加工可以刪掉了

**Comment by vitojeng** [comment]
shabondi collie 現在只有 JMX_PORT, JMX_HOSTNAME, OHARA_HEAP_OPTS 這三個環境變數.
用 escape 加工的部份是在參數列(arguments).

**Comment by chia7712** [comment]
我倒是覺得不管是k8s或是docker，透過參數傳遞實在有點危險，字符限制太多

或許我們要開放讓stream或shabondi反向對configurator拉參數回去，這樣可以避免掉許多限制

**Comment by vitojeng** [comment]
在有新的做法前，我想可以用 base64 encode/decode 解這個問題?
ping @oharastream/backend

**Comment by chia7712** [comment]
用base64作為暫時解這個沒問題

不過增加更多encode/decode將使我們維護/升級變得更加麻煩。現在故事是我們中間傳遞資料是透過shell arguments，這個對字符的限制會增加我們在處理字串的工作量，同時現在我們是server端encode，然後仰賴client去正確decode，這就產生諸如相容性如何處理等議題。考量我們用了很大力氣維護public APIs這個協定，在其他服務上我們也應該盡可能重複使用這個工具。

**Comment by vitojeng** [comment]
yes. 我也不喜歡 encode/decode. 因此我現在是在想, 在有新的方案前要用那一種暫解...
現在可能會先延用現雙引號的做法吧, 看起來最簡單.

**Comment by chia7712** [comment]
就開個議題留到0.11.0來處理，然後快上個PR來弄暫時解～
