### ISSUE TITLE
[Manager] Generate dropdown list for recommendedValues

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#5035]
![擷取選取區域_012](https://user-images.githubusercontent.com/6234750/82758108-2cb95000-9e17-11ea-8047-2a763a34b334.png)

recommendedValues沒有產生對應的下拉選單

_Originally posted by @chia7712 in https://github.com/oharastream/ohara/issues/4539#issuecomment-633248677_

**Comment by saivirtue** [comment]
@chia7712 
請問一下，這個欄位會對哪一些Type產生下拉選單?  目前看起來只有Type.STRING會需要?

**Comment by chia7712** [comment]
> 請問一下，這個欄位會對哪一些Type產生下拉選單? 目前看起來只有Type.STRING會需要?

目前後端只開放Type.String可以搭配recommendedvalues，現階段可以只處理這個case

**Comment by saivirtue** [comment]
> 現階段可以只處理這個case

OK
