### ISSUE TITLE
[Manager] Connector error state is not correctly reflected on Paper

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#5038]
![註解 2020-05-25 172703](https://user-images.githubusercontent.com/6234750/82799660-faf2c880-9eac-11ea-8c0a-aefd9a53b23b.png)

1. 當沒有任何task是成功的時候，connector應該要顯示成"失敗"
- [x] the connector is in running only if there are a running master and a slave at least (#5051)
2. 應該要顯示錯誤的原因 (抓error這個欄位)
- [x] Redesign and display the full error in Property view's Nodes panel (#4993)

_Originally posted by @chia7712 in https://github.com/oharastream/ohara/issues/4539#issuecomment-633476475_

**Comment by chia7712** [comment]
@konekoya this is related to backend. Let me take over this issue :)
