### ISSUE TITLE
the recommendedValues are not applied to Table type

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#5061]
1. - [x] add recommendedValues to dataType column (#5062)
2. - ~~[ ] [Manager] Apply recommendedValues to Type.Table~~ (implemented in #3408)

**Comment by chia7712** [comment]
@saivirtue please add your PR to description :)

**Comment by saivirtue** [comment]
The part of UI appears to be implemented by @wu87988622 (thanks again, @wu87988622 !)
I will update the description later

**Comment by chia7712** [comment]
@saivirtue ok. Let me close this issue :)
