### ISSUE TITLE
[Manager] Errors encountered were not handled correctly when user establish a pipeline

### ISSUE THREAD

**Issue by vitojeng** [oharastream/ohara#5077]
**Describe the bug**
沒有正確地處理錯誤的情形

**To Reproduce**
1. 在 Quickstart VM, 建立一個 workspace
2. 建立一個 pipeline
3. 拖入 Shabondi Source: s1
4. 拖入 Shabondi Sink: s2
5. 連線 s1 --> s2: 自動建立 T1
6. T1 始終呈現橘色, 但 Event log 沒有錯誤訊息
7. 打開 Web Developer Tools
    * 發現有 request 出現 Response 500
8. 在 Manager 頁面重新 refresh 後, 在 pipeline(p1) 發現 T1 沒有被建立
9. 單獨呼叫 GET /api/topics, 其實 T1 有被建立

**Expected behavior**
* 操作過程中若有錯誤，須能在 Pipeline 及 Event Log 呈現出來
* 頁面 refresh 後, 能呈現 T1

**Screenshots**
* Pipeline
![screenshot 33](https://user-images.githubusercontent.com/475186/82984789-6b245a00-a025-11ea-9fa9-89d0bfbd3612.jpg)
* Web Developer Tools, 發現有 http response 500, 且 Event Logs 沒有記錄
![screenshot 34](https://user-images.githubusercontent.com/475186/82984807-72e3fe80-a025-11ea-8cf2-97607a634e80.jpg)
![screenshot 35](https://user-images.githubusercontent.com/475186/82984818-79727600-a025-11ea-8333-ee0015b06037.jpg)
![screenshot 36](https://user-images.githubusercontent.com/475186/82984851-8b541900-a025-11ea-8ab3-d2c6faebefba.jpg)
* Web page after refresh, topic T1 沒有建立(沒有顯示)
![screenshot 37](https://user-images.githubusercontent.com/475186/82984888-97d87180-a025-11ea-8427-a6afbcad6efc.jpg)
* T1 實際建立成功
![screenshot 38](https://user-images.githubusercontent.com/475186/82985370-8348a900-a026-11ea-811b-119ecd6deef3.jpg)
* 在 workspace settings 裡可以找到 T1, 看出沒有對應的 Pipeline. T1 成了不能刪除的孤兒. XD
![screenshot 39](https://user-images.githubusercontent.com/475186/82986439-657c4380-a028-11ea-9488-3a7b40003bde.jpg)

**Operation System (please complete the following information):**
 - Browser & Version - Firefox 76.0.1

**Additional context**

**Comment by konekoya** [comment]
@vitojeng I can confirm this is a bug. And the issue here is that shabondi is trying to connect to a topic which is not yet ready (still starting...) so Configurator will return a failed response and thus the error described in the above. 

```json
{
  "code": "oharastream.ohara.configurator.route.ObjectCheckException",
  "message": "type:topic {\"group\":\"3e1117d3c\",\"name\":\"zx5wd\"} does not exist ",
  "stack": "oharastream.ohara.configurator.route.ObjectCheckException: type:topic {\"group\":\"3e1117d3c\",\"name\":\"zx5wd\"} does not exist \n\tat oharastream.ohara.configurator.route.ObjectChecker$$anon$1$$anon$2.compare(ObjectChecker.scala:653)\n\tat oharastream.ohara.configurator.route.ObjectChecker$$anon$1$$anon$2.$anonfun$check$24(ObjectChecker.scala:718)\n\tat scala.concurrent.impl.Promise$Transformation.run(Promise.scala:430)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\n"
}
```

**Comment by saivirtue** [comment]
Look at the snapshot, the `POST /topics` (create topic) seems executes successfully.
This is due to the `topic creation` and `connector update` requests sent at the same time; the `connector update` request may failed if the topic object is not ready yet in configurator.

**Comment by vitojeng** [comment]
LGTM, QA passed.
