### ISSUE TITLE
[Manager] The dragging icon of component in toolbox display incorrect

### ISSUE THREAD

**Issue by vitojeng** [oharastream/ohara#5078]
**To Reproduce**
1. 建立一個 Pipeline
2. 移動 Toolbox 到右方
3. 拖出一個 component
4. 可以看到 icon 與游標距離很遠

**Comment by vitojeng** [comment]
@konekoya 不算 critical bug, 因此 version 我先設在 v0.11

**Comment by konekoya** [comment]
Roger that 👌🏼

**Comment by konekoya** [comment]
Can confirm this is a bug, but I can only repro this in Firefox :)

![Imgur](https://imgur.com/ChecmLo.png)
