### ISSUE TITLE
[Question] 在 Quickstart VM, 建立一個 node IP 錯誤的情況

### ISSUE THREAD

**Issue by eechih** [oharastream/ohara#5084]
在 Quickstart VM, 建立一個 node IP 錯誤的情況:
* 輸入一個不存在的 IP
* 若是在 Create workspace 的階段進行 create node, 若發生錯誤須要提醒使用者.
* POST http://${host}:5050/api/nodes
  * 回傳 200, 但在 json 裡的 error 為 "the docker on xx.xx.xx.xx is unavailable"
* Event log 沒有錯誤訊息
  * 應該要有 error message
* State 呈現不同: 在 all nodes table 呈現 "Unavailabe" , 在 detail 呈現 "Dead"
  * 訊息應該要統一, 顏色若用紅色, 也要統一

![screenshot 30](https://user-images.githubusercontent.com/475186/82975437-00682400-a00f-11ea-871a-293d4bd58c98.jpg)
![screenshot 32](https://user-images.githubusercontent.com/475186/82975474-1ece1f80-a00f-11ea-96fe-c89cd1426885.jpg)

_Originally posted by @vitojeng in https://github.com/oharastream/ohara/issues/4539#issuecomment-634409841_

**Comment by saivirtue** [comment]
IIRC, the description:
> 若是在 Create workspace 的階段進行 create node, 若發生錯誤須要提醒使用者.

We could not select the `Unavailable` node after #4947?

**Comment by eechih** [comment]
> 輸入一個不存在的 IP
> Event log 沒有錯誤訊息
> 應該要有 error message

@vitojeng API 回應的狀態只要是 200 都視為成功，所以不會出現 error message。我們應該要進一步討論 Api 回應的狀態。

**Comment by eechih** [comment]
> IIRC, the description:

>> 若是在 Create workspace 的階段進行 create node, 若發生錯誤須要提醒使用者.

> We could not select the Unavailable node after #4947?

@saivirtue Yep

@vitojeng 無效的 node 在 create workspace 是不能被選擇的

<img width="960" alt="螢幕快照 2020-05-27 下午4 34 13" src="https://user-images.githubusercontent.com/703126/82996765-09b9b680-a038-11ea-8d71-ee6931d889ee.png">

**Comment by eechih** [comment]
Will be resolved by #5085
