### ISSUE TITLE
Service cache does not update the shabondi

### ISSUE THREAD

**Issue by jackyoh** [oharastream/ohara#5090]
使用 docker mode 啟動 shabondi source 的 pipeline 之後，透過 shabondis 的 restful api 查看資訊時發現 aliveNode 的 list 為 empty。目前已經排除是資源不夠的問題，有可能是程式的 bug

**Comment by chia7712** [comment]
The root cause is that we don't update the service cache for shabondi so our route can't see shabondi in docker mode :(

**Comment by jackyoh** [comment]
I got it. Thank you! ping @vitojeng  FYI

**Comment by vitojeng** [comment]
Thanks @chia7712 !
