### ISSUE TITLE
[Manager] Errors encountered were not handled correctly when user create workspace

### ISSUE THREAD

**Issue by vitojeng** [oharastream/ohara#5101]
**Describe the bug**
Exception not handle properly.

**To Reproduce**
1. Use QuickstartVM 0.10.0-SNAPSHOT
2. Create workspace
  2.1. Step 1: name `workspace1`
  2.2. Step 2: Create a new node and add it
  2.3. Step 3: Submit, encounter an error
  2.4. Step 3: Submit, encounter an error
  2.5. Step 3: Submit, encounter an error
  2.6. Check developer tools, find three errors.
  2.7. Back to Step 1, and cannot move to Step 3

**Expected behavior**
User can retry to submit if encounter server side error.

**Screenshots**
* Create workspace
![screenshot 41](https://user-images.githubusercontent.com/475186/83112133-4947d780-a0f8-11ea-9abf-cd9098546dbf.jpg)
* Encounter three errors
![screenshot 1](https://user-images.githubusercontent.com/475186/83113430-3c2be800-a0fa-11ea-8f19-02c1d26a57ef.jpg)
* Response of error1
![screenshot 2](https://user-images.githubusercontent.com/475186/83113451-41893280-a0fa-11ea-903d-982bd79df1f8.jpg)
* Response error 2, error 3
![screenshot 3](https://user-images.githubusercontent.com/475186/83113462-451cb980-a0fa-11ea-98d2-55bec42b889c.jpg)
* Cannot move to Step3
![screenshot 6](https://user-images.githubusercontent.com/475186/83114293-603bf900-a0fb-11ea-97b8-a384b3d9f6ef.jpg)

**Comment by saivirtue** [comment]
> 2.2. Step 2: Create a new node and add it
2.3. Step 3: Submit, encounter an error

Is the node expected valid? (i.e., the POST of `/nodes` return 200 and the node is `Available`)

**Comment by vitojeng** [comment]
yes. create node succeed.

**Comment by vitojeng** [comment]
想法討論: 
1. create workspace 一定有可能遇到 server side error. 而 user 遇到 error 後, 一定會想做 retry submit. 因此若 create workspace 過程遇到任何 fail, 曾經建立過的物件可能都需要被清除. 讓使用者可以 retry.
2. 目前 create workspace 若遇到錯誤, 其訊息只會短暫停留, 使用者有可能會沒有看到. 這部份需要修改.

**Comment by saivirtue** [comment]
> create workspace 一定有可能遇到 server side error. 而 user 遇到 error 後, 一定會想做 retry submit. 因此若 create workspace 過程遇到任何 fail, 曾經建立過的物件可能都需要被清除. 讓使用者可以 retry.

目前暫時解法可以重新刷新葉面(或回到home page)，從Settings的Delete workspace來刪除該未成功建立的workspace

**Comment by konekoya** [comment]
I'm not seeing this issue anymore. Has anyone run into this issue recently? If not, maybe we can consider closing this :)

**Comment by saivirtue** [comment]
> create workspace 一定有可能遇到 server side error. 而 user 遇到 error 後, 一定會想做 retry submit. 因此若 create workspace 過程遇到任何 fail, 曾經建立過的物件可能都需要被清除. 讓使用者可以 retry.

Thanks for the works of @eechih in #5247, We could `retry` the failed step in workspace creation.

**Comment by vitojeng** [comment]
How about move to QA phase if you guys think that this bug should be resolved ?

**Comment by saivirtue** [comment]
> How about move to QA phase if you guys think that this bug should be resolved ?

Sounds great!

**Comment by vitojeng** [comment]
QA passed. LGTM!
Thanks @oharastream/frontend !
