### ISSUE TITLE
Replace Apache archive by local mirror when building image by jenkins

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#5130]
The later is more faster :)

概念上我們依然保持dockerfile使用apache site，但在jenkins上我們把site換成local mirror，例如http://ftp.mirror.tw/pub

**Comment by chia7712** [comment]
FYI @jackyoh

**Comment by chia7712** [comment]
@jackyoh 我們的dockerfile有支援更換site，參數為MIRROR_SITE

可否麻煩你修改一下jenkins script讓它換成本土的mirror?

**Comment by chia7712** [comment]
@jackyoh 我先更新了QA的部份，然後也讓#5127重跑一次看看是否正常

我要先去吃飯了～你如果看到有空的話幫忙換換CD的site

**Comment by jackyoh** [comment]
> 你如果看到有空的話幫忙換換CD的site

收到，我來換看看 CD 的部份。

**Comment by chia7712** [comment]
seems the origin link works well. I'm going to close this issue.
