### ISSUE TITLE
[QA] Add a new task for tests of UI flow

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#5143]
UI testing will be separated into two different tasks:
1. **manager-e2e**: ought to basic normal case for UI flow, base on our test cases of QuickStart VM. Will use `k8s mode` to do this
2. **manager-it**: ought to test all the UI flow except runtime data (like start/stop). Will use `fake mode` to do this

~~To achieve the above purposes, we need to pass `--fake` and `--k8s` from our running command to QA script~~

**Comment by chia7712** [comment]
理論上測試都是靠public APIs 那跟使用哪一種模式的關聯為何？

**Comment by saivirtue** [comment]
manager-e2e會測試會與真實環境比較相同，由於前端測試會比較需要針對同一個頁面做各種不同操作來測試是否符合預期 (對public API來說就是同一隻、甚至是一組API，會用不同的資料不斷的重複呼叫)

因此在考量QA的資源與測試的時間下，我們希望把重複測試但與**真實環境**比較不相干的測試(例如：Paper內components彼此間連線或同名稱component重複加入、多組workspace與多組pipeline等)可以獨立出來，而e2e專心測試一般情況是否正常(例如我們Demo的流程就可以放進來)

**Comment by vitojeng** [comment]
> 因此在考量QA的資源與測試的時間下

@saivirtue 白話一點就是 k8s 資源耗費與時間過大，而有些 e2e 測試其實在 fake mode 上測試即已足夠，可以不須要用到 k8s 真實的環境。是這樣吧？ 😄

**Comment by saivirtue** [comment]
> 而有些 e2e 測試其實在 fake mode 上測試即已足夠

Indeed :)

**Comment by chia7712** [comment]
> 因此在考量QA的資源與測試的時間下，我們希望把重複測試但與真實環境比較不相干的測試(例如：Paper內components彼此間連線或同名稱component重複加入、多組workspace與多組pipeline等)可以獨立出來，而e2e專心測試一般情況是否正常(例如我們Demo的流程就可以放進來)

這個設計很棒。

> we need to pass --fake and --k8s

那這個的用途為何？ 我想像中前端的e2e和it會是不同的指令，然後都會額外吃一個configurator的路徑。例如我想測試前端的e2e，就敲```gradle ohara-manager:e2e -Pconfigurator=http://1.1.1.1:5050```

**Comment by saivirtue** [comment]
> 例如我想測試前端的e2e，就敲gradle ohara-manager:e2e -Pconfigurator=http://1.1.1.1:5050

與 @jackyoh 討論後，這裡有點小改變：
`gradle ohara-manager:e2e -Pconfigurator=http://1.1.1.1:5050 --mode k8s|fake|docker`
為了提供比較彈性的方式來執行測試(如未來可以執行e2e測試在docker mode上)

**Comment by chia7712** [comment]
> --mode k8s|fake|docker

我好奇的地方是這個參數的意義為何？ 前面```ohara-manager:e2e```已經指定要跑得測試類型，後面```-Pconfigurator=http://1.1.1.1:5050```也設定了要用做測試的機器。

**Comment by saivirtue** [comment]
如同前面所說，保留彈性
e2e測試如果同時要在docker與k8s環境進行測試，以目前的參數設置可能會變成
- `ohara-manager:e2e:docker`
- `ohara-manager:e2e:k8s`

現在的e2e測試雖然名稱"隱含"是要跑在production的環境，不過我還是希望可以由參數決定這個測試實際上是要跑在哪種環境
當然，如果都由task名稱來決定測試類型也可以，就是約定成俗，然後不同的測試類型就用不同的名稱這樣XD

**Comment by chia7712** [comment]
我前面有問到說「不都是用public apis嗎」？如果是的話，那麼使用k8s或是docker的區別是什麼？（password and user在0.11.0會變成必填，因為要處理volume)

**Comment by saivirtue** [comment]
> 我前面有問到說「不都是用public apis嗎」？如果是的話，那麼使用k8s或是docker的區別是什麼？

理論上不應該有區別。不過在實際運行時可能會有些不同(如#5090)
只是希望在測試時能夠提早避免此種狀況，如果這只是一個例外那就不需要了

**Comment by chia7712** [comment]
> 理論上不應該有區別。不過在實際運行時可能會有些不同(如#5090)

等下 這個是bug啊 如果實際運作的有所不同是因為bug的話，那根本不該是前段考慮改變作法，而是後段要負責去修正

**Comment by saivirtue** [comment]
> 等下 這個是bug啊

而這個bug是因為剛好在docker mode測試 XD  (我們目前的e2e都是跑在k8s mode...)
"實際運作有不同"這件事我希望可以藉由QA來幫駔我們提早發現，不然就要仰賴前/後端各自的測試要盡可能考慮所有情況了

**Comment by chia7712** [comment]
> "實際運作有不同"這件事我希望可以藉由QA來幫駔我們提早發現，不然就要仰賴前/後端各自的測試要盡可能考慮所有情況了

我是希望e2e就是根據傳入的configurator去做測試，而不用管是什麼模式。而QA這邊會負責去搭配不同模式產生不同的報告。

**Comment by saivirtue** [comment]
> 我是希望e2e就是根據傳入的configurator去做測試，而不用管是什麼模式

OK，那我這邊會建立一個新的task `manager:it`，而這個與e2e要跑的測試類型不同 (如描述上所說)
接下來我會先把前端的測試interface開出來，再請 @jackyoh 幫忙設定Jenkins

**Comment by chia7712** [comment]
> 而這個與e2e要跑的測試類型不同 (如描述上所說)
接下來我會先把前端的測試interface開出來，再請 @jackyoh 幫忙設定Jenkins

可以先把相關的gradle命令放上去（然後跑一些dumb test），jack就可以先整到QA

**Comment by jackyoh** [comment]
ok, 我先來看設定 QA 的部份。
