### ISSUE TITLE
Introduce new document building tools and docs skeleton

### ISSUE THREAD

**Issue by vitojeng** [oharastream/ohara#5149]
required by #5099 

Items:
- [x] Create new repo: [**ohara-docs**](https://github.com/oharastream/ohara-docs)
  * The folder **/docs** in the **ohara** repo will be keeped until all migration finished
- [x] Enable web site: http://oharastream.github.io/
- [x] Experiment hugo and academic theme
- [x] Init ohara-docs(https://github.com/oharastream/ohara-docs/issues/1)
- [x] Integrate **ohara-docs** repo with Jenkins build (@jackyoh )

Reference:
* Hugo - https://gohugo.io/
* Theme - https://sourcethemes.com/academic/

**Comment by vitojeng** [comment]
@jackyoh This issue's last item is Jenkins integration.
Could you help this item?

**Comment by jackyoh** [comment]
> @jackyoh This issue's last item is Jenkins integration.
> Could you help this item?

OK, No problem.

**Comment by vitojeng** [comment]
移除 jenkins 整合 docs 相關的工作, 移至 @5163

**Comment by jackyoh** [comment]
@vitojeng 這個議題 description 的每個項目已經完成了，所以此議題可以關閉了嗎？

**Comment by vitojeng** [comment]
這個 issue 不是 close 了嗎？

**Comment by jackyoh** [comment]
對，已經 close 掉了。我看錯了...
