### ISSUE TITLE
[Jenkins] Delivery job should check the result of building images

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#5158]
簡單來說，就是要檢查一下所有images的建置和發布狀況

**Comment by jackyoh** [comment]
這個議題我有興趣。我來增加檢查 docker image 的部份

**Comment by vitojeng** [comment]
感謝大家~

**Comment by jackyoh** [comment]
這個議題已經完成了。如果 build 出來的 docker image 不存在會丟出錯誤並且在 jenkins 的 slack 也會收到訊息
