### ISSUE TITLE
[Manager] Fix delete workspace progress dialog showing up during restarting workspace

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#5161]
This can be reproduced with the following steps:

1. Create a workspace named: workspace1
2. Delete this workspace
3. Create another workspace with the same name: "workspace1"
4. Restart the workspace, the delete workspace will show up on top of the restart workspace dialog during restarting...

**Comment by konekoya** [comment]
cc @wu87988622

**Comment by vitojeng** [comment]
Reopn and wait for QA passed.

**Comment by vitojeng** [comment]
QA passed, thanks @saivirtue and @konekoya !
