### ISSUE TITLE
Remove the stale docs builder

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#5163]
required by #5099

@vitojeng 正在轉換到新的docs平台，其中也會把專案下的docs移動到別的repo，換言之，我們可以將ohara裡面用來建置docs的元件刪掉，包含：

1. - [x] 移除QA裡面針對doc測試的部份 @jackyoh
1. - [x] 移除doc status from github PR @chia7712 
1. - [x] remove doc dependencies from deps image @chia7712 (#5287)
1. - [x] remove docs folder @chia7712

**Comment by chia7712** [comment]
@vitojeng 你覺得我們應該先移除，還是等你告一個段落？

**Comment by vitojeng** [comment]
現在還不能刪除喔.

目前的 ohara docs 是用 webhook 自動連結到 readthedocs. 刪掉了網站就消失了 XD
所以至少要等到 **ohara repo** /docs 資夾的內容, 全部 migrate 到 **ohara-docs** 後, 再來刪除.

這部份的工作, 原來我是安排在 #5149 工作項目, 請 @jackyoh 協助. 或是看你們如何分工. ^^

**Comment by vitojeng** [comment]
@chia7712 , @jackyoh 應該可以移除囉~

**Comment by chia7712** [comment]
我們有以下工作要做

1. 移除QA裡面針對doc測試的部份
1. 移除doc status from github PR
1. 刪除doc dependencies from deps image 

@jackyoh 工作一可否麻煩你處理？剩下兩個我來弄

**Comment by jackyoh** [comment]
OK, 第一個部份我來移除 QA 的設定，等等我會開 PR 來測試。

**Comment by jackyoh** [comment]
對了，還有 ohara 資料夾底下的 README.md ，有些文件連結需要修改

**Comment by vitojeng** [comment]
> 對了，還有 ohara 資料夾底下的 README.md ，有些文件連結需要修改

在 #5282 會處理

**Comment by jackyoh** [comment]
了解，在 description 的第三項。

**Comment by chia7712** [comment]
all done. thanks to @jackyoh and @vitojeng
