### ISSUE TITLE
Require to add nodes to Configurator manually instead of seeking nodes automaically

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#5173]
from #5164

The nodes on k8s mode also require the user and password so it is unnecessary to seek node automatically.

**Comment by saivirtue** [comment]
This issue will break the e2e tests of ohara-manager. Please notify me when this issue was done.

**Comment by chia7712** [comment]
> This issue will break the e2e tests of ohara-manager. Please notify me when this issue was done.

sure !

**Comment by jackyoh** [comment]
OK, No problem.
