### ISSUE TITLE
Change the type of password and type of user from Option[String] to String

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#5174]
blocked by #5172 and #5191

Both of user and password will be required after #5172 and #5173

**Comment by saivirtue** [comment]
#5172 had been resolved, we could add node in both docker and k8s mode :)

**Comment by chia7712** [comment]
@oharastream/frontend 我剛剛想到，port也需要讓使用者可以輸入，這部份有處理嘛？

**Comment by saivirtue** [comment]
The behavior of create node is same in both **docker** and **k8s** mode :)
