### ISSUE TITLE
[Question] 是否要將所有"reference"都改成單數

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#5177]
#4555為了支援reference，會在目前所有APIs添加singular的prefix，例如

1. /topic/
1. /topics/

上述兩者經過#4555後將變成都可以支援，然而維護兩種prefix實在沒有必要

或許為了符合reference用的單字（都是singular），我們可以考慮將plural移除？

**Comment by chia7712** [comment]
ping @oharastream/developer

**Comment by jackyoh** [comment]
+1, 但是前端不太確定是否會改很多

**Comment by vitojeng** [comment]
> 維護兩種prefix實在沒有必要

同意.

目前前端在這個 milestone 將要完善整個測試架構及測試量. 因此會比較建議下一個 milestone 再來進行. 前端有了完善的測試後, 再來進行這類較底層或大規模的改動, 就可以比較放心.

**Comment by saivirtue** [comment]
> 目前前端在這個 milestone 將要完善整個測試架構及測試量. 因此會比較建議下一個 milestone 再來進行. 前端有了完善的測試後, 再來進行這類較底層或大規模的改動, 就可以比較放心.

由於我們實際呼叫Configurator時使用的APIs都有統一由一個Interface負責，這部分如果只是把API的"複數"改成"單數"，要修改的地方應該不會太大

@eechih 這部分要在 #4555一起做嗎?

**Comment by vitojeng** [comment]
> 這部分如果只是把API的"複數"改成"單數"，要修改的地方應該不會太大

了解. 改變範圍不大, 且前端測試可以涵蓋到的話.
那應該可以放心改了 XD

**Comment by chia7712** [comment]
> 了解. 改變範圍不大, 且前端測試可以涵蓋到的話.
那應該可以放心改了 XD

+1000

**Comment by chia7712** [comment]
> @eechih 這部分要在 #4555一起做嗎?

any update?

**Comment by chia7712** [comment]
ping @oharastream/frontend

**Comment by chia7712** [comment]
@oharastream/frontend

有任何想法嘛？如果依照@saivirtue的說法，或許我們可以在這個版本就把多餘的APIs刪掉？

**Comment by saivirtue** [comment]
> 或許我們可以在這個版本就把多餘的APIs刪掉？

Sure. See #5394

**Comment by chia7712** [comment]
We have reached consensus that the singular will be removed as UI handles the mapping manually.
