### ISSUE TITLE
Add nodes parsed from docker arguments to k8s IT envs

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#5191]
#5174 will change the user and password from optional to required so all IT should take user and password from docker arguments :)

1. - [x] 確認ohara.it.docker有確實被QA使用 (@jackyoh)
1. - [x] Add nodes parsed from docker arguments to k8s IT envs (@chia7712) (#5192)

**Comment by chia7712** [comment]
@jackyoh QA的部份麻煩你驗證喔

**Comment by jackyoh** [comment]
> @jackyoh QA的部份麻煩你驗證喔

目前 ohara.it.docker 有設定在 QA 的 EXTRA_PROPERTIES 變數裡。

ohara.it.k8s.nodename （0.8 版以前的設定參數）我覺得等 0.11 release 可以刪除掉。

**Comment by chia7712** [comment]
> ohara.it.k8s.nodename 

現在就可以刪掉了吧

**Comment by jackyoh** [comment]
> 現在就可以刪掉了吧

ok, 我來移除掉 ohara.it.k8s.nodename 參數。

**Comment by chia7712** [comment]
works well so I'm going to close this issue
