### ISSUE TITLE
Remove potentially problematic language

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#5205]
勢不可檔，不可不擋，以下幾個字我覺得可以改一下

1. master -> Coordinator
1. slave -> Follower
1. black list -> deny list
1. master branch -> trunk branch

@oharastream/developer 歡迎補充其他字

related PRs

1. - [x] rename Status.master to Status.coordinator (#5208)
1. - [x] rename K8s.masterUrl to K8s.coordinatorUrl (#5225)
1. - [x] rename blackList to denyList (#5230)

**Comment by alan791205** [comment]
LOL

**Comment by chia7712** [comment]
調整master branch工程比較麻煩，大家覺得呢？

**Comment by saivirtue** [comment]
或許先針對使用者會碰到的部分( API與UI) 做調整呢?

**Comment by chia7712** [comment]
> 或許先針對使用者會碰到的部分( API與UI) 做調整呢?

聽起來不錯，不過我看了一下專案程式碼其實踩到的地方沒有很多，大部分應該都可以很快弄好

現在比較麻煩的就是master branch這個要不要改

**Comment by jackyoh** [comment]
master branch 修改應該也會影響到程式碼和 QA 的部份, 我覺得等 0.11 release 之後再改會不會比較好

**Comment by chia7712** [comment]
> master branch 修改應該也會影響到程式碼和 QA 的部份, 我覺得等 0.11 release 之後再改會不會比較好

同意

**Comment by vitojeng** [comment]
> 現在比較麻煩的就是master branch這個要不要改

個人想法是 master 能不改就不改.
除非連 git & github 這二大工具的 default 值都換了, 就另當別論了.
