### ISSUE TITLE
重構 SSH 和 K8S 的 collie

### ISSUE THREAD

**Issue by jackyoh** [oharastream/ohara#521]
目前 ssh 和 k8s collie的程式有很多重複的地方, 因此需要重構. 把相同的邏輯提取到抽象化類別.

**Comment by vitojeng** [comment]
k8s 相關工作是否己經完成? 若還沒有, 是不是完成後再進行重構比較好?

**Comment by jackyoh** [comment]
等到 PR-512 mrege 進去 master K8S 的工作就完成了. 可以使用 UI 來測試 k8s 的功能.

**Comment by vitojeng** [comment]
ok, thanks!

**Comment by chia7712** [comment]
this is duplicate to #651
