### ISSUE TITLE
[Manager] Delete the fail topic when creating a new topic on Paper failed

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#5221]
The correct behavior for a fail API request where it tries to create a new Paper element:
1. Display the error via snackbar
2. Save the complete error message in event log
3. Remove the fail element on Paper

**Comment by konekoya** [comment]
@saivirtue This one is a bit tricky. The problem now is once the server stop responding, the client code would fail (when trying to create a new topic in pipeline)
The error is handle in createAndStopTopicEpic:

```js
catchError((err) => {
  if (paperApi) {
    paperApi.updateElement(params.id, {
      status: CELL_STATUS.stopped,
    });
  }
  if (typeof promise?.reject === 'function') {
    promise.reject(err);
  }
  return from([
    actions.createAndStartTopic.failure(err),
    actions.createEventLog.trigger({ ...err, type: LOG_LEVEL.error }),
  ]);
}),
```

The error can be properly handled but the problem is that there will be two different errors, one from create (POST) and one from start (PUT). I have no way to distinguish them unless I'm comparing the title like: `err.title === 'create failure...'` but I feel this is not the right way to go about it... do you have suggestion or better idea for this?

**Comment by konekoya** [comment]
Conclusion: Move the error handle logic "up" to each epic calls':

```js
createTopic$.pipe( // handle the error here );
startTopic$.pipe( // handle he error here );
```

Thanks @saivirtue for the idea :)

**Comment by vitojeng** [comment]
QA passed, thanks @konekoya !
