### ISSUE TITLE
[Manager] Refactor the workspace creation

### ISSUE THREAD

**Issue by eechih** [oharastream/ohara#5247]
- [x] Refactor the workspace creation
- [x] Refactor the zookeeper creation
- [x] Refactor the broker creation
- [x] Refactor the worker creation
- [x] Refactor the zookeeper's start
- [x] Refactor the broker's start
- [x] Refactor the worker's start
- [x] createWorkerEpic test
- [x] createBrokerEpic test
- [x] createZookeeperEpic test
- [x] startWorkerEpic test
- [x] startBrokerEpic test
- [x] startZookeeperEpic test
- [x] attempt to start at intervals
- [x] e2e test

**Comment by vitojeng** [comment]
@eechih 不太確定這個 issue 的 QA 要進行什麼?

**Comment by eechih** [comment]
@vitojeng UI 的部分沒有調整，只要確定 Creation 能正常運作即可

**Comment by eechih** [comment]
抱歉～這個 issue 主要是調整架構，後續會有其他 Issue 處理 UI 的部分，因此可以不用進行 QA

**Comment by vitojeng** [comment]
嗯. 目前感覺個別 **issue QA** 比較適合有針對性的做測試, 例如 Bug 修復或是新功能的加入, 或是特定小範圍的改變.
重構應該是不涉及功能的改變, 且範圍有可能很大, 所以不納入 **issue QA** 範圍.

ping @oharastream/developer
