### ISSUE TITLE
[Manager] Split the logic of fetching and inspecting worker in fetchWorkerEpic

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#5249]
Putting them together often causes issue since when an "inspect" fails, the "fetch" will also be treated as failed. This issue can be repro as follow:

1. Create a workspace
2. Make a `PUT` request to stop the worker (so the worker will be stopped but the config remains there)
3. Reload the page and delete the workspace with UI
4. It will fail at the deleting broker stage as the worker config is still there but our `fetchWorkerEpic` will always fail because the "inspect" API will fail and thus the "fetch" part also fail

- [x] worker #5364

**Comment by wu87988622** [comment]
@eechih
