### ISSUE TITLE
Apply ohara Enum helper class to code base

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#525]
#329 introduce a great tool to enhance scala's enum. We should apply it to code base.

**Comment by chia7712** [comment]
FYI @saivirtue

**Comment by chia7712** [comment]
@saivirtue any updates? BTW, we should move com.island.ohara.client.kafka.Enum to com.island.ohara.client.Enum

**Comment by saivirtue** [comment]
I am working on #311 , so this issue may be started on next week.
let me summarize :
1. apply all (need to check) sealed class -> Enum
2. move com.island.ohara.client.kafka.Enum to com.island.ohara.client.Enum

**Comment by chia7712** [comment]
@saivirtue Thanks for contributions
