### ISSUE TITLE
[Question]Is the JSON format supported by the backend missing a timestamp?

### ISSUE THREAD

**Issue by wu87988622** [oharastream/ohara#5250]
這是我們目前支援的格式
Boolean
String
Short
Int
Long
Float
Double
Array[Byte]
Byte

使用者透過 Manager pipeline 去串接 JDBC Connector -> topic
GET inspect/topic
會出現 java.sql.Timestamp is unsupported!!!
timestamp 在JDBC是重要的欄位.

是否要支援timestamp在GET inspect/topic可正常顯示.

**Comment by wu87988622** [comment]
@oharastream/developer 有任何的想法嗎?

**Comment by saivirtue** [comment]
> 是否要支援timestamp在GET inspect/topic可正常顯示.

+1 to this

**Comment by chia7712** [comment]
> java.sql.Timestamp is unsupported!!!

有完整的錯誤資訊嘛？ 這個聽起來像是個bug

**Comment by wu87988622** [comment]
> > java.sql.Timestamp is unsupported!!!
> 
> 有完整的錯誤資訊嘛？ 這個聽起來像是個bug

![](https://files.slack.com/files-pri/TFK6D875F-F015EH8MQ21/image.png)
![](https://files.slack.com/files-pri/TFK6D875F-F015UHC755F/image.png)
![](https://files.slack.com/files-pri/TFK6D875F-F0165PKHJBS/image.png)

**Comment by jackyoh** [comment]
可以使用 docker logs ${CONFIGURATOR_CONTAINER_NAME}, 貼出更詳細的 log 訊息嗎？

**Comment by chia7712** [comment]
所以是在inspect topic的資料時，row裡面有timestamp型態的資料?

**Comment by wu87988622** [comment]
> 所以是在inspect topic的資料時，row裡面有timestamp型態的資料?

是的

**Comment by chia7712** [comment]
> 是的

see #5252

**Comment by wu87988622** [comment]
> > 是的
> 
> see #5252

thanks.

**Comment by wu87988622** [comment]
This problem will be solved in #5252
