### ISSUE TITLE
[Manager] Remove node should be disabled if there was service on it

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#5266]
![image](https://user-images.githubusercontent.com/8088616/84999447-babcf800-b183-11ea-8b73-8961c856e8dc.png)

- Also add a test case to cover the logic of "node deletion loading" in #5265 (see [here](https://github.com/oharastream/ohara/pull/5283#discussion_r443300323))

**Comment by saivirtue** [comment]
ping @chia7712 
When there are already some nodes existed (3 above), the getAll may contain the deletion object after deleting a node

**Comment by chia7712** [comment]
> When there are already some nodes existed (3 above), the getAll may contain the deletion object after deleting a node

**Comment by chia7712** [comment]
@saivirtue Did you wait for the response of deletion?

**Comment by saivirtue** [comment]
> Did you wait for the response of deletion?

Hmm... We send the **delete** and **getAll** API simultaneously. Does it cause the getAll request fetched deletion objects?

**Comment by chia7712** [comment]
> We send the delete and getAll API simultaneously.

maybe. They are executed at same time so getAll API may be executed before deleting object.

**Comment by saivirtue** [comment]
> > We send the delete and getAll API simultaneously.
> 
> maybe. They are executed at same time so getAll API may be executed before deleting object.

If so, I thought it's the frontend bug, not backend. Do you plan to reduce the "possibility" of this failure in #5290?

**Comment by vitojeng** [comment]
QA passed, thanks @saivirtue !
