### ISSUE TITLE
All user-defined fields which are duplicate to runtime fields should be removed

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#5267]
To reproduce:

1. Create zookeeper
2. Update zookeeper with following body
```json
{
  "state": "RUNNING"
}
```
3. Start zookeeper
4. Get zookeeper (state = "RUNNING")
5. Stop zookeeper 
6. Get zookeeper
   - expected: state = None
   - actual: state = "RUNNING"

**Comment by saivirtue** [comment]
The reproduce steps seems a little complex...I'll update the steps later

**Comment by saivirtue** [comment]
ping @chia7712

**Comment by chia7712** [comment]
thanks for this finding.
