### ISSUE TITLE
JDBC/HDFS/FTP/PERF connectors should get to write their setting definitions

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#527]
Our metadata of connectors is almost completed. The official connectors should start to write setting definitions which can make user see which settings they should define.

1. Ftp source is traced by #544
1. Ftp sink is traced by #547
1. Hdfs sink is traced by #563 
1. JDBC source is traced by #563
1. Perf source is traced by #791

FYI @jackyoh @konekoya @eechih

**Comment by chia7712** [comment]
@eechih If you have free cycle, please take over PR about adding setting definitions to Perf source

**Comment by jackyoh** [comment]
HDFS Sink Connector 和 JDBC Source Connector 我這邊會做修改

**Comment by chia7712** [comment]
@eechih Do you have free cycle to take over the latest (perf) connector?

**Comment by eechih** [comment]
@chia7712 Yes, I can take over the job.

**Comment by chia7712** [comment]
all sub tasks are completed. close it now.
