### ISSUE TITLE
jenkins encounters DNS failure. In order to keep QA running, we should remove operations which try to connect to other nodes

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#528]

**Comment by chia7712** [comment]
the following operations are removed. We should revert them after DNS gets working.
1. the nodes which can run the QA (jenkins-slave00 is excluded)
1. docker image sync (jenkins-slave00, jenkins-it01, jenkins-it02, jenkins-it03 and jenkins-it04 are excluded)

**Comment by chia7712** [comment]
@jackyoh Could we close this issue?

**Comment by jackyoh** [comment]
No Problem.
