### ISSUE TITLE
Update docs site related content

### ISSUE THREAD

**Issue by vitojeng** [oharastream/ohara#5282]
required by #5099
Items:
- Update the url link in Ohara code base
- Update README.md

**Comment by vitojeng** [comment]
在 oharastream/ohara-docs#37 & #5163 完成後將進行此工作.
ping @oharastream/developer

**Comment by jackyoh** [comment]
所以  oharastream/ohara-docs#37 合併進去之後，就可以移除 QA 的 make docs 的部份了嗎？

**Comment by vitojeng** [comment]
@jackyoh 我想是的.

**Comment by jackyoh** [comment]
OK, I got it. Thank you!
