### ISSUE TITLE
Create a special API to delete all objects with the same group

### ISSUE THREAD

**Issue by eechih** [oharastream/ohara#5291]
as title

/cc @chia7712

**Comment by eechih** [comment]
@chia7712  剛剛想到一點，Delete Workspace 應該要先刪除相關的 connectors, streams, shabondis, pipelines, services, and files（前面無關順序），最後才能刪除 workspace object。因為有順序的需求，所以可能要能支援`排外機制`或是`指定 kind` 🙏

**Comment by chia7712** [comment]
> 指定 kind pray

例如格式如下：

1. url => DELETE /v0
2. body =>
```json
{
  "groups": [
    "a"
  ]
  "kinds": [
    "connector"
  ]
}
```

上述範例是用來刪除group="a" and kind="connector"，陣列裡面可以增加更多group或是kind
