### ISSUE TITLE
[Jenkins] generate a summary report to PR

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#5301]
We need to post the final coverage report to PR, the following tasks must be resolved:
- [x] add the testing report type of `json-summary` to QA (@saivirtue ) (#5324)
- [x] trigger Jenkins task to post the report summary back to PR **status** with format **Statements: 90.00% (90/100)** (@jackyoh ) (blocked by #5337)
  - add a new test for generate coverage report (ut,  api, it): `gradle report`
  - this will have four coverage reports:
    - test/manager-ut:  `client/coverage/ut/lcov-report/index.html`
    - test/manager-api: `client/coverage/api/coverage-summary.json`
    - test/manager-it:  `client/coverage/it/coverage-summary.json`
    - code/coverage:  after trigger **gradle report**, `client/coverage/coverage-summary.json`

**Comment by saivirtue** [comment]
/cc @jackyoh @chia7712 
Any concerns about this issue?

**Comment by chia7712** [comment]
> trigger Jenkins task to post the report summary back to PR with format 

這個是要貼成"comment"還是"status"?

**Comment by saivirtue** [comment]
I'll prefer to use "status" since it the summary won't be covered by bunch of comments :_

**Comment by chia7712** [comment]
> I'll prefer to use "status"

LGTM :)

**Comment by jackyoh** [comment]
> Any concerns about this issue?

目前還沒想到問題，晚一點我再來做看看。

**Comment by vitojeng** [comment]
> I'll prefer to use "status" since it the summary won't be covered by bunches of comments :)

Cool!
