### ISSUE TITLE
Workspace going to change mode without any change.

### ISSUE THREAD

**Issue by vitojeng** [oharastream/ohara#5327]
**To Reproduce**
1. Create workspace1(select two node)
2. Create workspace2(select one node)
3. Switch to **workspace1** and open **workspace1** settings dialog.
4. The change warning message appear on the top.
![screenshot 12](https://user-images.githubusercontent.com/475186/85987913-e318e200-ba20-11ea-8fd4-58abc0d7d5f0.jpg)

**Comment by wu87988622** [comment]
It will be solved at #5335

**Comment by vitojeng** [comment]
Thanks @wu87988622 !
