### ISSUE TITLE
[Jenkins] Use same temp configurator container for manager tests `test/manager-api` and `test/manager-it`

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#5342]
This issue will achieve:
- trigger `test/manager-it` in PR submitted and `retry` command
- use one configurator container (fake mode) for the following commands
  - PR submitted
  - `retry`

**Comment by jackyoh** [comment]
ping @saivirtue 這個議題可以關閉了嗎？

**Comment by jackyoh** [comment]
ping @saivirtue  FYI

**Comment by saivirtue** [comment]
Sure~
