### ISSUE TITLE
Event log unread count is not cleared

### ISSUE THREAD

**Issue by vitojeng** [oharastream/ohara#5344]
Reproduce step:
1. Open Event log panel, and then make some errors. Now unread count is "3".
![screenshot 18](https://user-images.githubusercontent.com/475186/86218282-2440fb80-bbb3-11ea-84b2-fd0fa6c88378.jpg)

2. Press <kbd>Clear event logs</kbd>. And then all evet logs removed, but unread count still "3"
![screenshot 19](https://user-images.githubusercontent.com/475186/86218287-273bec00-bbb3-11ea-9e53-dd3987145118.jpg)

**Comment by vitojeng** [comment]
說明: Event log 開啟, 若有 Event log 進來時, unread count 會持續增加.

**Comment by saivirtue** [comment]
這個case的確沒有測到...在EventLog打開後，notification不應該繼續產生 (因為已經都是"read"狀態)
感謝回報!

**Comment by vitojeng** [comment]
QA passed, thanks @saivirtue !
