### ISSUE TITLE
Add material UI into manager

### ISSUE THREAD

**Issue by wu87988622** [oharastream/ohara#535]
required by #428

**Comment by konekoya** [comment]
@wu87988622 when you're creating a new issue, you need to make sure that:

- [ ] Add an assignee if you already know who should take care of that issue
- [ ] Add a planned label for the issue
- [ ] Add a milestone if you know when we're going to tackle it

Let me know if there's anything that's not clear enough :)

Good luck ❤️

**Comment by konekoya** [comment]
@wu87988622 Please add 0.5.0 label to this issue...
