### ISSUE TITLE
[Manager] Should not allow shared topic from adding into Paper if the name is already taken by other elements

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#5351]
Thanks @saivirtue for reporting this :)

### Expected behavior:
Every name in Paper is unique and therefor cannot be added more then one time

### Actual behavior:
Although a name is already taken, we can still add a shared topic into the Paper

### Steps to repro
1. Create a workspace and pipeline, then a shared topic name "aaa"
2. Add a new source name "aaa" into the Paper
3. Add the shared topic into the Paper. Now there are __two same elements exist in the same paper__

**Comment by konekoya** [comment]
@vitojeng could you help test this fix out. Thanks :)

**Comment by vitojeng** [comment]
LGTM. QA passed.
