### ISSUE TITLE
Ohara 0.11.0 product testing report

### ISSUE THREAD

**Issue by jackyoh** [oharastream/ohara#5374]
## 測試項目

<details>
<summary><b>1. 基本測試</b></summary>

- [ ] 確認畫面（UI）與設計稿（Design）是否一致
  - 顏色、字型、符號、圖片、...
- [ ] 檢查所有畫面的 Title 名稱是否正確
- [ ] 所有連結是否有前往正確頁面
- [ ] 切換視窗大小時，有無跑版情形
- [ ] 切換視窗大小後，文字與圖形是否竄行
- 表單
  - [ ] 任何一個必填欄位未填寫，不能送出
  - [ ] 表單送出中，應該明確表達正在處理中的訊號
  - [ ] 表單送出中，應該要凍結表單（除非有提供取消功能）
  - [ ] 任何表單至少要有 CTA 及 Cancel 兩類按紐 (CTA: Call-To-Action)
- 訊息
  - [ ] 成功訊息，應該要明確指出完成對象
  - [ ] 錯誤訊息，應該要明確指出錯誤對象
  - [ ] 確認訊息
    - [ ] 刪除確認，應該要明確指出欲刪除對象
- 按鈕
  - [ ] 任何一個刪除按鈕，都要有刪除確認提示
- 鼠標
  - [ ] 移動到所有可以點擊的元素，要出現 pointer cursor
      - Button, Link icon, Link text, ...
</details>

<a href="https://paper.dropbox.com/doc/Ohara-QA-Test-items--A3pGkPRhHwrpT2Eqs55JVV9dAg-QlquhEDRcveSABPjHiuxQ">測試項目連結</a>

**Comment by wu87988622** [comment]
在Pipeline中如果在element是stop的狀態中啟動Metrics開關接著啟動element後，element上不會出現Metrics。

**Comment by chuntsekevin** [comment]
[ ]Workspace 出現unstable tag後，無法進入workspace做刪除或重啟動作。
![image](https://user-images.githubusercontent.com/60953697/87738724-9ef35300-c810-11ea-8722-32bda609f467.png)

**Comment by saivirtue** [comment]
> Workspace 出現unstable tag後，無法進入workspace做刪除或重啟動作。
> ![image](https://user-images.githubusercontent.com/60953697/87738724-9ef35300-c810-11ea-8722-32bda609f467.png)

This is the desired result, please see #5385

**Comment by saivirtue** [comment]
> 當pipeline上有topic，無法重啟broker
> ![image](https://user-images.githubusercontent.com/60953697/87738897-01e4ea00-c811-11ea-935b-fbcf2466a9f0.png)

This looks like the exact problem to #5402 🤔 , would you share the testing steps?

**Comment by chuntsekevin** [comment]
> > 當pipeline上有topic，無法重啟broker
> > ![image](https://user-images.githubusercontent.com/60953697/87738897-01e4ea00-c811-11ea-935b-fbcf2466a9f0.png)
> 
> This looks like the exact problem to #5402 🤔 , would you share the testing steps?

My testing step 
1. create new pipeline
2. creat a new topic 
3. restart broker
thanks!

**Comment by eechih** [comment]
> 當pipeline上有topic，無法重啟broker
> ![image](https://user-images.githubusercontent.com/60953697/87738897-01e4ea00-c811-11ea-935b-fbcf2466a9f0.png)

一直遇到類似的問題，只要有 topic，不管是重啟 broker 或是 workspace 時，Start topic 一定會失敗 :(

**Comment by chia7712** [comment]
> 一直遇到類似的問題，只要有 topic，不管是重啟 broker 或是 workspace 時，Start topic 一定會失敗 :(

錯誤訊息呢？

**Comment by eechih** [comment]
>> 一直遇到類似的問題，只要有 topic，不管是重啟 broker 或是 workspace 時，Start topic 一定會失敗 :(

> 錯誤訊息呢？

測試步驟：
![螢幕快照 2020-07-20 下午3 57 38](https://user-images.githubusercontent.com/703126/87913767-2e636500-caa2-11ea-952b-53ef2ae9e402.png)
![螢幕快照 2020-07-20 下午3 59 47](https://user-images.githubusercontent.com/703126/87913781-33281900-caa2-11ea-9157-76c7903facd0.png)
![螢幕快照 2020-07-20 下午3 59 56](https://user-images.githubusercontent.com/703126/87913789-36bba000-caa2-11ea-9b04-a3c3b08216d7.png)

**Comment by chia7712** [comment]
這感覺跟worker的故事蠻像的？

**Comment by eechih** [comment]
Restart broker 成功後，重新整理畫面，pipeline 的 toolbox 無法正常顯示

測試步驟：
1. 啟動一個全新的 Ohara
2. 新建一組 node
3. 新建一組 workspace
4. 執行 Restart worker 成功
5. 呼叫 inspect broker api 正常
6. 呼叫 inspect worker api 正常
7. 執行 Restart broker 成功
8. 呼叫 inspect broker api 正常
9. 呼叫 inspect worker api 失敗

**Comment by eechih** [comment]
Delete workspace 成功後，如果沒有勾選 `close after finish`，Dialog 不應該被關閉。

**Comment by chuntsekevin** [comment]
Pipeline and connector fail to remove
--------
Add a JDBC connector (without JDBC connector plugin), when user forgot to add the plugin jar will cause the pipeline dead.
Can't remove any component(topic or connector) and pipeline can't delete.
And the connector should show failed status(red) but still show stopped status(gray), user have to refresh the page to see the real status.
![0727](https://user-images.githubusercontent.com/60953697/88498355-7bd95800-cff5-11ea-8f60-f884a59a0a91.PNG)
![072701](https://user-images.githubusercontent.com/60953697/88498357-7ed44880-cff5-11ea-9358-4986f1777cf2.PNG)
![072702](https://user-images.githubusercontent.com/60953697/88498362-81cf3900-cff5-11ea-9a0a-78b526eaebbe.PNG)
![072703](https://user-images.githubusercontent.com/60953697/88498370-85fb5680-cff5-11ea-960a-e9be6a3ced35.PNG)
![072705](https://user-images.githubusercontent.com/60953697/88498391-91e71880-cff5-11ea-861c-741b12c50161.PNG)

**Comment by vitojeng** [comment]
Thanks @chuntsekevin !
@oharastream/frontend Does anyone take a look?

**Comment by saivirtue** [comment]
It's a bug, I've opened a new issue [here](https://github.com/oharastream/ohara/issues/5497)

**Comment by konekoya** [comment]
> Add a JDBC connector (without JDBC connector plugin), when user forgot to add the plugin jar will cause the pipeline dead.
Can't remove any component(topic or connector) and pipeline can't delete.
And the connector should show failed status(red) but still show stopped status(gray), user have to refresh the page to see the real status.
Can't restart Workspace, Broker, Worker

A couple of bug we have discovered while trying to repro this issue:

- [ ] Inspect worker definitions always return success if it reaches the retry limit
- [ ] Separate start connectors/streams/shabondis epic's start and get logic
- [ ] Remove illegal element status from Paper

**Comment by jackyoh** [comment]
重複建立到相同的 workspace name 會造成 Pipeline Toolbox 的 Source 和 Sink 無法顯示

測試步驟如下：
1. 第一次啟動 configurator 和 manager 之後，建立 workspace1

2. 建立完成 workspace1 之後，把 configurator 和 manager 關閉掉。但是忘記刪除之前建立 workspace1 的 zookeeper, broker 和 worker container

3. 第二次啟動 configurator 和 manager 之後，再一次建立 workspace1

4. 完成 workspace1 的建立之後，再去建立 pipeline1，打開 pipeline1 就會看到如下的畫面：
![2020-07-28 10-36-43 的螢幕擷圖](https://user-images.githubusercontent.com/15885064/88613436-08504d00-d0c0-11ea-910f-1721f44215c6.png)

**Comment by jackyoh** [comment]
以上的問題主要是沒有將 configurator  container  存放的資料 (rockdb) 保留到 host 裡，才會造成 configurator 重啟時所有 workspace 的資訊都不見，使用以下指令可以把 configurator container 的資料保留到 host 裡：

```
docker run -d --rm -v /tmp/rockdb:/home/ohara/configurator -p 12345:12345 oharastream/configurator:0.11.0-SNAPSHOT --port 12345 --hostname ohara-jenkins-it-00 --folder /home/ohara/configurator
```

**Comment by jackyoh** [comment]
重新 Restart Broker 之後 worker 的 container 會收到如下的 warn 訊息：

```
[2020-07-29 06:22:01,852] WARN [Consumer clientId=consumer-ed51f67fb39846ebb2a483dfd-1, groupId=ed51f67fb39846ebb2a483dfd] 1 partitions have leader brokers without a matching listener, including [connect.offsetbbdbd649eacb41f1ae8031065-0] (org.apache.kafka.clients.NetworkClient:1063)
```

測試步驟如下：
1. 建立 workspsace
2. 當 workspace 建立完成之後，會建立一個 pipeline。pipeline 上面會有一個 perf connector 以及一個 topic
3. 重新啟動 broker。就會看到以上的 WARN 訊息，大概等 3 分鐘之後 worker container 就會出現 error 狀態。

**Comment by jackyoh** [comment]
> [2020-07-29 06:22:01,852] WARN [Consumer clientId=consumer-ed51f67fb39846ebb2a483dfd-1, groupId=ed51f67fb39846ebb2a483dfd] 1 partitions have leader brokers without a matching listener, including [connect.offsetbbdbd649eacb41f1ae8031065-0] (org.apache.kafka.clients.NetworkClient:1063)

以上的錯誤確定是因為目前，前端沒有整合 volume 的部份，所以在 restart broker 的 container 時也需要將 zookeeper container 也一起刪掉重啟。確保 zookeeper container 沒有存放到 restart 之前 broker container 的系統資料，這樣才能讓 broker container 和 worker container 正常執行。

**Comment by jackyoh** [comment]
0.11.0 已經 release 了，我先把此議題關閉。之後有發現問題再來 reopen 此議題
