### ISSUE TITLE
[Manager] The search input should not appear in view file dialog

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#5382]
**Describe the bug**
When clicking a detail view of stream file, the "View file" dialog should not have a search input since we are "viewing the only file"

**To Reproduce**
1. create workspace
2. click **stream jars** of Settings dialog
3. upload a file, then click **View file**

**Expected behavior**
The **Search** input should not exist

**Screenshots**
![image](https://user-images.githubusercontent.com/8088616/86735794-a030bd00-c065-11ea-9432-28f362abf525.png)

/cc @eechih

**Comment by eechih** [comment]
Why not have a quick search? 使用者可以使用關鍵字快速過濾並確認是否有預期的 class name，這不是很有用的功能嗎？🤔

**Comment by saivirtue** [comment]
> 使用者可以使用關鍵字快速過濾並確認是否有預期的 class name

Indeed. This should not be a bug, more like a feature for user to filter expect results.
I will close this issue now
