### ISSUE TITLE
[Manager] Add threshold of coverage

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#5384]
Since we are almost completed the tests (thanks @oharastream/frontend help!)
It's time to make some assurance about code reliability - percentage f code coverage
there are four thresholds could be config, for example:
```
{
  "branches": 80,
  "lines": 80,
  "functions": 80,
  "statements": 80
}
```

I thought we could set `statements > 80%` since all the passed PRs are better than this, how you guys think?

**Comment by saivirtue** [comment]
After discussed with @konekoya , I will split the coverage check into three different testing level:
- ut: `Statements > 40%`
- api: `Statements > 75%`
- it: `Statements > 75%`

Each test level will be failed if
- test cases failed
- threshold does not meet the above goal

The above thresholds are referenced from the latest passed PR (#5380).
If you have any suggestion, please let me know :)

/cc @oharastream/frontend

**Comment by eechih** [comment]
目前 ut 涵蓋率有超過 40% 嗎？

**Comment by saivirtue** [comment]
> 目前 ut 涵蓋率有超過 40% 嗎？

Looks yes.
![image](https://user-images.githubusercontent.com/8088616/86866276-2f3fe280-c103-11ea-8ec4-5ab3c719a895.png)

**Comment by eechih** [comment]
剛剛確認一下，目前 ut 的涵蓋率沒有算到 components folder，這是有意的嗎？

**Comment by saivirtue** [comment]
因為目前UT的測試"完全"沒有碰到component的目錄，還有context目錄也在coverage中被排除：
`--collectCoverageFrom=\"src/{!(components|context),}{*,/**}\"`

如果未來這部分的UT測試有增加，可以將這部分的排除名單刪除

**Comment by eechih** [comment]
> 因為目前UT的測試"完全"沒有碰到component的目錄，還有context目錄也在coverage中被排除：

應該只是排除 coverage，如果寫 component ut 應該會執行，對嗎？

**Comment by saivirtue** [comment]
>如果寫 component ut 應該會執行

Yep :)

**Comment by eechih** [comment]
> ut: Statements > 40%
api: Statements > 75%
it: Statements > 75%

+1
