### ISSUE TITLE
Cancel "create workspace" failed

### ISSUE THREAD

**Issue by vitojeng** [oharastream/ohara#5398]
Steps:
1. Remove zookeeper docker image from node1(ohara node)
2. Create workspace and select node1
3. Error during workspace creation(Start zookeeper failed)
4. Press <kbd>CANCEL</kbd>
5. Error during cancel creation(Workspace)
![screenshot 22](https://user-images.githubusercontent.com/475186/86896955-5e714680-c139-11ea-9b01-e95c838263ca.jpg)

Expected results:
Workspace create should be fully cancel.

**Comment by chia7712** [comment]
@eechih could you share the root cause to us?

**Comment by eechih** [comment]
@chia7712 這是 UI 的 bug，delete object 沒有帶到 name :(

**Comment by vitojeng** [comment]
> @eechih could you share the root cause to us?

這裡說明一下, 這應該算不小心遇到的 coner case. 
root cause 就是該 node 上不存在這個版本的 image.

例如有 node1, node2, node3;  而 node1 是 k8s master & slave

剛才開始決定 node1 只用來當 k8s master 用途, 不用來建 workspace.
所以只在 node2, node3 更新 ohara image.

後來建不同的 workspace 時, 不小心(或忘記) 點到 node1. 然後就發生這件事了...
剛開始看訊息不明白, 但後來想到 node1 其實根本沒更新 ohara image.

跟 @eechih 確認後端有正確的訊息傳出來, 但是被前端包起來了.

**Comment by eechih** [comment]
> 這裡說明一下, 這應該算不小心遇到的 coner case.
root cause 在後端是該 node 上不存在這個版本的 image.
> ...
> 跟 @eechih 確認後端有正確的訊息傳出來, 但是被前端包起來了.

@vitojeng 這應該是另一個問題 #5396 的 root cause

**Comment by vitojeng** [comment]
哈, 對. 這個 issue 是在 #5396 之後接著遇到的情形.

**Comment by vitojeng** [comment]
LGTM, QA passed.
