### ISSUE TITLE
Add more tests for PerfConnector

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#540]
This issue include following tasks.
- [x] add tests of sending incorrect props (moved to issue #833)
- [x] add tests of running connector with incorrect props (#902)

**Comment by chia7712** [comment]
I forgot this issue :(
@eechih If you have free cycle, please add a test against bad case for PerfConnector

**Comment by eechih** [comment]
ok

**Comment by chia7712** [comment]
all tasks are completed! @eechih Thanks for contribution!
