### ISSUE TITLE
Running manager tests breaks all version test of backend

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#5405]
我注意到最近後端的版本檢查一定會失敗，然後原因應該是前端測試過程中重新建立的jar，同時沒有傳遞測試過程中正確的版本資訊（測試過程中jenkins會動態的更動ohara.version），進而導致後端的版本測試失敗

```
/* eslint-disable no-process-exit, no-console */
  if (!fs.existsSync(`${distBase}`)) {	const buildJars = execa('./gradlew', ['ohara-it:jar'], {
    fs.mkdirSync(`${distBase}`, { recursive: true });	  cwd: '..',
  }	  stdio: 'inherit',
});
```

**Comment by chia7712** [comment]
@jackyoh 這個議題要在release之前解決

**Comment by chia7712** [comment]
@oharastream/frontend 麻煩看一下

@saivirtue 可否麻煩你解釋一下動機？

另外可能一個可能的解法，前端在產生jar的時候也需要把版本（ohara.version）帶進去

**Comment by jackyoh** [comment]
> @jackyoh 這個議題要在release之前解決

OK, 我盡量今天把這個問題解決

**Comment by saivirtue** [comment]
> @saivirtue 可否麻煩你解釋一下動機？

我們在進行IT與E2E測試時，會需要用到`ohara-it`包好的jars；這一段是由於我們自己的script`copy:jars`會將/ohara-it/build/libs下的jars複製到我們測試的目錄下，但在本機測試無法確保一定會有這些檔案在ohara-it下，因此包了一個"helper"在這個script內。

> 然後原因應該是前端測試過程中重新建立的jar，同時沒有傳遞測試過程中正確的版本資訊（測試過程中jenkins會動態的更動ohara.version），進而導致後端的版本測試失敗

不太理解這一段，意思是我們不能隨意的重新打包jars?

**Comment by saivirtue** [comment]
BTW, 上面那一段打包ohara-it jar的邏輯似乎是舊版的?

目前master上的邏輯:
```js
const filesExist = files.every((file) => fs.existsSync(`${distBase}/${file}`));

if (!filesExist) {
  /* eslint-disable no-process-exit, no-console */
  (async function () {
    try {
      const value = await execa('./gradlew', ['ohara-it:jar'], {
        cwd: '..',
        stdio: 'inherit',
      });
```
我們會在打包jar之前先檢查是否jar已經存在，若不存在才會重新打包

**Comment by chia7712** [comment]
> 不太理解這一段，意思是我們不能隨意的重新打包jars?

在QA環境中我們會傳遞一些測試用途的參數給compiler，而前端呼叫compiler的時候（也就是build jar）如果沒有帶相關參數，就會建置出忽略jenkins參數的jars，此時在跑後段測試的時候就會有問題。

**Comment by chia7712** [comment]
> 因此包了一個"helper"在這個script內。

這個helper在跑api測試的時候會被呼叫嗎？

**Comment by jackyoh** [comment]
> 如果沒有帶相關參數，就會建置出忽略jenkins參數的jars

是指 ohara-client  包出來的 jar 檔，會使用到預設的 gradle.properties 的 version (0.11.0-SNAPSHOT) 嗎？然後 QA 有指定 ohara.version，VersionUtils 的 VERSION 為 QA 指定的版號。而造成 oharastream.ohara.client.TestVersion 的測試失敗

**Comment by saivirtue** [comment]
> 這個helper在跑api測試的時候會被呼叫嗎？

不會。我們目前只有在`it`或e2e`測試下才會觸發這一段

**Comment by chia7712** [comment]
> 不好意思看錯...是api

這可能就是主因了，因為後段的變更也會觸發api測試

**Comment by chia7712** [comment]
> 是指 ohara-client 包出來的 jar 檔，會使用到預設的 gradle.properties 的 version (0.11.0-SNAPSHOT) 嗎？然後 QA 有指定 ohara.version，VersionUtils 的 VERSION 為 QA 指定的版號。而造成 oharastream.ohara.client.TestVersion 的測試失敗

You are right :)

**Comment by saivirtue** [comment]
> 這可能就是主因了，因為後段的變更也會觸發api測試

I will remove the re-build it jar task of QA phase in #5409

**Comment by saivirtue** [comment]
#5409 had been done, this issue could be closed. Thanks!

**Comment by jackyoh** [comment]
這個問題已經解決了，我先把此議題關閉了。

**Comment by chia7712** [comment]
@jackyoh @saivirtue thanks for all efforts!
