### ISSUE TITLE
[Manager] Ensure all related states are cleared after a workspace is deleted

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#5438]
### Expected behavior
When a workspace is deleted, the state that was stored (cached) in the local should also be removed

### Actual behavior
After a workspace is deleted, local state is not cleaned

### Steps to reproduce
1. Create a workspace and take the default name -> "workspace1", a pipeline named "pp" and then add a connector
2. Go to workspace settings page, and delete the workspace 
3. After successfully deleted the workspace, you should no workspace at this moment. Create a new workspace with the default name -> "workspace1" and then, add a pipeline with the same name "pp". __The newly created pipeline "pp" will have the connector it previous had before deleting__

- [x] 0.11(#5449)
- [x] 0.12 (#5442)

**Comment by konekoya** [comment]
cc @jackyoh I will backport this issue to 0.11

**Comment by jackyoh** [comment]
OK, 收到。

**Comment by vitojeng** [comment]
LGTM, QA passed.
