### ISSUE TITLE
Remove branch key for the gradle.properties

### ISSUE THREAD

**Issue by jackyoh** [oharastream/ohara#5440]
gradle.properties 的 branch key 之前主要給文件使用，目前已經沒有使用到了，因此需要移除掉。

- [ ] 0.11
- [ ] 0.12

**Comment by jackyoh** [comment]
我發現 branch key 會在 ShabondiUtils.scala 和 configurator/route/package.scala 有用到，因此是否還要移除此 key? ping @vitojeng @chia7712

**Comment by chia7712** [comment]
> 我發現 branch key 會在 ShabondiUtils.scala 和 configurator/route/package.scala 有用到

現在那段就是用來指到對應的APIs docs連結，如果我們的url已經跟版號脫離了，那就可以刪掉

**Comment by jackyoh** [comment]
OK, 我先改看看。我在用 PR 來確認是否有改對
