### ISSUE TITLE
[Manager] Event logs list 裡, message 太長時, 須要截斷

### ISSUE THREAD

**Issue by vitojeng** [oharastream/ohara#5446]
說明: List item 的高度應該只有一列, 避免因為訊息太長, 使高度過高.

![screenshot 25](https://user-images.githubusercontent.com/475186/87512948-794c3980-c6aa-11ea-982f-603d78836399.jpg)

**Comment by chia7712** [comment]
這台機器一定常常image上上下下

**Comment by vitojeng** [comment]
不斷地砍掉重練

**Comment by konekoya** [comment]
dupe of #4218.

**Comment by vitojeng** [comment]
LGTM, thanks @konekoya !
