### ISSUE TITLE
[Manager] Refactor Cypress custom commands to speed up the tests

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#5464]
Just notice that we have some `cy.wait`s in our custom commands which could be replaced with some of Cypress' commands that do wait until the element is ready (like `cy.get`)

**Comment by saivirtue** [comment]
It's not an easy job, at least for me 😅 
Thanks for working on this!

**Comment by konekoya** [comment]
@saivirtue I really love the rewrite our new tests ❤️  You have done something truly amazing my friend :)
