### ISSUE TITLE
[Manager] Fix force delete topic feature

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#5473]
This feature was implemented a while back to help users deleting a running topic as well as removing its connections (if it has) so it does a lot of work behind the sense:

1. Stop and delete the topic
2. Remove the connection from Paper (done automatically by JointJS)
3. Stop connector which are linked to it (if it has) so it can be updated later on
4. Update connector config so the topicKeys are removed 

### Expected behavior
Users should able to remove a running topic which connects to one or more running connectors without problem

### Current behavior
Deleting a topic which connects to one or more running connectors break our App

### Steps to reproduce
1. Create a workspace and a pipeline
2. Add a Perf source connector and then a Console sink connector
3. Create a connection by dragging and dropping from Perf source -> Console sink. A pipeline-only topic should be generated
4. Start the pipeline
5. Delete the topic via the delete action button located in topic menu.
6. This will break our App completed due to we're trying to update connectors before they are completely stopped 

- [x] 0.11 (#5530)
- [x] 0.12 (#5527)

**Comment by konekoya** [comment]
@eechih @saivirtue I have discussed this with @wu87988622 and this feature seems a bit dangerous when considering:

1. If we added multiple connection support in the future, when attempting to delete a topic. It could potentially need to delete a whole bunch of sources/sinks connectors that are connected to the topic
2. Users should able to decide the connector stopping order (which we don't have now) as the stopping order could be important and only users know best about the order (@chia7712 has mentioned this in a daily scrum a while ago)

And so I'm thinking about removing this feature all together. Any concerns or suggestions :)

**Comment by konekoya** [comment]
Ping @oharastream/frontend Any suggestions for this issue?

**Comment by saivirtue** [comment]
> Users should able to decide the connector stopping order

For this point, vote up to remove this dangerous feature 👍

**Comment by konekoya** [comment]
Conclusion from our meeting:

For 0.12, we can add this feature along with retry mechanism just like create workspace progress dialog.

For 0.11, we won't enable this feature, and so users have to manually stop connectors that are linked to the topic which is about to be removed. We should also provide a message telling users that they need to stop these linked connectors first, then they can safely remove the topic

**Comment by jackyoh** [comment]
@konekoya 這個議題可以關閉了嗎？

**Comment by konekoya** [comment]
> @konekoya 這個議題可以關閉了嗎？

Thanks for the help :)
