### ISSUE TITLE
[Manager] Fix start pipeline action does not load Paper element metrics issue

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#5479]
Reported by @wu87988622 

在Pipeline中如果在element是stop的狀態中啟動Metrics開關接著啟動element後，element上不會出現Metrics。

- [x] 0.11 (#5521)
- [x] 0.12 (#5480)

**Comment by jackyoh** [comment]
@konekoya 這個議題應該可以關閉了嗎？

**Comment by konekoya** [comment]
> @konekoya 這個議題應該可以關閉了嗎？

Yep :)
