### ISSUE TITLE
Stream IT jar only contains one custom field

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#5485]
This jar is now customized for quick start [VM's tutorial](https://oharastream.github.io/en/docs/master/quickstart/quickstartvm/) and so there should be two specific fields, one for filtering column and one for value. It's now however, only contains one of them. cc @saivirtue for the help 🙏 

- [x] for 0.12 (#5486)
- [x] backport to 0.11 (#5487)

**Comment by saivirtue** [comment]
Good catch!
didn't notice that until now... 😅

**Comment by jackyoh** [comment]
@saivirtue 我已經把程式合併到 0.11.x branch 了，是否可以關閉此議題了？
