### ISSUE TITLE
[Question] 是否需要將 ZookeeperApi 的 DATA_DIR_KEY 變數的值修改成 data.dir

### ISSUE THREAD

**Issue by jackyoh** [oharastream/ohara#5496]
目前在 ZookeeperApi.scala 的 DATA_DIR_KEY 變數值為 dataDir, 但是 BrokerApi.scala 的 LOG_DIRS_KEY 變數值為 log.dirs，為了要讓 value 的值一致是否需要將 ZookeeperApi#DATA_DIR_KEY 變數值修改成 data.dir

**Comment by vitojeng** [comment]
dataDir 應該是按照 Zookeeper 原有的命名, 似乎維持 dataDir 比較好?

**Comment by jackyoh** [comment]
了解。dataDir 是 zookeeper 的設定命名，log.dirs 是 kafka 的設定命名，那還是維持原來 dataDir 的命名好了。我將此議題關閉
