### ISSUE TITLE
[Manager] Could not remove failed objects

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#5497]
**Describe the bug**
When starting an object failed (`state=FAILED`), the **DELETE** API could not remove it and return an exception.

**To Reproduce**
1. Create workspace, pipeline
2. drag a **JDBCSourceConnector** and topic
3. link source connector and topic
4. edit setting of source connector with fake configuration
5. start pipeline

**Expected behavior**
start failed and could remove pipeline successfully.

**Screenshots**
![image](https://user-images.githubusercontent.com/8088616/88512972-fe740e80-d019-11ea-9952-3731d992d73f.png)

![image](https://user-images.githubusercontent.com/8088616/88512955-f2884c80-d019-11ea-9c7e-00624f90bd1d.png)

**Comment by saivirtue** [comment]
In `ConnectorRoute`:
```
objectChecker.checkList
        .connector(ConnectorKey.of(key.group(), key.name()), DataCondition.STOPPED)
```
looks we have two possible solutions:
1. delete the object if it is **STOP** or **FAILED**(means not start successfully or terminated)
2. force stop the object if start failed from UI

cc @oharastream/developer any suggestion?

**Comment by chia7712** [comment]
不太確定我是否有看懂問題，運行失敗的connector要刪除前，也需要呼叫STOP去將其從worker移除。因此是哪個動作有問題？

**Comment by saivirtue** [comment]
> 運行失敗的connector要刪除前

After re-test, the problem is UI doesn't reflect the actual state of `GET` API.
I will update the description later.

**Comment by saivirtue** [comment]
After discussed with @konekoya @eechih, it seems we have other works to do in order to resolve this issue 😅  (Thanks guys!)
I will close this issue now.
