### ISSUE TITLE
Topics are not showing up in the connector property forms

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#550]
**Describe the bug**
Topics list dropdown in all connector's' property forms are not displaying

**To Reproduce**
1. Create a pipeline with the UI
2. Add a new connector into the pipeline graph
3. Add a new topic (You should have created a new topic in the services/broker page before doing this)
4. The topic that you just added won't display in its property form

**Expected behavior**
It should display the topic list if there's any

**Screenshots**

**Operation System (please complete the following information):**

**Additional context**

**Comment by chia7712** [comment]
Could you share the requests which is used to generate this bug?

**Comment by konekoya** [comment]
Hmm, I think this is due to the recent API changes. The response object structure has been tweaked a bit and so the components are not rendering as it should be. I'll dig into this farther and let you know if I can resolve with some tweaks in the frontend code or not :)

**Comment by chia7712** [comment]
I guess this issue is related to #554

**Comment by konekoya** [comment]
Yep, I believe so

**Comment by konekoya** [comment]
This is actually a bug on my part... I'm gonna submit a PR to fix this as soon as I can. Sorry for the trouble 😅
