### ISSUE TITLE
[Manager] Pipeline and connector fail to remove

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#5503]
Pipeline and connector fail to remove
--------
Add a JDBC connector (without JDBC connector plugin), when user forgot to add the plugin jar will cause the pipeline dead.
Can't remove any component(topic or connector) and pipeline can't delete.
And the connector should show failed status(red) but still show stopped status(gray), user have to refresh the page to see the real status.
Can't restart Workspace, Broker, Worker
![0727](https://user-images.githubusercontent.com/60953697/88498355-7bd95800-cff5-11ea-8f60-f884a59a0a91.PNG)
![072701](https://user-images.githubusercontent.com/60953697/88498357-7ed44880-cff5-11ea-9358-4986f1777cf2.PNG)
![072702](https://user-images.githubusercontent.com/60953697/88498362-81cf3900-cff5-11ea-9a0a-78b526eaebbe.PNG)
![072703](https://user-images.githubusercontent.com/60953697/88498370-85fb5680-cff5-11ea-960a-e9be6a3ced35.PNG)
![072705](https://user-images.githubusercontent.com/60953697/88498391-91e71880-cff5-11ea-861c-741b12c50161.PNG)

  Tracked in #5501 and #5502

_Originally posted by @chuntsekevin in https://github.com/oharastream/ohara/issues/5374#issuecomment-664088968_

**Comment by konekoya** [comment]
@chuntsekevin This issue has been fixed by #5501 and #5506. Could you help test this again on your env with the newest docker images. Thanks!

**Comment by chuntsekevin** [comment]
@konekoya 
I tested it, everything works great ! Thanks

**Comment by konekoya** [comment]
Thanks for confirming this :)
