### ISSUE TITLE
Disable to execute start/stop requests concurrently

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#5515]
start/stop在有些服務很快，但有些涉及資料集的則會很慢(例如worker and broker)，如果我們同時處理start/stop的話，可能會造成不可預期的後果(例如start和stop交錯處理，則最後會是start還是stop?)

理論上，我們應該引入一個機制來針對API層級做互斥，如此之後可以方便擴充至任何APIs，不過考量時間問題，我們會先引入一個暫時解，先針對service start/stop做處理，將會包含以下變更：

1. 如果一個server正在stopping，則下一個stop request會立刻返回
1. 如果一個server正在stopping，則下一個start request會返回錯誤訊息
1. 如果一個server正在starting，則下一個stop request會返回錯誤訊息
1. 如果一個server正在starting，則下一個start request會立刻返回
1. 其他APIs則不受影響

這個變更會破壞behavior compatibility，例如前端在重啟過程中必須確保重複發送的stop requests都完成後才可以送start request，否則就會遇到錯誤

**Comment by chia7712** [comment]
ping @oharastream/frontend

**Comment by saivirtue** [comment]
> 如果一個server正在stopping，則下一個stop request會立刻返回

> 例如前端在重啟過程中必須確保重複發送的stop requests都完成後才可以送start request

這邊有兩個問題：
1. 完成的意思是指該start/stop request執行後，`state=RUNNING or FAILED / None or FAILED` 嗎?
2. 因為start / stop的動作涉及除了services以外，還有topic, stream, shabondi and connector。是否當正在啟動一個topic後，其他的topics的啟動都會做任何動作?  如果是，這部分前端也會有相關的調整需要做...

**Comment by chia7712** [comment]
> 完成的意思是指該start/stop request執行後，state=RUNNING or FAILED / None or FAILED 嗎?

沒錯，你是想問要如何透過API得知是否已經「完成」嗎

> 是否當正在啟動一個topic，其他一起啟動的topics都不會做任何動作?

只有container相關的服務才會有此限制

**Comment by saivirtue** [comment]
> 沒錯，你是想問要如何透過API得知是否已經「完成」嗎

Yes & Got it.

>只有container相關的服務才會有此限制

意思是stream 與 shabondi需要額外處理了。

**Comment by chia7712** [comment]
> 意思是stream 與 shabondi需要額外處理了。

他們基於container的服務

> Yes & Got it.

現在狀況是這樣，前端送了某個stop request，然後接著送出下一個start request，就後端而言目前就是看他們兩個誰跑得快誰跑得慢，也造成現在的議題。

有兩個方向：
1. 前端不要嘗試去送很多stop requests，而是改成送出一個stop request，接著GET一段時間，如果state沒有更動則視為錯誤
1. 前端一樣嘗試送一堆stop requests，然後在送start的時候遇到正在stopping的錯誤的話，則等待一段時間再重送start

**Comment by jackyoh** [comment]
我支持第一種做法，這樣才能預期總共送進來幾個 request。比較好預測程式的行為
