### ISSUE TITLE
an new dockerfile used to build kafka with specify revision

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#5547]
Sometimes we have to use kafka with specify revision to verify the bug happening on Ohara. The existent dockerfile can only accept "release" kafka and it is out-of-date as the bug fix may be not included already.

This issue aims to offer new dockerfile used to build image on specify kafka. For example, you can build image with latest kafka (xxx-SNAPSHOT) and then run it with Ohara to see what is broken.

**Comment by jackyoh** [comment]
這裡我猜實作的方法是將 apache Kafka 的原始碼透過寫 dockerfile 的方式將原始碼 clone 下來，然後在 dockerfile 寫 build apache kafka 的動作。之後啟動 broker 的作法應該跟之前是 一樣的。

**Comment by chia7712** [comment]
> 這裡我猜實作的方法是將 apache Kafka 的原始碼透過寫 dockerfile 的方式將原始碼 clone 下來，然後在 dockerfile 寫 build apache kafka 的動作。之後啟動 broker 的作法應該跟之前是 一樣的。

we are on the same page :)
