### ISSUE TITLE
Enable to configure the repo in building custom broker image

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#5549]
this is follow-up of #5547. The repo should be a argument so caller can define another one to change what is built.

**Comment by jackyoh** [comment]
> The repo should be a argument

我想使用情境應該是，如果是有 fork 程式碼並且有開 branch 的需求下就會用到 argument。

**Comment by chia7712** [comment]
> 如果是有 fork 程式碼並且有開 branch 的需求下就會用到 argument。

也可以測試自己的patch
