### ISSUE TITLE
PerfTask should sleep to avoid busy loop

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#5638]
PerfTask directly returns empty array before reaching time threshold. However, kafka keeps looping the poll and so it causes a busy loop which produces a large CPU overhead.

**Comment by chia7712** [comment]
@jackyoh 你覺得jdbc connecot也有類似的問題嗎？

**Comment by jackyoh** [comment]
jdbc source connector 應該也有類似問題，我會再開 issue 和 PR 來修正。
