### ISSUE TITLE
Modify java data type for the PerfSourceTask result cell

### ISSUE THREAD

**Issue by jackyoh** [oharastream/ohara#5656]
PerfSourceTask 的 run function 裡有做 value 的資料型態轉換，約 58 行到 66 行的地方。看起來是使用 scala 的 type 是否要修改成 java 的 type?

@chia7712 FYI

**Comment by chia7712** [comment]
nice finding. feel free to file PR to fix it :)

**Comment by jackyoh** [comment]
OK, I will open the PR to fix this issue.
