### ISSUE TITLE
Synchronized the project description

### ISSUE THREAD

**Issue by HarryChiang143** [oharastream/ohara#568]
Needed to update the README files Project description with 'Easy to deploy the streaming application'

**Comment by HarryChiang143** [comment]
@vitojeng 
Cause i don't have permission, plz help to update the ohara's repo description with this : 
[Ohara Stream - Easy to deploy the streaming application   ]

**Comment by chia7712** [comment]
> Ohara Stream - Easy to deploy the streaming application

done

**Comment by vitojeng** [comment]
@chia7712 Thanks!
