### ISSUE TITLE
[Manager] Failed to create volume in quick start mode

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#5700]
There are three problems I faced during the steps:
1. The "validation" was triggered by blur action, but didn't "stop validating" when repeat blurring
2. validation failed with unclear message (see below)
![image](https://user-images.githubusercontent.com/8088616/96951373-ef203680-151e-11eb-899d-3a818c053531.png)
3. Leave volume empty still trigger unknown snackbar message
![image](https://user-images.githubusercontent.com/8088616/96951438-124ae600-151f-11eb-8ee1-101dd4399655.png)

**Comment by eechih** [comment]
I take over this issue
