### ISSUE TITLE
[Manager] New volume user interface

### ISSUE THREAD

**Issue by eechih** [oharastream/ohara#5735]
Feature:
1. Service volume page 整合進到 service node page
2. 刪除原本的 service volume page
3. Service 新增節點時會直接生效，不需要 restart workspace
4. 使用者無法直接修改 volume 的設定 
5. Volume 的節點會隨著 service 的節點動態增加

UI:
![Broker](https://user-images.githubusercontent.com/703126/97659109-1a6bce00-1aa9-11eb-83c5-c2c1053b856f.png)

Task:
- [x] Remove unnecessary UI - The zookeeper's volume and broker's volume pages #5752 
- [x] Broker's incremental node
- [x] Worker's incremental node
- [x] Add volume information to the broker node page #5769

/cc @oharastream/developer

**Comment by saivirtue** [comment]
小細節提醒一下：
1. 現有的名稱會由"Broker nodes" 改成 "Broker nodes and volumes"
2. Zookeeper nodes and volumes頁面在0.12版會只能"檢視"，不能"修改"
