### ISSUE TITLE
[Manager] Could not display boolean value in devTool dialog normally

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#5737]
The **col3** column is empty
![image](https://user-images.githubusercontent.com/8088616/97821332-03b5b900-1ced-11eb-8bf7-8c75e71ca158.png)

But the **col3** has value "false"
![image](https://user-images.githubusercontent.com/8088616/97821346-0d3f2100-1ced-11eb-8637-791edf993f3c.png)

**Comment by konekoya** [comment]
No problem, I will give this a look
