### ISSUE TITLE
[Manager] The scrollbar of devTool dialog could not stick with the mouse moves

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#5739]
When I drag the scrollbar **rapidly** (see below snapshot), the display view changes as expected, but the scrollbar itself could not "scroll" to the desired position?

![image](https://user-images.githubusercontent.com/8088616/97822207-06fe7400-1cf0-11eb-860d-e370cc083dc9.png)

**Comment by saivirtue** [comment]
/cc @konekoya @eechih 
Do you have any idea about tihs?

**Comment by eechih** [comment]
I take over this issue.

**Comment by eechih** [comment]
@saivirtue 

先說明一下 Scrollbar 會偏移的原因

因為 CellMeasurer 會 **動態計算** 每行高度，計算後得到的 row height 與原本的 row height 不一樣時，就會即時改變 List height，因此 Scrollbar height 也會跟改變。

舉個例子，當資料有 100 筆，每行高度預設為 20，Scrollbar height 應該為 2000，由於每一行的 height 都要經過實際資料計算後才能得到，假如計算後每一行都為 30，因此每往下捲動一筆就造成 10 的偏移誤差（累加）。

目前還沒有找到解法 :(

**Comment by eechih** [comment]
resolved by #5745
