### ISSUE TITLE
[Manager] Save autofill from property will cause clean current data

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#5796]
**Describe the bug**
Save autofill from property will cause clean current data

**To Reproduce**
1. create workspace and pipeline
2. drag a ftpSource connector
3. fill data for the required fields
4. save it as an autofill

**Expected behavior**
Saved successfully and remain the fileds data

**Screenshots**
`Before click saving to autofill`
![image](https://user-images.githubusercontent.com/8088616/99352852-4f1bba00-28de-11eb-8a74-007ae8bdc88e.png)
`After clicked saving to autofill`
![image](https://user-images.githubusercontent.com/8088616/99352860-55aa3180-28de-11eb-8f22-88804fec40fa.png)

**Additional context**

**Comment by saivirtue** [comment]
/cc @konekoya @eechih 
I've remembered that we had discussed this issue before, but could not find the relative issue...

**Comment by konekoya** [comment]
Can confirm this is a bug. Thanks for reporting this!
