### ISSUE TITLE
[Manager] Endpoint field of Shabondi is missing before running?

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#5802]
**Describe the bug**
Endpoint field of Shabondi is missing

**To Reproduce**
1. Create workspace and pipeline
2. drag a `ShanbondiSource`
3. edit the property

**Expected behavior**
The Endpoint field should have more clear information instead of "Endpoint"

**Screenshots**
![image](https://user-images.githubusercontent.com/8088616/99629415-eade2f00-2a72-11eb-93d8-0deb3d9d0a49.png)

**Comment by vitojeng** [comment]
@saivirtue Thanks for report this.
Will update endpoint description to make more clear.

**Comment by saivirtue** [comment]
will be solved by #5804, close now.
