### ISSUE TITLE
[Manager] Endpoint field has an un-replaced variable?

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#5803]
**Describe the bug**
Endpoint field has an un-replaced variable

**To Reproduce**
1. Create workspace and pipeline
2. Drag a ShabondiSource
3. Fill the required property
4. Start it
5. View the property again

**Expected behavior**
The Endpoint field should not have un-replaced variables

**Screenshots**
![image](https://user-images.githubusercontent.com/8088616/99629673-5922f180-2a73-11eb-997d-b7c7f8f9cb2a.png)

![image](https://user-images.githubusercontent.com/8088616/99629703-67710d80-2a73-11eb-9793-36f4f69ddd2e.png)

**Comment by saivirtue** [comment]
Thanks @eechih for clarifying this!
So far it looks like an unclear doc problem... @vitojeng could we modify this to make it clear?

**Comment by vitojeng** [comment]
@saivirtue Thanks for report this.
Will update endpoint description to make more clear.

**Comment by saivirtue** [comment]
will be solved by #5804, close now.
