### ISSUE TITLE
Configurator 提供驗證 K8S 的 slave 是否有安裝的功能

### ISSUE THREAD

**Issue by jackyoh** [oharastream/ohara#585]
This issue includes following pull requests.
1. #597
move the validation from route to collie. Each collie is able to have different validation implementation
2. #xxx   (@jackyoh please fill the number)
implement verifyNode() for k8s collie

**Comment by chia7712** [comment]
不太一樣喔 是在驗證節點（/v0/validate/node)這支api上要加上測試節點是否有運作k8s的邏輯

**Comment by jackyoh** [comment]
ok, 我來改一下標題

**Comment by chia7712** [comment]
Let me do a bit refactor for this issue.

**Comment by chia7712** [comment]
#552 should be fixed first so as to diminish the changes produced by refactor.

**Comment by chia7712** [comment]
@jackyoh This is a basic function of validation route. Please go out of your way to resolve it as soon as possible.

**Comment by jackyoh** [comment]
> @jackyoh This is a basic function of validation route. Please go out of your way to resolve it as soon as possible.

我這邊要先寫K8S的使用文件，做完之後就來做這個 issue.

**Comment by saivirtue** [comment]
根據這邊的敘述，我預期這個issue會在`v0.4`完成，因此我把issue的label補上0.4
