### ISSUE TITLE
Enable metrics on ohara

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#601]
We already have a great wrap of connector for ohara. As a comprehensive tool, however, we still lack monitor infra - metrics and logs. This issue aims to implements a basic function of metrics that enable row connector to report "the various counter of data flow".

Summarily, there are five sub-tasks are included by this issue.
1. Enable JMX service on configurator (#634)
1. Port of RMI connector needs to be configured also (#635)
1. Add ohara-metrics module, basic bean object and accessor (#657)
1. Enable JMX service on worker cluster (#662)
1. add "unit" to Counter to show the meaning of value in Counter (#667)
1. add background metrics to row connector (#675)
1. the new APIs for /v0/pipelines ([docs](https://paper.dropbox.com/doc/Configurator-APIs--Aa1n6ube4696WXV6y46EHqIiAg-nYWQMqQLGsG0lffMaY7Xk#:uid=953035614408446657328839&h2=[object]-Object-Abstract)) (#676)
1. Add a helper method to create Counter quickly for custom connector (#679)
1. Add metrics to /v0/connector (#684)

2019/04/08
~~a simple APIs of retrieving metrics from row connectors~~
~~a metrics APIs for row counter~~
2019/04/09
~~We have contributed Counter APIs.~~

2019/04/09
Change all metrics methods from blocking to async (movied to issue #678)

**Comment by chia7712** [comment]
Personally, this issue should be incorporated into 0.4. But there is no label for 0.4.

**Comment by vitojeng** [comment]
@chia7712 Can we have a meeting about this issue for more detail idea?

**Comment by chia7712** [comment]
> Can we have a meeting about this issue for more detail idea?

sure

**Comment by chia7712** [comment]
all sub-issues are completed :)
