### ISSUE TITLE
 Update version of master branch to 0.4-SNAPSHOT

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#607]
The following tasks must be addressed 
- [x] update versions of master branch to 0.4-SNAPSHOT
- [x] upload 0.4-SNAPSHOT images to docker hub
- [x] update all versions of jenkins to 0.4-SNAPSHOT

required by #606

**Comment by saivirtue** [comment]
@chia7712 @jackyoh 
jenkins上的CD (Delivery, Deploy)我已經把`swagger`拔掉，並且更新image都會用`0.4-SNAPSHOT`了
再麻煩兩位幫忙把QA部分也更新囉，謝謝~

**Comment by chia7712** [comment]
> 麻煩兩位幫忙把QA部分也更新囉

Sure

**Comment by jackyoh** [comment]
ok, 我來更新

**Comment by chia7712** [comment]
> ok, 我來更新

I have updated our jenkins :)
