### ISSUE TITLE
No status found for connector

### ISSUE THREAD

**Issue by HarryChiang143** [oharastream/ohara#608]
**Describe the bug**
the configurator can not find the currect status with connector.

**To Reproduce**
1. Go to 'pipeline'
2. Create FTP source connector on 'pipeline page'
3. fill in the configuration  
4. Run the source connector
5. See error

**Expected behavior**
the source connector should be run success, cause the same scenario on release v0.2 was OK!

**Screenshots**
<img width="1440" alt="螢幕快照 2019-04-01 下午2 31 58" src="https://user-images.githubusercontent.com/46185836/55307801-33ef0300-548b-11e9-92d2-aca175a073a5.png">

**Operation System (please complete the following information):**
 - Backend OS & Version: [e.g. CentOS 7.6]
 - Browser & Version [e.g. Chrome 72.0.3626.119 64bit]

**Additional context**
the configurator logs
[configurator.log](https://github.com/oharastream/ohara/files/3028049/configurator.log)

**Comment by konekoya** [comment]
Thanks for reporting @HarryChiang143! We'll need to dig into this a bit and see if it's related to #586

**Comment by chia7712** [comment]
According to error message, you neglect the field of input folder. Could you check the second tab?

**Comment by HarryChiang143** [comment]
<img width="328" alt="螢幕快照 2019-04-01 下午3 02 23" src="https://user-images.githubusercontent.com/46185836/55309093-49fec280-548f-11e9-9775-791c63db59de.png">
<img width="332" alt="螢幕快照 2019-04-01 下午3 02 27" src="https://user-images.githubusercontent.com/46185836/55309097-4bc88600-548f-11e9-8096-267d909ae747.png">

all record is stay in UI

**Comment by konekoya** [comment]
@HarryChiang143  This is fixed in the v0.3.1 release.
