### ISSUE TITLE
出 Error Exception 時希望可在 Pipeline 上看到圖示是紅色的，且可以點選查看後台log

### ISSUE THREAD

**Issue by HarryChiang143** [oharastream/ohara#618]
# Description：

目前在pipeline UI上面所看到的各component狀態都是存放在status topic裡面由configurator去查詢並呈現在UI上，但是當Pipeline中運行的component如果發生Error，但status topic並無更新，會導致Pipeline UI上仍呈現該component正在運行，但是實際上是有問題的狀況。

# Disscuss:

討論如何將pipeline中運行的component狀態正確的呈現，並且於出現Exception時可點選查看該component log

**Comment by chia7712** [comment]
related to #601

**Comment by chia7712** [comment]
the new UI layout (#2470) has covered this issue :)
