### ISSUE TITLE
Refactor CommonUtils.requireNonEmpty

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#637]
Currently, we have following function to check object is `not null or empty` :

1. requireNonEmpty(**String** s)
2. requireNonEmpty(**String** s, Supplier<String> msg)
3. requireNonEmpty<**Collection** T>(Ts)
4. requireNonEmpty<**Collection**>(Ts, Supplier<String> msg)
5. requireNonEmpty<**Map**>(T s)
6. requireNonEmpty<**Map**>(T s, Supplier<String> msg)

But we could not write the following code in scala :
`requireNonEmpty(seq: Seq[String])`

this issue will address the problem and refactor utils

**Comment by saivirtue** [comment]
@chia7712 
因為目前很多scala都使用自己的方式去檢查，我會把有使用`requireNonEmpty`的地方都使用CommonUtils

**Comment by chia7712** [comment]
> 因為目前很多scala都使用自己的方式去檢查，我會把有使用requireNonEmpty的地方都使用CommonUtils

great!
