### ISSUE TITLE
As a developer, I need a proposal to understanding the overall design to enable metrics

### ISSUE THREAD

**Issue by eechih** [oharastream/ohara#642]
- [x] Wireframe
- [x] High level architecture concept of backend ([link](https://paper.dropbox.com/doc/OharaStream-metric-proposal-qa4de7FP9aJKxxLUnGzRt))
- [x] High level architecture concept of frontend

##### 1. Connector metrics
![Image of metrics connector](https://raw.githubusercontent.com/oharastream/images/master/issues/642/metrics_connector.png)
##### 2. Connector topic (收合)
![Image of metrics topic](https://raw.githubusercontent.com/oharastream/images/master/issues/642/metrics_topic_1.png)
##### 3. Connector topic (展開)
![Image of metrics topic](https://raw.githubusercontent.com/oharastream/images/master/issues/642/metrics_topic_2.png)

- 顯示 Metrics 規則：
  - Pipeline graph:
    - Connector, StreamApp 在 Running 狀態下顯示，其它狀態不顯示
    - Topic 不顯示
  - Component form:
    - Connector, StreamApp 在 Running 狀態下顯示，其它狀態不顯示
    - Topic 顯示
- 每個元件都有 Metrics 資訊，Metrics 是一個 List 物件
  - 不管 Metrics 有幾筆資料，基本上只顯示「最多」2 筆 Metric
  - 當 Metrics 資料超過 2 筆，會出現「Show more」，用來展開全部 Metrics，展開後可收合
- Highlight the current graph

**Comment by vitojeng** [comment]
@chia7712 Do you have time to write the proposal?

**Comment by chia7712** [comment]
> Do you have time to write the proposal?

I don't think so. There are too many guideline in my queue :(

**Comment by vitojeng** [comment]
> I don't think so. There are too many guideline in my queue :(

That's fine, Just curious. This issue does not urgent now.
But I think we need to finish it before the end of M27.
I can help to write the proposal if you needed.

**Comment by chia7712** [comment]
> But I think we still need to finish it before the end of M27.

Got it. I will complete it as hard as I can.

> I can help to write the proposal if you needed.

:)

**Comment by eechih** [comment]
@vitojeng @konekoya @wu87988622 @chia7712 @saivirtue @jackyoh  
I have uploaded wireframe images to this issue. Could you review? thanks :)

**Comment by konekoya** [comment]
@eechih Looks really good to me! Just a few things. 
- Could we change the connector metric's more icon (a rightward arrow) to an upward arrow when the connector metric has more info (is collapsed)? Since this is a more commonly seen practice :)

- Can we use gray shadow instead of bluish shadow for the sake of the consistency?

Thanks

**Comment by eechih** [comment]
@konekoya 
> change the connector metric's more icon (a rightward arrow) to an upward arrow

好建議

> Can we use gray shadow instead of bluish shadow

好喔
