### ISSUE TITLE
As a dev, I’m able to verify that pipeline pages are working as expected via e2e tests

### ISSUE THREAD

**Issue by eechih** [oharastream/ohara#645]
- [x] Users can create new pipelines and see the pipeline in the list page
- [x] Users can edit pipeline title and save it 
- [x] Users can add new connectors into pipelines
- [x] Users can add new topics into pipelines
- [x] Users can add new stream app into pipelines
- [x] Users can delete a pipeline with its delete button
- [x] Users can see the correct relation between connectors in the pipeline graph
- [x] Users can save graph after adding/removing new connectors

**Comment by konekoya** [comment]
@vitojeng Please review the story, Thanks!
