### ISSUE TITLE
As a dev, I’m able to verify that source connectors are working as expected via e2e tests

### ISSUE THREAD

**Issue by eechih** [oharastream/ohara#646]
- [ ] Users can start/stop a connector(including stream app) with its start/stop buttons
- [ ] Users can remove a connector(including topic) with its remove button
- [ ] Users can save connector config after add/editing a connector’s property form
- [ ] Users can test connection with connector property forms
- [ ] Users cannot edit connector property forms if the connector is running

**Comment by konekoya** [comment]
Moving up to new UI
