### ISSUE TITLE
身為開發者，我希望可以透過 UT 測試 stream router 功能是否正常

### ISSUE THREAD

**Issue by eechih** [oharastream/ohara#649]
- [ ] Stream Action APIs should be working as expected (normal cases)
- [ ] Stream List APIs should be working as expected (normal cases)
- [ ] Stream Property APIs should be working as expected (normal cases)
- [ ] Stream Action APIs should handle the exception cases
- [ ] Stream List APIs should handle the exception cases
- [ ] Stream Property APIs should handle the exception cases

**Comment by saivirtue** [comment]
the related issue is finished, change the state to `review`
