### ISSUE TITLE
Remove swagger from ohara

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#666]
Seems the swagger repo is already removed from docker hub. Should we remove swagger from our repo also?

BTW, this issue is critical since our CD is broken due to the failure of uploading swagger to docker hub.

**Comment by chia7712** [comment]
ping @vitojeng @jackyoh @eechih @konekoya @saivirtue

**Comment by vitojeng** [comment]
+1

**Comment by saivirtue** [comment]
+1+1
