### ISSUE TITLE
Complete the badges

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#669]
The following badges should be good to ohara :)
- [x] license badge (#670)
- [x] CD badge (duplicate to issue #779)

Are there any other magic badges suitable to ohara ?
ping @konekoya @vitojeng @eechih @jackyoh @saivirtue

**Comment by saivirtue** [comment]
@chia7712 like this?
https://shields.io/

**Comment by chia7712** [comment]
> https://shields.io/

There are too many badges in this world. It would be better to take the badges which are useful to ohara :)

**Comment by vitojeng** [comment]
We could add a community badge after we have a community chat room or mailing list.

**Comment by chia7712** [comment]
不小心按到關閉...

**Comment by chia7712** [comment]
seems no more badges are required in 0.4. close it now.
