### ISSUE TITLE
Add connectors info in the workers API

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#685]
We're now able to fetch connectors info from configurator's `v0/workers` API. But the same info cannot be obtained from the `v0/workers/${workerName}` API.

Adding this support would make frontend data fetching a whole lot easier :)

**Comment by chia7712** [comment]
How about replacing the container details by cluster info? For example.
GET /v0/worker/aaa
```
{
   "name": "xx",
   "clientPort": 123
}
```

**Comment by konekoya** [comment]
Could you elaborate a bit more? Not sure about what you mean by container details vs cluster info?

**Comment by chia7712** [comment]
> Could you elaborate a bit more? Not sure about what you mean by container details vs cluster info?

I means the data returned by "GET /v0/worker/aa" will be equals to "GET /v0/worker + filter for aa"

**Comment by konekoya** [comment]
Sounds good to me :)
