### ISSUE TITLE
Replace onSuccess() by complete()

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#686]
complete() suit us enough :)

2019/04/09
1. the first commit (#687) use wrong commit message.
1. #691 is used to revert #687
1. #694  is the final commit with correct message

**Comment by saivirtue** [comment]
I think the title should be "replace onSuccess by complete" XD
anyway, this is a good task 👍

**Comment by chia7712** [comment]
> I think the title should be "replace onSuccess by complete" XD
anyway, this is a good task

let me re-commit it ...
