### ISSUE TITLE
Complete the docs of restful APIs

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#701]
There are too many APIs in ohara so this issue will be made up of several pull requests.

1. add docs folder and initialize restful apis docs (#704)
1. add objects docs (#713)
1. add connector docs (#716)
1. add pipeline docs (#717)
1. add cluster docs (#725)
1. add validate docs (#737)
1. add containers docs (#739)
1. add streamapp docs (#743)
1. add jars docs (#744)
1. add logs docs (#747)

**Comment by chia7712** [comment]
@vitojeng Shabondi docs seems to be not complete so I don't file a PR for it

**Comment by vitojeng** [comment]
> @vitojeng Shabondi docs seems to be not complete so I don't file a PR for it

Sure. 👌

**Comment by chia7712** [comment]
Except for private APIs, all public APIs have be documented.  Close this issue now.
