### ISSUE TITLE
K8S 的 pod name 不支援大寫

### ISSUE THREAD

**Issue by jackyoh** [oharastream/ohara#705]
**Describe the bug**
K8S 的 Pod Name 不支援大寫，因此使用 ohara agent 建立 cluster 在 UI 上指定大寫，程式會出錯誤

**Comment by chia7712** [comment]
建議要加到route上去做統一的檢查

**Comment by jackyoh** [comment]
那 ssh 版本的 cluster name 也要小寫嗎？

**Comment by chia7712** [comment]
> 那 ssh 版本的 cluster name 也要小寫嗎？

放在route上就是給所有implementation套上相同的限制

**Comment by jackyoh** [comment]
OK，我來修改

**Comment by chia7712** [comment]
@saivirtue I feel this is not critical bug..so probably we don't need include it in 0.3.1?

**Comment by chia7712** [comment]
another Q: @jackyoh Is this a "bug"? Do you have a way to make k8s accept upper case?

**Comment by jackyoh** [comment]
因為程式不能建立 worker 我就指定 bug. k8s 的 pod name 不能是大寫. 參考網址如下：
https://kubernetes.io/docs/concepts/overview/working-with-objects/names/

**Comment by chia7712** [comment]
> 因為程式不能建立 worker 我就指定 bug. k8s 的 pod name 不能是大寫. 參考網址如下：

If you are able to "fix" it, it is ok to use "bug" label.

**Comment by jackyoh** [comment]
我的 fix 只是在 route 裡面加上判斷的條件. 如果輸入大寫就會丟出錯誤的訊息

**Comment by chia7712** [comment]
> 如果輸入大寫就會丟出錯誤的訊息

user still **can't** use upper case, right? If so, the upper case is **not** a bug in our system.

**Comment by jackyoh** [comment]
ok, 我來修改 label
