### ISSUE TITLE
確認 K8S 的 pod 名稱, 可以使用的字元

### ISSUE THREAD

**Issue by jackyoh** [oharastream/ohara#726]
目前發現 k8s 的 pod name 不能設定大寫的字串, 需要去確認還有哪些字元在 k8s 的 pod name 不能使用.

https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names

**Comment by chia7712** [comment]
any update?

**Comment by jackyoh** [comment]
這個議題沒有要更新了我先關閉掉
