### ISSUE TITLE
Use mock instead of FakeK8SClient

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#729]
Most functions in FakeK8SClient are not implemented so we can replace it by mock easily.

**Comment by chia7712** [comment]
FYI @jackyoh

**Comment by jackyoh** [comment]
這個我會修改使用 easy mock 來做

**Comment by chia7712** [comment]
there is a test "TestK8SClient" so do you plan to add more tests?

**Comment by jackyoh** [comment]
我想把 addConfig, removeConfig 和 inspectConfig 的方法，加入到 TestK8SClient 的測試
