### ISSUE TITLE
[Phase 1] Refactor K8sClient

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#731]
in #728 I tried to add an new method to K8sClient, and then I noted that it doesn't handle the akka stuff...

- [x] add UT for K8sClient.images (#1126)

- [x] cover all methods of K8sClient by unit tests (#1161 )

the follow-up to this is #1318

**Comment by chia7712** [comment]
FYI @jackyoh

**Comment by jackyoh** [comment]
在 K8SClient 呼叫 akka http 有很多重複的 code 需要重構, 減少程式碼的重複性

**Comment by jackyoh** [comment]
```
 Http().singleRequest(HttpRequest(HttpMethods.DELETE,
                  uri = s"${k8sApiServerURL}/namespaces/default/pods/${container.name}"))
                    .map(_ => container)
```
需要增加 error handler 的程式碼

**Comment by jackyoh** [comment]
Currently, K8SClient create a ActorSystem instance internally:
```
object K8SClient {
  def apply(k8sApiServerURL: String): K8SClient = {
    new K8SClient() with SprayJsonSupport {
      private[this] implicit val actorSystem: ActorSystem = ActorSystem(s"${classOf[K8SClient].getSimpleName}")
      private[this] implicit val actorMaterializer: ActorMaterializer = ActorMaterializer()
```

This would lead to two ActorSystem instances in Configuration. An ActorSystem is a heavyweight structure that will allocate 1…N Threads, so it should pass ActorSystem instance from outside into K8SClient to keep only one ActorSystem instance.

**Comment by chia7712** [comment]
@jackyoh I will file a PR to add a unit test for K8sClient.images. Please follow my sample to write tests for other methods of K8sClient.

**Comment by jackyoh** [comment]
OK, refactor 的時候我會按照這個 sample 來寫測試程式.

**Comment by chia7712** [comment]
可以考慮先補上測試再做refactor 這樣才能驗證你refactor沒有破壞東西

**Comment by jackyoh** [comment]
ok, 那看起來我應該另外開一個 issue

**Comment by chia7712** [comment]
@jackyoh Please add 0.5.0 label

**Comment by jackyoh** [comment]
OK
