### ISSUE TITLE
ZK & BK service info display is incomplete

### ISSUE THREAD

**Issue by HarryChiang143** [oharastream/ohara#738]
**Describe the bug**
UI 顯示的Service 資訊不完全

**To Reproduce**
1. start configurator>start manager>add ohara nodes>add zk service by rest>add bk service by rest
2. check the UI service page
3. see this bug.

**Expected behavior**
我認為雖然service list的內容是設定為不可編輯的，但應該讓資訊完整的顯示，而不是因為太長而被截斷。

**Screenshots**
![螢幕快照 2019-04-12 下午2 56 49](https://user-images.githubusercontent.com/46185836/56018182-f5cbcc00-5d33-11e9-80d5-3c265580ef5e.png)

![螢幕快照 2019-04-12 下午2 56 55](https://user-images.githubusercontent.com/46185836/56018187-f82e2600-5d33-11e9-9373-91aa0f19a976.png)

**Operation System (please complete the following information):**
- Backend OS & Version: [CentOS 7.6]
- Browser & Version [Chrome 72.0.3626.119 64bit]

**Additional context**
none.

**Comment by chia7712** [comment]
FYI @eechih @konekoya

**Comment by eechih** [comment]
@HarryChiang143 這個問題我們會盡快修好。
Broker & Zookeeper services 將會參考 Connector worker services 的列表顯示
