### ISSUE TITLE
K8SClient seems always pull image from docker hub

### ISSUE THREAD

**Issue by vitojeng** [oharastream/ohara#746]
I built a local image both in the two VMs. One is k8s master and the other is k8s slave.

Specify the local image to `K8SClient.ContainerCreator` to create pod, it always occur `ImagePullBackOff` error. For example:
```
Events:
  Type     Reason     Age                From                      Message
  ----     ------     ----               ----                      -------
  Normal   Scheduled  51s                default-scheduler         Successfully assigned default/shabondi-ohara-dev-vito2 to ohara-dev-vito2
  Normal   BackOff    19s (x2 over 47s)  kubelet, ohara-dev-vito2  Back-off pulling image "ohara/shabondi"
  Warning  Failed     19s (x2 over 47s)  kubelet, ohara-dev-vito2  Error: ImagePullBackOff
  Normal   Pulling    7s (x3 over 50s)   kubelet, ohara-dev-vito2  Pulling image "ohara/shabondi"
  Warning  Failed     4s (x3 over 47s)   kubelet, ohara-dev-vito2  Failed to pull image "ohara/shabondi": rpc error: code = Unknown desc = Error response from daemon: pull access denied for ohara/shabondi, repository does not exist or may require 'docker login'
  Warning  Failed     4s (x3 over 47s)   kubelet, ohara-dev-vito2  Error: ErrImagePull
```

It seems K8SClient always pull the image from docker hub.
The better way is the image pulled only if it is not already present locally.

**Comment by chia7712** [comment]
@jackyoh please **highlight** this behavior in our k8s docs

**Comment by vitojeng** [comment]
@jackyoh 我直接 hard code 修改 CreatePodContainer 做測試:
```scala
  final case class CreatePodContainer(name: String,
                                      image: String,
                                      env: Seq[CreatePodEnv],
                                      ports: Seq[CreatePodPortMapping],
                                      imagePullPolicy: String = "IfNotPresent")
```

這樣就沒有錯誤了.

**Comment by jackyoh** [comment]
> please **highlight** this behavior in our k8s docs

是寫在 ohara/kubernetes/README.md 的檔案裡面嗎？

**Comment by chia7712** [comment]
> 是寫在 ohara/kubernetes/README.md 的檔案裡面嗎？

沒錯。等我把docs目錄整理好後再移到底下

**Comment by jackyoh** [comment]
> @jackyoh 我直接 hard code 修改 CreatePodContainer 做測試:
> 
> ```scala
>   final case class CreatePodContainer(name: String,
>                                       image: String,
>                                       env: Seq[CreatePodEnv],
>                                       ports: Seq[CreatePodPortMapping],
>                                       imagePullPolicy: String = "IfNotPresent")
> ```
> 
> 這樣就沒有錯誤了.

我會開一個 PR 來修改這一段程式

**Comment by jackyoh** [comment]
@vitojeng 我有找到 k8s pull image policy 行為的討論, 如下網址：
https://github.com/kubernetes/kubernetes/issues/47775

FYI

**Comment by vitojeng** [comment]
> @vitojeng 我有找到 k8s pull image policy 行為的討論, 如下網址：
> [kubernetes/kubernetes#47775](https://github.com/kubernetes/kubernetes/issues/47775)

謝謝. 這樣的話, 似乎 `imagePullPolicy` default 沒有需要設成 `IfNotPresent ` ?

**Comment by jackyoh** [comment]
我覺得 api 還是要提供這個參數, 比較好修改設定的參數.

**Comment by vitojeng** [comment]
> 我覺得 api 還是要提供這個參數, 比較好修改設定的參數.

嗯, `imagePullPolicy` 有需要加. 不過我的意思是它的 *預設值* 還有需要設為 `IfNotPresent` 嗎?

**Comment by jackyoh** [comment]
看起來 imagePullPolicy default 不用設成 IfNotPresent
