### ISSUE TITLE
Show the download icon of bintray repo

### ISSUE THREAD

**Issue by mathsigit** [oharastream/ohara#779]
Currently, oharastream would publish artifacts to jfrog, and we can visualize the version for users to check.
And it looks like as below:
[![download version](https://api.bintray.com/packages/oharastream/ohara/ohara-client/images/download.svg)](https://bintray.com/oharastream/ohara)

**Comment by chia7712** [comment]
+1

**Comment by chia7712** [comment]
@mathsigit Do you plan to file PR for this issue? If so, I will assign this issue to you.

**Comment by saivirtue** [comment]
I would like to take this issue ;)

**Comment by mathsigit** [comment]
> @mathsigit Do you plan to file PR for this issue? 

Sure!
But I am so late to reply the message 😭

**Comment by chia7712** [comment]
> But I am so late to reply the message sob

We all are enthusiastic about resolving issue :)
