### ISSUE TITLE
StreamClusterInfo.ports should be a constant "empty" rather than a assignable variable

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#781]
see the comment.
```
    // We don't care the ports since streamApp communicates by broker
    ports: Seq[Int] = Seq.empty,
```
If the ports of StreamClusterInfo is always an empty collection, we should use **def** to define it.
```
override def ports: Seq[Int] = Seq.empty
```
It ensures that StreamClusterInfo's ports must be empty!

**Comment by saivirtue** [comment]
Good points, will fire pr later
