### ISSUE TITLE
Server connection refused after change streamApp.jar name

### ISSUE THREAD

**Issue by wu87988622** [oharastream/ohara#789]
Use ui change streamApp.jar name server connection refused

**Comment by saivirtue** [comment]
這個問題分為兩個點：
1. 直接使用API去上傳jar (/stream/jars)，目前會出現下面的訊息 (但使用Ohara Manager不會有問題!)
```
java.lang.IllegalStateException: Substream Source cannot be materialized more than once
```
這個是akka-http的issue，可以參考 (這個問題有很多類似的issue，目前看起來只有workaround)
[issue trace](https://github.com/akka/akka-http/issues?q=is%3Aissue+formFields+is%3Aclosed)
workaround會一起在2.的PR修正

2. 更新jar name會失敗
這個狀況不管使用API或Ohara Manager都會失敗，這個會開PR修正

**Comment by saivirtue** [comment]
這個問題的發生原因為streamApp會需要起container後，將jar download到container內；因streamApp可能會將container起在另一個container內導致無法正常下載jar (已經在調整啟動configurator的方式後不會出現此問題)。
Merge的PR為上傳jar時的akka-http bug，雖與此issue無直接關聯，但一併做修正
