### ISSUE TITLE
As a dev, I'm able to verify that users can start/stop a pipeline

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#802]
- [ ] Users can start/stop a pipeline with the start/stop buttons

This story is separate from #645 since it's too big to be criteria by itself.

**Comment by konekoya** [comment]
The detailed criteria haven't defined yet.

/cc @eechih

**Comment by eechih** [comment]
> The detailed criteria haven't defined yet.

謝謝~ 我們可以再找時間討論 criteria

**Comment by chia7712** [comment]
any update?

**Comment by konekoya** [comment]
@chia7712 No farther discussion over this very topic since then. But I think this issue is still valid in the new UI, so will keep this open

**Comment by konekoya** [comment]
In favor of #4049
