### ISSUE TITLE
Jenkins Server 設定免密碼

### ISSUE THREAD

**Issue by jackyoh** [oharastream/ohara#805]
目前跑 ohara 整合測試時會 build 出一個暫時的 template docker image, docker image 需要複製到 ohara-it 的每個節點上, 因此需要有 ssh 免密碼登入的設定. 另外要把 master 和 jenkins-slave00 的 user name 從 chia7712 修改成 ohara user name.

**Comment by chia7712** [comment]
required by #796

**Comment by jackyoh** [comment]
目前已經把免密碼的部份設定好了. 
authorized_keys 的檔案要設定成 600 才會有作用

**Comment by chia7712** [comment]
I have tested it. all pass. thank @jackyoh  for the helps!
