### ISSUE TITLE
FTP source and sink connectors cannot be started successfully

### ISSUE THREAD

**Issue by DavidMi-1** [oharastream/ohara#819]
**Describe the bug**
在 ohara dev 環境的 UI 頁面上. 啟動 pipline 的 ftp connector,
網頁上會秀出 error , 但是實際上後面的讀寫檔是有成功的

**To Reproduce**
1. 在 pipline 操作頁面
2. 點擊啟動 source connector
3. 畫面上顯示 error 訊息

**Screenshots**
![2019-04-19 11-04-53 的螢幕擷圖](https://user-images.githubusercontent.com/44669519/56403546-5d35ce80-6294-11e9-9b30-f8ab5b3c215b.png)

**Operation System (please complete the following information):**
 - OS & Version: [ CentOS 7.2]
 - Browser & Version [Google Chrome 版本 73.0.3683.103 (正式版本) (64 位元)]

**Additional context**
基本上點擊啟動 sink connector 也是一樣的 (附圖如下), 不過到 ftp 資料夾去看, 實際的讀寫檔案都有成功
![2019-04-19 11-12-33 的螢幕擷圖](https://user-images.githubusercontent.com/44669519/56403633-d8978000-6294-11e9-8320-6cd737d1a7ad.png)

**Comment by konekoya** [comment]
Thanks for reporting, I will look into it as soon as I can

**Comment by konekoya** [comment]
I'm not entirely sure if this is somewhat related to #807

**Comment by DavidMi-1** [comment]
> I'm not entirely sure if this is somewhat related to #807? Could you update your docker images and test again? Let's me know if the problem persists. Thanks!

ok ,I will check it later

**Comment by DavidMi-1** [comment]
> I'm not entirely sure if this is somewhat related to #807? Could you update your docker images and test again? Let's me know if the problem persists. Thanks!

cool , it's all pass !

**Comment by konekoya** [comment]
Thanks for confirming this, closing this PR then :)
