### ISSUE TITLE
Keep updating sbt script or not ?

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#832]
Does anyone have free cycle to update the sbt script to meet the function of gradle. For example:

1. generate VersionUtis.java dynamically
1. add ohara-metrics module
1. license check and auto-fix
1. codestyle check and auto-fix
1. tests jvm setting and output log
1. dynamically build test jar for ohara-it
1. assembly jar and uber jar
1. push artifact to bintray

If it is hard to address above functions recently, we should document the usage of our sbt setting.

PING @saivirtue @vitojeng @jackyoh

**Comment by saivirtue** [comment]
請問這邊是說"需不需要把目前sbt.version做升級的動作，並且確認gradle相關的功能是否能正常使用" 嗎?

**Comment by chia7712** [comment]
> 請問這邊是說"需不需要把目前sbt.version做升級的動作，並且確認gradle相關的功能是否能正常使用" 嗎?

沒錯 或者要文件一下我們提供的sbt能做到哪些事情

**Comment by saivirtue** [comment]
> 沒錯 或者要文件一下我們提供的sbt能做到哪些事情

了解。那等 @vitojeng 開完會後再討論作法好了

**Comment by vitojeng** [comment]
關於 sbt, 這是我的責任...沒有跟上 gradle 的進度...QQ

我的想法是: sbt 對於來自 scala community 的開發者是有相當的幫助.

不過目前在 ohara 要讓 sbt 要能夠完全做到 gradle 一樣的事, 我覺得現實層面不可行.
因此, 我的想法是可以做到 support development 的程度就足夠了.

我想可以分階段完成這個工作:
* upgrade all modules & dependencies
* important task(ex: generate VersionUtis.java...)
* update document

可以在下一個 Milestone 安排.

**Comment by vitojeng** [comment]
@chia7712 , @saivirtue , @jackyoh 
若針對 support development, 我想大約是:
0. generate VersionUtis.java dynamically
0. add ohara-metrics module
0. license check and auto-fix
0. codestyle check and auto-fix
0. tests jvm setting and output log
0. assembly jar and uber jar

你們覺得呢?

**Comment by chia7712** [comment]
+1 Please **append** it to the description of this issue.

**Comment by jackyoh** [comment]
+1

**Comment by vitojeng** [comment]
> +1 Please **append** it to the description of this issue.

After we have a conclusion, I will create another issue for this task.
