### ISSUE TITLE
Surveys the jointjs library to create the pipeline graph

### ISSUE THREAD

**Issue by eechih** [oharastream/ohara#866]
JavaScript diagramming library https://github.com/clientIO/joint

- [x] Able to add styles to the graph 
- [x] Graph can be moved around and re-position
- [x] Able to style the Line, arrow and adding a label
- [x] Line 要能多次直角轉彎（貪食蛇）
- [x] Connect two elements by drag and drop
- [ ] Able to preview (like a minimap) -- hold
- [x] Able to __zoom In__, __zoom out__, __reset__ and fit to the canvas 
- [x] Able to toggle a grid
- [x] Support drag and drop from Toolbar into the canvas
- [x] Able to save the graph

**Comment by konekoya** [comment]
Some capability I've noticed when researching this library

#### Link
- We can add label in the `Link`
- The link can be styled with stander SVG styling lang?

**Comment by konekoya** [comment]
Done :)
