### ISSUE TITLE
Incorrect serialization in creating connector on kafka

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#873]
I'm working custom connectors. After filling out necessary inputs with the UI. `/v0/${connectorId}/start` failed and given the following error:

```json
Expected String as JsString, but got {"connector":"74dc47f8-2508-4cd3-9a40-2df26fcc97c2","task":0}
```

`/v0/connectors/${connectorId}` response body

```json
{"topics":["7d7aba50-3a39-4933-b6ba-50f0f1b7b8ec"],"name":"Untitled source","state":null,"lastModified":1556006131771,"workerClusterName":"abc","configs":{"name":"Untitled source","workerClusterName":"abc","tasks.max":"1","connector.class":"com.island.ohara.it.connector.DumbSourceConnector","connector.name":"Untitled source"},"numberOfTasks":1,"id":"74dc47f8-2508-4cd3-9a40-2df26fcc97c2","schema":[],"error":null,"className":"com.island.ohara.it.connector.DumbSourceConnector","metrics":{"counters":[]},"settings":{"topics":["7d7aba50-3a39-4933-b6ba-50f0f1b7b8ec"],"name":"Untitled source","workerClusterName":"abc","tasks.max":"1","connector.class":"com.island.ohara.it.connector.DumbSourceConnector","connector.name":"Untitled source"}}
```

__UPDATED__: This behavior can also be reproduced with other connectors as well.

#### Steps to reproduce:
1. Create a connector, and fill out the config form, this includes a topic connected to it
2. Start the connector with the API: PUT `connectors/${connectorID}/start`
3. An error will be thrown from the configurator. Note that a) even though an error has occurred. The connector seems to be working fine. b) this error will only happen when you start the connector the first time.

**Comment by konekoya** [comment]
ping @chia7712

**Comment by chia7712** [comment]
This is caused by a temporary connector error happened in kakfa, and then kafka response a **incorrect** json report. I can file a PR to handle this **weird** response...

**Comment by konekoya** [comment]
No worries! Thanks for the fix 👍
