### ISSUE TITLE
Fix flaky TestFtpSourceTask.createTask

### ISSUE THREAD

**Issue by eechih** [oharastream/ohara#875]
建立 ftp source task 時，缺少 topic 相關資訊

**Comment by chia7712** [comment]
@eechih Could you fix all flaky in TestFtpSourceTask in this issue?

**Comment by eechih** [comment]
> @eechih Could you fix all flaky in TestFtpSourceTask in this issue?

ok

**Comment by chia7712** [comment]
@eechih Could we close this issue?

**Comment by eechih** [comment]
> @eechih Could we close this issue?

Sure~ I forgot to close it.
