### ISSUE TITLE
寫 K8S Demo 環境錯誤處裡的文件

### ISSUE THREAD

**Issue by jackyoh** [oharastream/ohara#883]
當 k8s 的環境遇到問題時要如何處裡, 寫一份文件來說明

**Comment by chia7712** [comment]
Please put this docs in /docs/user_guide.md. You can create a new section for k8s

**Comment by jackyoh** [comment]
OK, 收到

**Comment by chia7712** [comment]
any update?

**Comment by jackyoh** [comment]
目前沒有要更新，我先把此議題關閉
