### ISSUE TITLE
Add remove streamApp restful api

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#911]
Currently, when a streamApp is running in a pipeline, we could not remove the streamApp component only without remove others. There is a workaround that we could use DELETE pipeline api to remove streamApp, but we still need to support streamApp DELETE api.

DELETE /stream/property/${id}
**Response**
```
{
  "workerClusterName": "wk01",
  "id": "d312871a-4a05-488d-aae0-c8b27c5312c2",
  "name": "my-new-app",
  "instances": 1,
  "jarInfo": {
    "id": "1b022c59-93f9-452c-a062-f8e4cb6c00fe",
    "name": "new-name.jar",
    "size": 1234,
    "lastModified": 1542102595892
  },
  "from": [
    "topicA"
  ],
  "to": [
    "topicB"
  ],
  "lastModified": 1542102595892
}
```

- [x] implement delete api in stream router
- [x] update restful api doc
- [ ] support delete streamApp from ui

required by #423

**Comment by saivirtue** [comment]
ping @konekoya 
the related pr (#967) is opened, feel free to add comment if you have any question :)
the remain task (support delete streamApp from ui) will leave to you, thanks for helping !

**Comment by konekoya** [comment]
After the daily scrum discussion. I still have some questions about this matter. Could we have a very quick discussion over this topic today :)

**Comment by saivirtue** [comment]
> After the daily scrum discussion. I still have some questions about this matter. Could we have a very quick discussion over this topic today :)

Sure. We can review the flow of delete streamApp in next sprint :)
