### ISSUE TITLE
[docs] User Guide - phase 1

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#918]
This is a follow-up of #860 

- [x] Configurator introduction (#1119)
- [x] UI introduction (#1324)
- [x] zookeeper introduction (#1150)
- [x] broker introduction (#1182)
- [x] worker introduction (#1191)
- [x] docker introduction (#1248)
- [x] k8s introduction @jackyoh (#1295 )
- [x] trouble-shutting for configurator (#1183)

**Comment by chia7712** [comment]
@konekoya @wu87988622 Please help me complete UI (ohara manager) introduction. @jackyoh Please move the document from k8s folder to user guide. thanks!

**Comment by jackyoh** [comment]
OK, I am going to move the document from k8s folder to user guide.

**Comment by konekoya** [comment]
> @konekoya @wu87988622 Please help me complete UI (ohara manager) introduction. @jackyoh Please move the document from k8s folder to user guide. thanks!

Got it!

**Comment by wu87988622** [comment]
I got it

**Comment by chia7712** [comment]
@jackyoh @wu87988622 @konekoya Thanks, folks!!!

**Comment by jackyoh** [comment]
確認一下, 我要去寫有關於 K8S 的 介紹嗎？

**Comment by chia7712** [comment]
> 我要去寫有關於 K8S 的 介紹嗎？

簡介一下k8s 而主要內容要說ohara如何使用k8s

另外記得寫troubleshooting

**Comment by jackyoh** [comment]
收到. 我來寫看看

**Comment by konekoya** [comment]
@chia7712 UI intro has been added. Is it okay to close this out :)

**Comment by chia7712** [comment]
> UI intro has been added. Is it okay to close this out :)

@jackyoh @konekoya Thanks for helps!!!
