### ISSUE TITLE
Avoid multiple ActorSystem in one JVM

### ISSUE THREAD

**Issue by vitojeng** [oharastream/ohara#927]
Currently, K8SClient create a ActorSystem instance internally:
```scala
object K8SClient {
  def apply(k8sApiServerURL: String): K8SClient = {
    new K8SClient() with SprayJsonSupport {
      private[this] implicit val actorSystem: ActorSystem = ActorSystem(s"${classOf[K8SClient].getSimpleName}")
      private[this] implicit val actorMaterializer: ActorMaterializer = ActorMaterializer()
```

This would lead to two ActorSystem instances in Configuration. An ActorSystem is a heavyweight structure that will allocate 1…N Threads, so it should pass ActorSystem instance from outside into K8SClient to keep only one ActorSystem instance.

/cc @chia7712 , @saivirtue , @jackyoh

**Comment by chia7712** [comment]
> so it should pass ActorSystem instance from outside into K8SClient to keep only one ActorSystem instance.

This was a old story I had discussed with @jackyoh. And it should be resolved by #731

**Comment by vitojeng** [comment]
@chia7712 
Does this mean that #731 already cover this issue?

**Comment by vitojeng** [comment]
@chia7712 Thanks for the explanation.

**Comment by chia7712** [comment]
@jackyoh Please copy @vitojeng's description to #731. It should be a sub task of #731

**Comment by jackyoh** [comment]
OK, 我來 copy
