### ISSUE TITLE
Post method on /v0/hdfs giving "Unsupported API" respond

### ISSUE THREAD

**Issue by alan791205** [oharastream/ohara#942]
**Describe the bug**
I am trying to update my hdfs info to the configurator,
following the instructions in `ohara/docs/rest_interface.md`.
Using postman as my client, I created a post request on /v0/hdfs
with a body like
```
{"key":"name","value":"hdfs0","description":""},
{"key":"uri","value":"hdfs://myhdfsip:9000","description":""}
```
and it gives me a `Unsupported API: v0/hdfs` respond.
BTW, I've tried creating a get request on /v0/hdfs and gives me a `[]` respond.

**To Reproduce**

As described.

**Expected behavior**

As what readme said, should give me a respond like
```
{
  "name": "hdfs0",
  "uri": "hdfs://namenode:9999",
  "lastModified": 1553498552595,
  "id": "715e09c9-b4ee-41cc-8d05-cb544904ac38"
}
```

**Screenshots**
![擷取選取區域_069](https://user-images.githubusercontent.com/8744475/56875258-33d62900-6a72-11e9-9c58-f92f6cd85adf.png)

**Operation System (please complete the following information):**

Both centOS 7+

**Comment by konekoya** [comment]
Hi @alan791205,
Can you try using a `put` method instead of `post` to update your hdfs config? And remember to supply an existing hdfs config id. See the docs [here](https://github.com/oharastream/ohara/blob/master/docs/rest_interface.md#update-a-hdfs-information)

**Comment by chia7712** [comment]
seems our docs makes a mistake that the update should be PUT rather than POST. @alan791205 Do you have interest in fixing the typo?

**Comment by konekoya** [comment]
> seems our docs makes a mistake that the update should be PUT rather than POST

I somehow missed this...

**Comment by alan791205** [comment]
Solved, thanks to @chia7712 and @konekoya 
the body should not be formed-data but should be JSON form.
Should we put this specific thing in rest_interface.md?

> seems our docs makes a mistake that the update should be PUT rather than POST. @alan791205 
> Do you have interest in fixing the typo (see #943)?
Should we open a new issue regarding to this?

**Comment by chia7712** [comment]
> Should we open a new issue regarding to this?

I had filed a issue. See my previous comment (or #943)

**Comment by alan791205** [comment]
![擷取選取區域_070](https://user-images.githubusercontent.com/8744475/56878243-b1576480-6a85-11e9-9670-82be3a55ef61.png)

Actually I've tried the POST method on updating hdfs info, it really doesn't work LOL
But PUT method works fine.

**Comment by alan791205** [comment]
> I had filed a issue. See my previous comment (or #943)

OK, I thought it was the previous one

**Comment by chia7712** [comment]
@alan791205 Could we close this issue?

**Comment by alan791205** [comment]
> @alan791205 Could we close this issue?
Of course, thanks for the help!
