### ISSUE TITLE
The jars upload to worker should be moved to libs folder rather than plugins folder

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#986]
The jars in workers are deployed to different class loader so different plugins in different jars can't share the jars for each other. 

This issue aims to open a room to allow user to choose the location to deploy their jars. For example, An new argument called **plugins** that all jars are deployed to **plugin scope**. By contrast, the origin **jars** are deployed to global scope.

The above change does not break the compatibility and allow user to deploy jars easily.

We are going to release 0.4 so this issue **only** change the location of jars on workers. Before this issue, the jars are placed at plugins folder. Now, the jars are placed at libs folder so all jars are in global scope.

We have to introduce another argument **pluginIds** to enable user to deploy jar in plugin scope (see #995)

**Comment by chia7712** [comment]
FYI @g1geordie

**Comment by konekoya** [comment]
@chia7712 Does this issue will change the location of the test jars? Jars that frontend are using for end-to-end testing?

**Comment by chia7712** [comment]
> Does this issue change the location of the test jars?

The location changed by this PR is the worker’ jars path rather than the folder of generated test jars. Don’t worry for this PR. I won’t break the compatibility before you do release :)

**Comment by konekoya** [comment]
> The location changed by this PR is the worker’ jars path rather than the folder of generated test jars. Don’t worry for this PR. I won’t break the compatibility before you do release :)

Thanks for the clarification 💯
