### ISSUE TITLE
Syntax error on checkYarnVersion.js

### ISSUE THREAD

**Issue by alan791205** [oharastream/ohara#988]
**Describe the bug**
Using lower version of yarn..
`ohara/ohara-manager/scripts/checkYarnVersion.js`
```
31|      `Ohara Manger requires yarn 1.13.0 or greater, but you're using ${yarnVersion}`,
```
Are you missing something here?

**To Reproduce**

go to `ohara/`

```sh
$ gradle build -x test
```

**Expected behavior**

It shall give error message about lower version issue, but not a syntax error....

**Screenshots**

**Operation System (please complete the following information):**
CentOS Linux release 7.5.1804 (Core)
gradle 5.1.1

**Additional context**

**Comment by chia7712** [comment]
> Frontend OS & Version: [e.g. Windows 10]

I'm sorry but windows 10 is not supported if you want to develop ohara :(

**Comment by konekoya** [comment]
@alan791205 Thanks for reporting. Could you provide more info?

- node.js version:
- yarn version:

And full error logs if possible.

We'll look into this as soon as we can, Thanks :)

**Comment by alan791205** [comment]
actually if you specifically use a lower version (<13) of yarn when building ohara, you will get a syntax error on that line;
```31|      `Ohara Manger requires yarn 1.13.0 or greater, but you're using ${yarnVersion}`,```

for some reason I cannot reproduce that error again, maybe because of updating things?
But I am not sure about the "," there

**Comment by konekoya** [comment]
Hmm, I cannot repro this either. I'm going to close this issue since none of us are able to repro the behavior. And I've tested this on my local. Everything worked as it should. Thanks for your detailed report though :)
