### ISSUE TITLE
add template for umbrella issue 

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#993]
We prefer to split a hard task into many sub-issues to simplify the development, but it is hard to trace all issues after resolving them nevertheless. Jira has a specific issue type called umbrella issue, and it is responsible for collecting all related issues and provides a room to do a high level discussion. #681 is a example which has following attribute.
1. with "umbrella" label
1. no version tag
1. describe all related issues
1. no pull request

It seems to me a template of Umbrella makes our Issue keep tidy. Hence, I plan to file a PR to add a template for umbrella type which requires above attribute when opening a umbrella issue.

**Comment by chia7712** [comment]
@eechih @vitojeng @saivirtue @jackyoh @wu87988622 @konekoya Any suggestions???

**Comment by konekoya** [comment]
Sounds pretty good to me. But one question: does __no version tag__ mean the version label? Like: v0.4.0?

**Comment by chia7712** [comment]
> mean the version label? 

If the umbrella is used to collect all related issues, it should not have version tag. However, it is ok to have version if the umbrella is pushed to a version totally.

**Comment by saivirtue** [comment]
If we prefer to have umbrella issue template, I have two concern points:
1. `version` tag is used to identify "the issue itself" has commit ; as the umbrella is meant to be "group", no version tag is looks fine to me.
2. we still have `story` tag in our internal usage, should we apply the **umbrella** rules to the issue which is required by a story issue? 
ex : an issue that is required by a story and have a lot of sub tasks, have to add the following content:
2.1. a prefix "umbrella"
2.2. no version tag
2.3. describe all related issues
2.4. no pull request
2.5. add `required by #issue`

**Comment by chia7712** [comment]
> version tag is used to identify "the issue itself" has commit ; as the umbrella is meant to be "group", no version tag is looks fine to me.

If the **umbrella** issue has commit to ohara, having a tag version is ok I feel. We don't need a strict rule.

> we still have story tag in our internal usage, should we apply the umbrella rules to the issue which is required by a story issue?

In fact, I prefer to merge **story** issue and **umbrella* issue since I want to expose our internal term to other contributors in order to involve them in developing in the future. Probably we can use story tag instead of umbrella?

**Comment by saivirtue** [comment]
> Probably we can use story tag instead of umbrella?

Hmm...I think we need a quick blackboard discussion, maybe before noon?

**Comment by chia7712** [comment]
> I think we need a quick blackboard discussion, maybe before noon?

ok :)

**Comment by vitojeng** [comment]
For me, **story** and **umbrella** mean the same thing, just different wording. 😄 
So merge story and umbrella is ok to me.

**Comment by konekoya** [comment]
> If the umbrella is used to collect all related issues, it should not have version tag. However, it is ok to have version if the umbrella is pushed to a version totally.

So basically, if an umbrella issue is too big and could live across multiple sprints (milestones) -> No version tag

If an umbrella can be done in a single sprint -> add a version tag

**Comment by vitojeng** [comment]
> For me, story and umbrella mean the same thing, just different wording. 😄

Sorry, there need some corrections to clarify.  
**Umbrella** can be broad scope than a **story**.

**Comment by chia7712** [comment]
> Umbrella can be broad scope than a story.

that is really a unparalleled issue I'd say...

At any rate, the **story** is too **specific** to be a public issue. It would be better to merge story and umbrella. Also, having a rule for them is good for us and RM especially.
